// ============================================================
// Energy Copilot Platform — DAX Gap Fix v6
// Semantic Model : EnergyCopilotModel
// Last updated   : 2026-04-16
//
// BU DOSYA: Layout Planner v5'te tanımlanan ama mevcut
// 02_dax_measures.dax (v3) ve 10_dax_v5_final.dax (v5)
// dosyalarında BULUNMAYAN ölçüleri içerir.
//
// KURULUM:
//   Fabric Semantic Model editöründe:
//   Her ölçü için → New Measure → adı yaz → formülü yapıştır
//
// DEĞİŞİKLİK TABLOSU:
//   🆕 NEW     = Hiçbir versiyonda yoktu, tamamen yeni
//   🔄 CHANGED = Mevcut ölçünün yerine geçer
//   📛 ALIAS   = Layout planner'daki isim ile eşleştirme
// ============================================================


// ============================================================
// BÖLÜM A — SAYFA 2 EKSİK ÖLÇÜLER
// ============================================================

// 🆕 NEW — Solar üretiminin geçen yıl karşılaştırması
// Sayfa 2 Kart 4'ün "Target goals" alanına bağla.
// Direction: High is Good (üretim artışı iyidir)
// FORMAT: "#,##0"
Solar Generation PY kWh =
CALCULATE(
    [Total Solar Generated kWh],
    DATEADD(gold_kpi_daily[date], -1, YEAR)
)

// 🆕 NEW — Karbon yoğunluğu geçen yıl karşılaştırması
// Sayfa 2 Kart 6'nın "Target goals" alanına bağla.
// Direction: Low is Good
// FORMAT: "0.000"
Carbon Intensity PY kg m2 Day =
CALCULATE(
    [Avg Carbon Intensity kg m2],
    DATEADD(gold_kpi_daily[date], -1, YEAR)
)

// 🆕 NEW — Batarya SoC sabit hedef (optimal şarj seviyesi)
// Sayfa 2 Kart 5'in "Target goals" alanına bağla.
// Direction: High is Good
// Hedef 80% — Li-ion bataryalar için optimal SoC bandı 20-80%
// FORMAT: "0"
Battery SoC Target =
80


// ============================================================
// BÖLÜM B — SAYFA 1 KART 5 ALTERNATİF TARGET
// ============================================================

// ⚠️ NOT: [CRREM Pathway Target tCO2 Yr] ölçüsü mevcut v3'te
// tanımlı FAKAT gold_crrem_pathway tablosu henüz yok.
// Tablo oluşturulana kadar Card 5 target olarak
// [Previous Year Net Carbon tCO2] kullan (10_dax_v5_final.dax'ta var).
//
// Sayfa 1 Kart 5 → Target goals → [Previous Year Net Carbon tCO2]
//
// gold_crrem_pathway tablosu oluşturulduktan sonra:
// Sayfa 1 Kart 5 → Target goals → [CRREM Pathway Target tCO2 Yr]


// ============================================================
// BÖLÜM C — SAYFA 1 KART 1 DEBUG
// ============================================================

// ⚠️ SORUN: Card 1 target (Blank) gösteriyor.
// [Total Energy PY kWh] = CALCULATE([Total Consumption kWh],
//     DATEADD(gold_kpi_daily[date], -1, YEAR))
//
// OLASI NEDENLER:
// 1. Date tablosu "Mark as Date Table" olarak işaretlenmemiş
// 2. Date tablosu ile gold_kpi_daily[date] arasında relationship yok
// 3. Veri sadece tek bir yılı kapsıyor (PY verisi yok)
//
// ÇÖZÜM ADIMLARI:
// A) Model view → Date tablosu → sağ tık → "Mark as date table"
//    → Date[Date] kolonunu seç
// B) Model view → gold_kpi_daily[date] ile Date[Date] arasında
//    relationship olduğunu doğrula (Many-to-One, Active)
// C) Eğer veri tek yıl ise PY doğal olarak BLANK döner —
//    bu durumda Card 1 target field'ını boş bırak veya
//    [Energy Reduction Target kWh] kullan (PY × 0.95)
//
// ALTERNATİF TARGET (PY verisi yoksa):
// FORMAT: "#,##0"
Total Energy Target kWh =
[Energy Reduction Target kWh]
// ← PY consumption × 0.95 (EED %5 azaltma hedefi)
// Bu ölçü PY verisi olmasa bile çalışır çünkü
// [Energy Reduction Target kWh] zaten DATEADD ile PY'yi çeker
// ve × 0.95 yapar. PY yoksa bu da BLANK döner.
// O zaman sabit bir hedef kullan:


// 🆕 NEW — Sabit enerji bütçe hedefi (tüm portföy için)
// gold_kpi_daily verisindeki toplam gün sayısı × günlük bütçe
// Varsayım: Portföy günlük ortalama ~2750 kWh tüketir
// Bu değeri kendi portföy ortalamanıza göre güncelleyin
// FORMAT: "#,##0"
// ⚠️ BU ÖLÇÜ SADECE PY VERİSİ YOKSA KULLANILMALI
// PY varsa [Total Energy PY kWh] tercih edilmeli
// Portfolio Daily Budget kWh =
// 2750 * COUNTROWS(VALUES(gold_kpi_daily[date]))


// ============================================================
// BÖLÜM D — SAYFA 4 EKSİK ÖLÇÜLER
// ============================================================

// 🆕 NEW — 30 günlük forecast vs geçen yıl aynı dönem
// Sayfa 4 Kart 2 alternatif target
// FORMAT: "#,##0"
Forecast 30Day PY kWh =
VAR _last  = MAXX(ALL(gold_consumption_forecast), gold_consumption_forecast[forecast_date])
VAR _start = _last - 29
VAR _pyStart = EDATE(_start, -12)
VAR _pyEnd   = EDATE(_last, -12)
RETURN
CALCULATE(
    SUM(gold_kpi_daily[total_consumption_kwh]),
    gold_kpi_daily[date] >= _pyStart,
    gold_kpi_daily[date] <= _pyEnd
)


// ============================================================
// BÖLÜM E — SAYFA 6 EKSİK ÖLÇÜLER → ✅ TAMAMLANDI (2026-04-16)
// ============================================================

// Aşağıdaki tablolar oluşturuldu ve DAX ölçüleri yazıldı:
//
// ✅ gold_ghg_scope       → notebooks/gold/09_ghg_scope_engine.py
// ✅ gold_crrem_pathway   → notebooks/gold/10_crrem_pathway_loader.py
//
// ✅ [Scope 1 tCO2]               → 12_dax_v7_ghg_crrem.dax, Bölüm A
// ✅ [Scope 2 Location tCO2]      → 12_dax_v7_ghg_crrem.dax, Bölüm A
// ✅ [Scope 3 tCO2]               → 12_dax_v7_ghg_crrem.dax, Bölüm A
// ✅ [CRREM Pathway 2C kgCO2 m2 yr] → 12_dax_v7_ghg_crrem.dax, Bölüm E
// ✅ [Carbon Intensity Forecast kgCO2 m2] → 12_dax_v7_ghg_crrem.dax, Bölüm F
//
// Ek olarak şu ölçüler de eklendi (Bölüm B–G):
// ✅ [Total GHG Location tCO2], [GHG Intensity kgCO2 m2 yr]
// ✅ [CRREM Pathway Target tCO2 Yr], [CRREM Stranding Gap kgCO2 m2 yr]
// ✅ [CRREM Stranding Status], [GHG Reduction YoY Pct]
// ✅ [CSRD Total GHG tCO2e], [CSRD Carbon Budget Remaining tCO2]
//
// DEVAM ADIMI: Sayfa 1 Kart 5 target'ı güncelle:
//   ESKİ: [Previous Year Net Carbon tCO2]
//   YENİ: [CRREM Pathway Target tCO2 Yr]  ← artık çalışır


// ============================================================
// BÖLÜM F — İSİM EŞLEŞTİRME ALİASLARI
// ============================================================

// 📛 ALIAS — Layout planner'da [Total Cost PY EUR] olarak geçiyor
// Mevcut ölçü adı: [Previous Year Cost EUR]
// İkisi aynı — alias oluşturmaya gerek yok, layout güncellenecek

// 📛 ALIAS — Layout planner'da [Avg EUI kWh m2 Day] olarak geçiyor
// Mevcut ölçü adı: [Avg EUI kWh m2]
// İkisi aynı (günlük değer döndürür) — layout güncellenecek

// 📛 ALIAS — Layout planner'da [Unresolved Previous Week] olarak geçiyor
// Mevcut ölçü adı: [Unresolved Count Previous Week]
// İkisi aynı — layout güncellenecek


// ============================================================
// ÖZET: SAYFA BAŞINA HANGİ YENİ ÖLÇÜYÜ NEREYE EKLE
// ============================================================
//
// SAYFA 1:
//   Kart 1 → Target goals → [Total Energy PY kWh] (v3'te var)
//            ⚠️ BLANK dönüyorsa: Date table relationship kontrol et
//            ALTERNATİF: [Energy Reduction Target kWh] (v3'te var)
//   Kart 5 → Target goals → [Previous Year Net Carbon tCO2] (v5'te var)
//            (CRREM tablosu oluşturulunca [CRREM Pathway Target tCO2 Yr]'a geç)
//   Visual 7 → TABLE → MATRIX olarak değiştir
//            Rows: building_name
//            Columns: severity
//            Values: COUNT(anomaly_id)
//            CF: gradient background (dark → red)
//
// SAYFA 2:
//   Kart 4 → Target goals → [Solar Generation PY kWh]         (🆕 BÖLÜM A)
//   Kart 5 → Target goals → [Battery SoC Target]               (🆕 BÖLÜM A)
//   Kart 6 → Value         → [Avg Carbon Intensity kg m2]      (v3'te var, binding kontrol et)
//   Kart 6 → Target goals → [Carbon Intensity PY kg m2 Day]    (🆕 BÖLÜM A)
//   Chart 7 → Forecast serisini SİL
//            → Yerine [Energy 7Day Rolling Avg kWh] ekle (v3'te var)
//   EUI Gauge → "Good" label'ı yanlış
//            → [EUI Benchmark Status] measure'ını kontrol et
//   Slicers → 3 Building slicer'ı sil
//            → 1 Date range + 1 Building (single-select) ekle
//
// SAYFA 4:
//   Kart 2 → Target goals → [Forecast 30Day PY kWh]            (🆕 BÖLÜM D)
//
// SAYFA 6:
//   ⚠️ İleri aşama — tablolar oluşturulunca eklenecek          (BÖLÜM E)
// ============================================================
