// ============================================================
// Energy Copilot Platform — DAX Measures v7 (GHG + CRREM)
// Semantic Model : EnergyCopilotModel
// Last updated   : 2026-04-16
//
// BU DOSYA: 11_dax_v6_gap_fix.dax'ta "Bölüm E — İleri Aşama"
// olarak ertelenen tüm ölçüleri içerir.
// Artık gerekli tablolar mevcut:
//   gold_ghg_scope       → 09_ghg_scope_engine.py ile oluşturuldu
//   gold_crrem_pathway   → 10_crrem_pathway_loader.py ile oluşturuldu
//
// ÖNKOŞullar (Semantic Model'e eklenecekler):
//   1. gold_ghg_scope tablosu → ekle
//      İlişkiler:
//        gold_ghg_scope[building_id] → silver_building_master[building_id]  (Many-to-One)
//        gold_ghg_scope[year_month]  → Date[Date]                           (Many-to-One, ACTIVE)
//   2. gold_crrem_pathway tablosu → ekle
//      İlişkiler:
//        DOĞRUDAN ilişki yok — DAX LOOKUPVALUE ile bağlanır
//        (building_type + country_code çok-değerli composite key → relationship uygunsuz)
//
// ÖLÇÜ LİSTESİ:
//   === GHG SCOPE ÖLÇÜLERI (gold_ghg_scope) ===
//   [Scope 1 tCO2]               Kapsam 1: Doğalgaz + dizel yakımı
//   [Scope 2 Location tCO2]      Kapsam 2 Location: Şebeke elektriği
//   [Scope 2 Market tCO2]        Kapsam 2 Market: Yeşil enerji kontratı
//   [Scope 3 tCO2]               Kapsam 3: Tedarik zinciri tahmini
//   [Total GHG Location tCO2]    Scope1 + Scope2_Location + Scope3
//   [Total GHG Market tCO2]      Scope1 + Scope2_Market + Scope3
//   [Scope 1 Share Pct]          Scope 1'in toplam GHG içindeki payı
//   [Scope 2 Share Pct]          Scope 2'nin toplam GHG içindeki payı
//   [Scope 3 Share Pct]          Scope 3'ün toplam GHG içindeki payı
//   [GHG Intensity kgCO2 m2 yr]  Bina alanına normalize edilmiş toplam GHG
//   [Scope 1 PY tCO2]            Scope 1 geçen yıl (YoY karşılaştırma)
//   [Scope 2 Location PY tCO2]   Scope 2 Location geçen yıl
//   [Scope 3 PY tCO2]            Scope 3 geçen yıl
//   [Total GHG PY tCO2]          Toplam GHG geçen yıl
//   [GHG Reduction YoY Pct]      GHG azaltım oranı YoY
//
//   === CRREM PATHWAY ÖLÇÜLERI (gold_crrem_pathway) ===
//   [CRREM Pathway 2C kgCO2 m2 yr]    Seçili yıl için 2°C hedef değeri
//   [CRREM Pathway 15C kgCO2 m2 yr]   Seçili yıl için 1.5°C hedef değeri
//   [CRREM Pathway Target tCO2 Yr]    Pathway hedefi → tCO2/yıl (alan × hedef)
//   [CRREM Stranding Gap kgCO2 m2 yr] Mevcut yoğunluk ile pathway farkı
//   [CRREM Stranding Status]           "✅ On Track" | "⚠ At Risk" | "🔴 Stranded"
//   [CRREM Benchmark 2020]             2020 sektör başlangıç noktası
//
//   === FORECAST CARBON (gold_consumption_forecast) ===
//   [Carbon Intensity Forecast kgCO2 m2]   Forecast dönemi için tahmini yoğunluk
//   [Forecast CO2 tCO2]                     Forecast dönemi toplam emisyon tahmini
//
// FORMAT KURALI (tüm *Pct ölçüleri):
//   DAX içinde ×100 çarpılmış → format string "0.0" kullan
//   "0%" KULLANMA → Power BI yeniden ×100 çarpar → hata
// ============================================================


// ============================================================
// BÖLÜM A — TEMEL GHG SCOPE ÖLÇÜLERI
// Kaynak tablo: gold_ghg_scope
// ============================================================

// ─────────────────────────────────────────────────────────────
// [Scope 1 tCO2]
// Doğrudan emisyonlar: doğalgaz kazanı + dizel jeneratör
// GHG Protokol Kapsam 1 tanımı (GHG Protocol Corporate Standard, 2004)
// FORMAT: "#,##0.00"
// Sayfa 6 → Kapsam Dağılımı pastası veya bar chart'ında kullan
// ─────────────────────────────────────────────────────────────
Scope 1 tCO2 =
SUM(gold_ghg_scope[scope1_total_tco2])

// ─────────────────────────────────────────────────────────────
// [Scope 2 Location tCO2]
// Satın alınan elektriğin şebeke ortalama emisyonu
// Location-based method: ülke bazlı grid emisyon faktörü kullanır
// Market-based farklıysa ayrı ölçü var: [Scope 2 Market tCO2]
// FORMAT: "#,##0.00"
// ─────────────────────────────────────────────────────────────
Scope 2 Location tCO2 =
SUM(gold_ghg_scope[scope2_location_tco2])

// ─────────────────────────────────────────────────────────────
// [Scope 2 Market tCO2]
// Satın alınan elektriğin sözleşmeli/yeşil tarife emisyonu
// Yeşil enerji kontratı yoksa [Scope 2 Location tCO2] ile aynı olur
// FORMAT: "#,##0.00"
// ─────────────────────────────────────────────────────────────
Scope 2 Market tCO2 =
SUM(gold_ghg_scope[scope2_market_tco2])

// ─────────────────────────────────────────────────────────────
// [Scope 3 tCO2]
// Tedarik zinciri + çalışan ulaşımı (tahmini, %8 kural)
// CSRD ESRS E1-6 kapsamında raporlanması gerekir
// ⚠️ Bu değer tahmindir — gerçek Scope 3 envanter çalışması gerekir
// FORMAT: "#,##0.00"
// ─────────────────────────────────────────────────────────────
Scope 3 tCO2 =
SUM(gold_ghg_scope[scope3_estimated_tco2])

// ─────────────────────────────────────────────────────────────
// [Total GHG Location tCO2]
// Toplam sera gazı emisyonu (Location-based Scope 2 ile)
// CSRD raporlarında birincil metric olarak kullanılır
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
Total GHG Location tCO2 =
SUM(gold_ghg_scope[total_ghg_location_tco2])

// ─────────────────────────────────────────────────────────────
// [Total GHG Market tCO2]
// Toplam sera gazı emisyonu (Market-based Scope 2 ile)
// Yeşil enerji sertifikası (GreenSpec/EKOenerji) varsa daha düşük olur
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
Total GHG Market tCO2 =
SUM(gold_ghg_scope[total_ghg_market_tco2])


// ============================================================
// BÖLÜM B — GHG PAY ANALİZİ (Pasta / Waterfall için)
// ============================================================

// ─────────────────────────────────────────────────────────────
// [Scope 1 Share Pct]
// Toplam GHG içinde Scope 1 payı (0–100)
// FORMAT: "0.0"  — NEVER "0%"
// Sayfa 6 → Donut chart veya bar'da kullan
// ─────────────────────────────────────────────────────────────
Scope 1 Share Pct =
DIVIDE(
    [Scope 1 tCO2],
    [Total GHG Location tCO2],
    0
) * 100

// ─────────────────────────────────────────────────────────────
// [Scope 2 Share Pct]
// FORMAT: "0.0"
// ─────────────────────────────────────────────────────────────
Scope 2 Share Pct =
DIVIDE(
    [Scope 2 Location tCO2],
    [Total GHG Location tCO2],
    0
) * 100

// ─────────────────────────────────────────────────────────────
// [Scope 3 Share Pct]
// FORMAT: "0.0"
// ─────────────────────────────────────────────────────────────
Scope 3 Share Pct =
DIVIDE(
    [Scope 3 tCO2],
    [Total GHG Location tCO2],
    0
) * 100


// ============================================================
// BÖLÜM C — ALAN-NORMALIZE GHG YOĞUNLUĞU
// ============================================================

// ─────────────────────────────────────────────────────────────
// [GHG Intensity kgCO2 m2 yr]
// Yıllık GHG yoğunluğu: toplam emisyon / bina alanı / yıl
// CRREM ve GRESB raporlarında karşılaştırma için temel KPI
// FORMAT: "0.0"
// Sayfa 6 → Gauge veya KPI kartı
// Hedef: [CRREM Pathway 2C kgCO2 m2 yr]
// ─────────────────────────────────────────────────────────────
GHG Intensity kgCO2 m2 yr =
VAR _ghg_kg    = [Total GHG Location tCO2] * 1000     // tonne → kg
VAR _area      = SUM(silver_building_master[conditioned_area_m2])
VAR _months    = DISTINCTCOUNT(gold_ghg_scope[year_month])
VAR _years     = DIVIDE(_months, 12, 1)               // kısmi yıl desteği
RETURN
DIVIDE(
    _ghg_kg,
    _area * _years,
    BLANK()
)


// ============================================================
// BÖLÜM D — ZAMANSELLİK (GHG Year-over-Year)
// Ön koşul: Date tablosu "Mark as Date Table" ile işaretli olmalı
// ============================================================

// ─────────────────────────────────────────────────────────────
// [Scope 1 PY tCO2]
// Scope 1 geçen yıl değeri
//
// ✅ DATEADD KURALI: Her zaman 'Date'[Date] kullan — fact tablo kolonu değil.
//    Neden: Time intelligence fonksiyonları (DATEADD, SAMEPERIODLASTYEAR vb.)
//    yalnızca "Mark as Date Table" işaretli 'Date' tablosuyla çalışır.
//    gold_ghg_scope[year_month] doğrudan verilirse Power BI bu kolonu
//    "date table" olarak tanımaz → filtreleme doğru çalışmaz → BLANK döner.
//
//    Ön koşul (zaten belirtildi):
//      gold_ghg_scope[year_month] → Date[Date] aktif ilişkisi olmalı.
//    Bu ilişki kurulduğunda DATEADD('Date'[Date], -1, YEAR) gold_ghg_scope
//    üzerindeki filtre bağlamını otomatik olarak önceki yıla kaydırır.
//
// FORMAT: "#,##0.00"
// ─────────────────────────────────────────────────────────────
Scope 1 PY tCO2 =
CALCULATE(
    [Scope 1 tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)

// ─────────────────────────────────────────────────────────────
// [Scope 2 Location PY tCO2]
// FORMAT: "#,##0.00"
// ─────────────────────────────────────────────────────────────
Scope 2 Location PY tCO2 =
CALCULATE(
    [Scope 2 Location tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)

// ─────────────────────────────────────────────────────────────
// [Scope 3 PY tCO2]
// FORMAT: "#,##0.00"
// ─────────────────────────────────────────────────────────────
Scope 3 PY tCO2 =
CALCULATE(
    [Scope 3 tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)

// ─────────────────────────────────────────────────────────────
// [Total GHG PY tCO2]
// Toplam GHG geçen yıl (Sayfa 6 Kart 1 Target goals)
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
Total GHG PY tCO2 =
CALCULATE(
    [Total GHG Location tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)

// ─────────────────────────────────────────────────────────────
// [GHG Reduction YoY Pct]
// YoY GHG azaltım oranı (negatif = azalma = iyi)
// Pozitif değer artış = kötü. Low is Good yönü.
// FORMAT: "0.0"  (–12.3 = %12.3 azaltım)
// ─────────────────────────────────────────────────────────────
GHG Reduction YoY Pct =
DIVIDE(
    [Total GHG Location tCO2] - [Total GHG PY tCO2],
    [Total GHG PY tCO2],
    BLANK()
) * 100


// ============================================================
// BÖLÜM E — CRREM PATHWAY ÖLÇÜLERI
// Kaynak tablo: gold_crrem_pathway
// Bağlantı yöntemi: LOOKUPVALUE (composite key, relationship yok)
// ============================================================

// ─────────────────────────────────────────────────────────────
// [CRREM Pathway 2C kgCO2 m2 yr]
// Filtre bağlamındaki yıl ve bina türü için 2°C CRREM hedefi
//
// MİMARİ NOT: gold_crrem_pathway ile doğrudan relationship yok.
// LOOKUPVALUE kullanılır çünkü:
//   1. building_type × country_code composite key → Power BI tek kolon
//      relationship destekler, composite desteklemez.
//   2. Pathway yılı = seçilen filtre yılı (dinamik) → ilişki statik olamaz.
//
// VARSAYIM: Portföyde farklı bina türleri varsa,
//   bu ölçü tek bir değer döndürmez → AVERAGEX ile ağırlıklı ortalama alınır.
// FORMAT: "0.0"
// ─────────────────────────────────────────────────────────────
CRREM Pathway 2C kgCO2 m2 yr =
VAR _year = SELECTEDVALUE('Date'[Year], YEAR(TODAY()))
RETURN
AVERAGEX(
    VALUES(silver_building_master[building_id]),
    VAR _btype   = LOOKUPVALUE(
                       silver_building_master[building_type],
                       silver_building_master[building_id],
                       silver_building_master[building_id]
                   )
    VAR _country = LOOKUPVALUE(
                       silver_building_master[country_code],
                       silver_building_master[building_id],
                       silver_building_master[building_id]
                   )
    RETURN
    COALESCE(
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  _year
        ),
        // Ülke bulunamazsa EU default'a düş
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year
        ),
        // Bina türü bulunamazsa office'e düş
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year
        )
    )
)

// ─────────────────────────────────────────────────────────────
// [CRREM Pathway 15C kgCO2 m2 yr]
// 1.5°C senaryo hedefi — net-zero aligned bina standardı
// FORMAT: "0.0"
// ─────────────────────────────────────────────────────────────
CRREM Pathway 15C kgCO2 m2 yr =
VAR _year = SELECTEDVALUE('Date'[Year], YEAR(TODAY()))
RETURN
AVERAGEX(
    VALUES(silver_building_master[building_id]),
    VAR _btype   = LOOKUPVALUE(
                       silver_building_master[building_type],
                       silver_building_master[building_id],
                       silver_building_master[building_id]
                   )
    VAR _country = LOOKUPVALUE(
                       silver_building_master[country_code],
                       silver_building_master[building_id],
                       silver_building_master[building_id]
                   )
    RETURN
    COALESCE(
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_15c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  _year
        ),
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_15c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year
        ),
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_15c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year
        )
    )
)

// ─────────────────────────────────────────────────────────────
// [CRREM Pathway Target tCO2 Yr]
// CRREM 2°C hedefini mutlak tCO2'ye çevir (alan × pathway)
// Sayfa 1 Kart 5 → Target goals olarak bağla (şimdiye kadar PY kullanıldı)
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
CRREM Pathway Target tCO2 Yr =
VAR _pathway_kg_m2 = [CRREM Pathway 2C kgCO2 m2 yr]   // kgCO2/m²/yıl
VAR _area          = SUM(silver_building_master[conditioned_area_m2])
VAR _months        = DISTINCTCOUNT(gold_ghg_scope[year_month])
VAR _year_fraction = DIVIDE(_months, 12, 1)
RETURN
DIVIDE(
    _pathway_kg_m2 * _area * _year_fraction,
    1000,   // kg → tonne
    BLANK()
)

// ─────────────────────────────────────────────────────────────
// [CRREM Stranding Gap kgCO2 m2 yr]
// Mevcut GHG yoğunluğu ile CRREM hedefi arasındaki fark
// Pozitif = hedefi aştık = stranding riski var
// Negatif = pathway altındayız = uyumlu
// FORMAT: "0.0"
// Sayfa 6 → KPI kart (Low is Good, conditional formatting)
// ─────────────────────────────────────────────────────────────
CRREM Stranding Gap kgCO2 m2 yr =
[GHG Intensity kgCO2 m2 yr] - [CRREM Pathway 2C kgCO2 m2 yr]

// ─────────────────────────────────────────────────────────────
// [CRREM Stranding Status]
// Metin etiketi — Sayfa 6 kartı alt yazısı veya tooltip
// ─────────────────────────────────────────────────────────────
CRREM Stranding Status =
VAR _gap = [CRREM Stranding Gap kgCO2 m2 yr]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_gap),                    "— No data",
    _gap <= -10,                      "✅ Well Below Pathway",
    _gap <= 0,                        "✅ On Track",
    _gap <= 15,                       "⚠ At Risk",
                                      "🔴 Stranded Asset Risk"
)

// ─────────────────────────────────────────────────────────────
// [CRREM Benchmark 2020]
// 2020 sektör başlangıç noktası — grafiklerde baseline çizgisi
// FORMAT: "0.0"
// ─────────────────────────────────────────────────────────────
CRREM Benchmark 2020 =
AVERAGEX(
    VALUES(silver_building_master[building_id]),
    VAR _btype   = LOOKUPVALUE(
                       silver_building_master[building_type],
                       silver_building_master[building_id],
                       silver_building_master[building_id]
                   )
    VAR _country = LOOKUPVALUE(
                       silver_building_master[country_code],
                       silver_building_master[building_id],
                       silver_building_master[building_id]
                   )
    RETURN
    COALESCE(
        LOOKUPVALUE(
            gold_crrem_pathway[sector_benchmark_2020],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  2020
        ),
        LOOKUPVALUE(
            gold_crrem_pathway[sector_benchmark_2020],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  2020
        )
    )
)


// ============================================================
// BÖLÜM F — FORECAST KARBON TAHMİNİ
// Kaynak tablo: gold_consumption_forecast + şebeke emisyon faktörü
// ============================================================

// ─────────────────────────────────────────────────────────────
// [Carbon Intensity Forecast kgCO2 m2]
// Forecast dönemindeki tahmini karbon yoğunluğu
// Hesaplama: predicted_kwh × grid_ef (ülke ortalama) / alan
//
// VARSAYIM: Şebeke faktörü sabit (0.38 DE default)
//   Gerçek veri: gold_ghg_scope[emission_factor_grid] ortalamasını al
//   Bu ölçüde dinamik şebeke faktörü kullanmak istersen BÖLÜM C'deki
//   AVERAGEX pattern'ini tekrarla.
//
// FORMAT: "0.000"
// Sayfa 6 → Forecast vs Pathway karşılaştırma line chart'ında kullan
// ─────────────────────────────────────────────────────────────
Carbon Intensity Forecast kgCO2 m2 =
VAR _forecast_kwh = SUM(gold_consumption_forecast[predicted_kwh])
VAR _area         = SUM(silver_building_master[conditioned_area_m2])
VAR _days         = DISTINCTCOUNT(gold_consumption_forecast[forecast_date])
VAR _years        = DIVIDE(_days, 365, 1)
// Şebeke faktörü: gold_ghg_scope tablosundan al (varsa), yoksa DE default
VAR _grid_ef      =
    COALESCE(
        AVERAGE(gold_ghg_scope[emission_factor_grid]),
        0.38   // DE default fallback
    )
VAR _co2_kg       = _forecast_kwh * _grid_ef
RETURN
DIVIDE(
    _co2_kg,
    _area * MAX(_years, 0.01),  // sıfır bölme koruması
    BLANK()
)

// ─────────────────────────────────────────────────────────────
// [Forecast CO2 tCO2]
// Forecast dönemindeki toplam CO2 tahmini (mutlak, tonne)
// Sayfa 4 → Forecast sayfasında ek bilgi kartı
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
Forecast CO2 tCO2 =
VAR _forecast_kwh = SUM(gold_consumption_forecast[predicted_kwh])
VAR _grid_ef      =
    COALESCE(
        AVERAGE(gold_ghg_scope[emission_factor_grid]),
        0.38
    )
RETURN
DIVIDE(
    _forecast_kwh * _grid_ef,
    1000,   // kg → tonne
    BLANK()
)


// ============================================================
// BÖLÜM G — CSRD / ESRS E1 RAPORLAMA ÖLÇÜLERI
// CSRD: Corporate Sustainability Reporting Directive (2023/2024)
// ESRS E1: İklim değişikliği standardı (zorunlu emisyon açıklama)
// ============================================================

// ─────────────────────────────────────────────────────────────
// [CSRD Total GHG tCO2e]
// CSRD ESRS E1-6 kapsamında açıklanacak toplam GHG
// tCO2e = CO2 eşdeğeri (bu modelde CH4, N2O katkısı ihmal edildi)
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
CSRD Total GHG tCO2e =
[Total GHG Location tCO2]
// ⚠️ Gerçek CSRD raporlaması için CH4 ve N2O katkısı eklenmeli.
// Şu an sadece CO2 hesaplanmaktadır.
// ESRS E1-6 tam uyumluluk için: silver_refrigerant_log, gas_leak tabloları gerekir.

// ─────────────────────────────────────────────────────────────
// [CSRD Scope 1+2 tCO2e]
// ESRS E1'in birincil açıklama kalemi
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
CSRD Scope 1+2 tCO2e =
[Scope 1 tCO2] + [Scope 2 Location tCO2]

// ─────────────────────────────────────────────────────────────
// [CSRD Carbon Budget Remaining tCO2]
// CRREM 2°C pathway hedefine göre kalan "karbon bütçesi"
// Negatif = bütçeyi aştık
// FORMAT: "#,##0.0"
// ─────────────────────────────────────────────────────────────
CSRD Carbon Budget Remaining tCO2 =
[CRREM Pathway Target tCO2 Yr] - [Total GHG Location tCO2]


// ============================================================
// ÖZET: SAYFA 6 İÇİN HANGİ ÖLÇÜYÜ NEREYE BAĞLA
// ============================================================
//
// ╔══════════════════════════════════════════════════════════╗
// ║  SAYFA 6 — Sustainability & Compliance                  ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Kart 1 → Value  : [Total GHG Location tCO2]           ║
// ║           Target : [Total GHG PY tCO2]                 ║
// ║           Dir    : Low is Good                         ║
// ║           Format : "#,##0.0"                           ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Kart 2 → Value  : [Scope 1 tCO2]                      ║
// ║           Format : "#,##0.00"                          ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Kart 3 → Value  : [Scope 2 Location tCO2]             ║
// ║           Format : "#,##0.00"                          ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Kart 4 → Value  : [Scope 3 tCO2]                      ║
// ║           Format : "#,##0.00"                          ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Kart 5 → Value  : [GHG Intensity kgCO2 m2 yr]        ║
// ║           Target : [CRREM Pathway 2C kgCO2 m2 yr]     ║
// ║           Dir    : Low is Good                         ║
// ║           Format : "0.0"                               ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Kart 6 → Value  : [CRREM Stranding Status]            ║
// ║           (text measure → Card visual, no target)      ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Grafik 7 → Scope Dağılımı (Donut chart)               ║
// ║   Values   : [Scope 1 tCO2], [Scope 2 Location tCO2], ║
// ║              [Scope 3 tCO2]                            ║
// ║   Legend   : Manuel seri adı (DAX "Scope 1" literal)  ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Grafik 8 → CRREM Pathway vs Actual (Line chart)       ║
// ║   X-Axis  : Date[Year]                                 ║
// ║   Seri 1  : [GHG Intensity kgCO2 m2 yr]  (Actual)     ║
// ║   Seri 2  : [CRREM Pathway 2C kgCO2 m2 yr] (Target)   ║
// ║   Seri 3  : [CRREM Pathway 15C kgCO2 m2 yr] (1.5°C)   ║
// ║   Seri 4  : [CRREM Benchmark 2020]  (Reference line)  ║
// ╠══════════════════════════════════════════════════════════╣
// ║  Sayfa 1 Kart 5 → Target goals güncellemesi:           ║
// ║   ESKİ   : [Previous Year Net Carbon tCO2]             ║
// ║   YENİ   : [CRREM Pathway Target tCO2 Yr]             ║
// ║   (gold_crrem_pathway tablosu artık mevcut)            ║
// ╚══════════════════════════════════════════════════════════╝
//
// ÖNKOŞul KONTROL LİSTESİ (Power BI Desktop'ta):
//   □ gold_ghg_scope → Add to semantic model
//   □ gold_ghg_scope[building_id] → silver_building_master[building_id] ilişkisi
//   □ gold_ghg_scope[year_month]  → Date[Date] ilişkisi (Many-to-One, ACTIVE)
//   □ gold_crrem_pathway → Add to semantic model
//   □ gold_crrem_pathway → relationship YOK (LOOKUPVALUE kullanılır)
//   □ silver_building_master → building_type kolonu doğrula ("office"/"retail")
//   □ silver_building_master → country_code kolonu doğrula ("DE"/"TR"/"EU")
// ============================================================
