// ==========================================================================
// Energy Copilot Platform — DAX v8: HVAC & Envelope Analytics
// File: semantic-model/13_dax_v8_hvac_envelope.dax
// Source table: gold_hvac_analytics (notebook 11_hvac_analytics_engine)
// Also reads: silver_building_master (U-values, system flags)
// Page target: Page 7 — HVAC & Envelope Intelligence
//
// Sections:
//   A. HVAC Energy Disaggregation (heating / cooling / ventilation)
//   B. HVAC Efficiency & COP
//   C. Envelope & Insulation
//   D. Renovation Priority & System Labels
//   E. Technology Benchmarks & Comparison
//   F. KPI Cards (summary scalars for Page 7 top row)
//
// Prerequisites:
//   - gold_hvac_analytics loaded as Power BI table
//   - Relationship: gold_hvac_analytics[building_id] → silver_building_master[building_id] (Many-to-One)
//   - Relationship: gold_hvac_analytics[year_month] → 'Date'[Date] (Many-to-One, ACTIVE)
//     ↑ NOTE: column is 'year_month' (DATE type, YYYY-MM-01), NOT 'month_start'
//   - Date table marked as Date Table on 'Date'[Date] column
//   - Measures from 12_dax_v7_ghg_crrem.dax already imported
// ==========================================================================


// ==========================================================================
// A. HVAC ENERGY DISAGGREGATION
// ==========================================================================

[Heating Energy kWh] =
// Monthly heating energy estimate (EN ISO 13790 proportional model)
// Uses HDD-weighted share of total consumption per building type
// Column: heating_energy_kwh (notebook 11 FINAL_COLS output)
SUMX(
    gold_hvac_analytics,
    gold_hvac_analytics[heating_energy_kwh]
)

[Cooling Energy kWh] =
// Monthly cooling energy estimate (CDD-weighted share)
// Column: cooling_energy_kwh (notebook 11 FINAL_COLS output)
SUMX(
    gold_hvac_analytics,
    gold_hvac_analytics[cooling_energy_kwh]
)

[Ventilation Energy kWh] =
// Ventilation / AHU energy — building-type fixed share (office ~15%, hospital ~20%)
// Column: ventilation_kwh (notebook 11 FINAL_COLS output)
SUMX(
    gold_hvac_analytics,
    gold_hvac_analytics[ventilation_kwh]
)

[HVAC Total kWh] =
// Total HVAC system energy (heating + cooling + ventilation)
// Note: does not include plug loads, lighting, or data centre loads
[Heating Energy kWh] + [Cooling Energy kWh] + [Ventilation Energy kWh]

[HVAC Share Pct] =
// HVAC as % of total building electricity — benchmark: office 40–60%, hospital 50–70%
VAR _total = CALCULATE(SUM(gold_kpi_daily[total_kwh]))
RETURN
IF(
    _total > 0,
    DIVIDE([HVAC Total kWh], _total) * 100,
    BLANK()
)

[Heating Share Pct] =
// Heating as % of HVAC total — high values (>60%) in cold climates indicate heating-dominated buildings
DIVIDE([Heating Energy kWh], [HVAC Total kWh]) * 100

[Cooling Share Pct] =
// Cooling as % of HVAC total — high values (>50%) in warm climates or data-heavy buildings
DIVIDE([Cooling Energy kWh], [HVAC Total kWh]) * 100

[Heating Energy kWh m2] =
// Heating intensity per conditioned area — benchmark: GEG 2023 new build < 30 kWh/m²/yr
VAR _area = SUMX(
    RELATEDTABLE(silver_building_master),
    silver_building_master[conditioned_area_m2]
)
RETURN
DIVIDE([Heating Energy kWh], _area)

[Cooling Energy kWh m2] =
// Cooling intensity per conditioned area — benchmark: well-insulated office < 15 kWh/m²/yr
VAR _area = SUMX(
    RELATEDTABLE(silver_building_master),
    silver_building_master[conditioned_area_m2]
)
RETURN
DIVIDE([Cooling Energy kWh], _area)


// ==========================================================================
// B. HVAC EFFICIENCY & COP (Heat Pump Performance)
// ==========================================================================

[COP Monthly Actual] =
// Actual COP: heat delivered / electricity consumed (heat pump buildings only)
// COP < 2.5 → poor (suspect fault or extreme cold), COP > 4.5 → excellent
// Returns BLANK for gas-boiler buildings (COP concept does not apply)
AVERAGEX(
    gold_hvac_analytics,
    IF(
        gold_hvac_analytics[scop_rolling] > 0,
        gold_hvac_analytics[scop_rolling],
        BLANK()
    )
)

[SCOP Rolling 3M] =
// 3-month rolling Seasonal COP — smooths short-term weather spikes
// Preferred over single-month COP for operational decisions
AVERAGEX(
    gold_hvac_analytics,
    gold_hvac_analytics[scop_rolling]
)

[COP vs Target Gap] =
// Gap between actual SCOP and target SCOP 3.0 (ASHP minimum acceptable)
// Negative value = underperforming; -0.5 or worse = maintenance action needed
VAR _cop = [SCOP Rolling 3M]
VAR _target = 3.0
RETURN
IF(_cop > 0, _cop - _target, BLANK())

[COP Rating Label] =
// Human-readable COP performance label for table/card visuals
VAR _cop = [COP Monthly Actual]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_cop),       "N/A (Non-HP Building)",
    _cop >= 4.5,         "⭐ Excellent (≥4.5)",
    _cop >= 3.5,         "✅ Good (3.5–4.5)",
    _cop >= 3.0,         "⚠️ Acceptable (3.0–3.5)",
    _cop >= 2.0,         "🔴 Poor (2.0–3.0)",
                         "❌ Critical (<2.0) — Check HP"
)

[HP Buildings Count] =
// Count of buildings with active heat pumps in current selection
CALCULATE(
    COUNTROWS(silver_building_master),
    silver_building_master[has_heat_pump] = TRUE()
)

[Avg SCOP HP Portfolio] =
// Portfolio-wide average SCOP across all heat pump buildings
// Used in Page 7 KPI card — target: ≥ 3.0
CALCULATE(
    AVERAGEX(gold_hvac_analytics, gold_hvac_analytics[scop_rolling]),
    FILTER(silver_building_master, silver_building_master[has_heat_pump] = TRUE())
)

[HVAC Efficiency Score] =
// 0–100 score: HP buildings scored vs COP target 4.5; gas buildings capped at 50
// Used in portfolio ranking and renovation priority matrix
AVERAGEX(
    gold_hvac_analytics,
    gold_hvac_analytics[hvac_efficiency_score]
)

[HVAC Efficiency Label] =
VAR _score = [HVAC Efficiency Score]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_score), BLANK(),
    _score >= 80,    "A — High Efficiency",
    _score >= 60,    "B — Above Average",
    _score >= 40,    "C — Average",
    _score >= 20,    "D — Below Average",
                     "E — Poor — Action Required"
)


// ==========================================================================
// C. ENVELOPE & INSULATION
// ==========================================================================

[U Wall Actual] =
// Actual U-value of external walls (W/m²K) — lower = better insulated
// Source: silver_building_master (from building_master.csv / asset register)
// GEG 2023 retrofit standard: ≤ 0.24 W/m²K
AVERAGE(silver_building_master[wall_u_value])

[U Roof Actual] =
// Actual U-value of roof (W/m²K)
// GEG 2023 retrofit standard: ≤ 0.20 W/m²K
AVERAGE(silver_building_master[roof_u_value])

[U Floor Actual] =
// Actual U-value of floor slab (W/m²K)
// GEG 2023 retrofit standard: ≤ 0.35 W/m²K
AVERAGE(silver_building_master[floor_u_value])

[U Window Actual] =
// Actual U-value of glazing (W/m²K) — triple glazing: ~0.7; single: ~5.8
// GEG 2023 retrofit standard: ≤ 1.30 W/m²K; Passivhaus: ≤ 0.80 W/m²K
AVERAGE(silver_building_master[window_u_value])

[U Composite] =
// Weighted composite U-value: wall 40%, window 30%, roof 20%, floor 10%
// Lower is better. Passivhaus: ~0.15; Old stock: >0.8
AVERAGEX(
    gold_hvac_analytics,
    gold_hvac_analytics[u_composite]
)

[Insulation Score] =
// 0–100 score comparing actual U-values vs GEG 2023 retrofit benchmarks
// 100 = meets all GEG standards; < 50 = significant retrofit needed
// Formula: weighted min(100, benchmark_U / actual_U × 100) per component
AVERAGEX(
    gold_hvac_analytics,
    gold_hvac_analytics[insulation_score]
)

[Insulation Rating Label] =
// Letter rating for insulation score — used in matrix table and cards
VAR _score = [Insulation Score]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_score), BLANK(),
    _score >= 90,    "A — Passivhaus Level",
    _score >= 75,    "B — GEG Compliant",
    _score >= 55,    "C — Partial Upgrade Needed",
    _score >= 35,    "D — Significant Retrofit",
                     "E — Full Envelope Overhaul"
)

[Heat Loss kWh m2 Month] =
// Monthly heat loss through building envelope per m² (EN ISO 13370 simplified)
// High values → poor insulation → high heating bills
// Benchmark: well-insulated office < 5 kWh/m²/month in winter
AVERAGEX(
    gold_hvac_analytics,
    gold_hvac_analytics[heat_loss_kwh_m2]
)

[Heat Loss kWh m2 Annual] =
// Annual sum of monthly heat loss per m² — key envelope performance indicator
SUMX(
    gold_hvac_analytics,
    gold_hvac_analytics[heat_loss_kwh_m2]
)

[Thermal Bridge Penalty] =
// Additional heat loss from thermal bridges (EN ISO 14683 default: +0.10 W/m²K)
// Buildings built before 2000 without certified bridge-free detailing assumed to have full penalty
// Returns "Yes" / "No" for table column, as TRUE/FALSE from silver_building_master
IF(
    CALCULATE(
        MAX(silver_building_master[has_thermal_bridge]),
        ALLEXCEPT(silver_building_master, silver_building_master[building_id])
    ) = TRUE(),
    "Yes — +0.10 W/m²K applied",
    "No bridge assumed"
)

[Window to Wall Ratio] =
// WWR: glazing area / total façade area — high WWR increases cooling load
// Optimal for offices in Central Europe: 25–40%
// Source: silver_building_master[window_to_wall_ratio]
AVERAGE(silver_building_master[window_to_wall_ratio]) * 100

[GEG Compliance Wall] =
// Wall compliance check vs GEG 2023 retrofit standard 0.24 W/m²K
IF([U Wall Actual] <= 0.24, "✅ Compliant", "❌ Non-Compliant (>" & FORMAT(0.24, "0.00") & ")")

[GEG Compliance Roof] =
IF([U Roof Actual] <= 0.20, "✅ Compliant", "❌ Non-Compliant (>" & FORMAT(0.20, "0.00") & ")")

[GEG Compliance Window] =
IF([U Window Actual] <= 1.30, "✅ Compliant", "❌ Non-Compliant (>" & FORMAT(1.30, "0.00") & ")")


// ==========================================================================
// D. RENOVATION PRIORITY & SYSTEM CLASSIFICATION
// ==========================================================================

[Renovation Priority Label] =
// High / Medium / Low priority based on insulation band × HVAC system type matrix
// High: poor insulation (score < 55) OR gas boiler; Medium: partial gaps; Low: HP + good envelope
// Source: gold_hvac_analytics[renovation_priority]
CALCULATE(
    MAXX(gold_hvac_analytics, gold_hvac_analytics[renovation_priority]),
    ALLEXCEPT(gold_hvac_analytics, gold_hvac_analytics[building_id])
)

[Renovation Priority Icon] =
VAR _label = [Renovation Priority Label]
RETURN
SWITCH(
    _label,
    "High",   "🔴 High — Act Now",
    "Medium", "🟡 Medium — Plan in 2 Years",
    "Low",    "🟢 Low — Monitor Only",
    "Unknown"
)

[System Type Label] =
// heat_pump / hybrid / gas_boiler / other
// Source: gold_hvac_analytics[system_type]
CALCULATE(
    MAXX(gold_hvac_analytics, gold_hvac_analytics[system_type]),
    ALLEXCEPT(gold_hvac_analytics, gold_hvac_analytics[building_id])
)

[System Type Display] =
// Human-friendly label with technology context for Page 7 table
VAR _sys = [System Type Label]
RETURN
SWITCH(
    _sys,
    "heat_pump",  "🔵 Air/Ground Source Heat Pump",
    "hybrid",     "🟣 Hybrid (HP + Gas Backup)",
    "gas_boiler", "🟠 Gas Boiler (Fossil — CSRD Risk)",
    "other",      "⚪ Other / Not Specified",
    "Unknown"
)

[High Priority Building Count] =
// Count of buildings with High renovation priority in current selection
CALCULATE(
    COUNTROWS(
        DISTINCT(
            SELECTCOLUMNS(
                FILTER(gold_hvac_analytics, gold_hvac_analytics[renovation_priority] = "High"),
                "bid", gold_hvac_analytics[building_id]
            )
        )
    )
)

[Gas Boiler Building Count] =
// Count of gas boiler buildings — CSRD stranded asset risk
CALCULATE(
    COUNTROWS(silver_building_master),
    silver_building_master[has_gas_heating] = TRUE(),
    silver_building_master[has_heat_pump] = FALSE()
)


// ==========================================================================
// E. TECHNOLOGY BENCHMARKS & MARKET COMPARISON
// ==========================================================================

// ── Market reference benchmarks ──────────────────────────────────────────
// Source: EHPA 2024 European Heat Pump Outlook, BSRIA 2024, IEA EMHP 2024
// These are static reference measures for comparison cards on Page 7

[Benchmark COP ASHP Market 2024] =
// Average field-measured SCOP for Air Source Heat Pumps in European climate
// IEA / EHPA field data 2023-2024: 2.8–3.5 average depending on climate zone
// Returns as scalar for comparison gauge or bullet chart
3.1

[Benchmark COP GSHP Market 2024] =
// Ground Source Heat Pump SCOP benchmark (more stable, higher COP)
// EHPA 2024: 3.8–4.5 typical for European commercial buildings
4.2

[Benchmark Insulation Score Good] =
// Insulation score threshold considered "good practice" (GEG 2023 compliant)
75

[Benchmark Heat Loss kWh m2 yr Target] =
// Annual heat loss target for well-insulated commercial building
// Passivhaus: < 15 kWh/m²/yr; Near-zero energy: < 30 kWh/m²/yr
25

[COP vs Market Benchmark] =
// Difference vs market average ASHP COP 3.1
// Positive = outperforming market; negative = underperforming
[COP Monthly Actual] - [Benchmark COP ASHP Market 2024]

[COP vs Market Label] =
VAR _gap = [COP vs Market Benchmark]
RETURN
IF(
    ISBLANK(_gap),
    "N/A",
    IF(
        _gap >= 0,
        "+" & FORMAT(_gap, "0.00") & " vs market avg",
        FORMAT(_gap, "0.00") & " vs market avg"
    )
)

[HP Penetration Rate Pct] =
// % of portfolio buildings with heat pump (any type) — benchmark: EU 2030 target > 60%
DIVIDE(
    CALCULATE(COUNTROWS(silver_building_master), silver_building_master[has_heat_pump] = TRUE()),
    COUNTROWS(silver_building_master)
) * 100

[Portfolio HP Savings Potential kWh] =
// Estimated annual electricity savings if gas boiler buildings converted to ASHP (COP 3.1)
// Conservative model: heating kWh / 3.1 (HP) vs heating kWh / 0.90 (gas boiler efficiency)
// NOTE: This is an illustrative estimate, not an engineering audit
VAR _gas_buildings_heating = CALCULATE(
    [Heating Energy kWh],
    silver_building_master[has_gas_heating] = TRUE()
)
VAR _with_gas = DIVIDE(_gas_buildings_heating, 0.90)    -- primary energy equivalent
VAR _with_hp  = DIVIDE(_gas_buildings_heating, 3.10)    -- electricity if converted to HP
RETURN
MAX(0, _with_gas - _with_hp)

[Insulation Upgrade ROI Label] =
// Qualitative ROI label based on insulation score gap
// Used in Page 7 recommendation card
VAR _score = [Insulation Score]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_score),   BLANK(),
    _score < 35,       "High ROI — 5–7 yr payback typical",
    _score < 55,       "Medium ROI — 7–12 yr payback typical",
    _score < 75,       "Low ROI — Selective upgrade only",
                       "Minimal ROI — Already well insulated"
)


// ==========================================================================
// F. KPI CARDS — TOP ROW SCALARS (Page 7)
// ==========================================================================

[Card: Avg Portfolio Insulation Score] =
// KPI card: portfolio average insulation score (0–100)
// Good: ≥ 75. Target: all buildings ≥ 75 by 2030 (GEG retrofit obligation)
AVERAGEX(
    VALUES(gold_hvac_analytics[building_id]),
    CALCULATE(AVERAGEX(gold_hvac_analytics, gold_hvac_analytics[insulation_score]))
)

[Card: Avg Portfolio COP] =
// KPI card: portfolio average SCOP for heat pump buildings
// BLANK if no heat pump buildings in selection
CALCULATE(
    AVERAGEX(gold_hvac_analytics, gold_hvac_analytics[scop_rolling]),
    silver_building_master[has_heat_pump] = TRUE()
)

[Card: HVAC Share of Total Energy] =
// KPI card: HVAC as % of portfolio total consumption
// Typical range: office 40–55%, hospital 50–70%, logistics 25–40%
DIVIDE([HVAC Total kWh], CALCULATE(SUM(gold_kpi_daily[total_kwh]))) * 100

[Card: Buildings Needing Renovation] =
// KPI card: count of buildings with High renovation priority
[High Priority Building Count]

[Card: Annual Heat Loss kWh m2] =
// KPI card: portfolio avg annual heat loss through envelope per m² conditioned area
[Heat Loss kWh m2 Annual]

[Card: HP Portfolio Penetration] =
// KPI card: % of buildings with heat pump installed
[HP Penetration Rate Pct]

[Card: Gas Boiler Risk Count] =
// KPI card: number of buildings still on gas boiler (CSRD stranded asset exposure)
[Gas Boiler Building Count]

[Card: HVAC Efficiency Score] =
// KPI card: avg HVAC efficiency score (0–100) across portfolio
[HVAC Efficiency Score]


// ==========================================================================
// END OF 13_dax_v8_hvac_envelope.dax
// Next file: layouts/page7_hvac_layout.md (visual placement guide)
// ==========================================================================
