// ==========================================================================
// Energy Copilot Platform — DAX v9: Date Table Weekly Columns + Time Intelligence
// File: semantic-model/14_dax_v9_date_weekly.dax
// Last updated: 2026-04-17
//
// BU DOSYA 2 BÖLÜMDEN OLUŞUR:
//   BÖLÜM 1 — Date tablosuna eklenecek HESAPLANMIŞ KOLONLAR
//             (Model view → Date tablosu → New column)
//   BÖLÜM 2 — Semantic model'e eklenecek ÖLÇÜLER (Measures)
//             Last Week / Last Month time intelligence
//
// ÖNKOŞULlar:
//   - Date tablosu "Mark as Date Table" → Date[Date] kolonu seçili
//   - MonthIndex kolonu mevcut: YEAR('Date'[Date]) * 100 + MONTH('Date'[Date])
//   - gold_kpi_daily[date] → Date[Date] ilişkisi ACTIVE
//
// KURULUM SIRASI:
//   1. Önce BÖLÜM 1 kolonlarını ekle (Model view → Date → New column)
//   2. Ardından BÖLÜM 2 ölçülerini ekle (New measure)
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — DATE TABLOSU HESAPLANMIŞ KOLONLAR
// Bu kolonları Power BI Desktop'ta şu şekilde ekle:
//   Model view → Sol panelde "Date" tablosunu seç
//   → Üst menü "New column" → formülü yapıştır → Enter
// ==========================================================================

// ── Kolon 1: WeekNumber ──────────────────────────────────────────────────
// ISO 8601 hafta numarası (1–53)
// Enerji raporlarında standart: Pazar değil Pazartesi başlangıçlı hafta (ISO)
// Kullanım: Haftalık tüketim bar chart'ı için eksen
WeekNumber = WEEKNUM('Date'[Date], 2)
// NOT: 2. parametre "2" = Pazartesi başlangıçlı hafta (ISO 8601 uyumlu)
// "1" kullansaydın Pazar başlangıçlı olurdu — enerji raporlarında ISO tercih et

// ── Kolon 2: YearWeek ────────────────────────────────────────────────────
// Yıl + hafta birleşimi (örn: "2025-W03") — grafikte eksen etiketi için
// Sıralama için YearWeekIndex kullan (aşağıda)
YearWeek = FORMAT('Date'[Date], "YYYY") & "-W" & FORMAT(WEEKNUM('Date'[Date], 2), "00")

// ── Kolon 3: YearWeekIndex ───────────────────────────────────────────────
// Sayısal hafta sıralama anahtarı: YearWeek'i bu kolona göre sırala
// YearWeek → Sort by column → YearWeekIndex
YearWeekIndex = YEAR('Date'[Date]) * 100 + WEEKNUM('Date'[Date], 2)

// ── Kolon 4: WeekStart (Haftanın Pazartesi tarihi) ───────────────────────
// Haftanın başlangıç tarihi — haftalık toplam görsellerde legend için
// Kullanım: Matrix satırı veya line chart x-ekseni
WeekStart = 'Date'[Date] - WEEKDAY('Date'[Date], 2) + 1
// WEEKDAY(date, 2): Pazartesi=1, Salı=2, ..., Pazar=7 döner
// date - (weekday-1) = o haftanın Pazartesisi

// ── Kolon 5: WeekStartLabel ──────────────────────────────────────────────
// Haftalık görseller için okunabilir etiket (örn: "17 Mar")
WeekStartLabel = FORMAT('Date'[Date] - WEEKDAY('Date'[Date], 2) + 1, "DD MMM")

// ── Kolon 6: IsCurrentWeek ───────────────────────────────────────────────
// Bu haftanın günleri için TRUE — "Current Week" slicer veya filtre için
// Dikkat: TODAY() anlık = her rapor açılışında güncellenir
IsCurrentWeek =
WEEKNUM('Date'[Date], 2) = WEEKNUM(TODAY(), 2)
    && YEAR('Date'[Date]) = YEAR(TODAY())

// ── Kolon 7: IsLastWeek ──────────────────────────────────────────────────
// Geçen haftanın günleri için TRUE
IsLastWeek =
VAR _currentWeek = WEEKNUM(TODAY(), 2)
VAR _currentYear = YEAR(TODAY())
VAR _lastWeekNum = IF(_currentWeek = 1, 52, _currentWeek - 1)
VAR _lastWeekYear = IF(_currentWeek = 1, _currentYear - 1, _currentYear)
RETURN
    WEEKNUM('Date'[Date], 2) = _lastWeekNum
    && YEAR('Date'[Date]) = _lastWeekYear

// ── Kolon 8: IsCurrentMonth ──────────────────────────────────────────────
// Bu ayın günleri için TRUE
IsCurrentMonth =
MONTH('Date'[Date]) = MONTH(TODAY())
    && YEAR('Date'[Date]) = YEAR(TODAY())

// ── Kolon 9: IsLastMonth ─────────────────────────────────────────────────
// Geçen ayın günleri için TRUE
IsLastMonth =
VAR _lastMonth = IF(MONTH(TODAY()) = 1, 12, MONTH(TODAY()) - 1)
VAR _lastYear  = IF(MONTH(TODAY()) = 1, YEAR(TODAY()) - 1, YEAR(TODAY()))
RETURN
    MONTH('Date'[Date]) = _lastMonth
    && YEAR('Date'[Date]) = _lastYear

// ── Kolon 10: DayOfWeekLabel ─────────────────────────────────────────────
// Gün adı kısaltması — haftalık dağılım bar chart için
// Pazartesi=1 başlangıçlı sıralama (ISO)
DayOfWeekLabel = FORMAT('Date'[Date], "DDD")
// Örnekler: "Mon", "Tue", ..., "Sun"

// ── Kolon 11: DayOfWeekIndex ─────────────────────────────────────────────
// DayOfWeekLabel sıralama anahtarı (Pazartesi=1)
// DayOfWeekLabel → Sort by column → DayOfWeekIndex
DayOfWeekIndex = WEEKDAY('Date'[Date], 2)
// 2 = Pazartesi=1 modu


// ==========================================================================
// BÖLÜM 2 — ÖLÇÜLER (Measures)
// Bunları semantic model'e "New measure" ile ekle
// ==========================================================================


// ==========================================================================
// A. LAST WEEK TIME INTELLIGENCE
// ==========================================================================

[Last Week Consumption kWh] =
// Geçen haftanın toplam elektrik tüketimi (Pazartesi–Pazar)
// Kullanım: Page 1 / Page 2 KPI card — "vs Last Week" karşılaştırması
// NOT: Date tablosunun gold_kpi_daily[date]'e bağlı olması gerekir
CALCULATE(
    [Total Consumption kWh],
    'Date'[IsLastWeek] = TRUE()
)

[Current Week Consumption kWh] =
// Bu haftanın tüketimi (Pazartesi'den bugüne)
CALCULATE(
    [Total Consumption kWh],
    'Date'[IsCurrentWeek] = TRUE()
)

[Week over Week Consumption Pct] =
// Bu hafta tüketimi / geçen hafta tüketimi karşılaştırması (%)
// Pozitif = artış, Negatif = azalış
// FORMAT: "0.0" (×100 yapılmış)
VAR _thisWeek = [Current Week Consumption kWh]
VAR _lastWeek = [Last Week Consumption kWh]
RETURN
DIVIDE(_thisWeek - _lastWeek, _lastWeek, BLANK()) * 100

[Week over Week Arrow] =
// WoW değişim için ok etiketi — KPI card conditional formatting için
VAR _pct = [Week over Week Consumption Pct]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 5,       "▲▲ " & FORMAT(_pct, "+0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(_pct, "+0.0") & "%",
    _pct < -5,      "▼▼ " & FORMAT(_pct, "0.0")  & "%",
    _pct < 0,       "▼ "  & FORMAT(_pct, "0.0")  & "%",
                    "→ 0.0%"
)

[Last Week Cost EUR] =
// Geçen haftanın enerji maliyeti (EUR)
CALCULATE(
    [Total Energy Cost EUR],
    'Date'[IsLastWeek] = TRUE()
)

[Last Week CO2 Emissions tCO2] =
// Geçen haftanın CO₂ emisyonu (metrik ton)
CALCULATE(
    [Total CO2 Emissions tCO2],
    'Date'[IsLastWeek] = TRUE()
)

[Last Week Peak Demand kW] =
// Geçen hafta maksimum güç talebi (kW)
CALCULATE(
    [Peak Demand kW],
    'Date'[IsLastWeek] = TRUE()
)

[Last Week Solar Generated kWh] =
// Geçen hafta güneş enerjisi üretimi
CALCULATE(
    [Solar Generated kWh],
    'Date'[IsLastWeek] = TRUE()
)

[WoW Solar Change Pct] =
// Güneş üretiminde haftalık değişim — hava koşulu etkisini takip için
VAR _thisWeek = CALCULATE([Solar Generated kWh], 'Date'[IsCurrentWeek] = TRUE())
VAR _lastWeek = [Last Week Solar Generated kWh]
RETURN
DIVIDE(_thisWeek - _lastWeek, _lastWeek, BLANK()) * 100


// ==========================================================================
// B. LAST MONTH TIME INTELLIGENCE
// ==========================================================================

[Last Month Consumption kWh] =
// Geçen ayın toplam tüketimi
// Kullanım: MoM trend, Page 1 KPI sparkline karşılaştırması
CALCULATE(
    [Total Consumption kWh],
    'Date'[IsLastMonth] = TRUE()
)

[Current Month Consumption kWh] =
// Bu ayın tüketimi (1'inden bugüne)
CALCULATE(
    [Total Consumption kWh],
    'Date'[IsCurrentMonth] = TRUE()
)

[Month over Month Consumption Pct] =
// Bu ay / geçen ay tüketim değişimi (%)
// Not: Ay tamamlanmamışsa eksik gün sayısı dikkate alınmaz — tam ay için kullan
// FORMAT: "0.0"
VAR _thisMonth = [Current Month Consumption kWh]
VAR _lastMonth = [Last Month Consumption kWh]
RETURN
DIVIDE(_thisMonth - _lastMonth, _lastMonth, BLANK()) * 100

[Month over Month Arrow] =
// MoM değişim ok etiketi
VAR _pct = [Month over Month Consumption Pct]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 10,      "▲▲ " & FORMAT(_pct, "+0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(_pct, "+0.0") & "%",
    _pct < -10,     "▼▼ " & FORMAT(_pct, "0.0")  & "%",
    _pct < 0,       "▼ "  & FORMAT(_pct, "0.0")  & "%",
                    "→ 0.0%"
)

[Last Month Cost EUR] =
// Geçen ayın enerji maliyeti
CALCULATE(
    [Total Energy Cost EUR],
    'Date'[IsLastMonth] = TRUE()
)

[Last Month CO2 Emissions tCO2] =
// Geçen ayın CO₂ emisyonu
CALCULATE(
    [Total CO2 Emissions tCO2],
    'Date'[IsLastMonth] = TRUE()
)

[Last Month Peak Demand kW] =
// Geçen ayın pik güç talebi
CALCULATE(
    [Peak Demand kW],
    'Date'[IsLastMonth] = TRUE()
)

[Last Month Solar Generated kWh] =
// Geçen ayın güneş üretimi
CALCULATE(
    [Solar Generated kWh],
    'Date'[IsLastMonth] = TRUE()
)

[MoM Cost Change Pct] =
// Maliyet değişimi ay bazında
VAR _thisMonth = CALCULATE([Total Energy Cost EUR], 'Date'[IsCurrentMonth] = TRUE())
VAR _lastMonth = [Last Month Cost EUR]
RETURN
DIVIDE(_thisMonth - _lastMonth, _lastMonth, BLANK()) * 100

[MoM CO2 Change Pct] =
// CO₂ değişimi ay bazında — emisyon azaltma hedefi takibi için
VAR _thisMonth = CALCULATE([Total CO2 Emissions tCO2], 'Date'[IsCurrentMonth] = TRUE())
VAR _lastMonth = [Last Month CO2 Emissions tCO2]
RETURN
DIVIDE(_thisMonth - _lastMonth, _lastMonth, BLANK()) * 100


// ==========================================================================
// C. ROLLING WINDOW MEASURES (Son N gün, hafta bağımsız)
// ==========================================================================
// NOT: Bu ölçüler Date tablosuna ihtiyaç duymaz — gold_kpi_daily[date]
// üzerinden çalışır. Slicer seçiminden etkilenmez (REMOVEFILTERS).

[Last 7 Days Consumption kWh] =
// Son 7 günün tüketimi — rolling pencere (bugün dahil)
// Slicer'dan bağımsız — her zaman son 7 günü gösterir
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate, -7, DAY)
)

[Last 30 Days Consumption kWh] =
// Son 30 günün tüketimi — rolling pencere
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate, -30, DAY)
)

[Last 7 Days Cost EUR] =
// Son 7 günün maliyeti
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total Energy Cost EUR],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate, -7, DAY)
)

[Last 30 Days Cost EUR] =
// Son 30 günün maliyeti
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total Energy Cost EUR],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate, -30, DAY)
)

[Last 7 Days CO2 tCO2] =
// Son 7 günün CO₂ emisyonu
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total CO2 Emissions tCO2],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate, -7, DAY)
)

[Last 30 Days CO2 tCO2] =
// Son 30 günün CO₂ emisyonu
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total CO2 Emissions tCO2],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate, -30, DAY)
)


// ==========================================================================
// D. WEEKLY KPI CARDS — Özellikle Page 1 / Page 2 için
// ==========================================================================

[Card: Last Week vs Previous Week Pct] =
// Page 1 KPI card: Geçen hafta / bir önceki hafta karşılaştırması
// (Bugünkü hafta henüz tamamlanmadı, daha sağlıklı karşılaştırma)
VAR _last = [Last Week Consumption kWh]
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _twoWeeksAgo = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate - 7, -7, DAY)
)
RETURN
DIVIDE(_last - _twoWeeksAgo, _twoWeeksAgo, BLANK()) * 100

[Card: Last Month vs Previous Month Pct] =
// Page 1 KPI card: Geçen ay / bir önceki ay
VAR _lastMonth = [Last Month Consumption kWh]
VAR _prevMonth = CALCULATE(
    [Total Consumption kWh],
    PREVIOUSMONTH(DATESINPERIOD('Date'[Date], MIN('Date'[Date]), 0, DAY))
)
RETURN
DIVIDE(_lastMonth - _prevMonth, _prevMonth, BLANK()) * 100

[Card: Weekly Avg Consumption kWh] =
// Son 4 haftanın haftalık ortalama tüketimi — trend baseline için
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _28days = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESINPERIOD(gold_kpi_daily[date], _maxDate, -28, DAY)
)
RETURN
DIVIDE(_28days, 4, BLANK())


// ==========================================================================
// KURULUM NOTU — Sort by Column (Haftalık Görseller)
// ==========================================================================
// Date tablosuna kolonları ekledikten sonra:
//
//   YearWeek    → Sort by column → YearWeekIndex
//   WeekStartLabel → Sort by column → WeekStart (DATE olarak)
//   DayOfWeekLabel → Sort by column → DayOfWeekIndex
//
// YearWeek'i grafik X-ekseni olarak kullanırsan sol panel → "Sort axis" →
// "YearWeek ascending" yerine "YearWeekIndex ascending" seçmeyi unutma.
//
// Haftalık tüketim grafiği için önerilen görsel:
//   X-ekseni: YearWeek (sıralama: YearWeekIndex)
//   Değer: [Total Consumption kWh]
//   Gösterge (legend): building_name (bina bazlı renklendirme için)
//   Görsel tipi: Clustered Bar veya Line Chart
// ==========================================================================

// ==========================================================================
// END OF 14_dax_v9_date_weekly.dax
// ==========================================================================
