// ==========================================================================
// Energy Copilot Platform — DAX v10: Report Review Fixes
// File: semantic-model/15_dax_v10_review_fixes.dax
// Last updated: 2026-04-20
// Kaynak: 2026-04-20 tarihli "Energy Co Pilot.pdf" rapor review'u
//
// AMAÇ:
//   PDF review'unda tespit edilen bozuk / boş / yanlış formatlı
//   KPI ve ölçüleri düzeltmek. Eski ölçüleri SİLMEYIN — bunlar
//   "Display" / "Safe" sarmalayıcılarıdır; mevcut DAX v3–v9 ölçüleri
//   olduğu gibi kalacak.
//
// DOSYA YAPISI (5 BÖLÜM):
//   BÖLÜM 1 — Percent format fix ölçüleri (0-100 döndüren ama
//             "0%" format'ı yüzünden şişen değerler için)
//   BÖLÜM 2 — BLANK / Infinity% karşı güvenli sarmalayıcılar
//   BÖLÜM 3 — Sayfa 3 anomali dağılımı doğru formülü
//   BÖLÜM 4 — Sayfa 4 Forecast güven aralığı (confidence band)
//   BÖLÜM 5 — Sayfa 6 CO₂ trend ölçek düzeltmesi + Sayfa 7 HVAC Share fix
//
// KURULUM:
//   Power BI Desktop → Model view → Home → New Measure (her biri için)
//   Display name'leri mevcut ölçülerle çakışmayacak şekilde "Display" ya da
//   "Safe" eki aldı — visual'ları yeni ölçülere yönlendirin.
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — PERCENT FORMAT SAFE ÖLÇÜLERİ
// Sorun: DAX v3–v9'daki tüm "Pct" ölçüleri 0–100 değer döndürür
//        ("0.0" format'ı ile kullanılmak üzere).
//        Bazı kartlarda yanlışlıkla "0%" format'ı seçilmiş → Power BI
//        değeri ×100 yapıp % ekler → "37.98" değeri "%3798" görünür
//        (Sayfa 5 Avg Occupancy Rate bug'ı).
//
// İKİ SEÇENEK:
//   A) Kart format'ını "0.00" + string suffix " %" yap (ÖNERİLEN)
//   B) Aşağıdaki "Ratio" ölçülerini kullan — bunlar 0–1 döndürür,
//      "0.00%" format'ı ile doğru görünür.
// ==========================================================================

// ── Sayfa 5: Avg Occupancy Rate — Ratio formunda (0-1)
Avg Occupancy Rate Ratio =
DIVIDE ( [Avg Occupancy Rate Pct], 100 )
// Kullanım: Card format → "0.00%"
// Sonuç: 37.98 → "37.98%" (doğru görünür)

// ── Sayfa 7: HVAC Share — Ratio formunda
HVAC Share Ratio =
DIVIDE ( [HVAC Share Pct], 100 )

// ── Sayfa 6: Renewable Share — Ratio formunda
Renewable Energy Rate Ratio =
DIVIDE ( [Renewable Energy Rate Pct], 100 )

// ── Sayfa 3: Data Quality fallback — Ratio formunda
Active Anomaly Rate Ratio =
DIVIDE ( [Active Anomaly Rate Pct], 100 )


// ==========================================================================
// BÖLÜM 2 — BLANK / INFINITY% KARŞI GÜVENLİ SARMALAYICILAR
// Sorun: Bazı KPI kartları "Goal: Blank (+∞%)" ya da "(-100%)"
//        gösteriyor çünkü prior period veya target yok.
//        Manager için okunamaz — "n/a" davranışı gerekiyor.
// ==========================================================================

// ── Sayfa 1 & 2: Last Week YoY — prior period boşsa BLANK dön
LW Consumption YoY Pct Safe =
VAR _current = [LW Consumption kWh]
VAR _prior   = CALCULATE ( [LW Consumption kWh], DATEADD ( 'Date'[Date], -1, YEAR ) )
RETURN
    IF (
        ISBLANK ( _prior ) || _prior = 0,
        BLANK (),
        DIVIDE ( _current - _prior, _prior ) * 100
    )
// Kullanım: Sayfa 1 C7 kartı — format "+0.0;-0.0;—"
// Prior period boşsa kartta tire (—) görünür, "-100%" değil.

// ── Sayfa 1 & 2: Last Month MoM — aynı mantık
LM Consumption MoM Pct Safe =
VAR _current = [LM Consumption kWh]
VAR _prior   = CALCULATE ( [LM Consumption kWh], DATEADD ( 'Date'[Date], -1, MONTH ) )
RETURN
    IF (
        ISBLANK ( _prior ) || _prior = 0,
        BLANK (),
        DIVIDE ( _current - _prior, _prior ) * 100
    )

// ── Sayfa 2: Energy per Occupant — sıfıra bölmeyi önle
Energy per Occupant Safe =
DIVIDE (
    [Total Consumption kWh],
    [Total Occupancy Hours],
    BLANK ()  // 0 yerine BLANK — kartta "(Blank)" görünsün, "∞" değil
)

// ── Sayfa 6: Net CO₂ Display — savings yoksa gross değeri göster
Net CO2 Emissions tCO2 Display =
COALESCE (
    [Net CO2 Emissions tCO2],
    [Gross CO2 Emissions tCO2]
)
// Net Carbon Footprint tCO2 ölçüsü savings olmadığında BLANK döner.
// Bu sarmalayıcı gross'a düşer — manager "Blank" yerine gerçek değer görür.

// ── Sayfa 7: Avg COP Display — gaz binalarında "n/a (gas)" etiketi
Avg COP Display =
IF (
    ISBLANK ( [COP Monthly Actual] ),
    "n/a",            // Text — Card visual kabul eder
    FORMAT ( [COP Monthly Actual], "0.00" )
)
// NOT: Bu ölçü string döner. Sadece "Card (new)" visual'ında kullan,
// "KPI" visual'ında değil. KPI için ayrıca numeric ölçüyü kullan.


// ==========================================================================
// BÖLÜM 3 — SAYFA 3 ANOMALI DAĞILIMI DÜZELTMESİ
// Sorun: Current visual "0.1%, 0.1%, 0.0%" gösteriyor — bölen yanlış
//        (muhtemelen TÜM rows üzerinden, filtrelenmemiş).
//        Doğru formül: seçili bina anomalileri / portföyün tamamı
// ==========================================================================

Building Anomaly Share Pct =
VAR _building_anomalies = [Active Anomaly Count]
VAR _portfolio_anomalies =
    CALCULATE (
        [Active Anomaly Count],
        ALL ( silver_building_master )
    )
RETURN
    DIVIDE ( _building_anomalies, _portfolio_anomalies ) * 100
// Format: "0.0"
// Kullanım: Sayfa 3 V4 "Building-Based Distribution" bar chart
// X: silver_building_master[building_name]
// Y: Building Anomaly Share Pct
// Sonuç: her bina için % of total anomalies (toplamı ~100 olmalı)


// ==========================================================================
// BÖLÜM 4 — SAYFA 4 FORECAST GÜVEN ARALIĞI (CONFIDENCE BAND)
// Sorun: Current "Forecast + Confidence Interval" visual'ı düz bir çizgi
//        gösteriyor — güven bandı yok. Area series ekle.
//
// Not: Eğer ML notebook çıktısı gold_forecast_daily tablosunda
//      "forecast_lower_95" / "forecast_upper_95" kolonları yoksa
//      aşağıdaki ölçülere ihtiyacın yok — Notebook tarafında çıkarım
//      yapılması gerekir. Eğer varsa, aşağıdakileri kullan.
// ==========================================================================

Forecast Lower 95 kWh =
SUM ( gold_forecast_daily[forecast_lower_95] )

Forecast Upper 95 kWh =
SUM ( gold_forecast_daily[forecast_upper_95] )

// Visual kurulumu:
//   Line and stacked column chart
//   Column Y-axis: Forecast Lower 95 kWh (şeffaf, band alt sınırı için)
//   Column Y-axis: Forecast Upper 95 kWh  — Lower'dan farkı bandı oluşturur
//   Line Y-axis:   Predicted Consumption kWh (ana tahmin çizgisi)
//   Line Y-axis:   Total Consumption kWh (gerçekleşen — kıyas için)
// Alternatif: Deneb custom visual ile native area band (daha temiz)


// ==========================================================================
// BÖLÜM 5 — SAYFA 6 CO₂ TREND ÖLÇEK + SAYFA 7 HVAC SHARE FIX
// ==========================================================================

// ── Sayfa 6: CO₂ Trend kg → tCO₂ ölçek düzeltmesi
// Sorun: Current chart Y ekseni 4,000,000 tCO₂ gösteriyor — imkansız.
//        Muhtemelen kg değeri tCO₂ etiketiyle çiziliyor.
// Çözüm: Doğru birime dönüş ölçüsü.

Total CO2 Emissions tCO2 Display =
DIVIDE ( [Total CO2 Emissions kg], 1000 )
// Format: "#,##0.0"
// Kullanım: Sayfa 6 "CO2 Emission Trend (Annual)" line chart Y-ekseni
// ALTERNATIF: Mevcut "Total CO2 Emissions tCO2" ölçüsünü kullan
//             (eğer Gross CO2 Emissions tCO2 zaten doğru birimdeyse).
//             Bu ölçüyü sadece birim karışıklığı tespit edersen kullan.

// ── Sayfa 7: HVAC Share Pct — DOĞRU denominator
// Sorun: Current value 2.4% — ofisler için benchmark 40–60%
//        Denominator büyük olasılıkla TÜM binaların toplam tüketimi,
//        filtrelenmemiş. Aynı filter context içinde olmalı.
//
// NOT: Eğer mevcut HVAC Share Pct ölçüsü zaten doğruysa (aşağıdaki
//      gibi), sorun filtre seçiminde olabilir — building slicer
//      seçilmediğinde ortalama alınmayıp toplam/toplam hesaplanıyor.
//      Bu ölçü onu garantiler.

HVAC Share Pct Safe =
DIVIDE (
    [HVAC Total kWh],
    [Total Consumption kWh],
    BLANK ()
) * 100
// Aynı filter context — slicer seçimi her iki tarafa uygulanır.
// Beklenen sonuç: 40–60% (ofis), 20–40% (retail), 50–70% (hastane)

// ── Sayfa 7: Heat Loss Display — boşsa placeholder
Heat Loss kWh m2 Display =
IF (
    ISBLANK ( [Heat Loss kWh m2 Month] ),
    BLANK (),
    [Heat Loss kWh m2 Month]
)
// (Identity wrapper — yalnızca KPI card'ın boşluklarda "(Blank)"
//  değil "—" göstermesi için format string'inde tire kullan.)


// ==========================================================================
// KULLANIM TABLOSU — YENİ ÖLÇÜLERİ NEREYE BAĞLAYACAKSIN
//
// Sayfa 1 Card C7  : LW Consumption YoY Pct Safe
// Sayfa 1 Card C9  : LM Consumption MoM Pct Safe
// Sayfa 2 Card     : Energy per Occupant Safe  (varsa)
// Sayfa 3 Card 5   : Active Anomaly Rate Ratio (format 0.00%)
// Sayfa 3 V4       : Building Anomaly Share Pct (format 0.0)
// Sayfa 4 V3       : Forecast Lower 95 kWh + Forecast Upper 95 kWh
// Sayfa 5 Card 1   : Avg Occupancy Rate Ratio (format 0.00%)
// Sayfa 6 Card 1   : Net CO2 Emissions tCO2 Display
// Sayfa 6 Card 4   : Renewable Energy Rate Ratio (format 0.00%)
// Sayfa 6 V2       : Total CO2 Emissions tCO2 Display
// Sayfa 7 Card 2   : Avg COP Display (Card visual, string ölçü)
// Sayfa 7 Card 3   : HVAC Share Ratio (format 0.00%)
//                    veya HVAC Share Pct Safe (format 0.0 + "%" suffix)
// ==========================================================================

// SON
