// ==========================================================================
// Energy Copilot Platform — DAX v12: Stranding Year Fix
// File: semantic-model/17_dax_v12_stranding_year_fix.dax
// Last updated: 2026-04-23
//
// SORUN:
//   Mevcut [Stranding Year] ölçüsü (02_dax_measures.dax, line 1114) iki
//   yanlış kolon adı kullanıyor:
//     ❌ gold_crrem_pathway[pathway_kgco2_m2_yr]  → böyle bir kolon YOK
//     ❌ gold_crrem_pathway[year]                 → böyle bir kolon YOK
//
//   Doğru kolon adları (10_crrem_pathway_loader.py'den):
//     ✅ gold_crrem_pathway[pathway_2c_kgco2_m2_yr]  (2°C senaryo hedefi)
//     ✅ gold_crrem_pathway[pathway_year]              (yıl — INT)
//
//   Ayrıca [Carbon Intensity kgCO2 m2 yr] yerine artık
//   [GHG Intensity kgCO2 m2 yr] (12_dax_v7_ghg_crrem.dax) kullanılmalı
//   çünkü artık gold_ghg_scope tablosu mevcut ve daha doğru emisyon hesabı yapıyor.
//
// KURULUM:
//   Power BI Desktop → New Measure
//   "Stranding Year" adını yaz, formülü yapıştır → Enter
//   ESKİ ölçünün üzerine yazar.
// ==========================================================================


// ==========================================================================
// [Stranding Year] — DÜZELTİLMİŞ VERSİYON
//
// MANTIK:
//   1. Seçili portföy/bina için mevcut GHG yoğunluğunu al (kgCO2/m²/yıl)
//   2. Aynı bina türü + ülke için bu yılın CRREM 2°C hedefini bul
//   3. Zaten hedefin üstündeysek → şu yıl zaten stranded
//   4. Altındaysak → pathway ne kadar düşüyor? Bina ne zaman geçilir?
//      Doğrusal projeksiyon ile hesapla.
//
// VARSAYIM:
//   Binanın emisyon yoğunluğunun SABIT KALMASI durumunu hesaplar
//   (en kötü durum senaryosu — bina iyileştirme yapmaz).
//   Gerçek stranding yılı iyileştirme planına göre değişir.
//
// FORMAT: "0"  (yıl: 2031 gibi tam sayı)
// Sayfa 6 → CRREM kart veya tooltip
// ==========================================================================

Stranding Year =
VAR _currentIntensity = [GHG Intensity kgCO2 m2 yr]
VAR _currentYear      = YEAR(TODAY())

// Bu yıl için CRREM 2°C hedefi (AVERAGEX: portföydeki her bina kendi bina türü
// ve ülkesine ait pathway değerini alır, ağırlıklı ortalama döner)
VAR _pathwayCurrent =
    AVERAGEX(
        VALUES(silver_building_master[building_id]),
        VAR _btype   = LOOKUPVALUE(
                           silver_building_master[building_type],
                           silver_building_master[building_id],
                           silver_building_master[building_id]
                       )
        VAR _country = LOOKUPVALUE(
                           silver_building_master[country_code],
                           silver_building_master[building_id],
                           silver_building_master[building_id]
                       )
        RETURN
        COALESCE(
            LOOKUPVALUE(
                gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
                gold_crrem_pathway[building_type], _btype,
                gold_crrem_pathway[country_code],  _country,
                gold_crrem_pathway[pathway_year],  _currentYear
            ),
            LOOKUPVALUE(
                gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
                gold_crrem_pathway[building_type], _btype,
                gold_crrem_pathway[country_code],  "EU",
                gold_crrem_pathway[pathway_year],  _currentYear
            ),
            LOOKUPVALUE(
                gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
                gold_crrem_pathway[building_type], "office",
                gold_crrem_pathway[country_code],  "EU",
                gold_crrem_pathway[pathway_year],  _currentYear
            )
        )
    )

// Bir sonraki yılın CRREM hedefi (pathway eğimini hesaplamak için)
VAR _pathwayNext =
    AVERAGEX(
        VALUES(silver_building_master[building_id]),
        VAR _btype   = LOOKUPVALUE(
                           silver_building_master[building_type],
                           silver_building_master[building_id],
                           silver_building_master[building_id]
                       )
        VAR _country = LOOKUPVALUE(
                           silver_building_master[country_code],
                           silver_building_master[building_id],
                           silver_building_master[building_id]
                       )
        RETURN
        COALESCE(
            LOOKUPVALUE(
                gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
                gold_crrem_pathway[building_type], _btype,
                gold_crrem_pathway[country_code],  _country,
                gold_crrem_pathway[pathway_year],  _currentYear + 1
            ),
            LOOKUPVALUE(
                gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
                gold_crrem_pathway[building_type], _btype,
                gold_crrem_pathway[country_code],  "EU",
                gold_crrem_pathway[pathway_year],  _currentYear + 1
            ),
            LOOKUPVALUE(
                gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
                gold_crrem_pathway[building_type], "office",
                gold_crrem_pathway[country_code],  "EU",
                gold_crrem_pathway[pathway_year],  _currentYear + 1
            )
        )
    )

// Yıllık pathway düşüş hızı (negatif olmalı — pathway düşüyor)
VAR _pathwaySlope = _pathwayNext - _pathwayCurrent

// Mevcut yoğunluk ile pathway arasındaki fark
// Pozitif = zaten pathway üzerindeyiz = stranded
// Negatif = pathway altındayız = henüz güvende
VAR _excessNow = _currentIntensity - _pathwayCurrent

RETURN
    IF(
        ISBLANK(_currentIntensity) || ISBLANK(_pathwayCurrent),
        BLANK(),
        IF(
            _excessNow >= 0,
            // Şu an pathway üzerinde → zaten stranded, bu yıl dön
            _currentYear,
            IF(
                _pathwaySlope >= 0 || ISBLANK(_pathwaySlope),
                // Pathway düşmüyor (veri yok veya yanlış) → hesaplanamaz
                BLANK(),
                // Binanın sabit yoğunluğu ile düşen pathway ne zaman kesişir?
                // excess / pathway_slope = kaç yıl sonra geçer
                // (excess negatif, slope negatif → bölen pozitif → doğru yıl)
                _currentYear + INT(DIVIDE(ABS(_excessNow), ABS(_pathwaySlope), BLANK()))
            )
        )
    )


// ==========================================================================
// YARDIMCI: Stranding Gap by Building (Tablo / Matrix için)
// Her bina için CRREM 2°C hedefine uzaklık (kgCO2/m²/yıl)
// Pozitif = pathway üzerinde = risk, Negatif = uyumlu
// Format: "+0.0;-0.0;—"
// Sayfa 6 → Building-level CRREM tablo visual'ı
// ==========================================================================

CRREM Gap by Building kgCO2 m2 =
VAR _intensity = [GHG Intensity kgCO2 m2 yr]
VAR _currentYear = YEAR(TODAY())
VAR _btype =
    SELECTEDVALUE(silver_building_master[building_type], "office")
VAR _country =
    SELECTEDVALUE(silver_building_master[country_code], "EU")
VAR _pathway =
    COALESCE(
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  _currentYear
        ),
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _currentYear
        ),
        LOOKUPVALUE(
            gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _currentYear
        )
    )
RETURN
    IF(
        ISBLANK(_intensity) || ISBLANK(_pathway),
        BLANK(),
        _intensity - _pathway
    )
