// ==========================================================================
// Energy Copilot Platform — DAX v13: CRREM Tam Düzeltme
// File: semantic-model/18_dax_v13_crrem_complete_fix.dax
// Last updated: 2026-04-23
//
// BU DOSYA ŞU ÖLÇÜLERİN YERİNİ ALIR:
//   eski: 02_dax_measures.dax → CRREM Pathway 1p5C + Stranding Year (bozuk)
//   eski: 12_dax_v7_ghg_crrem.dax → CRREM Pathway 2C/15C/Target/Gap/Status
//   eski: 17_dax_v12_stranding_year_fix.dax → Stranding Year (hala bozuk)
//
// SORUNLAR VE ÇÖZÜMLER:
//
//   SORUN 1 — Yanlış kolon adları (02_dax_measures.dax'ta):
//     ❌ gold_crrem_pathway[pathway_kgco2_m2_yr]  → kolon yok
//     ❌ gold_crrem_pathway[year]                 → kolon yok
//     ✅ gold_crrem_pathway[pathway_2c_kgco2_m2_yr]
//     ✅ gold_crrem_pathway[pathway_year]
//
//   SORUN 2 — Kırmızı 'Date'[Year] (12_dax_v7_ghg_crrem.dax'ta):
//     ❌ SELECTEDVALUE('Date'[Year], YEAR(TODAY()))
//        → 'Date' tablosunda 'Year' kolonu adı farklıysa hata
//     ✅ YEAR(MAX('Date'[Date]))
//        → Date[Date] (tarih kolonu) her zaman var, tipi DATE
//        → Line chart X ekseni = Date[Year] olduğunda her yıl için doğru değeri döner
//        → Card (filtresiz) olduğunda datasetteki son tarihin yılını döner
//
//   SORUN 3 — Stranding Year bozuk:
//     ❌ Projection yaklaşımı: slope hesaplama, GHG Intensity'ye bağımlı
//        → GHG Intensity BLANK olunca tüm hesap BLANK döner
//     ✅ Doğrudan tablo lookup: gold_crrem_pathway üzerinden
//        MIN(pathway_year WHERE pathway_2c < current_intensity)
//        → Carbon Intensity kgCO2 m2 yr kullanır (gold_kpi_daily bazlı, daha güvenilir)
//        → FILTER + ALL ile relationship bağımsız çalışır
//
// KURULUM:
//   Power BI Desktop → New Measure
//   Her ölçünün adını ve formülünü yapıştır → Enter
//   ESKİ aynı adlı ölçülerin üzerine yazar.
// ==========================================================================


// ══════════════════════════════════════════════════════════════════════════
// BÖLÜM 1 — CRREM PATHWAY LOOKUP ÖLÇÜLERI (YIL DÜZELTİLDİ)
//
// NASIL ÇALIŞIR:
//   _year = YEAR(MAX('Date'[Date]))
//   → Line chart'ta Date[Year] X-ekseninde kullanıldığında:
//     her yıl için o yılın MAX tarihi = o yılın son günü → YEAR() = o yıl ✅
//   → Card'da yıl filtresi yokken:
//     datasetteki son tarih = 2024-12-31 → YEAR() = 2024 ✅
//   → Hiçbir zaman kırmızı vermez çünkü 'Date'[Date] standart DATE kolonu
// ══════════════════════════════════════════════════════════════════════════

// ── CRREM 2°C Pathway (kgCO₂/m²/yıl)
// Sayfa 6 → V6 Line Chart seri 2 (dashed) + Kart 5 hedef
// Format: "0.0"
CRREM Pathway 2C kgCO2 m2 yr =
VAR _year = YEAR(MAX('Date'[Date]))
RETURN
AVERAGEX(
    VALUES(silver_building_master[building_id]),
    VAR _btype   = LOOKUPVALUE(silver_building_master[building_type],
                               silver_building_master[building_id],
                               silver_building_master[building_id])
    VAR _country = LOOKUPVALUE(silver_building_master[country_code],
                               silver_building_master[building_id],
                               silver_building_master[building_id])
    RETURN
    COALESCE(
        LOOKUPVALUE(gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  _year),
        LOOKUPVALUE(gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year),
        LOOKUPVALUE(gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year)
    )
)

// ── CRREM 1.5°C Pathway (kgCO₂/m²/yıl)
// Sayfa 6 → V6 Line Chart seri 3 (dashed, farklı renk)
// Format: "0.0"
CRREM Pathway 15C kgCO2 m2 yr =
VAR _year = YEAR(MAX('Date'[Date]))
RETURN
AVERAGEX(
    VALUES(silver_building_master[building_id]),
    VAR _btype   = LOOKUPVALUE(silver_building_master[building_type],
                               silver_building_master[building_id],
                               silver_building_master[building_id])
    VAR _country = LOOKUPVALUE(silver_building_master[country_code],
                               silver_building_master[building_id],
                               silver_building_master[building_id])
    RETURN
    COALESCE(
        LOOKUPVALUE(gold_crrem_pathway[pathway_15c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  _year),
        LOOKUPVALUE(gold_crrem_pathway[pathway_15c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year),
        LOOKUPVALUE(gold_crrem_pathway[pathway_15c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year)
    )
)

// ── CRREM 2°C Pathway Hedefi (mutlak tCO₂/yıl)
// Alan × pathway × yıl kesri → tCO₂ cinsinden yıllık hedef
// Sayfa 6 Kart 5 → KPI Target goals alanı
// Format: "#,##0.0"
CRREM Pathway Target tCO2 Yr =
VAR _pathway_kg_m2  = [CRREM Pathway 2C kgCO2 m2 yr]
VAR _area           = SUM(silver_building_master[conditioned_area_m2])
VAR _months         = DISTINCTCOUNT(gold_ghg_scope[year_month])
VAR _year_fraction  = DIVIDE(_months, 12, 1)
RETURN
DIVIDE(
    _pathway_kg_m2 * _area * _year_fraction,
    1000,
    BLANK()
)

// ── CRREM Stranding Gap (kgCO₂/m²/yıl fark)
// Pozitif = pathway aşıldı = risk, Negatif = uyumlu
// Sayfa 6 → KPI kart (Low is Good, conditional formatting)
// Format: "+0.0;-0.0;—"
CRREM Stranding Gap kgCO2 m2 yr =
[GHG Intensity kgCO2 m2 yr] - [CRREM Pathway 2C kgCO2 m2 yr]

// ── CRREM Uyumluluk Durumu (metin etiketi)
// Sayfa 6 → Metin kartı veya tooltip
// Format: text (Card visual kullan, KPI visual değil)
CRREM Stranding Status =
VAR _gap = [CRREM Stranding Gap kgCO2 m2 yr]
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_gap),   "— No data",
    _gap <= -10,     "✅ Well Below Pathway",
    _gap <=   0,     "✅ On Track",
    _gap <=  15,     "⚠ At Risk",
                     "🔴 Stranded Asset Risk"
)

// ── CRREM 2020 Benchmark (sektör başlangıç noktası)
// Sayfa 6 V6 → Line chart referans çizgisi
// Format: "0.0"
CRREM Benchmark 2020 =
AVERAGEX(
    VALUES(silver_building_master[building_id]),
    VAR _btype   = LOOKUPVALUE(silver_building_master[building_type],
                               silver_building_master[building_id],
                               silver_building_master[building_id])
    VAR _country = LOOKUPVALUE(silver_building_master[country_code],
                               silver_building_master[building_id],
                               silver_building_master[building_id])
    RETURN
    COALESCE(
        LOOKUPVALUE(gold_crrem_pathway[sector_benchmark_2020],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  2020),
        LOOKUPVALUE(gold_crrem_pathway[sector_benchmark_2020],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  2020)
    )
)


// ══════════════════════════════════════════════════════════════════════════
// BÖLÜM 2 — STRANDING YEAR (TAMAMEN YENİDEN YAZILDI)
//
// YENİ YAKLAŞIM — Doğrudan tablo lookup (projection değil):
//   Stranding year = gold_crrem_pathway'de pathway_2c < mevcut yoğunluk
//   olan en erken yıl (pathway_year >= bugün filtreliyle)
//
// NEDEN DAHA İYİ:
//   ✅ gold_ghg_scope'a bağımlı değil → her zaman çalışır
//   ✅ Carbon Intensity kgCO2 m2 yr kullanır (gold_kpi_daily bazlı)
//   ✅ FILTER+ALL → relationship bağımsız (semantic model ilişkisi olmasa da çalışır)
//   ✅ COALESCE: tam eşleşme → EU fallback → office/EU fallback
//   ✅ Hiçbir kırmızı referans yok
//
// YORUM:
//   "Bu bina bugünkü performansıyla devam ederse,
//    CRREM 2°C pathway X yılında bu binayı geçecek."
//   Düşük = kötü (erken stranding). Yüksek = iyi (geç veya hiç stranded olmama).
// ══════════════════════════════════════════════════════════════════════════

// ── Stranding Year
// Sayfa 6 → Kart (tek bina seçilince anlamlı, portföyde en erken yılı gösterir)
// Format: "0"  (tam yıl: 2031)
Stranding Year =
VAR _intensity = [Carbon Intensity kgCO2 m2 yr]
VAR _btype     = SELECTEDVALUE(silver_building_master[building_type], "office")
VAR _country   = SELECTEDVALUE(silver_building_master[country_code], "EU")
VAR _today     = YEAR(TODAY())

// Tam eşleşme: bina türü + ülke
VAR _exact =
    MINX(
        FILTER(
            ALL(gold_crrem_pathway),
            gold_crrem_pathway[building_type]         = _btype
            && gold_crrem_pathway[country_code]       = _country
            && gold_crrem_pathway[pathway_2c_kgco2_m2_yr] < _intensity
            && gold_crrem_pathway[pathway_year]       >= _today
        ),
        gold_crrem_pathway[pathway_year]
    )

// Fallback 1: aynı bina türü, EU ülkesi
VAR _eu_fb =
    MINX(
        FILTER(
            ALL(gold_crrem_pathway),
            gold_crrem_pathway[building_type]         = _btype
            && gold_crrem_pathway[country_code]       = "EU"
            && gold_crrem_pathway[pathway_2c_kgco2_m2_yr] < _intensity
            && gold_crrem_pathway[pathway_year]       >= _today
        ),
        gold_crrem_pathway[pathway_year]
    )

// Fallback 2: office + EU (genel)
VAR _off_fb =
    MINX(
        FILTER(
            ALL(gold_crrem_pathway),
            gold_crrem_pathway[building_type]         = "office"
            && gold_crrem_pathway[country_code]       = "EU"
            && gold_crrem_pathway[pathway_2c_kgco2_m2_yr] < _intensity
            && gold_crrem_pathway[pathway_year]       >= _today
        ),
        gold_crrem_pathway[pathway_year]
    )

VAR _result = COALESCE(_exact, _eu_fb, _off_fb)

RETURN
IF(
    ISBLANK(_intensity),
    BLANK(),
    IF(
        ISBLANK(_result),
        // Pathway hiç bina yoğunluğunun altına düşmüyor → 2050 sonrası (pratik: 2050)
        2050,
        _result
    )
)


// ══════════════════════════════════════════════════════════════════════════
// BÖLÜM 3 — BINA BAZLI CRREM DURUM TABLOSU
// Sayfa 6 → Table/Matrix visual için satır bazlı ölçüler
// ══════════════════════════════════════════════════════════════════════════

// ── Bina bazında CRREM fark (Tablo visual için)
// Pozitif = stranding riski, Negatif = uyumlu
// Format: "+0.0;-0.0;—"
CRREM Gap by Building kgCO2 m2 =
VAR _intensity = [Carbon Intensity kgCO2 m2 yr]
VAR _year      = YEAR(MAX('Date'[Date]))
VAR _btype     = SELECTEDVALUE(silver_building_master[building_type], "office")
VAR _country   = SELECTEDVALUE(silver_building_master[country_code], "EU")
VAR _pathway =
    COALESCE(
        LOOKUPVALUE(gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  _country,
            gold_crrem_pathway[pathway_year],  _year),
        LOOKUPVALUE(gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], _btype,
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year),
        LOOKUPVALUE(gold_crrem_pathway[pathway_2c_kgco2_m2_yr],
            gold_crrem_pathway[building_type], "office",
            gold_crrem_pathway[country_code],  "EU",
            gold_crrem_pathway[pathway_year],  _year)
    )
RETURN
IF(
    ISBLANK(_intensity) || ISBLANK(_pathway),
    BLANK(),
    _intensity - _pathway
)

// ── Bina bazında Stranding Year (Tablo visual için)
// Table'da her bina satırında kendi stranding yılını gösterir
// Format: "0"
Stranding Year by Building =
VAR _intensity = [Carbon Intensity kgCO2 m2 yr]
VAR _btype     = SELECTEDVALUE(silver_building_master[building_type], "office")
VAR _country   = SELECTEDVALUE(silver_building_master[country_code], "EU")
VAR _today     = YEAR(TODAY())
VAR _exact =
    MINX(FILTER(ALL(gold_crrem_pathway),
        gold_crrem_pathway[building_type]   = _btype
        && gold_crrem_pathway[country_code] = _country
        && gold_crrem_pathway[pathway_2c_kgco2_m2_yr] < _intensity
        && gold_crrem_pathway[pathway_year] >= _today),
        gold_crrem_pathway[pathway_year])
VAR _eu_fb =
    MINX(FILTER(ALL(gold_crrem_pathway),
        gold_crrem_pathway[building_type]   = _btype
        && gold_crrem_pathway[country_code] = "EU"
        && gold_crrem_pathway[pathway_2c_kgco2_m2_yr] < _intensity
        && gold_crrem_pathway[pathway_year] >= _today),
        gold_crrem_pathway[pathway_year])
RETURN
IF(ISBLANK(_intensity), BLANK(),
    COALESCE(_exact, _eu_fb, _today))


// ══════════════════════════════════════════════════════════════════════════
// BÖLÜM 4 — KULLANIM HARİTASI
//
// SAYFA 6 — Sustainability & Compliance
// ┌─────────────────────────────────────────────────────────────────────┐
// │ Kart / KPI           │ Ölçü                         │ Format      │
// ├─────────────────────────────────────────────────────────────────────┤
// │ GHG Intensity Kart   │ GHG Intensity kgCO2 m2 yr    │ "0.0"       │
// │   Target Goals       │ CRREM Pathway 2C kgCO2 m2 yr │             │
// │   Yön                │ Low is Good                  │             │
// ├─────────────────────────────────────────────────────────────────────┤
// │ CRREM Status Kart    │ CRREM Stranding Status        │ text        │
// ├─────────────────────────────────────────────────────────────────────┤
// │ Stranding Year Kart  │ Stranding Year                │ "0"         │
// │   (bina seçilince)   │ (bina slicer'dan seç)        │             │
// ├─────────────────────────────────────────────────────────────────────┤
// │ V6 Line Chart        │ X: Date[Year]                 │             │
// │   Seri 1 (gerçek)    │ GHG Intensity kgCO2 m2 yr    │ solid       │
// │   Seri 2 (2°C)       │ CRREM Pathway 2C kgCO2 m2 yr │ dashed      │
// │   Seri 3 (1.5°C)     │ CRREM Pathway 15C kgCO2 m2 yr│ dashed      │
// │   Seri 4 (benchmark) │ CRREM Benchmark 2020          │ dotted      │
// ├─────────────────────────────────────────────────────────────────────┤
// │ V12 CRREM Tablo      │ Rows: silver_building_master[building_name] │
// │                      │ Sütun 1: GHG Intensity kgCO2 m2 yr         │
// │                      │ Sütun 2: CRREM Pathway 2C kgCO2 m2 yr      │
// │                      │ Sütun 3: CRREM Gap by Building kgCO2 m2     │
// │                      │ Sütun 4: Stranding Year by Building          │
// │                      │ Sütun 5: CRREM Stranding Status             │
// └─────────────────────────────────────────────────────────────────────┘
//
// ÖNEMLİ NOT: gold_crrem_pathway[year_month] → Date[Date] ilişkisi
// Line chart için gerekli. Bu ilişki kurulmuşsa V6 çalışır.
// Eğer hala boşsa: gold_crrem_pathway[year_month] kolonunun tipi
// Power Query'de DATE olmalı. Transform → Data Type → Date.
// ══════════════════════════════════════════════════════════════════════════
