// ==========================================================================
// Energy Copilot Platform — DAX v14: Page 1 Production Fixes
// File: semantic-model/19_dax_v14_page1_fixes.dax
// Created: 2026-04-24
//
// AMAÇ:
//   Page 1 Portfolio Overview'daki 3 ayrı sorunu düzeltir:
//
//   SORUN 1 — C6/C7/C8/C9 kartları boş ("--") gösteriyor
//     Kök neden: IsLastWeek / IsLastMonth Date tablosu kolonları TODAY()
//     fonksiyonunu kullanıyor. Veri seti 2025 veya erken 2026'da bitiyorsa
//     bu kolonlar hiçbir satırla eşleşmez → ölçüler BLANK döner → kartta "--".
//     Çözüm: TODAY() yerine MAX(gold_kpi_daily[date]) kullan. Bu şekilde
//     veri ne zaman biterse bitsin, "geçen hafta" ve "geçen ay" her zaman
//     veri setinin son dönemine göre hesaplanır.
//
//   SORUN 2 — LW / LM referans hatası (v10 ölçüleri bozuk)
//     Kök neden: 15_dax_v10_review_fixes.dax'taki LW Consumption YoY Pct Safe
//     ve LM Consumption MoM Pct Safe ölçüleri [LW Consumption kWh] ve
//     [LM Consumption kWh] isimli ölçülere referans veriyor. Bu ölçüler
//     hiç tanımlanmamıştı → Power BI "measure reference not found" hatası.
//     Çözüm: Bu dosyada tanımlanıyor, yeni data-relative ölçülere yönlendiriliyor.
//
//   SORUN 3 — V7 Anomaly Heatmap görsel tipi yanlış
//     Kök neden: Visual, Table olarak bırakılmış + "Count of anomaly_id"
//     (raw aggregate) kullanıyor. Doğrusu Matrix + [Active Anomaly Count] ölçüsü.
//     Ancak alan kısıtlı (420×228px) ve çoğu severity sütunu boş → Stacked Bar
//     önerilir. Bu bölümde her iki seçenek için de gerekli ölçüler verilmiştir.
//
// KURULUM:
//   Power BI Desktop → Model view → Home → New Measure
//   Her ölçüyü ayrı ayrı "New Measure" ile ekle.
//   Mevcut v9 ölçülerini silme — bu dosya wrapper/override'dır.
//
// BAĞLAMA TABLOSU (dosya sonunda):
//   Her ölçünün hangi karta/visual'a bağlanacağı listelenmiştir.
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — DATA-RELATIVE HAFTALIK / AYLIK ÖLÇÜLER
//
// Bu ölçüler mevcut v9 ölçülerinin (IsLastWeek/IsLastMonth tabanlı)
// yerini alır. TODAY() kullanmaz — veri setinin maksimum tarihini baz alır.
//
// Neden bu yaklaşım daha sağlam:
//   - Demo verisi + prod verisi için eşit çalışır
//   - Veri tazelemesi gecikmeli bile olsa kart boş kalmaz
//   - MAX date'i REMOVEFILTERS ile hesaplar → slicer seçimi onu etkilemez
//     (rolling window, slicer-bağımsız davranmalı — Page 1 validation gereksinimi)
// ==========================================================================

// ── C6: Geçen Hafta Tüketimi (data-relative) ───────────────────────────────
Last Week kWh v14 =
// Veri setinin en son tarihinden 8–14 gün öncesi ("geçen hafta penceresi")
// Örnek: max date = 2026-01-18 → 5–11 Ocak arası
VAR _maxDate    = CALCULATE ( MAX ( gold_kpi_daily[date] ), REMOVEFILTERS ( 'Date' ) )
VAR _weekEnd    = _maxDate - 7      // geçen haftanın son günü
VAR _weekStart  = _maxDate - 13     // geçen haftanın ilk günü (7 tam gün)
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( gold_kpi_daily[date], _weekStart, _weekEnd )
)
// Format  : #,##0 "kWh"
// Kart    : C6 — Last Week Consumption
// Yön     : Low is Good

// ── C8: Geçen Ay Tüketimi (data-relative) ──────────────────────────────────
Last Month kWh v14 =
// Veri setinin son tarihinin bir önceki tam takvim ayı
// Örnek: max date = 2026-01-18 → Ocak değil, Aralık 2025'in tamamı
VAR _maxDate        = CALCULATE ( MAX ( gold_kpi_daily[date] ), REMOVEFILTERS ( 'Date' ) )
VAR _lastMonthEnd   = DATE ( YEAR ( _maxDate ), MONTH ( _maxDate ), 1 ) - 1
VAR _lastMonthStart = DATE ( YEAR ( _lastMonthEnd ), MONTH ( _lastMonthEnd ), 1 )
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( gold_kpi_daily[date], _lastMonthStart, _lastMonthEnd )
)
// Format  : #,##0 "kWh"
// Kart    : C8 — Last Month Consumption
// Yön     : Low is Good

// ── "Bu hafta" — WoW karşılaştırması için baz ──────────────────────────────
Current Week kWh v14 =
// Veri setinin son 7 günü ("mevcut hafta" gibi davranır)
VAR _maxDate = CALCULATE ( MAX ( gold_kpi_daily[date] ), REMOVEFILTERS ( 'Date' ) )
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESINPERIOD ( gold_kpi_daily[date], _maxDate, -7, DAY )
)
// Bu ölçü doğrudan karta bağlanmaz — sadece Week over Week Arrow v14 içinde kullanılır

// ── "Bu ay" — MoM karşılaştırması için baz ─────────────────────────────────
Current Month kWh v14 =
// Veri setinin son tarihinin içinde bulunduğu ayın 1'inden son tarihe kadar
VAR _maxDate    = CALCULATE ( MAX ( gold_kpi_daily[date] ), REMOVEFILTERS ( 'Date' ) )
VAR _monthStart = DATE ( YEAR ( _maxDate ), MONTH ( _maxDate ), 1 )
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( gold_kpi_daily[date], _monthStart, _maxDate )
)
// Bu ölçü doğrudan karta bağlanmaz — sadece Month over Month Arrow v14 içinde kullanılır


// ==========================================================================
// BÖLÜM 2 — WoW / MoM OK ETİKETLERİ (C7 ve C9 kartları)
//
// v9'daki Week over Week Arrow ve Month over Month Arrow ölçülerinin
// yerini alır. Artık data-relative v14 baz ölçüleri kullanıyor.
// ==========================================================================

Week over Week Arrow v14 =
// C7 — Haftalık tüketim değişimi, ok etiketi olarak
// Format: General (text ölçüsü — Standard Card visual kullan, KPI değil)
VAR _thisWeek = [Current Week kWh v14]
VAR _lastWeek = [Last Week kWh v14]
VAR _pct      = DIVIDE ( _thisWeek - _lastWeek, _lastWeek, BLANK() ) * 100
RETURN
SWITCH (
    TRUE (),
    ISBLANK ( _pct ),   "—",
    _pct > 5,           "▲▲ " & FORMAT (      _pct,  "+0.0" ) & "%",
    _pct > 0,           "▲ "  & FORMAT (      _pct,  "+0.0" ) & "%",
    _pct < -5,          "▼▼ " & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct < 0,           "▼ "  & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
                        "→ 0.0%"
)
// Renk kodu: ▲ = kırmızı (artış kötü), ▼ = yeşil (azalış iyi)
// Kart: C7 — Week-over-Week Change

Month over Month Arrow v14 =
// C9 — Aylık tüketim değişimi, ok etiketi olarak
// Format: General (text ölçüsü)
VAR _thisMonth = [Current Month kWh v14]
VAR _lastMonth = [Last Month kWh v14]
VAR _pct       = DIVIDE ( _thisMonth - _lastMonth, _lastMonth, BLANK() ) * 100
RETURN
SWITCH (
    TRUE (),
    ISBLANK ( _pct ),   "—",
    _pct > 10,          "▲▲ " & FORMAT (      _pct,  "+0.0" ) & "%",
    _pct > 0,           "▲ "  & FORMAT (      _pct,  "+0.0" ) & "%",
    _pct < -10,         "▼▼ " & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct < 0,           "▼ "  & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
                        "→ 0.0%"
)
// Kart: C9 — Month-over-Month Change


// ==========================================================================
// BÖLÜM 3 — v10 BOZUK REFERANSLARI DÜZELT
//
// 15_dax_v10_review_fixes.dax dosyasındaki iki ölçü, hiç tanımlanmamış
// ölçü isimlerine referans veriyor:
//   LW Consumption YoY Pct Safe  → [LW Consumption kWh]  ← TANIMLI DEĞİL
//   LM Consumption MoM Pct Safe  → [LM Consumption kWh]  ← TANIMLI DEĞİL
//
// Bu bölüm bu isimleri tanımlıyor ve yeni data-relative ölçülere
// yönlendiriyor. Böylece v10 ölçüleri de otomatik düzelecek.
// ==========================================================================

LW Consumption kWh =
// v10 LW Consumption YoY Pct Safe'in beklediği ölçü adı
// → yeni data-relative ölçüye yönlendir
[Last Week kWh v14]

LM Consumption kWh =
// v10 LM Consumption MoM Pct Safe'in beklediği ölçü adı
// → yeni data-relative ölçüye yönlendir
[Last Month kWh v14]


// ==========================================================================
// BÖLÜM 4 — V7 ANOMALİ VİSUALI İÇİN UPPERCASE DÜZELTMESİ
//
// DAX v11 ile severity değerleri UPPERCASE yapıldı: "CRITICAL", "HIGH",
// "MEDIUM", "LOW". Ancak 02_dax_measures.dax'taki eski ölçüler hâlâ
// lowercase "critical", "high" vs. kullanıyor.
//
// Eğer V7'yi Matrix (heatmap) olarak kullanıyorsan:
//   Rows  = silver_building_master[building_name]
//   Cols  = gold_anomaly_log[severity]
//   Values = [Active Anomaly Count]   ← bu ölçü zaten is_resolved=FALSE filtreli
//   Bu durumda severity sütun değerleri veri tabanından otomatik gelir ("CRITICAL" vs.)
//   ve bu bölümdeki ölçülere gerek kalmaz.
//
// Eğer V7'yi Stacked Bar (ÖNERİLEN — bkz. açıklama altında) olarak yaparsan:
//   Her severity için ayrı ölçü series olarak eklenebilir.
// ==========================================================================

Critical Anomaly Count v14 =
// Uppercase fix — v11 sonrası "CRITICAL"
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "CRITICAL",
    gold_anomaly_log[is_resolved] = FALSE
)
// Kullanım: V7 Stacked Bar — CRITICAL serisi (kırmızı #FF4560)

High Anomaly Count v14 =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "HIGH",
    gold_anomaly_log[is_resolved] = FALSE
)
// Kullanım: V7 Stacked Bar — HIGH serisi (turuncu #FF6B35)

Medium Anomaly Count v14 =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "MEDIUM",
    gold_anomaly_log[is_resolved] = FALSE
)
// Kullanım: V7 Stacked Bar — MEDIUM serisi (sarı #FFC107)

Low Anomaly Count v14 =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "LOW",
    gold_anomaly_log[is_resolved] = FALSE
)
// Kullanım: V7 Stacked Bar — LOW serisi (yeşil #00D264)


// ==========================================================================
// BÖLÜM 5 — NOTLAR: GOAL DEĞERLERİ VE EUI BİRİMİ
//
// Bu iki sorun DAX değişikliği gerektirmez — Power BI arayüz ayarı.
//
// GOAL DEĞERLERİ (-517%, -531% sapmaları):
//   Kök neden: Veri setinde Ağustos 2025 döneminde anormal spike var.
//   Bu spike toplam tüketimi şişiriyor, PY değeri düşük kalıyor.
//   Yapılacak:
//     C1 Target → [Energy Reduction Target kWh] yap (PY×0.95 — mantıklı)
//     Spike kontrolü: gold_kpi_daily'de 2025-08 dönemini filtrele
//     Eğer tek ay tüm portföy toplamına yakınsa → test verisi artifact'ı
//
// EUI BİRİMİ (kWh/m²/day vs. kWh/m²/year):
//   Mevcut kart başlığı: "Avg EUI (kWh/m²/day)" — 0.60
//   Endüstri standardı: kWh/m²/year (ASHRAE, EU EPBD)
//   0.60 × 365 = 219 kWh/m²/year — mevcut portföy için makul
//   Yapılacak seçenekler:
//     A) Kart başlığını "Avg EUI (kWh/m²/day)" olarak koru — operasyonel
//        Dashboard için günlük daha anlamlı. Tooltip'te yıllık eşdeğeri yaz.
//     B) [Avg EUI kWh m2] × 365 ile yeni ölçü yaz, birimi /year yap
//   ÖNERİ: Seçenek A — müşteri zaten günlük dashboard kullanacak.
//          Bir tooltip kutusu (Text Box) ekleyerek "≈ X kWh/m²/year" yaz.
// ==========================================================================


// ==========================================================================
// KULLANIM TABLOSU — v14 ÖLÇÜLERİNİ NEREYE BAĞLAYACAKSIN
//
//  KART  ÖLÇÜ                         FORMAT           AÇIKLAMA
//  ────  ───────────────────────────  ───────────────  ──────────────────────
//  C6    Last Week kWh v14            #,##0 "kWh"      v9 yerini alır
//  C7    Week over Week Arrow v14     General (text)   v9 yerini alır
//  C8    Last Month kWh v14           #,##0 "kWh"      v9 yerini alır
//  C9    Month over Month Arrow v14   General (text)   v9 yerini alır
//  C10   Last 7 Days Cost EUR         € #,##0           v9 — dokunma ✅
//  C11   Last 30 Days CO2 tCO2        #,##0.0 "tCO₂"   v9 — dokunma ✅
//
//  v10 referans düzeltmesi:
//        LW Consumption kWh           (tanımlandı — v10 artık çalışır)
//        LM Consumption kWh           (tanımlandı — v10 artık çalışır)
//
//  V7 Stacked Bar seçilirse (ÖNERİLEN):
//        Y-axis  : silver_building_master[building_name]
//        Series 1: Critical Anomaly Count v14   (#FF4560 kırmızı)
//        Series 2: High Anomaly Count v14       (#FF6B35 turuncu)
//        Series 3: Medium Anomaly Count v14     (#FFC107 sarı)
//        Series 4: Low Anomaly Count v14        (#00D264 yeşil)
//        Sort     : Total (desc) — en fazla anomalili bina üstte
//        Legend   : Top
//        Data labels: ON (toplam değer)
//
//  V7 Matrix (Heatmap) seçilirse (orijinal plan):
//        Rows    : silver_building_master[building_name]
//        Columns : gold_anomaly_log[severity]
//        Values  : [Active Anomaly Count]
//        CF Background: gradient min=#0A1528 max=#FF4560
//        Row/Column subtotals: OFF
//        Cell values: ON, 10pt white bold
//        Bu durumda Bölüm 4 ölçülerine gerek yok
// ==========================================================================

// SON — 19_dax_v14_page1_fixes.dax
