// ==========================================================================
// Energy Copilot Platform — DAX v15: Page 1 Date Table + CF Fixes
// File: semantic-model/20_dax_v15_page1_datetable_cf.dax
// Created: 2026-04-24
//
// v14'TEKİ SORUN:
//   DATESBETWEEN(gold_kpi_daily[date], ...) fiziksel kolonu kullandı.
//   Ama ilişki 'Date'[Date] → gold_kpi_daily[date] şeklinde kurulu.
//   Power BI'da slicer 'Date'[Date]'i filtreler, biz REMOVEFILTERS('Date')
//   ile onu kaldırıp gold_kpi_daily[date]'e DATESBETWEEN yazınca Fabric
//   bazen doğru propagate etmiyor.
//   Çözüm: Tüm rolling ölçüler 'Date'[Date] kolonunu kullanacak.
//
// YAPI:
//   BÖLÜM 1 — Date tablosu tabanlı rolling window ölçüleri (C6, C8)
//   BÖLÜM 2 — WoW / MoM ok etiketi ölçüleri (C7, C9) — text
//   BÖLÜM 3 — CF renk ölçüleri (C7, C9 arka plan rengi için)
//   BÖLÜM 4 — Veri doğrulama ölçüleri (debug — rapor dışı)
//   BÖLÜM 5 — Alias düzeltmeleri (v10 referans fix — v14'ten devralındı)
//
// TASARIM KARARI — Slicer etkisi:
//   Bina sliceri (Building Name) → TÜM kartları etkiler ✅
//   Tarih sliceri (Date Range)   → C1–C5 KPI kartlarını etkiler ✅
//                                   C6–C11 rolling kartları ETKİLEMEZ ⚠️
//   Bu kasıtlı davranış: "last week" her zaman verinin son haftasıdır,
//   slicer'da hangi tarih seçilmiş olursa olsun. Operasyonel dashboard
//   standardı budur — "son 7 günü her zaman göster."
//   Eğer tarih slicerının C6–C11'i de etkilemesini istersen bunu belirt.
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — DATE TABLOSU TABANLI ROLLING WINDOW ÖLÇÜLERİ
//
// Tüm MAX() çağrıları 'Date'[Date] kolonunu kullanıyor.
// DATESBETWEEN de 'Date'[Date] üzerinden çalışıyor.
// Bu şekilde ilişki doğru çalışır, Fabric query fold sorunsuz.
// ==========================================================================

// ── C6: Geçen Hafta Tüketimi ────────────────────────────────────────────────
Last Week kWh v15 =
VAR _maxDate   = CALCULATE ( MAX ( 'Date'[Date] ), REMOVEFILTERS ( 'Date' ) )
VAR _weekEnd   = _maxDate - 7
VAR _weekStart = _maxDate - 13
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( 'Date'[Date], _weekStart, _weekEnd )
)
// Format  : #,##0 "kWh"
// Kart    : C6 — Last Week Consumption kWh
// NOT     : Tarih slicerından bağımsız. Bina slicerı etkiler.

// ── C8: Geçen Ay Tüketimi ───────────────────────────────────────────────────
Last Month kWh v15 =
VAR _maxDate        = CALCULATE ( MAX ( 'Date'[Date] ), REMOVEFILTERS ( 'Date' ) )
VAR _lastMonthEnd   = DATE ( YEAR ( _maxDate ), MONTH ( _maxDate ), 1 ) - 1
VAR _lastMonthStart = DATE ( YEAR ( _lastMonthEnd ), MONTH ( _lastMonthEnd ), 1 )
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( 'Date'[Date], _lastMonthStart, _lastMonthEnd )
)
// Format  : #,##0 "kWh"
// Kart    : C8 — Last Month Consumption kWh

// ── C10: Son 7 Gün Maliyet ─────────────────────────────────────────────────
Last 7 Days Cost EUR v15 =
VAR _maxDate = CALCULATE ( MAX ( 'Date'[Date] ), REMOVEFILTERS ( 'Date' ) )
RETURN
CALCULATE (
    [Total Energy Cost EUR],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( 'Date'[Date], _maxDate - 6, _maxDate )
)
// Format  : € #,##0
// Kart    : C10 — Last 7 Days Cost EUR

// ── C11: Son 30 Gün CO₂ ────────────────────────────────────────────────────
Last 30 Days CO2 tCO2 v15 =
VAR _maxDate = CALCULATE ( MAX ( 'Date'[Date] ), REMOVEFILTERS ( 'Date' ) )
RETURN
CALCULATE (
    [Total CO2 Emissions tCO2],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( 'Date'[Date], _maxDate - 29, _maxDate )
)
// Format  : #,##0.0 "tCO₂"
// Kart    : C11 — Last 30 Days CO₂

// ── Yardımcı: Bu Hafta (WoW için baz) ──────────────────────────────────────
_Current Week kWh v15 =
VAR _maxDate = CALCULATE ( MAX ( 'Date'[Date] ), REMOVEFILTERS ( 'Date' ) )
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( 'Date'[Date], _maxDate - 6, _maxDate )
)
// Kart bağlama — sadece WoW Arrow v15 içinde kullanılır

// ── Yardımcı: Bu Ay (MoM için baz) ─────────────────────────────────────────
_Current Month kWh v15 =
VAR _maxDate        = CALCULATE ( MAX ( 'Date'[Date] ), REMOVEFILTERS ( 'Date' ) )
VAR _currentMonthStart = DATE ( YEAR ( _maxDate ), MONTH ( _maxDate ), 1 )
RETURN
CALCULATE (
    [Total Consumption kWh],
    REMOVEFILTERS ( 'Date' ),
    DATESBETWEEN ( 'Date'[Date], _currentMonthStart, _maxDate )
)
// Kart bağlama — sadece MoM Arrow v15 içinde kullanılır


// ==========================================================================
// BÖLÜM 2 — WoW / MoM OK ETİKETİ (TEXT — C7 ve C9)
//
// Bu ölçüler string döndürür. Doğrudan "Value" alanına bağla.
// CF için Bölüm 3'teki renk ölçülerini "Background Color" alanına bağla.
// ==========================================================================

Week over Week Arrow v15 =
VAR _this = [_Current Week kWh v15]
VAR _last = [Last Week kWh v15]
VAR _pct  = DIVIDE ( _this - _last, _last, BLANK() ) * 100
RETURN
SWITCH (
    TRUE (),
    ISBLANK ( _pct ),   "—",
    _pct > 5,           "▲▲ " & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct > 0,           "▲ "  & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct < -5,          "▼▼ " & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct < 0,           "▼ "  & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
                        "→ 0%"
)
// KURULUM: Card (new) visual → Value = bu ölçü
// CF    : Format → Callout value → Font color → Field value → WoW CF Color v15

Month over Month Arrow v15 =
VAR _this = [_Current Month kWh v15]
VAR _last = [Last Month kWh v15]
VAR _pct  = DIVIDE ( _this - _last, _last, BLANK() ) * 100
RETURN
SWITCH (
    TRUE (),
    ISBLANK ( _pct ),   "—",
    _pct > 10,          "▲▲ " & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct > 0,           "▲ "  & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct < -10,         "▼▼ " & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
    _pct < 0,           "▼ "  & FORMAT ( ABS ( _pct ), "0.0" ) & "%",
                        "→ 0%"
)
// KURULUM: Card (new) visual → Value = bu ölçü
// CF    : Format → Callout value → Font color → Field value → MoM CF Color v15


// ==========================================================================
// BÖLÜM 3 — CF RENK ÖLÇÜLERİ
//
// Power BI'da text ölçülerine CF uygulanamaz doğrudan.
// Çözüm: Ayrı bir HEX renk ölçüsü yaz → Card (new) visual'da:
//   Format pane → Callout value → Font color → fx → Field value → bu ölçü
//
// Mantık: Tüketim azalışı = İYİ = YEŞİL
//         Tüketim artışı  = KÖTÜ = KIRMIZI
//         Veri yok        = GRİ
// ==========================================================================

WoW CF Color v15 =
// C7 kartı font rengi — HEX string döndürür
VAR _this = [_Current Week kWh v15]
VAR _last = [Last Week kWh v15]
VAR _pct  = DIVIDE ( _this - _last, _last, BLANK() ) * 100
RETURN
IF (
    ISBLANK ( _pct ),
    "#808080",              // Gri — veri yok
    IF ( _pct < 0,
        "#00D264",          // Yeşil — azalış (iyi)
        "#FF4560"           // Kırmızı — artış (kötü)
    )
)
// KURULUM:
//   Card (new) → Format pane → Callout value → Font color
//   → Açılan pencerede "fx" → Field value → WoW CF Color v15
//
// AYNI MANTIK ile arka plan rengi de eklenebilir:
//   Card background → fx → Field value → WoW CF BG Color v15 (aşağıda)

WoW CF BG Color v15 =
// C7 kartı arka plan rengi — transparan veya hafif ton
VAR _this = [_Current Week kWh v15]
VAR _last = [Last Week kWh v15]
VAR _pct  = DIVIDE ( _this - _last, _last, BLANK() ) * 100
RETURN
IF (
    ISBLANK ( _pct ),
    "#1A1A2E",              // Varsayılan koyu arka plan
    IF ( _pct < 0,
        "#0D2E1A",          // Koyu yeşil tonu — azalış
        "#2E0D1A"           // Koyu kırmızı tonu — artış
    )
)
// KURULUM: Card (new) → Format pane → Card background → fx → Field value

MoM CF Color v15 =
// C9 kartı font rengi
VAR _this = [_Current Month kWh v15]
VAR _last = [Last Month kWh v15]
VAR _pct  = DIVIDE ( _this - _last, _last, BLANK() ) * 100
RETURN
IF (
    ISBLANK ( _pct ),
    "#808080",
    IF ( _pct < 0, "#00D264", "#FF4560" )
)
// KURULUM: C9 Card → Callout value → Font color → fx → Field value → MoM CF Color v15

MoM CF BG Color v15 =
// C9 kartı arka plan rengi
VAR _this = [_Current Month kWh v15]
VAR _last = [Last Month kWh v15]
VAR _pct  = DIVIDE ( _this - _last, _last, BLANK() ) * 100
RETURN
IF (
    ISBLANK ( _pct ),
    "#1A1A2E",
    IF ( _pct < 0, "#0D2E1A", "#2E0D1A" )
)


// ==========================================================================
// BÖLÜM 4 — VERİ DOĞRULAMA ÖLÇÜLERİ
//
// Bu ölçüleri geçici bir Card veya Table visual'a bağla, değerleri kontrol
// et, sonra rapor dışına al (hidden) veya sil.
//
// Neden önemli: "Değerlerin mantıklı olup olmadığından emin değilim" →
// bu ölçüler hangi tarih aralığında ne kadar veri olduğunu gösterir.
// ==========================================================================

// ── Veri tarih aralığı ─────────────────────────────────────────────────────
Debug Min Date =
// Veri setinin en erken tarihi — Date tablosunda ilişkili en eski satır
CALCULATE (
    MIN ( 'Date'[Date] ),
    NOT ISBLANK ( [Total Consumption kWh] )
)
// Beklenen: ~2024-12-01 veya daha erken
// Format: Short Date

Debug Max Date =
// Veri setinin en son tarihi — rolling ölçüler buna göre çalışıyor
CALCULATE (
    MAX ( 'Date'[Date] ),
    NOT ISBLANK ( [Total Consumption kWh] )
)
// Bu tarih ile TODAY() arasındaki fark = rolling kartların "boş görünme" sebebi
// Örnek: max = 2026-01-18, TODAY = 2026-04-24 → IsLastWeek/IsLastMonth hiç eşleşmez
// Format: Short Date

Debug Days in Dataset =
// Kaç günlük veri var
VAR _min = CALCULATE ( MIN ( 'Date'[Date] ), NOT ISBLANK ( [Total Consumption kWh] ) )
VAR _max = CALCULATE ( MAX ( 'Date'[Date] ), NOT ISBLANK ( [Total Consumption kWh] ) )
RETURN
    _max - _min
// Beklenen: > 365 gün (1+ yıl) — PY karşılaştırmaları için gerekli
// Format: #,##0 "gün"

Debug Building Count =
// Kaç farklı bina var
DISTINCTCOUNT ( gold_kpi_daily[building_id] )
// Beklenen: 6
// Format: #,##0

Debug Null Consumption Days =
// Tüketim verisi BLANK olan gün sayısı — veri kalitesi kontrolü
CALCULATE (
    COUNTROWS ( 'Date' ),
    ISBLANK ( [Total Consumption kWh] ),
    'Date'[Date] >= CALCULATE ( MIN ( 'Date'[Date] ), NOT ISBLANK ( [Total Consumption kWh] ) ),
    'Date'[Date] <= CALCULATE ( MAX ( 'Date'[Date] ), NOT ISBLANK ( [Total Consumption kWh] ) )
)
// Beklenen: 0 (hiç boşluk olmamalı)
// Eğer > 0 → bazı günler/binalar için veri eksik
// Format: #,##0 "gün"

Debug Avg Daily Consumption Per Building =
// Bina başına ortalama günlük tüketim — mantık kontrolü
DIVIDE (
    [Total Consumption kWh],
    [Debug Building Count] * [Debug Days in Dataset],
    BLANK()
)
// Beklenen aralık (bina tipine göre):
//   Ofis 500–5000 m²    : 100–800 kWh/gün
//   Hastane             : 2000–15000 kWh/gün
//   Lojistik hub        : 500–3000 kWh/gün
// Eğer 50 kWh/gün altındaysa simülasyon verisi gerçekçi değil
// Eğer 50.000 kWh/gün üstündeyse birim hatası var (kW yerine kWh?)
// Format: #,##0 "kWh"

Debug Last Week Window =
// Rolling kartların baktığı tarih penceresini göster
VAR _maxDate   = CALCULATE ( MAX ( 'Date'[Date] ), REMOVEFILTERS ( 'Date' ) )
VAR _weekEnd   = _maxDate - 7
VAR _weekStart = _maxDate - 13
RETURN
FORMAT ( _weekStart, "DD.MM.YYYY" ) & " → " & FORMAT ( _weekEnd, "DD.MM.YYYY" )
// Bu kartta görünen tarih aralığı = C6'nın baktığı pencere
// Format: General (text)
// C6 boşsa bu pencerede gerçekten veri yok demektir


// ==========================================================================
// BÖLÜM 5 — ALIAS DÜZELTMELERİ (v14'ten devralındı)
//
// v10 dosyasındaki LW/LM Consumption YoY/MoM Pct Safe ölçüleri
// bu isimlere referans veriyor — burada yeniden tanımlanıyor.
// ==========================================================================

LW Consumption kWh =
[Last Week kWh v15]

LM Consumption kWh =
[Last Month kWh v15]


// ==========================================================================
// KURULUM SIRASI VE KART BAĞLAMA TABLOSU
//
//  ADIM  İŞLEM
//  ────  ──────────────────────────────────────────────────────────────────
//  1.    Bu dosyadaki tüm ölçüleri New Measure ile ekle
//  2.    Geçici bir Card'a Debug Min/Max Date + Debug Last Week Window bağla
//        → Veri aralığını ve rolling penceresini doğrula
//  3.    Debug Null Consumption Days'i kontrol et → 0 olmalı
//  4.    Debug Avg Daily Consumption Per Building'i kontrol et → makul aralıkta mı?
//  5.    Debug kartları gizle (Hidden) veya sil → rapor temiz kalsın
//
//  KART  ÖLÇÜ (Value)                FORMAT           CF ÖLÇÜSÜ
//  ────  ───────────────────────────  ───────────────  ──────────────────────
//  C6    Last Week kWh v15            #,##0 "kWh"      —
//  C7    Week over Week Arrow v15     General           Font: WoW CF Color v15
//                                                       BG  : WoW CF BG Color v15
//  C8    Last Month kWh v15           #,##0 "kWh"      —
//  C9    Month over Month Arrow v15   General           Font: MoM CF Color v15
//                                                       BG  : MoM CF BG Color v15
//  C10   Last 7 Days Cost EUR v15     € #,##0           —
//  C11   Last 30 Days CO2 tCO2 v15    #,##0.0 "tCO₂"   —
//
//  CF KURULUM ADIMLARI (C7 örneği — C9 için aynı adımlar):
//  1. C7 Card visual'ı seç
//  2. Format pane → Visual → Callout value → Font color
//  3. Yanındaki "fx" butonuna tıkla
//  4. Format style: "Field value"
//  5. What field should we base this on: "WoW CF Color v15"
//  6. OK → Kart artık yeşil/kırmızı/gri renk alıyor
//  (Arka plan için: Card background → fx → WoW CF BG Color v15)
//
//  NOT: v14 dosyasındaki ölçüleri artık kullanmıyorsun.
//       v15 tamamen v14'ün yerini alır — Power BI'da eski v14
//       ölçülerini kartlardan kaldır, v15'leri bağla.
// ==========================================================================

// SON — 20_dax_v15_page1_datetable_cf.dax
