// ==========================================================================
// Energy Copilot Platform — DAX v16: Date Table Complete Rewrite
// File: semantic-model/21_dax_v16_datetable_complete.dax
// Created: 2026-04-24
//
// AMAÇ — MİMARİ KARAR:
//   Tüm DAX ölçülerinde gold_kpi_daily[date] fiziksel kolonu yerine
//   'Date'[Date] boyut tablosu kolonu kullanılacak.
//
// NEDEN:
//   1. Date tablosu "Mark as Date Table" → DATEADD/DATESINPERIOD
//      için Power BI'ın time intelligence motoru buradan çalışmalı.
//   2. gold_kpi_daily'de her Date[Date] satırı için veri yok.
//      MAX('Date'[Date]) tarih tablosunun son satırını döndürür,
//      ama veri orada bitmemiş olabilir → rolling kartlar -100% gösterir.
//      Çözüm: _maxDate her zaman "verinin son tarihi" olarak hesaplanmalı.
//
// _DATA_MAX_DATE PATTERN (tüm rolling ölçülerde kullanılacak):
//   VAR _maxDate = CALCULATE(
//       MAX('Date'[Date]),
//       NOT ISBLANK([Total Consumption kWh]),
//       REMOVEFILTERS('Date')
//   )
//   → Slicer'dan bağımsız, sadece gerçek veri olan son günü alır.
//
// KAPSAM — Bu dosya aşağıdaki dosyaları OVERRIDE eder:
//   02_dax_measures.dax      (PY + rolling ölçüler)
//   10_dax_v5_final.dax      (PY CO2, Anomaly)
//   11_dax_v6_gap_fix.dax    (Solar PY, Carbon PY)
//   14_dax_v9_date_weekly.dax (tüm Last Week/Month ölçüleri)
//   19_dax_v14_page1_fixes.dax (v14 — tamamen yerini alır)
//   20_dax_v15_page1_datetable_cf.dax (v15 — tamamen yerini alır)
//
// KURULUM:
//   Power BI Desktop → Home → New Measure ile her ölçüyü tek tek ekle.
//   Mevcut eski ölçüler silinmeden override edilebilir — aynı isme
//   sahip yeni ölçü, visual'larda öncelik alır.
//   VEYA: Eski ölçüleri sil, bu dosyadan ekle (daha temiz).
// ==========================================================================


// ==========================================================================
// BÖLÜM A — PRIOR YEAR (PY) KARŞILAŞTIRMA ÖLÇÜLERİ
//
// Değişiklik: DATEADD(gold_kpi_daily[date], -1, YEAR)
//         → DATEADD('Date'[Date], -1, YEAR)
//
// Neden: Date tablosu "Mark as Date Table" ile işaretlendiğinde
//        DATEADD yalnızca boyut tablosundaki Date kolonu üzerinde
//        güvenilir çalışır. Fiziksel kolon kullanımı Power BI'da
//        ilişki yayılımı sorunlarına yol açabilir.
// ==========================================================================

// ── Sayfa 1 C1 Target: Geçen Yıl Tüketimi ─────────────────────────────────
Total Energy PY kWh =
CALCULATE(
    [Total Consumption kWh],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0 "kWh"
// Kullanım : Sayfa 1 C1 KPI Indicator → Target goals

// ── Genel: Geçen Yıl Tüketimi (alias) ────────────────────────────────────
Previous Year Consumption kWh =
CALCULATE(
    [Total Consumption kWh],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0 "kWh"

// ── Sayfa 6: Geçen Yıl CO₂ ────────────────────────────────────────────────
Previous Year CO2 Emissions tCO2 =
CALCULATE(
    [Total CO2 Emissions tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0.0 "tCO₂"
// Kullanım : Sayfa 6 karbon trend karşılaştırması

// ── Sayfa 1 C5 Target: Geçen Yıl Net Karbon ──────────────────────────────
Previous Year Net Carbon tCO2 =
CALCULATE(
    [Net Carbon Footprint tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0.0 "tCO₂"
// Kullanım : Sayfa 1 C5 KPI Indicator → Target goals

// ── Sayfa 3 C2 Target: Geçen Yıl Anomali Sayısı ──────────────────────────
Anomaly Count PY Same Period =
CALCULATE(
    [Active Anomaly Count],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0
// Kullanım : Sayfa 3 C2 KPI Indicator → Target goals

// ── Sayfa 1/2 C4 Target: Geçen Yıl Maliyet ──────────────────────────────
Previous Year Cost EUR =
CALCULATE(
    [Total Energy Cost EUR],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : € #,##0
// Kullanım : Sayfa 1 C4 / Sayfa 2 maliyet KPI → Target goals

// ── Sayfa 1 C1 Alternatif Target: EED %5 Azaltım Hedefi ──────────────────
Energy Reduction Target kWh =
VAR _py = CALCULATE(
    [Total Consumption kWh],
    DATEADD('Date'[Date], -1, YEAR)
)
RETURN
    _py * 0.95
// Format   : #,##0 "kWh"
// Kullanım : Sayfa 1 C1 Target (PY verisi varsa Total Energy PY kWh,
//            yoksa bu ölçü daha sağlam)
// Mantık   : EED 2023/1791 → kamu sektörü %5 yıllık azaltım zorunluluğu

// ── Sayfa 2: Solar Geçen Yıl ─────────────────────────────────────────────
Solar Generation PY kWh =
CALCULATE(
    [Total Solar Generated kWh],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0 "kWh"
// Kullanım : Sayfa 2 C4 Solar KPI → Target goals

// ── Sayfa 2 C6: Karbon Yoğunluğu Geçen Yıl ──────────────────────────────
Carbon Intensity PY kg m2 Day =
CALCULATE(
    [Avg Carbon Intensity kg m2],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : 0.000 "kgCO₂/m²"
// Kullanım : Sayfa 2 C6 KPI → Target goals

// ── Sayfa 5: Doluluk Geçen Yıl ───────────────────────────────────────────
Vacancy Rate PY Pct =
CALCULATE(
    [Vacancy Rate Pct],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : 0.0%

Energy Per Occupant PY kWh =
CALCULATE(
    [Energy Per Occupant kWh],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0.0

// ── Sayfa 6: Yenilenebilir Oran Geçen Yıl ────────────────────────────────
Renewable Rate PY Pct =
CALCULATE(
    [Renewable Energy Rate Pct],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : 0.0%

// ── Sayfa 4: Yıllık Tasarruf Hedefi ─────────────────────────────────────
Annual Saving Target EUR =
VAR _pyCost = CALCULATE(
    [Total Energy Cost EUR],
    DATEADD('Date'[Date], -1, YEAR)
)
RETURN
    _pyCost * 0.10
// Format   : € #,##0
// Mantık   : PY maliyetin %10'u = ESOS/EED program hedefi

// ── YoY Pct (tüm sayfalar için) ──────────────────────────────────────────
Consumption YoY Pct =
VAR _prev = [Previous Year Consumption kWh]
RETURN
    DIVIDE([Total Consumption kWh] - _prev, _prev, BLANK()) * 100
// Format   : 0.0

Consumption YoY Label =
VAR _pct = [Consumption YoY Pct]
RETURN
    IF(
        ISBLANK(_pct), "—",
        IF(_pct > 0, "▲ ", "▼ ") & FORMAT(ABS(_pct), "#,##0.0") & "% vs Last Year"
    )

CO2 YoY Pct =
VAR _prev = [Previous Year CO2 Emissions tCO2]
RETURN
    DIVIDE([Total CO2 Emissions tCO2] - _prev, _prev, BLANK()) * 100
// Format   : 0.0


// ==========================================================================
// BÖLÜM B — DATA-AWARE _maxDate PATTERN
//
// Bu bölümdeki tüm ölçüler aynı _maxDate hesaplama desenini kullanır:
//   CALCULATE(MAX('Date'[Date]), NOT ISBLANK([Total Consumption kWh]),
//             REMOVEFILTERS('Date'))
//
// Neden: Date tablosunun son satırı (17.01.2026) ile gold_kpi_daily'nin
//        son verisi (örn. 10.01.2026) arasında boşluk olabilir.
//        NOT ISBLANK filtresi → gerçek verinin son gününü alır.
//        REMOVEFILTERS('Date') → tarih slicerından bağımsız çalışır.
// ==========================================================================

// ── Sayfa 2: 7 Günlük Kayan Ortalama ─────────────────────────────────────
Energy 7Day Rolling Avg kWh =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh])
    // NOT: REMOVEFILTERS yok — bu ölçü slicer context'e göre çalışmalı
)
RETURN
CALCULATE(
    AVERAGE(gold_kpi_daily[total_consumption_kwh]),
    DATESINPERIOD('Date'[Date], _maxDate, -7, DAY)
)
// Format   : #,##0
// Kullanım : Sayfa 2 çift eksenli grafik — kesik çizgi overlay serisi

// ── Sayfa 2 C1 Target: 30 Günlük Kayan Ortalama ─────────────────────────
Avg Daily Consumption 30Day Rolling =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh])
)
RETURN
CALCULATE(
    AVERAGE(gold_kpi_daily[total_consumption_kwh]),
    DATESINPERIOD('Date'[Date], _maxDate, -30, DAY)
)
// Format   : #,##0

// ── Sayfa 2 C2 Target: 30 Günlük Peak Demand Ortalaması ──────────────────
Avg Peak Demand 30Day kW =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh])
)
RETURN
CALCULATE(
    AVERAGE(gold_kpi_daily[peak_demand_kw]),
    DATESINPERIOD('Date'[Date], _maxDate, -30, DAY)
)
// Format   : #,##0.0 "kW"

// ── Sayfa 3: Önceki Hafta Yüksek Anomali (target) ────────────────────────
High Anomaly Count Previous Week =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
RETURN
CALCULATE(
    [High Anomaly Count],
    DATESINPERIOD('Date'[Date], _maxDate - 7, -7, DAY)
)
// Format   : #,##0

Unresolved Count Previous Week =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
RETURN
CALCULATE(
    [Unresolved Count],
    DATESINPERIOD('Date'[Date], _maxDate - 7, -7, DAY)
)
// Format   : #,##0

// ── Sayfa 5: 30 Günlük Doluluk Ortalaması ────────────────────────────────
Avg Occupancy Rate 30Day Rolling =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh])
)
RETURN
CALCULATE(
    AVERAGE(gold_kpi_daily[avg_occupancy_rate]),
    DATESINPERIOD('Date'[Date], _maxDate, -30, DAY)
) * 100
// Format   : 0.0%

// ── Sayfa 4: Son 7 Günün Gerçekleşen Tüketimi ────────────────────────────
Actual Last 7Day kWh =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh])
)
RETURN
CALCULATE(
    SUM(gold_kpi_daily[total_consumption_kwh]),
    DATESINPERIOD('Date'[Date], _maxDate, -7, DAY)
)
// Format   : #,##0


// ==========================================================================
// BÖLÜM C — SAYFA 1 ROLLING KARTLAR (C6–C11)
//
// Tüm kartlar _maxDate ile çalışır. Bina sliceri etkiler,
// tarih sliceri ETKİLEMEZ (REMOVEFILTERS + rolling window mantığı).
// ==========================================================================

// ── C6: Geçen Hafta Tüketimi ────────────────────────────────────────────
Last Week kWh v16 =
// "Geçen hafta" = verinin son tarihinden 8–14 gün öncesi
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
VAR _weekEnd   = _maxDate - 7
VAR _weekStart = _maxDate - 13
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _weekStart, _weekEnd)
)
// Format   : #,##0 "kWh"
// Kart     : C6

// ── C8: Geçen Ay Tüketimi ────────────────────────────────────────────────
Last Month kWh v16 =
// "Geçen ay" = verinin son tarihinin bir önceki tam takvim ayı
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
// Format   : #,##0 "kWh"
// Kart     : C8

// ── C10: Son 7 Gün Maliyet ───────────────────────────────────────────────
Last 7 Days Cost EUR v16 =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
RETURN
CALCULATE(
    [Total Energy Cost EUR],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
// Format   : € #,##0
// Kart     : C10

// ── C11: Son 30 Gün CO₂ ─────────────────────────────────────────────────
Last 30 Days CO2 tCO2 v16 =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
RETURN
CALCULATE(
    [Total CO2 Emissions tCO2],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 29, _maxDate)
)
// Format   : #,##0.0 "tCO₂"
// Kart     : C11

// ── Yardımcı: Bu Hafta (WoW baz) ─────────────────────────────────────────
_This Week kWh v16 =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
// KPI karta bağlanmaz — sadece WoW Arrow v16 içinde kullanılır

// ── Yardımcı: Bu Ay (MoM baz) ────────────────────────────────────────────
_This Month kWh v16 =
VAR _maxDate = CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
VAR _thisMonthStart = DATE(YEAR(_maxDate), MONTH(_maxDate), 1)
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _thisMonthStart, _maxDate)
)
// KPI karta bağlanmaz — sadece MoM Arrow v16 içinde kullanılır


// ==========================================================================
// BÖLÜM D — WoW / MoM OK ETİKETLERİ (C7 ve C9) — TEXT ÖLÇÜLER
// ==========================================================================

Week over Week Arrow v16 =
VAR _this = [_This Week kWh v16]
VAR _last = [Last Week kWh v16]
VAR _pct  = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),   "—",
    _pct > 5,        "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,        "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -5,       "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,        "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                     "→ 0%"
)
// Format   : General (text ölçüsü)
// Kart     : C7 — Card (new) visual → Value
// CF       : Font color → WoW CF Color v16

Month over Month Arrow v16 =
VAR _this = [_This Month kWh v16]
VAR _last = [Last Month kWh v16]
VAR _pct  = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),   "—",
    _pct > 10,       "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,        "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -10,      "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,        "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                     "→ 0%"
)
// Format   : General (text ölçüsü)
// Kart     : C9 — Card (new) visual → Value
// CF       : Font color → MoM CF Color v16


// ==========================================================================
// BÖLÜM E — CF RENK ÖLÇÜLERİ (C7, C9 için font / arka plan rengi)
//
// KURULUM (C7 örneği):
//   C7 Card (new) seç → Format pane → Callout value → Font color
//   → "fx" butonuna tıkla → Format style: Field value
//   → What field: WoW CF Color v16 → OK
// ==========================================================================

WoW CF Color v16 =
VAR _pct = DIVIDE([_This Week kWh v16] - [Last Week kWh v16], [Last Week kWh v16], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#808080",    // Gri — veri yok
   IF(_pct < 0,   "#00D264",    // Yeşil — tüketim azaldı (iyi haber)
                  "#FF4560"))   // Kırmızı — tüketim arttı (kötü haber)
// KURULUM: C7 → Format → Callout value → Font color → fx → Field value

WoW CF BG Color v16 =
VAR _pct = DIVIDE([_This Week kWh v16] - [Last Week kWh v16], [Last Week kWh v16], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#1A1A2E",
   IF(_pct < 0,   "#0A2010",    // Koyu yeşil arka plan
                  "#2E0A14"))   // Koyu kırmızı arka plan
// KURULUM: C7 → Format → Card background → fx → Field value

MoM CF Color v16 =
VAR _pct = DIVIDE([_This Month kWh v16] - [Last Month kWh v16], [Last Month kWh v16], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#808080",
   IF(_pct < 0,   "#00D264", "#FF4560"))
// KURULUM: C9 → Format → Callout value → Font color → fx → Field value

MoM CF BG Color v16 =
VAR _pct = DIVIDE([_This Month kWh v16] - [Last Month kWh v16], [Last Month kWh v16], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#1A1A2E",
   IF(_pct < 0,   "#0A2010", "#2E0A14"))
// KURULUM: C9 → Format → Card background → fx → Field value


// ==========================================================================
// BÖLÜM F — v10 ALIAS DÜZELTMELERİ (v15'ten devralındı)
// ==========================================================================

LW Consumption kWh =
[Last Week kWh v16]

LM Consumption kWh =
[Last Month kWh v16]


// ==========================================================================
// BÖLÜM G — VERİ DOĞRULAMA ÖLÇÜLERİ (debug — geçici kullan, sonra gizle)
//
// Bu ölçüleri geçici Card visuallara bağla, değerleri kontrol et.
// Tamam olunca Power BI'da "Hidden" yap veya sil.
// ==========================================================================

Debug Data Min Date =
CALCULATE(
    MIN('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
// Beklenen: ~2024-01-01 veya daha erken
// Format   : Short Date
// Kart etiket: "Verinin başlangıç tarihi"

Debug Data Max Date =
CALCULATE(
    MAX('Date'[Date]),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
// Bu tarihe göre rolling window hesaplanır
// Format   : Short Date
// Kart etiket: "Verinin bitiş tarihi (rolling baz)"

Debug Date Table Max =
CALCULATE(
    MAX('Date'[Date]),
    REMOVEFILTERS('Date')
)
// Date tablosunun son satırı — veri bitmemiş olabilir
// Debug Data Max Date ile fark varsa → GAP var demektir
// Format   : Short Date

Debug Data Gap Days =
VAR _dataMax   = [Debug Data Max Date]
VAR _tableMax  = [Debug Date Table Max]
RETURN
    _tableMax - _dataMax
// Eğer > 0: Date tablosu veri tabanından daha ileriye uzanıyor
// Bu gapte rolling "current week/month" window'u düşerse → -100%
// Format   : #,##0 "gün"
// Beklenen : 0 (ideal) veya küçük pozitif sayı (kabul edilebilir)

Debug Rolling Window C6 =
VAR _maxDate   = [Debug Data Max Date]
VAR _weekEnd   = _maxDate - 7
VAR _weekStart = _maxDate - 13
RETURN
    FORMAT(_weekStart, "DD.MM.YYYY") & " → " & FORMAT(_weekEnd, "DD.MM.YYYY")
// C6 kartının baktığı tarih aralığını gösterir
// Bu aralıkta veri varsa C6 değer gösterir, yoksa göstermez
// Format   : General (text)

Debug Rolling Window C7 =
VAR _maxDate  = [Debug Data Max Date]
VAR _thisEnd  = _maxDate
VAR _thisStart = _maxDate - 6
RETURN
    FORMAT(_thisStart, "DD.MM.YYYY") & " → " & FORMAT(_thisEnd, "DD.MM.YYYY")
// C7 WoW oranının "bu hafta" penceresi
// Bu aralıkta veri yoksa WoW = -100% → sorun burada

Debug Avg Daily Per Building =
VAR _days = CALCULATE(
    COUNTROWS(VALUES('Date'[Date])),
    NOT ISBLANK([Total Consumption kWh]),
    REMOVEFILTERS('Date')
)
VAR _buildings = CALCULATE(
    DISTINCTCOUNT(gold_kpi_daily[building_id]),
    REMOVEFILTERS('Date')
)
VAR _total = CALCULATE([Total Consumption kWh], REMOVEFILTERS('Date'))
RETURN
    DIVIDE(_total, _days * _buildings, BLANK())
// Mantık kontrolü: bina başına günlük ortalama tüketim
// Beklenen aralık:
//   Ofis (500-5000 m²)    : 100 – 800 kWh/gün
//   Hastane               : 2.000 – 15.000 kWh/gün
//   Lojistik hub          : 500 – 3.000 kWh/gün
// Format   : #,##0 "kWh/gün"


// ==========================================================================
// BÖLÜM H — ANOMALİ VİSUAL ÖLÇÜLERİ (V7 Stacked Bar için)
//
// v11'de severity UPPERCASE yapıldı. Bu ölçüler güncel uppercase
// değerleri kullanıyor. V7'yi stacked bar olarak kuruyorsan
// her severity için ayrı series olarak ekle.
// ==========================================================================

Critical Anomaly Count v16 =
CALCULATE(
    COUNTROWS(gold_anomaly_log),
    gold_anomaly_log[severity] = "CRITICAL",
    gold_anomaly_log[is_resolved] = FALSE
)
// Renk: #FF4560 (kırmızı)

High Anomaly Count v16 =
CALCULATE(
    COUNTROWS(gold_anomaly_log),
    gold_anomaly_log[severity] = "HIGH",
    gold_anomaly_log[is_resolved] = FALSE
)
// Renk: #FF6B35 (turuncu)

Medium Anomaly Count v16 =
CALCULATE(
    COUNTROWS(gold_anomaly_log),
    gold_anomaly_log[severity] = "MEDIUM",
    gold_anomaly_log[is_resolved] = FALSE
)
// Renk: #FFC107 (sarı)

Low Anomaly Count v16 =
CALCULATE(
    COUNTROWS(gold_anomaly_log),
    gold_anomaly_log[severity] = "LOW",
    gold_anomaly_log[is_resolved] = FALSE
)
// Renk: #00D264 (yeşil)


// ==========================================================================
// KURULUM ÖZETİ VE BAĞLAMA TABLOSU
//
// ADIM 1: Bu dosyadaki tüm ölçüleri New Measure ile ekle
// ADIM 2: Debug ölçülerini geçici kartlara bağla, kontrol et:
//         - Debug Data Max Date → verinin gerçekten bittiği tarih
//         - Debug Data Gap Days → 0 mı? Değilse gap var
//         - Debug Rolling Window C6 → C6'nın baktığı pencerede veri var mı?
//         - Debug Avg Daily Per Building → değer mantıklı mı?
// ADIM 3: Kartları güncelle:
//
//  KART   YENİ ÖLÇÜ (Value)              FORMAT           CF
//  ─────  ───────────────────────────    ───────────────  ──────────────────
//  C1     Total Consumption kWh          #,##0 "kWh"      —
//  C1 TGT Energy Reduction Target kWh   #,##0 "kWh"      (Target goals)
//  C4 TGT Previous Year Cost EUR        € #,##0           (Target goals)
//  C5 TGT Previous Year Net Carbon tCO2 #,##0.0 "tCO₂"   (Target goals)
//  C6     Last Week kWh v16             #,##0 "kWh"       —
//  C7     Week over Week Arrow v16      General           Font: WoW CF Color v16
//                                                         BG  : WoW CF BG Color v16
//  C8     Last Month kWh v16            #,##0 "kWh"       —
//  C9     Month over Month Arrow v16    General           Font: MoM CF Color v16
//                                                         BG  : MoM CF BG Color v16
//  C10    Last 7 Days Cost EUR v16      € #,##0            —
//  C11    Last 30 Days CO2 tCO2 v16     #,##0.0 "tCO₂"    —
//
// ADIM 4: Debug ölçülerini Hidden yap (Model view → ölçü → gözü kapat)
// ADIM 5: v14 ve v15 ölçülerini sil (artık kullanılmıyor)
//
// MİMARİ NOT — Bu dosyadan sonra yeni ölçü yazarken:
//   PY karşılaştırması → DATEADD('Date'[Date], -1, YEAR)
//   Rolling window     → _maxDate = CALCULATE(MAX('Date'[Date]),
//                            NOT ISBLANK([Total Consumption kWh]),
//                            REMOVEFILTERS('Date'))
//                        ardından DATESBETWEEN('Date'[Date], ...)
//   Max date (slicer'a duyarlı) → MAX('Date'[Date])  [normal context]
//   Max date (slicer'dan bağımsız) → yukarıdaki _maxDate pattern
// ==========================================================================

// SON — 21_dax_v16_datetable_complete.dax
