// ==========================================================================
// Energy Copilot Platform — DAX v17: Page 1 Final Fix
// File: semantic-model/22_dax_v17_page1_final.dax
// Created: 2026-04-24
//
// v16 NEDEN ÇÖKTÜ:
//   CALCULATE içinde NOT ISBLANK([Total Consumption kWh]) filtresi
//   her Date satırı için ölçüyü evaluate etti → ilişki zayıflığında
//   tüm rolling ölçüler hata verdi.
//   Ayrıca Avg Occupancy Rate 30Day Rolling ölçüsü
//   gold_kpi_daily[avg_occupancy_rate] kolonunu kullandı → bu kolon yok.
//
// v17 YAKLAŞIMI:
//   _maxDate için kanıtlanmış pattern:
//     CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
//   Bu pattern v9'da zaten çalışıyordu (C10, C11 kartları).
//   Filtering için Date tablosu kullanılıyor ('Date'[Date]).
//   NOT ISBLANK pattern tamamen kaldırıldı.
//
// BU DOSYADAN ÖNCE YAPILMASI GEREKENLER:
//   1. v16 dosyasından eklenen TÜM ölçüleri Power BI'dan sil
//      (özellikle Avg Occupancy Rate 30Day Rolling)
//   2. Date tablosunu "Mark as Date Table" yap (aşağıda açıklama var)
//   3. Bu dosyadaki ölçüleri ekle
// ==========================================================================


// ==========================================================================
// BÖLÜM 0 — DATE TABLOSU DÜZELTMESİ
//
// Bu bölüm DAX ölçüsü değil — Date tablosuna eklemen gereken kolonları
// ve yapılması gereken Power BI ayarlarını açıklar.
//
// ADIM 1 — Date tablosu formülüne MonthIndex kolonu ekle:
//   (Model view → Date tablosu → formülü aç → ADDCOLUMNS'a ekle)
//
//   "MonthIndex",   YEAR([Date]) * 100 + MONTH([Date]),
//
//   Sonuç: 2024-01 → 202401, 2024-02 → 202402 ...
//   Kullanım: YearMonth kolonunu MonthIndex'e "Sort by Column" yap
//             → Aylık trend grafiği kronolojik sıralanır
//
// ADIM 2 — Date tablosunu "Mark as Date Table" yap:
//   Model view → Date tablosu → sağ tık → "Mark as date table"
//   → Date[Date] kolonunu seç → Confirm
//   NEDEN: DATEADD('Date'[Date], -1, YEAR) çalışması için şart
//
// ADIM 3 — Date tablosu başlangıcını kontrol et:
//   Mevcut: DATE(2023, 1, 1)
//   gold_kpi_daily verisi: 2024'ten başlıyor
//   → 2023 yılı için Date tablosunda satırlar var ama veri yok
//   → Bu bir sorun değil, ama Year slicerında 2023 görünür (boş)
//   → Dilersen DATE(2024, 1, 1) yap veya olduğu gibi bırak
//
// ADIM 4 — İlişki kontrolü (Model view → Relationships):
//   Date[Date] ↔ gold_kpi_daily[date]    → ACTIVE, Many-to-One ✅
//   Date[Date] ↔ gold_anomaly_log[date]  → ilişki var mı? kontrol et
//   Date[Date] ↔ gold_kpi_monthly[?]     → varsa kontrol et
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — PRIOR YEAR (PY) ÖLÇÜLERİ
//
// Date tablosu "Mark as Date Table" yapıldıktan sonra
// DATEADD('Date'[Date], -1, YEAR) güvenilir çalışır.
//
// Bu ölçüler eski 02_dax_measures.dax, 10_dax_v5_final.dax,
// 11_dax_v6_gap_fix.dax ölçülerinin yerini alır.
// ==========================================================================

Total Energy PY kWh =
CALCULATE(
    [Total Consumption kWh],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0 "kWh"
// Kart     : C1 → Target goals
// NOT      : Date tablosu "Mark as Date Table" yapılmadan çalışmaz

Previous Year Consumption kWh =
CALCULATE(
    [Total Consumption kWh],
    DATEADD('Date'[Date], -1, YEAR)
)

Previous Year Net Carbon tCO2 =
CALCULATE(
    [Net Carbon Footprint tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0.0 "tCO₂"
// Kart     : C5 → Target goals

Previous Year CO2 Emissions tCO2 =
CALCULATE(
    [Total CO2 Emissions tCO2],
    DATEADD('Date'[Date], -1, YEAR)
)

Anomaly Count PY Same Period =
CALCULATE(
    [Active Anomaly Count],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : #,##0
// Kart     : C3 → Target goals

Previous Year Cost EUR =
CALCULATE(
    [Total Energy Cost EUR],
    DATEADD('Date'[Date], -1, YEAR)
)
// Format   : € #,##0
// Kart     : C4 → Target goals

Energy Reduction Target kWh =
VAR _py = CALCULATE(
    [Total Consumption kWh],
    DATEADD('Date'[Date], -1, YEAR)
)
RETURN _py * 0.95
// Format   : #,##0 "kWh"
// Kart     : C1 → Target goals (PY verisi varsa bu tercih edilmeli)

Solar Generation PY kWh =
CALCULATE(
    [Total Solar Generated kWh],
    DATEADD('Date'[Date], -1, YEAR)
)

Carbon Intensity PY kg m2 Day =
CALCULATE(
    [Avg Carbon Intensity kg m2],
    DATEADD('Date'[Date], -1, YEAR)
)

Vacancy Rate PY Pct =
CALCULATE(
    [Vacancy Rate Pct],
    DATEADD('Date'[Date], -1, YEAR)
)

Renewable Rate PY Pct =
CALCULATE(
    [Renewable Energy Rate Pct],
    DATEADD('Date'[Date], -1, YEAR)
)

Annual Saving Target EUR =
VAR _py = CALCULATE(
    [Total Energy Cost EUR],
    DATEADD('Date'[Date], -1, YEAR)
)
RETURN _py * 0.10


// ==========================================================================
// BÖLÜM 2 — ROLLING WINDOW ÖLÇÜLERİ (C6-C11)
//
// _maxDate PATTERN (v9'da kanıtlanmış, C10-C11 zaten çalışıyordu):
//   VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
//
// Bu pattern:
//   ✅ Date slicerından bağımsız
//   ✅ Bina slicerına duyarlı
//   ✅ Verinin gerçekten bittiği tarihi alır (Date tablosunun sonu değil)
//   ✅ v9'da C10, C11 için zaten çalışıyor
//
// Filtering: DATESBETWEEN('Date'[Date], ...) — Date tablosu üzerinden
//            ilişki yayılımını kullanır → gold_kpi_daily otomatik filtreli
// ==========================================================================

// ── C6: Geçen Hafta ─────────────────────────────────────────────────────────
Last Week kWh v17 =
VAR _maxDate   = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _weekEnd   = _maxDate - 7
VAR _weekStart = _maxDate - 13
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _weekStart, _weekEnd)
)
// Format   : #,##0 "kWh"
// Kart     : C6

// ── C8: Geçen Ay ─────────────────────────────────────────────────────────────
Last Month kWh v17 =
VAR _maxDate        = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
// Format   : #,##0 "kWh"
// Kart     : C8

// ── C10: Son 7 Gün Maliyet ───────────────────────────────────────────────────
Last 7 Days Cost EUR v17 =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total Energy Cost EUR],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
// Format   : € #,##0
// Kart     : C10

// ── C11: Son 30 Gün CO₂ ─────────────────────────────────────────────────────
Last 30 Days CO2 tCO2 v17 =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total CO2 Emissions tCO2],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 29, _maxDate)
)
// Format   : #,##0.0 "tCO₂"
// Kart     : C11


// ==========================================================================
// BÖLÜM 3 — WoW / MoM HESAPLAMA (C7, C9)
//
// "Bu hafta/ay" = verinin son 7 günü / son tam ayı
// "Geçen hafta/ay" = Bölüm 2'deki C6/C8 ölçüleri
// ==========================================================================

// Yardımcı: Bu hafta (C7 için)
_This Week kWh v17 =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)

// Yardımcı: Bu ay (C9 için)
_This Month kWh v17 =
VAR _maxDate        = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _thisMonthStart = DATE(YEAR(_maxDate), MONTH(_maxDate), 1)
RETURN
CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _thisMonthStart, _maxDate)
)

// ── C7: Haftalık Değişim Oku ─────────────────────────────────────────────────
Week over Week Arrow v17 =
VAR _this = [_This Week kWh v17]
VAR _last = [Last Week kWh v17]
VAR _pct  = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 5,       "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -5,      "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,       "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                    "→ 0%"
)
// Format   : General (text)
// Kart     : C7 → Card (new) visual, Value alanı

// ── C9: Aylık Değişim Oku ────────────────────────────────────────────────────
Month over Month Arrow v17 =
VAR _this = [_This Month kWh v17]
VAR _last = [Last Month kWh v17]
VAR _pct  = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 10,      "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -10,     "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,       "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                    "→ 0%"
)
// Format   : General (text)
// Kart     : C9 → Card (new) visual, Value alanı


// ==========================================================================
// BÖLÜM 4 — CF RENK ÖLÇÜLERİ (C7, C9)
//
// KURULUM:
//   C7 kartı → Format pane → Callout value → Font color → fx
//   → Format style: Field value → WoW CF Color v17 → OK
// ==========================================================================

WoW CF Color v17 =
VAR _pct = DIVIDE([_This Week kWh v17] - [Last Week kWh v17], [Last Week kWh v17], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#808080", IF(_pct < 0, "#00D264", "#FF4560"))

WoW CF BG Color v17 =
VAR _pct = DIVIDE([_This Week kWh v17] - [Last Week kWh v17], [Last Week kWh v17], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#1A1A2E", IF(_pct < 0, "#0A2010", "#2E0A14"))

MoM CF Color v17 =
VAR _pct = DIVIDE([_This Month kWh v17] - [Last Month kWh v17], [Last Month kWh v17], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#808080", IF(_pct < 0, "#00D264", "#FF4560"))

MoM CF BG Color v17 =
VAR _pct = DIVIDE([_This Month kWh v17] - [Last Month kWh v17], [Last Month kWh v17], BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#1A1A2E", IF(_pct < 0, "#0A2010", "#2E0A14"))


// ==========================================================================
// BÖLÜM 5 — v10 ALIAS (LW/LM referansları)
// ==========================================================================

LW Consumption kWh =
[Last Week kWh v17]

LM Consumption kWh =
[Last Month kWh v17]


// ==========================================================================
// BÖLÜM 6 — ROLLING OVERLAY (Sayfa 2 grafikleri için)
//
// NOT: Avg Occupancy Rate 30Day Rolling KASITLI OLARAK BURAYA KONULMADI.
//      gold_kpi_daily[avg_occupancy_rate] kolonu mevcut değil.
//      Bu ölçü Sayfa 5 için ayrı bir v18 dosyasında doğru tabloyla
//      yazılacak (gold_occupancy_profile tablosu kullanılacak).
// ==========================================================================

Energy 7Day Rolling Avg kWh =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]))
// NOT: REMOVEFILTERS yok — bu ölçü slicer'a göre çalışmalı (Sayfa 2 grafik)
RETURN
CALCULATE(
    AVERAGE(gold_kpi_daily[total_consumption_kwh]),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
// Format   : #,##0
// Kart     : Sayfa 2 → 7 günlük kayan ortalama overlay

Avg Daily Consumption 30Day Rolling =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]))
RETURN
CALCULATE(
    AVERAGE(gold_kpi_daily[total_consumption_kwh]),
    DATESBETWEEN('Date'[Date], _maxDate - 29, _maxDate)
)
// Format   : #,##0

Avg Peak Demand 30Day kW =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]))
RETURN
CALCULATE(
    AVERAGE(gold_kpi_daily[peak_demand_kw]),
    DATESBETWEEN('Date'[Date], _maxDate - 29, _maxDate)
)
// Format   : #,##0.0 "kW"

High Anomaly Count Previous Week =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [High Anomaly Count v16],
    DATESBETWEEN('Date'[Date], _maxDate - 13, _maxDate - 7)
)

Unresolved Count Previous Week =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
RETURN
CALCULATE(
    [Unresolved Count],
    DATESBETWEEN('Date'[Date], _maxDate - 13, _maxDate - 7)
)

Actual Last 7Day kWh =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]))
RETURN
CALCULATE(
    SUM(gold_kpi_daily[total_consumption_kwh]),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)


// ==========================================================================
// UYGULAMA SIRASI — ADIM ADIM
//
// ❶ v16 ölçülerini sil (Power BI → Model view → sil):
//    Sileceklerin: Last Week kWh v16, Last Month kWh v16, _This Week kWh v16,
//    _This Month kWh v16, Last 7 Days Cost EUR v16, Last 30 Days CO2 tCO2 v16,
//    Week over Week Arrow v16, Month over Month Arrow v16, WoW/MoM CF v16,
//    LW/LM Consumption kWh, Critical/High/Medium/Low Anomaly Count v16,
//    Debug ölçüleri, Avg Occupancy Rate 30Day Rolling (KESİNLİKLE SİL)
//    Tüm Bölüm A-H v16 ölçüleri silinmeli.
//
// ❷ Date tablosuna MonthIndex ekle:
//    Model view → Date tablosu → formülü aç
//    ADDCOLUMNS kısmına şunu ekle (virgülle ayırarak):
//    "MonthIndex", YEAR([Date]) * 100 + MONTH([Date]),
//
// ❸ Date tablosunu Mark as Date Table yap:
//    Model view → Date tablosu üstüne sağ tık
//    → Mark as date table → Date[Date] seç
//
// ❹ Bu dosyadaki ölçüleri New Measure ile ekle.
//
// ❺ Kartları güncelle:
//    C6  → Last Week kWh v17
//    C7  → Week over Week Arrow v17
//          CF Font: WoW CF Color v17
//          CF BG  : WoW CF BG Color v17
//    C8  → Last Month kWh v17
//    C9  → Month over Month Arrow v17
//          CF Font: MoM CF Color v17
//          CF BG  : MoM CF BG Color v17
//    C10 → Last 7 Days Cost EUR v17
//    C11 → Last 30 Days CO2 tCO2 v17
//    C1 TGT → Energy Reduction Target kWh
//    C3 TGT → Anomaly Count PY Same Period
//    C4 TGT → Previous Year Cost EUR
//    C5 TGT → Previous Year Net Carbon tCO2
//
// ❻ YearMonth Sort by Column:
//    Model view → Date tablosu → YearMonth kolonunu seç
//    → Column tools → Sort by Column → MonthIndex
//
// ❼ Raporu yenile → Sayfa 1'i test et
// ==========================================================================

// SON — 22_dax_v17_page1_final.dax
