// ==========================================================================
// Energy Copilot Platform — DAX v17 Patch
// File: semantic-model/23_dax_v17_patch.dax
// Created: 2026-04-24
//
// SORUN: [_This Month kWh v17] ve [_This Week kWh v17] referansları
//        Power BI'da bulunamıyor — alt çizgi prefix'li ölçüler
//        hidden sayılıp başka ölçülerden referans alınamıyor.
//
// ÇÖZÜM: Hesaplamalar doğrudan arrow ve CF ölçülerine gömüldü.
//        _This Month ve _This Week alt ölçüleri artık gerekmiyor,
//        Power BI'dan silebilirsin.
//
// YAPILACAK:
//   1. Aşağıdaki 4 ölçüyü mevcut v17 versiyonlarının üzerine güncelle
//      (aynı isimli ölçüyü seç → formülü değiştir → Enter)
//   2. _This Week kWh v17 ve _This Month kWh v17 ölçülerini sil (opsiyonel)
// ==========================================================================

Week over Week Arrow v17 =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _this = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 13, _maxDate - 7)
)
VAR _pct = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 5,       "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -5,      "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,       "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                    "→ 0%"
)

Month over Month Arrow v17 =
VAR _maxDate        = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
VAR _thisMonthStart = DATE(YEAR(_maxDate), MONTH(_maxDate), 1)
VAR _this = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _thisMonthStart, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
VAR _pct = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 10,      "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -10,     "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,       "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                    "→ 0%"
)

WoW CF Color v17 =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _this = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 13, _maxDate - 7)
)
VAR _pct = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#808080", IF(_pct < 0, "#00D264", "#FF4560"))

MoM CF Color v17 =
VAR _maxDate        = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
VAR _thisMonthStart = DATE(YEAR(_maxDate), MONTH(_maxDate), 1)
VAR _this = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _thisMonthStart, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
VAR _pct = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
IF(ISBLANK(_pct), "#808080", IF(_pct < 0, "#00D264", "#FF4560"))

// SON — 23_dax_v17_patch.dax
