// ==========================================================================
// DAX v17 CF Patch — Numeric CF ölçüleri
// Power BI Card (new) visualda "Field value" hex string çalışmıyor.
// Çözüm: Numeric ölçü + Rules CF kullan.
//
// KURULUM (C7 örneği):
//   C7 kartı → Format pane → Callout value → Font color → fx
//   Format style: Rules
//   What field: WoW Pct Numeric v17
//   Kural 1: If value < 0         → #00D264  (yeşil — azalış iyi)
//   Kural 2: If value >= 0        → #FF4560  (kırmızı — artış kötü)
//
// Aynısını C9 için MoM Pct Numeric v17 ile yap.
// ==========================================================================

WoW Pct Numeric v17 =
VAR _maxDate = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _this = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _maxDate - 13, _maxDate - 7)
)
RETURN
    DIVIDE(_this - _last, _last, BLANK()) * 100
// Format   : 0.0 (gizli ölçü — sadece CF için kullanılır)
// CF Rules : < 0 → #00D264 | >= 0 → #FF4560

MoM Pct Numeric v17 =
VAR _maxDate        = CALCULATE(MAX(gold_kpi_daily[date]), REMOVEFILTERS('Date'))
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
VAR _thisMonthStart = DATE(YEAR(_maxDate), MONTH(_maxDate), 1)
VAR _this = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _thisMonthStart, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    REMOVEFILTERS('Date'),
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
RETURN
    DIVIDE(_this - _last, _last, BLANK()) * 100
// Format   : 0.0 (gizli ölçü — sadece CF için kullanılır)
// CF Rules : < 0 → #00D264 | >= 0 → #FF4560

// SON
