// ==========================================================================
// Energy Copilot Platform — DAX v18: Slicer-Aware Rolling Measures
// File: semantic-model/25_dax_v18_slicer_aware.dax
// Created: 2026-04-24
//
// v17 SORUNU:
//   REMOVEFILTERS('Date') → tarih slicerı tamamen görmezden gelindi.
//   Bina slicerı ise REMOVEFILTERS nedeniyle bazı durumlarda
//   gold_kpi_daily'e doğru propagate olmadı.
//   Sonuç: hiçbir slicer bu kartları etkilemedi.
//
// v18 YAKLAŞIMI — REMOVEFILTERS TAMAMEN KALDIRILDI:
//   _maxDate = MAX(gold_kpi_daily[date])
//     → Slicer context içinde çalışır
//     → Date slicer "2025" seçilirse → Aralık 2025'in son günü
//     → Building "Frankfurt" seçilirse → Frankfurt'un son veri günü
//     → Tüm slicer'lar ÇALIŞtıktan sonra son tarihi alır
//
//   RETURN CALCULATE(..., DATESBETWEEN('Date'[Date], start, end))
//     → DATESBETWEEN, slicer'ın date filterını override eder
//     → "Seçili period'ın sonuna göre geçen hafta/ay" mantığı
//     → Bina filtresi olduğu gibi kalır → bina slicerı çalışır
//
// SONUÇ:
//   ✅ Building Name slicer → kartlar değişir
//   ✅ City/Country/Type slicer → kartlar değişir
//   ✅ Date Range slicer → kartlar, seçili aralığın son haftasını gösterir
//   ✅ Veri boşluğu güvenli → MAX gold_kpi_daily[date] fiziksel kolonu
//
// KALDIRILAN ÖLÇÜLER (Power BI'dan sil):
//   _This Week kWh v17, _This Month kWh v17
//   Last Week kWh v17, Last Month kWh v17
//   Last 7 Days Cost EUR v17, Last 30 Days CO2 tCO2 v17
//   Week over Week Arrow v17, Month over Month Arrow v17
//   WoW/MoM CF Color/BG v17, WoW/MoM Pct Numeric v17
//   LW/LM Consumption kWh (v17 versiyonu)
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — ROLLING WINDOW ÖLÇÜLERİ (C6, C8, C10, C11)
//
// Tümü slicer-aware. _maxDate context'e göre hesaplanır.
// ==========================================================================

Last Week kWh v18 =
VAR _maxDate   = MAX(gold_kpi_daily[date])
VAR _weekEnd   = _maxDate - 7
VAR _weekStart = _maxDate - 13
RETURN
CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _weekStart, _weekEnd)
)
// Örnek (Tüm bina, tüm tarih):
//   maxDate = 10.01.2026 → geçen hafta = 28.12.2025–03.01.2026
// Örnek (Frankfurt, 2025):
//   maxDate = 31.12.2025 (Frankfurt'un 2025 son günü)
//   → geçen hafta = 18.12.2025–24.12.2025
// Format : #,##0 "kWh" | Kart: C6

Last Month kWh v18 =
VAR _maxDate        = MAX(gold_kpi_daily[date])
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
RETURN
CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
// Format : #,##0 "kWh" | Kart: C8

Last 7 Days Cost EUR v18 =
VAR _maxDate = MAX(gold_kpi_daily[date])
RETURN
CALCULATE(
    [Total Energy Cost EUR],
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
// Format : € #,##0 | Kart: C10

Last 30 Days CO2 tCO2 v18 =
VAR _maxDate = MAX(gold_kpi_daily[date])
RETURN
CALCULATE(
    [Total CO2 Emissions tCO2],
    DATESBETWEEN('Date'[Date], _maxDate - 29, _maxDate)
)
// Format : #,##0.0 "tCO₂" | Kart: C11


// ==========================================================================
// BÖLÜM 2 — WoW / MoM OK ETİKETLERİ (C7, C9)
//
// "Bu hafta/ay" = maxDate'den geriye N gün
// "Geçen hafta/ay" = Bölüm 1'deki ölçüler
// Tüm hesaplar inline — alt ölçü referansı yok.
// ==========================================================================

Week over Week Arrow v18 =
VAR _maxDate   = MAX(gold_kpi_daily[date])
VAR _thisStart = _maxDate - 6
VAR _lastEnd   = _maxDate - 7
VAR _lastStart = _maxDate - 13
VAR _this = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _thisStart, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _lastStart, _lastEnd)
)
VAR _pct = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 5,       "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -5,      "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,       "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                    "→ 0%"
)
// Format : General (text) | Kart: C7

Month over Month Arrow v18 =
VAR _maxDate        = MAX(gold_kpi_daily[date])
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
VAR _thisMonthStart = DATE(YEAR(_maxDate), MONTH(_maxDate), 1)
VAR _this = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _thisMonthStart, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
VAR _pct = DIVIDE(_this - _last, _last, BLANK()) * 100
RETURN
SWITCH(
    TRUE(),
    ISBLANK(_pct),  "—",
    _pct > 10,      "▲▲ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct > 0,       "▲ "  & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < -10,     "▼▼ " & FORMAT(ABS(_pct), "0.0") & "%",
    _pct < 0,       "▼ "  & FORMAT(ABS(_pct), "0.0") & "%",
                    "→ 0%"
)
// Format : General (text) | Kart: C9


// ==========================================================================
// BÖLÜM 3 — CF NUMERIC ÖLÇÜLERİ (Rules CF için)
//
// KURULUM:
//   C7 → Format → Callout value → Font color → fx
//   Format style: Rules
//   Field: WoW Pct Numeric v18
//   Kural 1: Değer < 0     → Renk: #00D264 (yeşil)
//   Kural 2: Değer >= 0    → Renk: #FF4560 (kırmızı)
//   Aynısı C9 için MoM Pct Numeric v18 ile.
// ==========================================================================

WoW Pct Numeric v18 =
VAR _maxDate   = MAX(gold_kpi_daily[date])
VAR _this = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _maxDate - 6, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _maxDate - 13, _maxDate - 7)
)
RETURN
    DIVIDE(_this - _last, _last, BLANK()) * 100
// Format : 0.0 | CF Rules: < 0 → #00D264, >= 0 → #FF4560

MoM Pct Numeric v18 =
VAR _maxDate        = MAX(gold_kpi_daily[date])
VAR _lastMonthEnd   = DATE(YEAR(_maxDate), MONTH(_maxDate), 1) - 1
VAR _lastMonthStart = DATE(YEAR(_lastMonthEnd), MONTH(_lastMonthEnd), 1)
VAR _thisMonthStart = DATE(YEAR(_maxDate), MONTH(_maxDate), 1)
VAR _this = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _thisMonthStart, _maxDate)
)
VAR _last = CALCULATE(
    [Total Consumption kWh],
    DATESBETWEEN('Date'[Date], _lastMonthStart, _lastMonthEnd)
)
RETURN
    DIVIDE(_this - _last, _last, BLANK()) * 100
// Format : 0.0 | CF Rules: < 0 → #00D264, >= 0 → #FF4560


// ==========================================================================
// BÖLÜM 4 — v10 ALIAS (referans uyumu için)
// ==========================================================================

LW Consumption kWh =
[Last Week kWh v18]

LM Consumption kWh =
[Last Month kWh v18]


// ==========================================================================
// UYGULAMA — 4 ADIM
//
// ❶ Power BI'da v17 rolling ölçülerini sil:
//    Last Week/Month kWh v17, Last 7 Days Cost EUR v17,
//    Last 30 Days CO2 tCO2 v17, Week/Month over Week/Month Arrow v17,
//    WoW/MoM CF Color/BG Color v17, WoW/MoM Pct Numeric v17
//    _This Week/Month kWh v17, LW/LM Consumption kWh (v17 versiyonu)
//
// ❷ Bu dosyadaki ölçüleri New Measure ile ekle (8 ölçü).
//
// ❸ Kartları güncelle:
//    C6  → Last Week kWh v18
//    C7  → Week over Week Arrow v18
//          CF: Format → Callout value → Font color → fx → Rules
//              WoW Pct Numeric v18 | < 0: #00D264 | >= 0: #FF4560
//    C8  → Last Month kWh v18
//    C9  → Month over Month Arrow v18
//          CF: MoM Pct Numeric v18 | < 0: #00D264 | >= 0: #FF4560
//    C10 → Last 7 Days Cost EUR v18
//    C11 → Last 30 Days CO2 tCO2 v18
//
// ❹ TEST:
//    a) Building Name = Frankfurt Klinikum → C6/C8/C10/C11 değişmeli
//    b) Date Range = 2025 → C6 Aralık 2025'in son haftasını göstermeli
//    c) Tüm filtreleri kaldır → portföy toplamları
// ==========================================================================

// SON — 25_dax_v18_slicer_aware.dax
