// ==========================================================================
// Energy Copilot Platform — DAX v19c: Battery SoC — Definitive Fix
// File: semantic-model/28_dax_v19c_battery_soc_revert.dax
// Created: 2026-04-25
//
// SORUN ÖZETI:
//   v19  → Date Cap Pattern uygulandı → V10 trend grafiği bozuldu (kümülatif avg)
//   v19b → Conditional Cap Pattern → "Fix this" hatası devam etti
//
// KÖK NEDEN — KPI Indicator Visual:
//   C5 görseli "KPI Indicator" tipinde. Bu visual, "Trend axis" field'ı ile
//   her veri noktası için ayrı bir DAX evaluation context açar.
//   REMOVEFILTERS('Date') veya karmaşık CALCULATE çağrıları bu contextte
//   Power BI'ın evaluation engine'ini karıştırıyor → "Fix this" hatası.
//
//   Kanıt: EUI ölçüsü (Avg EUI kWh m2) aynı AVERAGEX(FILTER(<>BLANK()))
//   pattern'ini kullanıyor ve herhangi bir Date Cap olmadan çalışıyor.
//   Neden? AVERAGEX sadece gold_kpi_daily'de MEVCUT satırlar üzerinde iter.
//   Future tarihler için gold_kpi_daily'de satır yok → doğal filtre oluşur.
//
// ÇÖZÜM — İki adım:
//
//   ADIM 1 — DAX (bu dosya):
//     Avg Battery SoC Pct → EUI pattern'ine geri dön.
//     AVERAGEX(FILTER(<>BLANK())) → Date Cap'e gerek yok.
//     V10 trend grafiği: her tarih D için gold_kpi_daily'de sadece D'nin satırı
//     var → o günün min/max ortalaması döner. ✅
//     C5 kart (slicer 2026-07): gold_kpi_daily'de 2026-04-18 sonrası yok →
//     AVERAGEX otomatik olarak sadece mevcut veriyi hesaplar. ✅
//
//   ADIM 2 — Power BI UI (30 saniye):
//     C5 görselini seç → Visual type: "KPI Indicator" → "New Card" olarak değiştir.
//     New Card formatı: Callout value → Avg Battery SoC Pct bağlı kalacak.
//     Format code: "0.0" (değişmez).
//     KPI Indicator'ın Trend axis field'ı New Card'da yok → evaluation
//     problemi ortadan kalkar.
//
// Power BI'DA UYGULANACAK İŞLEM:
//   Modeling → Avg Battery SoC Pct → formülü aşağıdaki ile değiştir
// ==========================================================================


// ── Avg Battery SoC Pct (UPDATE — v19c ile değiştir) ─────────────────────
// P2 C5 Value + V10 Battery SoC Trend ekseni
// Format: 0.0  (NOT "0%" — spec gereği)
// Yön: High is Good | Hedef: Battery SoC Target (sabit 80)
//
// NOT: v19 ve v19b'den FARKLI — Date Cap yok, Conditional Cap yok.
//      EUI ile aynı pattern. "New Card" visual ile beraber çalışır.
Avg Battery SoC Pct =
AVERAGEX(
    FILTER(
        gold_kpi_daily,
        gold_kpi_daily[battery_soc_min_pct] <> BLANK() &&
        gold_kpi_daily[battery_soc_max_pct] <> BLANK()
    ),
    (gold_kpi_daily[battery_soc_min_pct] + gold_kpi_daily[battery_soc_max_pct]) / 2
)
// Bu formül neden future-date blank sorununa karşı güvenli?
//   → AVERAGEX(FILTER(gold_kpi_daily, ...)) yalnızca mevcut satırlar üzerinde iter.
//   → Date slicer 2026-07'ye uzasa da gold_kpi_daily'de o tarihler yok.
//   → Filter context gold_kpi_daily'yi doğal olarak 2026-04-18'e kadar kısıtlar.
//   → BLANK() filtresi zaten null satırları eler.
//   → Eğer seçili bina/dönemde gerçekten veri yoksa BLANK() döner → doğru davranış.


// ==========================================================================
// POWER BI'DA YAPILACAK İŞLEMLER (Sırasıyla)
// ==========================================================================
//
// ADIM 1 — DAX ölçüsünü güncelle:
//   Modeling → Measures → "Avg Battery SoC Pct" seç
//   Mevcut formülü tamamen sil, yukarıdaki formülü yapıştır
//   Enter → Kaydet
//
// ADIM 2 — C5 görsel tipini değiştir:
//   Sayfa 2 → C5 kartını (Battery SoC) seç
//   Visualizations pane → "KPI Indicator" ikonuna tıkla
//   → "New Card" (veya "Card") seç
//   Görsel dönüşecek; format ve field bağlantısı genellikle korunur.
//   Eğer field kaybolursa: Fields pane → "Avg Battery SoC Pct" sürükle
//   → Callout value alanına bırak.
//
// ADIM 3 — Format kontrol:
//   C5 seçili iken Format pane → Callout value → Format code: "0.0"
//   (KPI Indicator'dan gelince "0%" olabilir — kontrol et)
//
// ADIM 4 — Test:
//   Slicer: 12.04.2025 → 17.07.2026
//   Tek bina seç (B001 Berliner Bürogebäude Alpha)
//   C5: değer göstermeli (~65-80 arası), "Fix this" yok ✅
//   V10 Battery SoC Trend: dalgalı trend, düz çizgi değil ✅
//   (Trend grafiği düz görünüyorsa → simulation fix gerekiyor — ayrı konu)
//
// ==========================================================================
// Beklenen davranış:
//   C5 Kart (2025 içinde)  → seçili dönem ortalaması (ör. 72.4) ✅
//   C5 Kart (2026-07 sonu) → 2026-04-18'e kadar ortalama, blank yok ✅
//   V10 Trend chart        → her ay gerçek SoC ortalaması (kümülatif değil) ✅
//   "Fix this" hatası      → tamamen ortadan kalkar ✅
// ==========================================================================
