// ==========================================================================
// Energy Copilot Platform — DAX v21: Page 3 Clean Measures
// File: semantic-model/30_dax_v21_page3_clean_measures.dax
// Last updated: 2026-04-25
//
// AMAÇ:
//   Sayfa 3 kartlarında versiyonlanan ölçüler (v14, v16 vb.) kafa karışıklığı
//   yaratıyor ve yanlış değerler gösteriyor. Bu dosya Page 3'teki TÜM kartlar
//   için "P3_" prefix'li, bağımsız, garantili doğru formüllü ölçüleri tanımlar.
//   Bu ölçüleri kullandıktan sonra Page 3 kartlarında başka bir ölçüye ihtiyaç yok.
//
// KURULUM:
//   Power BI Desktop → Home → New Measure
//   Her ölçü için adı ve formülü yapıştır.
//
// ÖNEMLİ — DATEADD SYNTAX:
//   Bu dosyada '''Date'''[Date] formatı kullanılmıştır.
//   Fabric semantic modelinde Date tablosunun adı nasıl görünüyorsa
//   mevcut çalışan ölçülerindeki formatla aynı şekilde kullan.
//
// VISUAL BINDING TABLOSU (dosyanın sonunda):
//   Her kart için hangi ölçünün nereye bağlanacağı tam olarak belirtildi.
// ==========================================================================


// ==========================================================================
// ── KART C1: TOTAL ANOMALIES ──────────────────────────────────────────────
//
// Tüm anomaliler — çözülmüş + çözülmemiş, tüm severity.
// Trend: Bu dönem vs geçen yıl aynı dönem → genel portföy risk trendi.
// ==========================================================================

// C1 → Value alanı
// Format: "#,##0"
P3 Total Anomaly Count =
COUNTROWS ( gold_anomaly_log )

// C1 → Target alanı
// Format: "#,##0"
P3 Total Anomaly PY =
CALCULATE (
    [P3 Total Anomaly Count],
    DATEADD ( '''Date'''[Date], -1, YEAR )
)


// ==========================================================================
// ── KART C2: CRITICAL ANOMALIES (OPEN) ───────────────────────────────────
//
// Sadece CRITICAL severity + is_resolved = FALSE olan anomaliler.
// Hedef her zaman 0 — kritik hiçbir şey açık kalmamalı.
// Bu kart New Card olarak kullanılmalı (KPI Indicator sorunlu, aşağıya bak).
// ==========================================================================

// C2 → Value alanı
// Format: "#,##0"  Renk: #FF4560 (kırmızı)
P3 Critical Open Count =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "CRITICAL",
    gold_anomaly_log[is_resolved] = FALSE
)


// ==========================================================================
// ── KART C3: HIGH ANOMALIES ──────────────────────────────────────────────
//
// Sadece HIGH severity anomaliler (resolved dahil — trend görmek için).
// Hedef: Geçen ay aynı dönemdeki HIGH sayısı.
// Anomaly detection aylık çalışıyor → haftalık target anlamsız, aylık doğru.
// ==========================================================================

// C3 → Value alanı
// Format: "#,##0"  Renk: #FF6B35 (turuncu)
P3 High Anomaly Count =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "HIGH"
)

// C3 → Target alanı
// Format: "#,##0"
P3 High Anomaly Previous Month =
CALCULATE (
    [P3 High Anomaly Count],
    DATEADD ( '''Date'''[Date], -1, MONTH )
)


// ==========================================================================
// ── KART C4: UNRESOLVED ANOMALIES ────────────────────────────────────────
//
// Çözümlenmemiş (open) anomali sayısı — tüm severity.
// Hedef: Geçen yıl aynı dönemdeki unresolved sayısı (YoY karşılaştırma).
// NOT: Notebook çalıştıktan sonra bu değer 197'den düştü → gerçekçi görünüm ✓
// ==========================================================================

// C4 → Value alanı
// Format: "#,##0"  Renk: #FFC107 (sarı)
P3 Unresolved Count =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[is_resolved] = FALSE
)

// C4 → Target alanı
// Format: "#,##0"
P3 Unresolved YoY =
CALCULATE (
    [P3 Unresolved Count],
    DATEADD ( '''Date'''[Date], -1, YEAR )
)


// ==========================================================================
// ── KART C5: DATA QUALITY SCORE ──────────────────────────────────────────
//
// silver_data_quality tablosundaki kalite skoru ortalaması (0-100 arası).
// Bu kart MUTLAKA New Card visual olmalı — KPI Indicator:
//   • Aylık tabloya haftalık trend axis bağlayınca BLANK hafta → "See details"
//   • Tek bina seçiminde daha da kırılgan
// New Card: sadece değeri gösterir, trend sorununa girmez.
// ==========================================================================

// C5 → Value alanı (New Card visual kullan)
// Format: "0.0"
P3 Data Quality Score =
AVERAGE ( silver_data_quality[quality_score_pct] )

// C5 → Reference Line değeri (opsiyonel, Format pane → Reference line)
// Format: "0.0"
P3 Data Quality Target =
VAR _target = 95
RETURN _target


// ==========================================================================
// ── YARDIMCI: MEDIUM ANOMALİ SAYISI (V8 chart için) ──────────────────────
// ==========================================================================

// V8 Stacked Column → Series alanlarından biri
// Format: "#,##0"
P3 Medium Anomaly Count =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "MEDIUM"
)

// V8 → CRITICAL için (zaten P3 Critical Open Count var ama
//       V8'de resolved dahil tüm critical lazım)
// Format: "#,##0"
P3 Critical Anomaly Count =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "CRITICAL"
)

// V8 → LOW (varsa)
// Format: "#,##0"
P3 Low Anomaly Count =
CALCULATE (
    COUNTROWS ( gold_anomaly_log ),
    gold_anomaly_log[severity] = "LOW"
)


// ==========================================================================
// ── YARDIMCI: BUILDING ANOMALY SHARE (V9 chart için) ─────────────────────
// ==========================================================================

// V9 Building Anomaly Share → Horizontal bar chart X alanı
// Portföydeki her binanın anomali payı (toplam ~100%)
// Format: "0.0"
P3 Building Anomaly Share Pct =
VAR _building = [P3 Total Anomaly Count]
VAR _portfolio =
    CALCULATE (
        [P3 Total Anomaly Count],
        ALL ( silver_building_master )
    )
RETURN
    DIVIDE ( _building, _portfolio ) * 100


// ==========================================================================
// ── YARDIMCI: ANOMALY DEVIATION PCT (V6 tablo için) ──────────────────────
// ==========================================================================

// V6 Tablo → "Active Anomaly" sütununu kaldır, bunu ekle
// "Eşiği ne kadar aştı?" sorusunu yanıtlar
// metric_value = tespit edilen değer
// threshold_value = aşılan eşik
// Format: "+0.0;-0.0;—"
P3 Anomaly Deviation Pct =
VAR _metric    = AVERAGE ( gold_anomaly_log[metric_value] )
VAR _threshold = AVERAGE ( gold_anomaly_log[threshold_value] )
RETURN
    IF (
        NOT ISBLANK ( _threshold ) && ABS ( _threshold ) > 0,
        DIVIDE ( _metric - _threshold, ABS ( _threshold ) ) * 100,
        BLANK ()
    )


// ==========================================================================
// VISUAL BINDING TABLOSU — SAYFA 3 KARTLARı
// ==========================================================================
//
// ┌────┬──────────────────────────┬───────────────┬──────────────────────────┬─────────────────────────────┬────────────────┬──────────────┐
// │    │ Kart Adı                 │ Visual Type   │ Value                    │ Target / Trend Axis         │ Format         │ Direction    │
// ├────┼──────────────────────────┼───────────────┼──────────────────────────┼─────────────────────────────┼────────────────┼──────────────┤
// │ C1 │ Total Anomalies          │ KPI Indicator │ P3 Total Anomaly Count   │ Target: P3 Total Anomaly PY │ #,##0          │ Low is Good  │
// │    │                          │               │                          │ Trend: Date[Date]           │                │              │
// ├────┼──────────────────────────┼───────────────┼──────────────────────────┼─────────────────────────────┼────────────────┼──────────────┤
// │ C2 │ Critical Anomalies (Open)│ NEW CARD ★    │ P3 Critical Open Count   │ (yok — New Card'da target   │ #,##0          │ —            │
// │    │                          │               │                          │  yok, renk kırmızı yap)     │ Renk: #FF4560  │              │
// ├────┼──────────────────────────┼───────────────┼──────────────────────────┼─────────────────────────────┼────────────────┼──────────────┤
// │ C3 │ High Anomalies           │ KPI Indicator │ P3 High Anomaly Count    │ Target: P3 High Anomaly     │ #,##0          │ Low is Good  │
// │    │                          │               │                          │         Previous Month      │                │              │
// │    │                          │               │                          │ Trend: Date[Date]           │                │              │
// ├────┼──────────────────────────┼───────────────┼──────────────────────────┼─────────────────────────────┼────────────────┼──────────────┤
// │ C4 │ Unresolved Anomalies     │ KPI Indicator │ P3 Unresolved Count      │ Target: P3 Unresolved YoY   │ #,##0          │ Low is Good  │
// │    │                          │               │                          │ Trend: Date[Date]           │                │              │
// ├────┼──────────────────────────┼───────────────┼──────────────────────────┼─────────────────────────────┼────────────────┼──────────────┤
// │ C5 │ Data Quality Score (%)   │ NEW CARD ★    │ P3 Data Quality Score    │ Reference Line (opsiyonel): │ 0.0            │ —            │
// │    │                          │               │                          │ P3 Data Quality Target (95) │ Subtitle: "%"  │              │
// └────┴──────────────────────────┴───────────────┴──────────────────────────┴─────────────────────────────┴────────────────┴──────────────┘
//
// ★ NEW CARD → KPI Indicator değil!
//   C2 ve C5 mutlaka New Card olmalı.
//   KPI Indicator: is_resolved=0 veya aylık tablo + haftalık trend → crash/blank.
//
// V8 STACKED COLUMN — Monthly Anomalies by Severity
//   X axis : Date[YearMonth]  (Sort by Column → MonthIndex)
//   Legend/Series:
//     CRITICAL → P3 Critical Anomaly Count   (renk: #FF4560)
//     HIGH     → P3 High Anomaly Count        (renk: #FF6B35)
//     MEDIUM   → P3 Medium Anomaly Count      (renk: #FFC107)
//
// V9 HORIZONTAL BAR — Building Anomaly Share
//   Y axis : silver_building_master[building_name]
//   X axis : P3 Building Anomaly Share Pct
//   Format : "0.0"  (data labels ON)
//   Sort   : DESC
//
// V6 TABLE — Anomaly Detail
//   Sütunlar (sırayla):
//   1. silver_building_master[building_name]   → "Building"
//   2. gold_anomaly_log[severity]              → "Severity"   (CF: CRITICAL=#FF4560 HIGH=#FF6B35 MEDIUM=#FFC107)
//   3. gold_anomaly_log[anomaly_type]          → "Type"
//   4. gold_anomaly_log[detected_date]         → "Detected"   (format: DD.MM.YYYY)
//   5. gold_anomaly_log[is_resolved]           → "Status"     (CF: FALSE="Open"=#FF4560 TRUE="Resolved"=#00E5A0)
//   6. P3 Anomaly Deviation Pct               → "Deviation %" (format: "+0.0;-0.0;—")
//   ★ "Active Anomaly" sütununu kaldır
//
// ==========================================================================

// SON
