// ==========================================================================
// Energy Copilot Platform — DAX v24: Page 4 Production Fix
// File: semantic-model/33_dax_v24_page4_production_fix.dax
// Last updated: 2026-04-26
//
// AMAÇ:
//   Sayfa 4 (Forecast & Recommendations) embed öncesi production hazırlığı.
//   Screenshot analizinden tespit edilen sorunlar ve yeni layout gereksinimlerine
//   göre oluşturulmuş ölçüler.
//
// KAPSAM (5 BÖLÜM):
//   BÖLÜM 1 — C2 FIX:  Forecast 30Day PY kWh (eksik ölçü → Goal blank → -∞%)
//   BÖLÜM 2 — C3 FIX:  Savings Goal EUR (BLANK-safe, PY cost fallback'li)
//   BÖLÜM 3 — C5 YENİ: Avg MAPE kart ölçüleri (hedef + safe wrapper)
//   BÖLÜM 4 — V12 YENİ: Actions by Priority bar chart ölçüleri
//   BÖLÜM 5 — FORECAST KALİTE: 30-Day data yeterliliği kontrolü + aligned actual
//
// ÖNEMLI VERİ NOTU (Root Cause Analizi):
//   7-Day ve 30-Day KPI kartları aynı değeri (35.428 kWh) gösteriyor.
//   Neden: gold_consumption_forecast tablosu yalnızca 7 günlük veri içeriyor.
//   Forecast 30Day kWh aynı 7 günü topluyor → aynı sonuç.
//   DAX Fix: Bölüm 5'teki Forecast 30Day Safe kWh ölçüsü bunu kontrol eder.
//   Gerçek fix: forecast notebook'un 30 günlük veri üretmesi gerekiyor.
//
//   C1 Goal (+84%) sorunu:
//   Actual Last 7Day kWh = MAX(gold_kpi_daily[date]) son 7 günün PORTFÖY toplamı
//   (~6 bina × 7 gün × ortalama ~5.000 kWh ≈ 221.530 kWh).
//   Forecast 7Day kWh = son 7 forecast gününün toplamı (tek bina bazında olabilir).
//   Elma-portakal karşılaştırması → anlamsız yüzde.
//   DAX Fix: Bölüm 5'teki Actual 7Day Aligned kWh her iki metriği aynı pencereye bağlar.
//
// KURULUM:
//   Power BI Desktop → Home → New Measure → her ölçü için adı + formülü yapıştır.
//   Sıra önemli değil — bölümler bağımsız.
//
// ETKİLENEN SAYFALAR: Sayfa 4 (Forecast & Recommendations)
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — C2 FIX: FORECAST 30DAY PY kWh
//
// Sorun:
//   Layout plannerda C2 (30-Day Forecast) kartının Goal field'ına
//   "Forecast 30Day PY kWh" bağlanması gerekiyor — ama bu ölçü
//   hiçbir DAX dosyasında tanımlanmamış.
//   Goal field boş → Power BI (-∞%) gösteriyor.
//
// Tasarım Kararı:
//   "PY Forecast" için historik tahmin verisi yok (makul — ML modeli geçmişi saklamaz).
//   Bunun yerine: aynı 30 günlük pencereyi geçen yıl actual tüketim verisiyle karşılaştır.
//   Anlam: "Tahmin edilen 30 gün, geçen yıl aynı dönemden daha mı kötü?"
//   Bu karşılaştırma enerji açısından en anlamlı benchmark'tır.
//
// Teknik:
//   gold_consumption_forecast tablosunun son forecast tarihini anchor olarak al.
//   Aynı 30 günlük pencereyi 1 yıl geriye kaydır.
//   gold_kpi_daily tablosunda o döneme ait actual tüketimi topla.
//   REMOVEFILTERS('Date') — slicer filtresi bu hesabı bozmasın.
//
// Kart: C2 → Goal / Target Field
// Format: "#,##0" (kWh)
// Direction: Low is Good (daha az tüketim daha iyidir)
// ==========================================================================

Forecast 30Day PY kWh =
VAR _forecastLast =
    MAXX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _forecastStart = _forecastLast - 29
// Geçen yıl aynı 30 günlük pencere
VAR _pyLast  = DATE ( YEAR ( _forecastLast ) - 1, MONTH ( _forecastLast ), DAY ( _forecastLast ) )
VAR _pyStart = DATE ( YEAR ( _forecastStart ) - 1, MONTH ( _forecastStart ), DAY ( _forecastStart ) )
RETURN
    CALCULATE (
        SUM ( gold_kpi_daily[total_consumption_kwh] ),
        gold_kpi_daily[date] >= _pyStart,
        gold_kpi_daily[date] <= _pyLast,
        REMOVEFILTERS ( 'Date' )
    )
// Beklenen değer: ~100.000-150.000 kWh (portföy bazında, 30 gün, 6 bina)
// Forecast 30Day kWh ile karşılaştır → sapma makul görünmeli


// ==========================================================================
// BÖLÜM 2 — C3 FIX: SAVINGS GOAL EUR — BLANK-SAFE
//
// Sorun:
//   Annual Saving Target EUR (v5 Tier 6) = PY Cost × 0.10
//   Slicer gerçek veri bitişini (örn. 2026-04-18) aştığında
//   veya PY maliyet datası yoksa → BLANK → (+∞%) hatası.
//
// Düzeltme Mantığı:
//   1. PY cost'u dene (DATEADD -1 YEAR)
//   2. PY blank veya 0 ise mevcut dönem cost'unu kullan (fallback)
//   3. Mevcut dönem de blank ise → BLANK döndür (kart boş görünsün, ∞ değil)
//
// Varsayım: %10 enerji maliyet azaltma hedefi
//   Gerekçe: ESOS (UK), EED 2023/1791 (EU), Türkiye EV
//            tipik kısa vadeli hedefi %10'dur.
//   Daha agresif hedef için çarpanı 0.15 veya 0.20 yap.
//
// Kart: C3 → Goal / Target Field
// Format: "€ #,##0"
// Direction: High is Good (tasarruf hedefini geçmek iyidir)
// ==========================================================================

Savings Goal EUR =
VAR _pyCost =
    CALCULATE (
        [Total Energy Cost EUR],
        DATEADD ( gold_kpi_daily[date], -1, YEAR )
    )
VAR _currentCost = [Total Energy Cost EUR]
VAR _safeBase =
    IF ( ISBLANK ( _pyCost ) || _pyCost = 0, _currentCost, _pyCost )
RETURN
    IF (
        ISBLANK ( _safeBase ) || _safeBase = 0,
        BLANK (),
        ROUND ( _safeBase * 0.10, 0 )
    )
// ⚠️ Eğer bu ölçü de blank dönerse:
//    → Total Energy Cost EUR'u doğrula (gold_kpi_daily[estimated_cost_eur] boş mu?)
//    → Alternatif: sabit hedef kullan → Savings Fixed Target EUR (aşağıda)

Savings Fixed Target EUR =
VAR _target = 120000
RETURN _target
// FORMAT: "€ #,##0"
// Kullanım: Savings Goal EUR BLANK dönerse bu ölçüyü fallback olarak kullan.
// 120.000 € = mevcut portföy tasarruf potansiyelinin (102.033 €) %18 üzeri
//             — ulaşılabilir ama zorlayıcı hedef.
// Production'da bu değeri gerçek sözleşme hedefiyle değiştir.


// ==========================================================================
// BÖLÜM 3 — C5 YENİ KPI KARTI: MAPE MODEL ACCURACY
//
// Yeni 5. kart: Ortalama model hata payını gösterir.
// Karar vericiye "Bu tahminlere ne kadar güvenebilirim?" sorusunu yanıtlar.
// MAPE < 10% = mükemmel, 10-20% = kabul edilebilir, >20% = güvenilmez.
//
// Bölümler:
//   Avg MAPE Pct Safe   — kart ana değeri (round 1 decimal)
//   MAPE Goal Pct       — hedef: 10 (industry threshold)
//   MAPE Status Label   — conditional text için (tooltip/subtitle)
// ==========================================================================

// Ana değer — Callout field
// Mevcut Avg Model MAPE Pct formülüne ROUND ve null-guard ekler
Avg MAPE Pct Safe =
VAR _mape = AVERAGE ( gold_consumption_forecast[model_mape_pct] )
RETURN
    IF ( ISBLANK ( _mape ), BLANK (), ROUND ( _mape, 1 ) )
// FORMAT: "0.0"
// Direction: Low is Good

// Hedef — Goal/Target field
// Sabit: MAPE < 10% = endüstri standardı "mükemmel" eşiği
MAPE Goal Pct =
VAR _goal = 10
RETURN _goal
// FORMAT: "0.0"
// Kaynak: ASHRAE Guideline 14 ve IPMVP literatüründe
//         enerji tahmin modeli için kabul edilebilir MAPE eşiği %10'dur.
//         10-20%: iyi, 20-30%: kabul edilebilir, >30%: güvenilmez.

// Text label — New Card subtitle veya tooltip
MAPE Status Label =
VAR _mape = [Avg MAPE Pct Safe]
RETURN
    SWITCH (
        TRUE (),
        ISBLANK ( _mape ), "— No forecast data",
        _mape < 10,  "🟢 Excellent · " & FORMAT ( _mape, "0.0" ) & "%",
        _mape < 20,  "🟡 Good · "      & FORMAT ( _mape, "0.0" ) & "%",
        _mape < 30,  "🟠 Acceptable · " & FORMAT ( _mape, "0.0" ) & "%",
        "🔴 Poor — review model · " & FORMAT ( _mape, "0.0" ) & "%"
    )
// Kullanım: New Card → Category Label veya Data label
// NOT: Bu ölçü string döner — Callout value yerine subtitle/label alanına bağla.


// ==========================================================================
// BÖLÜM 4 — V12 YENİ GÖRSEL: ACTIONS BY PRIORITY (Clustered Bar)
//
// Mevcut tabloda CRITICAL/HIGH/LOW/INFORMATIONAL dağılımı var ama
// aggregate olarak görülmüyor. Yeni bar chart bu boşluğu doldurur.
//
// Görsel tipi: Clustered Bar (Horizontal)
// Y-axis: gold_recommendations[priority_label]  (4 kategori)
// X-axis: Total Recommendation Count (COUNTROWS — zaten mevcut)
//
// ALTERNATIF: Native chart kurulumu — yeni DAX gerekmez.
// priority_label eksen olarak kullanıldığında Power BI otomatik grup oluşturur.
// Ancak aşağıdaki ölçüler renk conditional formatting ve card tooltip için gerekli:
// ==========================================================================

// HIGH priority recommendation count
Rec Count HIGH =
VAR _count =
    CALCULATE (
        COUNTROWS ( gold_recommendations ),
        UPPER ( gold_recommendations[priority_label] ) = "HIGH"
    )
RETURN IF ( ISBLANK ( _count ), 0, _count )
// FORMAT: "#,##0"

// LOW priority recommendation count
Rec Count LOW =
VAR _count =
    CALCULATE (
        COUNTROWS ( gold_recommendations ),
        UPPER ( gold_recommendations[priority_label] ) = "LOW"
    )
RETURN IF ( ISBLANK ( _count ), 0, _count )
// FORMAT: "#,##0"

// INFORMATIONAL / INFO priority recommendation count
// ⚠️ priority_label sütunundaki gerçek değeri kontrol et:
//    gold_recommendations[priority_label] → DAX Studio veya tablo görselinde
//    benzersiz değerleri listele. "INFORMATIONAL" mi, "INFO" mi, "MEDIUM" mi?
Rec Count INFORMATIONAL =
VAR _count =
    CALCULATE (
        COUNTROWS ( gold_recommendations ),
        UPPER ( gold_recommendations[priority_label] ) IN
            { "INFORMATIONAL", "INFO", "MEDIUM" }
    )
RETURN IF ( ISBLANK ( _count ), 0, _count )
// FORMAT: "#,##0"
// ⚠️ MEDIUM veya INFO ise IN listesini güncelle.

// Portföy genelinde toplam yıllık tasarruf (kritik öncelikli)
// Pie tooltip veya bar chart data label olarak kullanılabilir
Savings by CRITICAL EUR =
CALCULATE (
    [Total Annual Saving EUR],
    UPPER ( gold_recommendations[priority_label] ) = "CRITICAL"
)
// FORMAT: "€ #,##0"

Savings by HIGH EUR =
CALCULATE (
    [Total Annual Saving EUR],
    UPPER ( gold_recommendations[priority_label] ) = "HIGH"
)
// FORMAT: "€ #,##0"


// ==========================================================================
// BÖLÜM 5 — FORECAST KALİTE KONTROL & ALIGNED ACTUAL
//
// ROOT CAUSE: 7-Day ve 30-Day aynı değeri gösteriyor (35.428 kWh)
//   → gold_consumption_forecast sadece 7 günlük veri içeriyor.
//   → Forecast 30Day kWh bu 7 günü topluyor → 7Day ile aynı sonuç.
//
// FIX A (DAX): 30Day için minimum veri kontrolü ekle — yetersizse BLANK döndür.
// FIX B (Data): Forecast notebook 30 günlük veri üretmeli.
//               08_consumption_forecast.py → forecast_horizon_days = 30 yap.
//
// ROOT CAUSE 2: 7-Day Goal %+84 gibi saçma görünüyor
//   → Actual Last 7Day kWh: MAX(gold_kpi_daily[date])'den 7 gün geriye git.
//      Tüm binaların toplamı (~221.530 kWh / 6 bina × 7 gün).
//   → Forecast 7Day kWh: Forecast tablonun son 7 günü.
//      Forecast sadece 1 bina veya daha küçük ölçekte → ~35.428 kWh.
//      Elma-portakal karşılaştırması → anlamsız %.
// ==========================================================================

// FIX A — 30Day veri yeterliliği kontrolü
// Eğer forecast'ta 20'den az benzersiz gün varsa, 30-Day hesabı anlamlı değildir.
Forecast 30Day Safe kWh =
VAR _last =
    MAXX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _start = _last - 29
VAR _available_days =
    CALCULATE (
        DISTINCTCOUNT ( gold_consumption_forecast[forecast_date] ),
        gold_consumption_forecast[forecast_date] >= _start,
        gold_consumption_forecast[forecast_date] <= _last,
        ALL ( gold_consumption_forecast )
    )
RETURN
    IF (
        _available_days < 20,
        // 20 günden az forecast varsa BLANK döndür → kart "—" gösterir
        // (Power BI KPI Indicator blank goal'u daha iyi işler: "n/a" yerine sadece değer gösterir)
        BLANK (),
        CALCULATE (
            SUM ( gold_consumption_forecast[predicted_kwh] ),
            gold_consumption_forecast[forecast_date] >= _start,
            gold_consumption_forecast[forecast_date] <= _last
        )
    )
// Kullanım: C2 kartı Value field'ına önce bu ölçüyü dene.
//   Eğer BLANK dönerse: notebook'ta forecast_horizon_days = 30 yap, yeniden çalıştır.
//   BLANK halinde kart boş görünür — yanıltıcı 35.428 değerinden iyidir.

// FIX B — 7-Day Aligned Actual (aynı pencere, aynı bina filtresi)
// Forecast anchor penceresinin hemen öncesindeki 7 günlük actual tüketimi verir.
// Böylece Forecast 7Day kWh ile elma-elma karşılaştırması yapılır.
Actual 7Day Aligned kWh =
VAR _forecastLast =
    MAXX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _forecastStart = _forecastLast - 6
// Forecast hemen başlamadan önceki 7 günlük actual pencere
VAR _actualEnd   = _forecastStart - 1
VAR _actualStart = _actualEnd - 6
RETURN
    CALCULATE (
        SUM ( gold_kpi_daily[total_consumption_kwh] ),
        gold_kpi_daily[date] >= _actualStart,
        gold_kpi_daily[date] <= _actualEnd,
        REMOVEFILTERS ( 'Date' )
    )
// FORMAT: "#,##0"
// Kullanım: C1 (7-Day Forecast) → Goal/Target field → bu ölçüyü kullan
//   Mevcut "Actual Last 7Day kWh" yerine.
//   Beklenen sonuç: ~35.000-45.000 kWh (forecast ile orantılı sapma)
//   %+84 gibi saçma bir değer görmemeli.

// Forecast coverage label — C1/C2 kartlarında subtitle için
// "7 days of forecast data" veya "Only X days available" gibi bilgi verir
Forecast Data Coverage Label =
VAR _last =
    MAXX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _first =
    MINX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _days = DATEDIFF ( _first, _last, DAY ) + 1
RETURN
    IF (
        ISBLANK ( _days ),
        "— No forecast data",
        IF (
            _days < 20,
            "⚠️ Only " & _days & " days of forecast",
            "✓ " & _days & "-day forecast horizon"
        )
    )
// Kullanım: Forecast chart subtitle veya C2 card category label
// Yöneticiye "Bu veri 7 günlük" uyarısını gösterir.


// ==========================================================================
// BÖLÜM 6 — FORECAST REFERENCE LINE (Chart Analytics)
//
// Forecast grafiğinde actual veri ile tahmin sınırını işaretler.
// "Forecast Start" etiketli dikey çizgi olmadan kullanıcı
// nereye kadar gerçek, nereye kadar tahmin bilinmiyor.
//
// Kullanım:
//   Forecast line chart → Analytics pane → Reference Line
//   Value: Forecast Start Date (bu ölçü)
//   Renk: #FFC107 (Amber) dashed 1px
//   Label: "Forecast →"
// ==========================================================================

Forecast Start Date =
CALCULATE (
    MIN ( gold_consumption_forecast[forecast_date] ),
    ALLSELECTED ( gold_consumption_forecast )
)
// TYPE: Scalar Date
// ⚠️ Power BI Analytics pane reference line için scalar date ölçüleri
//    bazen desteklenmez. Alternatif: constant reference line → tarihi manuel gir.
//    Veya Deneb custom visual ile daha esnek çizgi ekle.


// ==========================================================================
// KURULUM REHBERİ — POWER BI ADIMLAR
// ==========================================================================
//
// ADIM 1 — BÖLÜM 1: C2 Goal fix
//   C2 kartını seç (30-Day Forecast)
//   Fields pane → Goal/Target → mevcut ölçüyü kaldır
//   → Forecast 30Day PY kWh ekle (yeni ölçü)
//   Beklenen: Goal ~100.000-150.000 kWh (geçen yıl portföy 30-day)
//   Eğer BLANK → gold_kpi_daily'de PY verisi yok → notebook yeniden çalıştır
//
// ADIM 2 — BÖLÜM 2: C3 Goal fix
//   C3 kartını seç (Savings Potential)
//   Fields pane → Goal/Target → Annual Saving Target EUR yerine
//   → Savings Goal EUR ekle (yeni ölçü)
//   Beklenen: ~20.000-22.000 € (PY maliyetin %10'u)
//   Eğer BLANK → Savings Fixed Target EUR kullan (120.000 €)
//
// ADIM 3 — BÖLÜM 3: C5 yeni kart ekle (MAPE)
//   Canvas'a yeni KPI Indicator veya New Card ekle
//   Value: Avg MAPE Pct Safe
//   Goal: MAPE Goal Pct (= 10)
//   Format: "0.0"
//   Direction: Low is Good
//   Subtitle: MAPE Status Label (Category label alanına)
//   Conditional format: <10 → #00E5A0 | 10-20 → #FFC107 | >20 → #FF4560
//
// ADIM 4 — BÖLÜM 4: V12 yeni görsel (Actions by Priority)
//   Canvas'a Clustered Bar (Horizontal) ekle
//   Y-axis: gold_recommendations[priority_label]
//   X-axis: Total Recommendation Count
//   CF Bar: CRITICAL=#FF4560, HIGH=#FF6B35, LOW=#00C8FF, INFORMATIONAL=#7DB4DC
//   Sort: Priority severity sırasına göre (CRITICAL en üstte)
//   ⚠️ Sort için: priority_label sütununa göre sort çalışmaz — Sort Column gerekir.
//      Alternatif: priority_rank hesaplanmış sütun (aşağıda)
//
//   ── Priority Rank hesaplanmış sütun (gold_recommendations tablosuna ekle):
//   priority_rank =
//   SWITCH(
//       UPPER(gold_recommendations[priority_label]),
//       "CRITICAL",      1,
//       "HIGH",          2,
//       "MEDIUM",        3,
//       "LOW",           4,
//       "INFORMATIONAL", 5,
//       "INFO",          5,
//                        6
//   )
//   → Sort by Column: priority_label → priority_rank
//
// ADIM 5 — BÖLÜM 5: C1 Goal fix
//   C1 kartını seç (7-Day Forecast)
//   Goal/Target → Actual Last 7Day kWh ÇIKAR
//   → Actual 7Day Aligned kWh ekle
//   Beklenen: ~30.000-45.000 kWh → %+84 değil, makul sapma
//
// ADIM 6 — BÖLÜM 5: C2 Value fix (eğer 30Day aynı değeri gösteriyorsa)
//   C2 → Value field → Forecast 30Day kWh yerine Forecast 30Day Safe kWh
//   Eğer BLANK dönerse: forecast notebook'ta horizon = 30 gün yap, yeniden çalıştır.
//
// ADIM 7 — Forecast grafiğine Forecast Start reference line ekle
//   Forecast line chart → Analytics pane → Reference Line → Value → Forecast Start Date
//   Veya: Constant reference line → tarihi manuel gir
//   Label: "Forecast →" | Renk: #FFC107 dashed
//
// ==========================================================================
// DOĞRULAMA — Tüm değişiklikler uygulandıktan sonra kontrol et
//
// ✅ C1 → Goal ~35-45k kWh arası → sapma %±20 içinde
// ✅ C2 → Goal ~100-150k kWh (PY 30-day actual) → anlamlı karşılaştırma
//         VEYA: Forecast 30Day Safe kWh BLANK → "—" gösteriyor (30 gün veri yok)
// ✅ C3 → Goal ~20-22k EUR → "+∞%" değil, anlamlı sapma
// ✅ C5 → MAPE değeri gösteriyor, Goal 10, direction Low is Good
// ✅ V12 → Bar chart 4 öncelik seviyesini gösteriyor
// ✅ Forecast grafiği → "Forecast Start" dikey çizgi görünüyor
// ==========================================================================

// SON
