// ==========================================================================
// Energy Copilot Platform — DAX v26: Page 4 V4 Date[Date] Axis + Bug Fixes
// File: semantic-model/35_dax_v26_page4_v4_dateaxis_fix.dax
// Last updated: 2026-04-26
//
// AMAÇ: Sayfa 4 kalan kritik sorunları çöz.
//       Option B: V4 "Forecast + Confidence Interval" → Date[Date] ekseni ile
//       hem geçmiş actual hem gelecek forecast aynı sürekli zaman serisinde.
//
// ÇÖZÜLEN SORUNLAR:
//
//   C1 "7-Day Forecast kWh" Goal → (Blank)
//     NEDEN: FORECAST_HORIZON 7→30 değişince _forecastStart = MAXX - 6
//            yanlış tarihe baktı (forecast sonunun 7 günü, başı değil).
//            _actualEnd = Feb 17 → gerçek veri yok → BLANK.
//     FİX: MINX kullan (ilk tahmin tarihi) → _actualEnd = Jan 25 → veri var.
//
//   C3 "Savings Potential (€)" → Hamburg gibi compliance-only binalarda BLANK
//     NEDEN: CRITICAL+HIGH filtresi NULL döndürünce BLANK gösteriliyor.
//     FİX: COALESCE(..., 0) — sıfır göster, boşluk değil.
//
//   V4 "Forecast + Confidence Interval" — Anlamsız grafik
//     NEDEN: X-ekseni = forecast_date → gold_kpi_daily bu eksene bağlı değil
//            → Actual Daily kWh sabit aggregate olarak çiziliyor (17.443K düz çizgi).
//     FİX: X-ekseni = Date[Date] (tablo 2023-2027 arası, ilişkiler aktif).
//          gold_kpi_daily[date] → Date[Date] (aktif)
//          gold_consumption_forecast[forecast_date] → Date[Date] (aktif)
//          Her ölçü kendi tarih aralığında BLANK döndürür → net past/future ayrımı.
//          Edit Interactions: Date Range slicer → V4 = None (slicer kesmez).
//
//   V11 "Payback vs Savings" — Negatif EUR / sıfır scatter noktaları
//     NEDEN: Commission Mandatory Energy gibi compliance eylemlerinde
//            annual_saving_eur = NULL, payback_years = NULL → scatter'a dahil.
//     FİX: Rec Has Financial Data = 1 helper ölçüsü → Visual-level filter.
//
//   Amsterdam MAPE 56.4% — Uyarısız gösterim
//     NEDEN: Üniversite binası, akademik takvim nedeniyle çok değişken tüketim.
//            Prophet bu bina için yetersiz kalıyor.
//     FİX: MAPE Warning Count + High MAPE Label → V5 tooltipte veya kart olarak.
//
// VISUAL İSİMLERİ (menüdeki gibi):
//   V4: "Forecast + Confidence Interval"    → Date[Date] ekseni (Option B)
//   V11: "Payback vs Savings"               → Financial data filtresi
//   V5: "MAPE Accuracy by Building"         → Warning annotation
//   C1: "7-Day Forecast kWh"               → Goal fix
//   C3: "Savings Potential (€)"            → 0 fallback
//
// KURULUM SIRASI:
//   1. Bu dosyadaki ölçüleri New Measure ile ekle
//   2. V4 "Forecast + Confidence Interval" — X-eksenini Date[Date] yap (bölüm 3 UI)
//   3. Edit Interactions: Date Range slicer → V4 = None
//   4. V11 "Payback vs Savings" → visual-level filter: Rec Has Financial Data = 1
//   5. Power BI refresh
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — C1 FİX: Actual 7Day Aligned kWh (MINX ile yeniden yazıldı)
//
// ESKI HATA:
//   _forecastLast = MAXX → Feb 24 (30 günlük horizonla)
//   _forecastStart = _forecastLast - 6 → Feb 18 ← forecast bitişine yakın!
//   _actualEnd = Feb 17 → gerçek veri yok → BLANK
//
// YENİ YAKLAŞIM:
//   _forecastFirst = MINX → Jan 26 (ilk tahmin günü)
//   _actualEnd = Jan 25 (tahmin başlamadan hemen önceki gün)
//   _actualStart = Jan 19 → gerçek veri var → değer döner
//
// C1 "7-Day Forecast kWh" kartı → Goal/Target field → bu ölçüyü bağla
// Format: "#,##0"
// ==========================================================================

Actual 7Day Aligned kWh =
VAR _forecastFirst =
    MINX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _actualEnd   = _forecastFirst - 1      // Tahmin başlamadan önceki son gün
VAR _actualStart = _actualEnd - 6          // 7 günlük geriye dönük pencere
RETURN
    CALCULATE (
        SUM ( gold_kpi_daily[total_consumption_kwh] ),
        gold_kpi_daily[date] >= _actualStart,
        gold_kpi_daily[date] <= _actualEnd,
        REMOVEFILTERS ( 'Date' )
    )
// DOĞRULAMA: C1 Goal ~35.000-45.000 kWh arası (tüm binalar)
//             Bina seçilince bina başı ~6.000-8.000 kWh
//             Sapma: Forecast 7Day / Actual 7Day Aligned → %±30 içinde makul


// ==========================================================================
// BÖLÜM 2 — C3 FİX: Total CRITICAL HIGH Savings EUR (0 fallback)
//
// MEVCUT SORUN:
//   CRITICAL+HIGH filtresi hiç eşleşmeyince BLANK döner.
//   Hamburg Logistics: sadece "Commission Mandatory Energy" (LOW) → (Blank).
//
// YENİ MANTIK:
//   COALESCE → CRITICAL+HIGH yoksa 0 göster (BLANK değil).
//   Bu dürüst bir sinyaldir: "Bu bina için acil finansal fırsat yok."
//   Başlık veya tooltip'te açıklama eklenebilir.
//
// C3 "Savings Potential (€)" kartı → Value field → bu ölçüyü bağla
// Format: "€ #,##0"
// ==========================================================================

Total CRITICAL HIGH Savings EUR =
VAR _critHigh =
    CALCULATE (
        SUM ( gold_recommendations[annual_saving_eur] ),
        gold_recommendations[priority_label] IN { "CRITICAL", "HIGH" }
    )
RETURN COALESCE ( _critHigh, 0 )
// NOT: 0 dönünce Goal 150.000 € → "0 / 150.000 (-100%)" görünür.
//      Bu doğrudur: bu bina için CRITICAL+HIGH hiç tasarruf fırsatı yok.
//      C3 Subtitle (tooltip): "CRITICAL & HIGH priority actions only"


// ==========================================================================
// BÖLÜM 3 — V4 OPTİON B: Date[Date] EKSENİ — SÜREKLI ZAMAN SERİSİ
//
// MİMARİ:
//   Date tablosu: 2023-01-01 → 2027-12-31 (setup guide onaylı)
//   İlişkiler (aktif):
//     gold_kpi_daily[date]                 → Date[Date]
//     gold_consumption_forecast[forecast_date] → Date[Date]
//
//   Her ölçü kendi tarih aralığında değer döndürür, dışında BLANK:
//     Actual:  Date ≤ son gerçek veri tarihi  → geçmiş tüketim
//     Forecast: Date ≥ ilk tahmin tarihi      → gelecek tahmin + CI bandı
//   Bu sayede grafik düz bir çizgiyle geçmişten geleceğe akar.
//
// KRİTİK UI ADIMI:
//   V4 "Forecast + Confidence Interval" seç →
//   Üst menü → Format → Edit Interactions →
//   "Date Range" slicer → V4 ikonu → "None" (zincir kırık) seç.
//   Böylece slicer V4'ü kesmez, Building Name slicer hâlâ çalışır.
//
// V4 grafik serisi yapısı (Line and Stacked Area Chart):
//   X-axis:  Date[Date]
//   Line:    Actual Consumption Per Day kWh   (#00C8FF, 2px solid)
//   Line:    Predicted kWh Per Day            (#A064FF, 2px dashed)
//   Area:    CI Lower Per Day kWh             (transparan, sandviç alt)
//   Area:    CI Upper Per Day kWh             (#7B61FF, 25% opacity, sandviç üst)
//   Ref Line: Actual Data End Date            (#FFC107, dashed, "Forecast →")
// ==========================================================================

// V4 Seri 1 — Geçmiş: Gerçekleşen günlük tüketim
// Sadece gold_kpi_daily verisinin olduğu tarihlerde değer döndürür.
// Format: "#,##0"
Actual Consumption Per Day kWh =
VAR _maxActual = MAXX ( ALL ( gold_kpi_daily ), gold_kpi_daily[date] )
VAR _currentDate = MAX ( 'Date'[Date] )
RETURN
    IF (
        NOT ISBLANK ( _currentDate ) && _currentDate <= _maxActual,
        CALCULATE ( SUM ( gold_kpi_daily[total_consumption_kwh] ) ),
        BLANK ()
    )
// NOT: CALCULATE + aktif ilişki → Date[Date] bağlamında kpi_daily otomatik filtreler.
// Slicer hariç tutulunca (Edit Interactions = None) tüm geçmiş görünür.


// V4 Seri 2 — Gelecek: Tahmin edilen günlük tüketim
// Sadece gold_consumption_forecast verisinin olduğu tarihlerde değer döndürür.
// Format: "#,##0"
Predicted kWh Per Day =
VAR _firstForecast =
    MINX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _currentDate = MAX ( 'Date'[Date] )
RETURN
    IF (
        NOT ISBLANK ( _currentDate ) && _currentDate >= _firstForecast,
        CALCULATE ( SUM ( gold_consumption_forecast[predicted_kwh] ) ),
        BLANK ()
    )


// V4 Seri 3 — CI Alt Sınır (sandviç bandının alt yarısı)
// Format: "#,##0" | Fill: transparan (0% opacity)
CI Lower Per Day kWh =
VAR _firstForecast =
    MINX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _currentDate = MAX ( 'Date'[Date] )
RETURN
    IF (
        NOT ISBLANK ( _currentDate ) && _currentDate >= _firstForecast,
        CALCULATE ( SUM ( gold_consumption_forecast[lower_bound_kwh] ) ),
        BLANK ()
    )


// V4 Seri 4 — CI Üst Sınır (sandviç bandının üst yarısı)
// Format: "#,##0" | Fill: #7B61FF, 25% opacity
CI Upper Per Day kWh =
VAR _firstForecast =
    MINX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _currentDate = MAX ( 'Date'[Date] )
RETURN
    IF (
        NOT ISBLANK ( _currentDate ) && _currentDate >= _firstForecast,
        CALCULATE ( SUM ( gold_consumption_forecast[upper_bound_kwh] ) ),
        BLANK ()
    )


// V4 Reference Line değeri — Actual veri bitiş tarihi (sayısal olarak)
// Analytics pane → Constant Line → bu ölçüyü kullan
// Grafikte "Forecast →" etiketiyle dikey referans çizgisi çizer.
Actual Data End Date Numeric =
VAR _end = MAXX ( ALL ( gold_kpi_daily ), gold_kpi_daily[date] )
RETURN IF ( NOT ISBLANK ( _end ), INT ( _end ), BLANK () )
// NOT: Power BI Analytics pane → Constant Line → measure field'a bu ölçüyü bağla
//      Renk: #FFC107 dashed | Label: "Forecast →"


// ==========================================================================
// BÖLÜM 4 — V11 "Payback vs Savings" FİLTRE YARDIMCISI
//
// MEVCUT SORUN:
//   Commission Mandatory Energy (compliance) eylemleri:
//     annual_saving_eur = NULL, payback_years = NULL
//   Scatter'da negatif veya anlamsız koordinatlara düşüyor.
//   Örnek: Hamburg Logistics → sadece compliance → scatter -1 EUR, -1 yıl.
//
// YENİ YAKLAŞIM:
//   Visual-level filter: "Rec Has Financial Data = 1"
//   Bu filtre compliance eylemlerini V11'den dışarıda bırakır.
//   V10 Recommendations Table'da hâlâ görünürler (compliance takip için önemli).
//
// V11 "Payback vs Savings" → Filters pane → Visual-level → bu ölçü = 1
// ==========================================================================

Rec Has Financial Data =
VAR _saving  = SUM ( gold_recommendations[annual_saving_eur] )
VAR _payback = AVERAGE ( gold_recommendations[payback_years] )
RETURN
    IF (
        NOT ISBLANK ( _saving ) && _saving > 0
        && NOT ISBLANK ( _payback ) && _payback > 0,
        1, 0
    )
// V11 "Payback vs Savings" → Filters pane → Add filter → Rec Has Financial Data
//   Filter type: "Basic filtering" → check "1" → Apply filter
// Beklenen: Compliance eylemleri scatter'dan kalkar, finansal eylemler kalır.


// ==========================================================================
// BÖLÜM 5 — MAPE UYARI: Yüksek MAPE Bina İşaretleme
//
// MEVCUT DURUM:
//   Amsterdam Universiteit Zeta: MAPE = 56.4% — çok yüksek (modeli güvenilmez)
//   Neden: Üniversite binası, akademik takvim dönemi geçişleri (tatil/dönem)
//          tüketimi çok değişken → Prophet bu pattern'i öğrenemiyor.
//
// ÇÖZÜM:
//   1. V5 "MAPE Accuracy by Building" X-axis max → 60 (Amsterdam görünsün)
//   2. Tooltip: High MAPE Building Label → "⚠️ Retrain recommended"
//   3. MAPE Warning Count kart → kaç bina >30% MAPE var?
//
// Bu ölçüler modelin "sağlık durumu" hakkında yöneticiye şeffaf sinyal verir.
// ==========================================================================

// Kaç bina MAPE > 30% (zayıf model kalitesi)?
// Format: "#,##0" | Kart renk: > 0 → #FF4560
High MAPE Building Count =
CALCULATE (
    DISTINCTCOUNT ( gold_consumption_forecast[building_id] ),
    REMOVEFILTERS ( 'Date' ),
    AVERAGEX (
        VALUES ( gold_consumption_forecast[building_id] ),
        CALCULATE (
            AVERAGE ( gold_consumption_forecast[model_mape_pct] ),
            REMOVEFILTERS ( 'Date' )
        )
    ) > 30
)
// NOT: Bu ölçü pahalı olabilir (iç içe AVERAGEX). Alternatif olarak
//      gold_consumption_forecast üzerinde calculated column ekle:
//      is_poor_model = IF(model_mape_pct > 30, 1, 0)


// MAPE uyarı etiketi — V5 "MAPE Accuracy by Building" tooltipinde
// Format: metin
MAPE Quality Label =
VAR _mape = CALCULATE (
    AVERAGE ( gold_consumption_forecast[model_mape_pct] ),
    REMOVEFILTERS ( 'Date' )
)
RETURN
    SWITCH (
        TRUE (),
        ISBLANK ( _mape ),  "— No data",
        _mape < 10,         "🟢 Excellent forecast",
        _mape < 20,         "🟡 Good forecast",
        _mape < 30,         "🟠 Acceptable — monitor",
        _mape < 50,         "🔴 Poor — retrain recommended",
                            "🔴 Critical — model unreliable"
    )
// V5 "MAPE Accuracy by Building" → Tooltip → bu ölçüyü ekle


// Model yeniden eğitim önerisi durumu (text)
// Özet kart veya V5 alt başlığı için
Model Retrain Status =
VAR _poorCount = [High MAPE Building Count]
RETURN
    SWITCH (
        TRUE (),
        ISBLANK ( _poorCount ) || _poorCount = 0,
            "✅ All models performing well",
        _poorCount = 1,
            "⚠️ 1 building needs model review",
        "🔴 " & _poorCount & " buildings need model review"
    )


// ==========================================================================
// BÖLÜM 6 — V4 GRAFIK DOĞRULAMA ÖLÇÜSÜ
//
// V4 "Forecast + Confidence Interval" Option B kurulumunu doğrulamak için.
// Eğer grafik doğru kurulduysa, geçmiş (actual) ve gelecek (forecast) tarihleri
// arasındaki toplam veri noktası sayısını gösterir.
// ==========================================================================

// Toplam unique tarih sayısı — geçmiş actual + gelecek forecast
V4 Total Data Points =
VAR _actualDays =
    CALCULATE (
        DISTINCTCOUNT ( gold_kpi_daily[date] ),
        REMOVEFILTERS ( 'Date' )
    )
VAR _forecastDays =
    CALCULATE (
        DISTINCTCOUNT ( gold_consumption_forecast[forecast_date] ),
        REMOVEFILTERS ( 'Date' )
    )
RETURN _actualDays + _forecastDays
// BEKLENEN: ~760 gün actual (2024-2026) + 30 gün forecast = ~790 toplam
// V4 grafiğinde bu kadar veri noktası olmalı.
// Bu sayı BLANK dönerse Date[Date] ilişki sorunu var — modeli kontrol et.


// ==========================================================================
// UI ADIMLARI ÖZETİ — Power BI Desktop (v26 sonrası)
//
// 1. TÜMÜ: Bu dosyadaki ölçüleri New Measure ile ekle (overwrite için aynı ad)
//
// 2. C1 "7-Day Forecast kWh" Goal → Actual 7Day Aligned kWh bağla (overwrite)
//    Beklenen: ~35.000-45.000 kWh (blank değil)
//
// 3. C3 "Savings Potential (€)" Value → Total CRITICAL HIGH Savings EUR (overwrite)
//    Hamburg gibi compliance binalar için 0 gösterecek (blank değil)
//
// 4. V4 "Forecast + Confidence Interval" — TAM YENİDEN YAPILANDIR:
//    a) X-axis: gold_consumption_forecast[forecast_date] → DATE[Date] ile değiştir
//    b) Values/Y-axis alanını temizle (tüm eski serileri kaldır)
//    c) Ekle (sırayla):
//       - Stacked Area: CI Lower Per Day kWh     (fill: transparan, 0%)
//       - Stacked Area: CI Upper Per Day kWh     (fill: #7B61FF, 25%)
//       - Line:         Actual Consumption Per Day kWh (#00C8FF, solid 2px)
//       - Line:         Predicted kWh Per Day    (#A064FF, dashed 2px)
//    d) Format pane → Y-Axis → Secondary Y-Axis → OFF
//    e) Legend → ON (4 seri etiketlenmeli)
//    f) Analytics pane → Constant Line → Value: Actual Data End Date Numeric
//       Label: "Forecast →" | Renk: #FFC107 | Stil: Dashed
//    g) Visual-level filter: Date[Date] >= 01.10.2025
//       (Son ~4 ay actual + 30 gün forecast → odaklı zaman penceresi)
//
// 5. Edit Interactions — KRİTİK:
//    Üst menü → Format → Edit Interactions (seçili görsel yokken tıkla)
//    Sonra "Date Range" slicer'ı seç → V4 grafiğinin üstünde ikon çıkar
//    → "None" (zincir kırık simgesi) seç → Uygula
//    SONUÇ: Date slicer V4'ü kesmez, Building Name hâlâ çalışır
//
// 6. V11 "Payback vs Savings" → Filters pane (sağ panel) →
//    "Add data to filter" → Rec Has Financial Data
//    Filter type: Basic → "1" işaretle → Apply
//    SONUÇ: Hamburg Commission Mandatory scatter'dan kalkar
//
// 7. V5 "MAPE Accuracy by Building" →
//    Format → X-axis → Max → 60 (Amsterdam 56.4% görünsün)
//    Tooltip: MAPE Quality Label + Forecast Coverage Days ekle
//    Reference line: X=10, X=30 (iki eşik — iyi/zayıf sınırları)
//
// 8. Power BI refresh → Doğrulama checklistini kontrol et (aşağıda)
//
// DOĞRULAMA:
//   ✅ C1 "7-Day Forecast kWh" Goal → sayısal değer (blank değil)
//   ✅ C3 "Savings Potential (€)" → compliance binalar için 0, diğerleri için değer
//   ✅ V4: Sol: actual (mavi düz), Sağ: forecast+CI (mor dashed + bant), tek Y-ekseni
//   ✅ V4: Edit Interactions → date slicer V4'ü kesmez, building slicer çalışır
//   ✅ V11: Hamburg seçilince compliance eylemleri scatter'da görünmez
//   ✅ V5: Tüm 6 bina, X-max=60, Amsterdam 56.4% çubuğu tam görünür
// ==========================================================================

// SON
