// ==========================================================================
// Energy Copilot Platform — DAX v27: V4 Monthly Actual + Forecast Chart
// File: semantic-model/36_dax_v27_page4_v4_monthly_chart.dax
// Last updated: 2026-04-26
//
// AMAÇ: V4 "Forecast + Confidence Interval" grafiğini tamamen değiştir.
//       Günlük CI band yaklaşımı → Aylık Actual + Forecast + YoY çizgisi.
//
// YENİ GRAFİK: "Monthly Consumption: Actual + Forecast"
//   Tip: Line and Clustered Column Chart
//   X-axis: Date[YearMonth] ("YYYY-MM" — alfabetik olarak doğru sıralar)
//   Column 1 (mavi): Monthly Actual kWh — geçmiş aylar
//   Column 2 (mor):  Monthly Forecast kWh — gelecek ay(lar)
//   Line (sarı):     Monthly PY kWh — geçen yıl aynı dönem
//   Visual filter:   Date[Year] >= 2025
//
// NEDEN DAHA İYİ:
//   Eski:  Günlük CI band → teknik, kalabalık, Date[Date] eksen sorunu,
//          "17.443K" flat çizgi, çift Y-ekseni, anlaşılmaz.
//   Yeni:  Aylık granülite → trend net görünür, forecast son bar olarak dikkat çeker,
//          geçen yıl çizgisi YoY karşılaştırma sağlar, herhangi bir seviyeden okunabilir.
//
// ENERJI YÖNETİCİSİNİN GÖRDÜĞÜ:
//   "Bu yıl tüketimim nasıl seyrediyordu? Önümüzdeki ay ne bekliyorum?
//    Geçen yıla göre iyi miyim?"
//
// VERİ MİMARİSİ:
//   gold_kpi_daily[date] → Date[Date] (aktif ilişki — aylık context'te otomatik filtreler)
//   gold_consumption_forecast[forecast_date] → Date[Date] (aktif ilişki)
//   Date[YearMonth] X-ekseni → her ay ayrı bir sütun
//
// GEÇIŞ AYI (Ocak 2026):
//   gold_kpi_daily: 1-25 Ocak gerçek veri
//   gold_consumption_forecast: 26-31 Ocak tahmin
//   → Monthly Actual kWh Ocak'ı gösterir (çoğunluk gerçek)
//   → Monthly Forecast kWh Şubat'tan başlar (ilk "saf tahmin" ayı)
//   → Bu doğal ve dürüst bir ayrım.
//
// KURULUM:
//   Power BI Desktop → Sayfa 4 → V4 grafiğini seç
//   → Visual type: Line and Clustered Column Chart
//   → X-axis: Date[YearMonth]
//   → Column values: Monthly Actual kWh + Monthly Forecast kWh
//   → Line values: Monthly PY kWh
//   → Visual filter: Date[Year] >= 2025
//   → Detaylar için bölüm sonundaki UI ADIMLARI'na bak
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — ANA SÜTUNLAR: Geçmiş Actual + Gelecek Forecast
// ==========================================================================

// Column 1 — Geçmiş aylık tüketim (mavi: #00C8FF)
// Date[YearMonth] bağlamında gold_kpi_daily otomatik filtrelenir.
// Veri olmayan gelecek aylar doğal olarak BLANK döner.
// Format: "#,##0"
Monthly Actual kWh =
VAR _v = SUM ( gold_kpi_daily[total_consumption_kwh] )
RETURN IF ( ISBLANK ( _v ), BLANK (), _v )


// Column 2 — Gelecek aylık tahmin (mor: #A064FF)
// "Saf tahmin ayı" tanımı: son actual tarihin bir sonraki ayı.
// Ocak 2026 (geçiş ayı) ACTUAL olarak gösterilir — daha dürüst.
// Şubat 2026 ve sonrası FORECAST olarak gösterilir.
// Format: "#,##0"
Monthly Forecast kWh =
VAR _maxActualDate =
    MAXX ( ALL ( gold_kpi_daily ), gold_kpi_daily[date] )
VAR _firstPureForecastMonth =
    DATE ( YEAR ( EDATE ( _maxActualDate, 1 ) ), MONTH ( EDATE ( _maxActualDate, 1 ) ), 1 )
VAR _currentMonthStart =
    DATE ( YEAR ( MAX ( 'Date'[Date] ) ), MONTH ( MAX ( 'Date'[Date] ) ), 1 )
RETURN
    IF (
        _currentMonthStart >= _firstPureForecastMonth,
        SUM ( gold_consumption_forecast[predicted_kwh] ),
        BLANK ()
    )
// BEKLENEN: Şubat 2026 → tek sütun (mor), Ocak 2026 ve öncesi BLANK


// ==========================================================================
// BÖLÜM 2 — YoY REFERANS ÇİZGİSİ: Geçen Yıl Aynı Dönem
// ==========================================================================

// Line — Geçen yıl aynı ay actual tüketim (sarı: #FFC107)
// Ocak 2025 → Ocak 2024 referansı
// Ocak 2026 → Ocak 2025 referansı
// Format: "#,##0"
Monthly PY kWh =
CALCULATE (
    SUM ( gold_kpi_daily[total_consumption_kwh] ),
    DATEADD ( 'Date'[Date], -1, YEAR )
)
// NOT: Veri olmayan aylar (2024 öncesi) BLANK döner — grafik çizgiyi keser, normal.
// Grafik → Line: kesiksiz çizgi istersen "Show empty values as: Connect" ayarını aç.


// ==========================================================================
// BÖLÜM 3 — EUR MALİYET PARALLELI
// Kart tooltip veya ek görsel için aylık maliyet versiyonları.
// ==========================================================================

// Aylık gerçekleşen maliyet (EUR)
// Format: "€ #,##0"
Monthly Actual Cost EUR =
VAR _v = SUM ( gold_kpi_daily[estimated_cost_eur] )
RETURN IF ( ISBLANK ( _v ), BLANK (), _v )


// Aylık tahmin maliyeti (EUR) — forecast ayları için
// Format: "€ #,##0"
Monthly Forecast Cost EUR =
VAR _maxActualDate =
    MAXX ( ALL ( gold_kpi_daily ), gold_kpi_daily[date] )
VAR _firstPureForecastMonth =
    DATE ( YEAR ( EDATE ( _maxActualDate, 1 ) ), MONTH ( EDATE ( _maxActualDate, 1 ) ), 1 )
VAR _currentMonthStart =
    DATE ( YEAR ( MAX ( 'Date'[Date] ) ), MONTH ( MAX ( 'Date'[Date] ) ), 1 )
VAR _rate = [Avg Electricity Rate EUR kWh]
RETURN
    IF (
        _currentMonthStart >= _firstPureForecastMonth,
        ROUND ( SUM ( gold_consumption_forecast[predicted_kwh] ) * _rate, 0 ),
        BLANK ()
    )


// Geçen yıl aynı ay maliyet (EUR) — YoY cost benchmark
// Format: "€ #,##0"
Monthly PY Cost EUR =
CALCULATE (
    SUM ( gold_kpi_daily[estimated_cost_eur] ),
    DATEADD ( 'Date'[Date], -1, YEAR )
)


// ==========================================================================
// BÖLÜM 4 — AY-ÜSTÜ-AY DEĞİŞİM ETIKETI
// Grafik tooltip veya referans çizgi etiketi için.
// ==========================================================================

// Geçen aya göre değişim (%) — actual aylar için
// Format: "+0.0%;-0.0%;—"
Monthly MoM Change Pct =
VAR _current = SUM ( gold_kpi_daily[total_consumption_kwh] )
VAR _prev    = CALCULATE (
    SUM ( gold_kpi_daily[total_consumption_kwh] ),
    DATEADD ( 'Date'[Date], -1, MONTH )
)
RETURN
    IF (
        NOT ISBLANK ( _current ) && NOT ISBLANK ( _prev ) && _prev > 0,
        ROUND ( DIVIDE ( _current - _prev, _prev ) * 100, 1 ),
        BLANK ()
    )


// Geçen yıla göre değişim (%) — karşılaştırma etiketi
// Format: "+0.0%;-0.0%;—"
Monthly YoY Change Pct =
VAR _current = SUM ( gold_kpi_daily[total_consumption_kwh] )
VAR _py      = [Monthly PY kWh]
RETURN
    IF (
        NOT ISBLANK ( _current ) && NOT ISBLANK ( _py ) && _py > 0,
        ROUND ( DIVIDE ( _current - _py, _py ) * 100, 1 ),
        BLANK ()
    )


// Tahmin vs geçen yıl aynı dönem (%) — forecast ayı için beklenti
// Format: "+0.0%;-0.0%;—"
Monthly Forecast vs PY Pct =
VAR _forecast = [Monthly Forecast kWh]
VAR _py       = [Monthly PY kWh]
RETURN
    IF (
        NOT ISBLANK ( _forecast ) && NOT ISBLANK ( _py ) && _py > 0,
        ROUND ( DIVIDE ( _forecast - _py, _py ) * 100, 1 ),
        BLANK ()
    )


// ==========================================================================
// BÖLÜM 5 — DOĞRULAMA ÖLÇÜSÜ
// Grafik kurulumunu doğrulamak için.
// ==========================================================================

// Kaç ay actual, kaç ay forecast?
Monthly Data Summary =
VAR _actualMonths = CALCULATE (
    DISTINCTCOUNTNOBLANK ( 'Date'[YearMonth] ),
    NOT ISBLANK ( SUM ( gold_kpi_daily[total_consumption_kwh] ) )
)
VAR _forecastMonths = CALCULATE (
    DISTINCTCOUNTNOBLANK ( 'Date'[YearMonth] ),
    NOT ISBLANK ( [Monthly Forecast kWh] )
)
RETURN
    IF (
        ISBLANK ( _actualMonths ),
        "— No data in context",
        _actualMonths & " actual + " & COALESCE ( _forecastMonths, 0 ) & " forecast months"
    )
// BEKLENEN (visual filter 2025+): "13 actual + 1 forecast months"
//   (Ocak 2025 – Ocak 2026 actual, Şubat 2026 forecast)


// ==========================================================================
// UI ADIMLARI — Power BI Desktop
//
// ADIM 1 — Visual type değiştir:
//   V4 "Forecast + Confidence Interval" grafiğini seç
//   Visualizations pane → "Line and Clustered Column Chart" (çizgi+sütun ikonunu bul)
//   NOT: Bu seçimde mevcut tüm field bağlantıları sıfırlanır — sıfırdan kur.
//
// ADIM 2 — X-axis:
//   X-axis (Category): Date[YearMonth] sürükle
//   → "YYYY-MM" formatı zaten doğru sıralıyor (alfabetik = kronolojik)
//
// ADIM 3 — Column values (sütun/bar):
//   Column Y-axis → ekle: Monthly Actual kWh   (mavi sütun)
//   Column Y-axis → ekle: Monthly Forecast kWh  (mor sütun)
//
// ADIM 4 — Line values (çizgi):
//   Line Y-axis → ekle: Monthly PY kWh          (sarı çizgi)
//
// ADIM 5 — Renklendirme:
//   Format → Data colors:
//     Monthly Actual kWh:   #00C8FF (cyan mavi)
//     Monthly Forecast kWh: #A064FF (mor)
//     Monthly PY kWh (line): #FFC107 (altın sarı), kalınlık 2px, dashed
//
// ADIM 6 — Visual-level filter (odak penceresi):
//   Filters pane → "Add data to filter" → Date[Year]
//   Filter type: Basic → "2025" ve "2026" işaretle → Apply
//   SONUÇ: 13 actual ay (Oca 2025 - Oca 2026) + 1 forecast ay (Şub 2026)
//
// ADIM 7 — Eksen ayarları:
//   Format → Column Y-axis → Title: "Consumption (kWh)" | Format: #,##0
//   Format → Line Y-axis → Secondary Y-axis → OFF (tek Y ekseni)
//   Format → X-axis → Title: OFF (tarih sütunları kendi kendini açıklıyor)
//
// ADIM 8 — Data labels:
//   Format → Data labels → ON sadece forecast sütununda
//   Monthly Forecast kWh sütunu seç → label: "#,##0" → konum: içte üst
//   (Diğer sütunlarda label kapatık kalsın — grafik kalabalık olmasın)
//
// ADIM 9 — Tooltip:
//   Tooltip alanına ekle:
//     Monthly Actual Cost EUR   (EUR maliyet bağlamı)
//     Monthly YoY Change Pct    (actual aylar için YoY delta)
//     Monthly Forecast vs PY Pct (forecast ayı için beklenti)
//
// ADIM 10 — Title:
//   Visual title: "Monthly Consumption — Actual & Forecast"
//   Subtitle: "Blue = Actual | Purple = Forecast | Yellow = Prior Year"
//   Font: beyaz, 12px
//
// ADIM 11 — Edit Interactions (önemli):
//   Date Range slicer → V4 için "None" seç → slicer grafiği kesmez
//   (Slicer başka görselleri filtrelerken V4 tüm yıl trendini göstermeye devam eder)
//
// DOĞRULAMA:
//   ✅ 13 sütun mavi (Oca 2025 – Oca 2026) + 1 sütun mor (Şub 2026)
//   ✅ Sarı çizgi tüm grafik boyunca uzanıyor (YoY referans)
//   ✅ Tek Y-ekseni — sekonder yok
//   ✅ Tooltip: kWh + EUR + YoY%
//   ✅ Date slicer V4'ü etkilemiyor (Edit Interactions)
//   ✅ Building slicer çalışıyor (bina seçince o binanın aylık trendi)
// ==========================================================================

// SON
