// ==========================================================================
// Energy Copilot Platform — DAX v35: Page 7 ALLEXCEPT BUG FIX
// File: semantic-model/44_dax_v35_page7_hvac_allexcept_fix.dax
// Last updated: 2026-05-04
//
// ===  NEDEN v35? ============================================================
//
// v34'te V2 tablosu tüm binalar için "Heat Pump" gösteriyordu.
// V5 scatter'da tüm bubble'lar aynı renkteydi ("Medium" priority).
// KÖK SEBEP: ALLEXCEPT(silver_building_master, building_id) bug'ı.
//
// ─── ALLEXCEPT BUG AÇIKLAMASI ──────────────────────────────────────────────
//
// V2 Tablo visual'ında satır boyutu → silver_building_master[building_name]
// Bu filter context'te silver_building_master'a building_NAME filtresi gelir.
// (building_ID filtresi gelmez — doğrudan building_name filtreleniyor)
//
// v34'teki ALLEXCEPT(silver_building_master, silver_building_master[building_id]):
//   ► silver_building_master üzerindeki TÜM filtreleri kaldır (building_name dahil)
//   ► SADECE building_id filtresini koru
//   ► Ama satır context'i building_NAME üzerinden geldi, building_ID yok!
//   ► Sonuç: silver_building_master'da filter yok → ilişki üzerinden
//     gold_hvac_analytics'e de filter yok → MAX(system_type) = "heat_pump"
//     (alfabetik MAX: "heat_pump" > "gas_boiler" > "hybrid")
//
// KANIT: V2'de tüm satırlar "Heat Pump" + "Medium — Plan in 2 Years"
//   • "Medium" = MAX("High", "Low", "Medium") alfabetik → "Medium" ✅ kanıt
//   • "heat_pump" = MAX("gas_boiler", "heat_pump", "hybrid") → "heat_pump" ✅ kanıt
//
// ─── v35 ÇÖZÜMÜ ─────────────────────────────────────────────────────────────
//
// ALLEXCEPT KALDIRILDI. Bunun yerine doğrudan MAX() / AVERAGE() kullanılıyor.
//
// Power BI'da bir Table visual'da building_name satır boyutu kullandığında,
// silver_building_master[building_name] → silver_building_master[building_id]
// ilişkisi Power BI tarafından OTOMATIK filter'a çevrilir ve bu filtre
// gold_hvac_analytics'e yansır. ALLEXCEPT'e gerek yok.
//
// Yani:
//   MAX(gold_hvac_analytics[system_type]) — herhangi bir ALLEXCEPT olmadan —
//   satır context'inde DOĞRU bina verisini döner.
//
// ===  BU DOSYADA NELER VAR ====================================================
//
//   6 ölçü (v34 olanların yerini alır — aynı ada sahip DEĞİL, v35 suffix):
//     1. System Type Display v35   → V2 sütun 2
//     2. Renovation Priority Icon v35 → V2 sütun 3
//     3. COP Display v35           → V2 sütun 4
//     4. Action Recommendation v35 → V2 sütun 7
//     5. Renovation Priority Color v35 → V5 color saturation
//     6. U-Value Actual            → V3 bar chart (kolon adı düzeltmesi)
//
//   AYRICA:
//     DATATABLE 'U-Value Categories' — V3 için calculated table.
//     (Power BI Desktop'ta New Table olarak ekle, DAX query view değil)
//
// ===  V2 TABLO → GÜNCEL ÖLÇÜ HARİTASI ========================================
//
//   Sütun 1: silver_building_master[building_name]       (değişmez)
//   Sütun 2: System Type Display v35                     (v34'ün yerini alır)
//   Sütun 3: Renovation Priority Icon v35                (v34'ün yerini alır)
//   Sütun 4: COP Display v35                             (v34'ün yerini alır)
//   Sütun 5: Insulation Score v34                        (değişmez, çalışıyor)
//   Sütun 6: Heat Loss kWh m2 Annual v34                 (değişmez, çalışıyor)
//   Sütun 7: Action Recommendation v35                   (v34'ün yerini alır)
//
//   V5:
//   Color saturation: Renovation Priority Color v35      (v34'ün yerini alır)
//
// ==========================================================================


// ==========================================================================
// 1) System Type Display v35
//    ALLEXCEPT kaldırıldı — MAX() doğrudan ilişki üzerinden çalışır
// ==========================================================================

System Type Display v35 =
VAR _sys = MAX ( gold_hvac_analytics[system_type] )
RETURN
    SWITCH (
        _sys,
        "heat_pump",  "🔵  Heat Pump (ASHP/GSHP)",
        "hybrid",     "🟣  Hybrid HP + Gas Backup",
        "gas_boiler", "🟠  Gas Boiler (CSRD risk)",
        "other",      "⚪  Other / Not specified",
        "n/a"
    )
// Format: text
// V2 tablo sütun 2'ye ekle
// Beklenen: B001 → "🔵 Heat Pump (ASHP/GSHP)", diğerleri → "🟠 Gas Boiler (CSRD risk)"


// ==========================================================================
// 2) Renovation Priority Icon v35
//    ALLEXCEPT kaldırıldı
// ==========================================================================

Renovation Priority Icon v35 =
VAR _label = MAX ( gold_hvac_analytics[renovation_priority] )
RETURN
    SWITCH (
        _label,
        "High",   "🔴  High — Act now",
        "Medium", "🟡  Medium — Plan in 2 yr",
        "Low",    "🟢  Low — Monitor",
        "—"
    )
// Beklenen V2'de:
//   B001 Berliner: Low   → 🟢
//   B002 Istanbul: High  → 🔴
//   B003 Hamburg:  Medium → 🟡
//   B004 Wien:     Medium → 🟡
//   B005 Frankfurt: High → 🔴  (Notebook 11 re-run sonrası)
//   B006 Amsterdam: High → 🔴


// ==========================================================================
// 3) COP Display v35
//    ALLEXCEPT kaldırıldı — silver_building_master zaten satır context'inde
// ==========================================================================

COP Display v35 =
VAR _scop =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[scop_rolling] ),
        gold_hvac_analytics[scop_rolling] > 0
    )
VAR _rated  = AVERAGE ( silver_building_master[heat_pump_cop_rated] )
VAR _has_hp = MAX ( silver_building_master[has_heat_pump] )
RETURN
    SWITCH (
        TRUE (),
        NOT _has_hp,                               "n/a (gas)",
        NOT ISBLANK ( _scop ) && _scop > 0,
            FORMAT ( _scop, "0.00" ) & "  (actual)",
        NOT ISBLANK ( _rated ) && _rated > 0,
            FORMAT ( _rated, "0.00" ) & "  (rated)",
        "n/a"
    )
// NOT: silver_building_master[has_heat_pump] = BOOLEAN (True/False).
// MAX(BOOLEAN) → TRUE varsa TRUE döner → NOT TRUE = FALSE → has_hp = TRUE branch çalışır.
// Beklenen: B001 → "3.80 (rated)", diğerleri → "n/a (gas)"


// ==========================================================================
// 4) Action Recommendation v35
//    ALLEXCEPT kaldırıldı
// ==========================================================================

Action Recommendation v35 =
VAR _sys = MAX ( gold_hvac_analytics[system_type] )
VAR _ins = AVERAGE ( gold_hvac_analytics[insulation_score] )
RETURN
    SWITCH (
        TRUE (),
        ISBLANK ( _sys ),                     "Audit recommended",
        _sys = "gas_boiler" && _ins < 55,     "Switch to ASHP + insulate envelope",
        _sys = "gas_boiler" && _ins < 75,     "Plan ASHP retrofit by 2030",
        _sys = "gas_boiler",                  "Envelope ok — plan ASHP transition",
        _sys = "hybrid",                      "Reduce gas backup share",
        _sys = "heat_pump" && _ins < 55,      "Insulate envelope — boost SCOP",
        _sys = "heat_pump",                   "Monitor SCOP & service interval",
        "Audit recommended"
    )
// Beklenen (her satır farklı metin):
//   B001 Berliner:  "Monitor SCOP & service interval"
//   B002 Istanbul:  "Switch to ASHP + insulate envelope"  (ins < 55)
//   B003 Hamburg:   "Plan ASHP retrofit by 2030"          (ins 55-75)
//   B004 Wien:      "Plan ASHP retrofit by 2030"
//   B005 Frankfurt: "Switch to ASHP + insulate envelope"  (ins < 55 + gas)
//   B006 Amsterdam: "Switch to ASHP + insulate envelope"  (ins < 55)


// ==========================================================================
// 5) Renovation Priority Color v35
//    ALLEXCEPT kaldırıldı — V5 Scatter için
// ==========================================================================

Renovation Priority Color v35 =
VAR _label = MAX ( gold_hvac_analytics[renovation_priority] )
RETURN
    SWITCH (
        _label,
        "Low",    1,
        "Medium", 2,
        "High",   3,
        BLANK ()
    )
// V5 Scatter → Format → Bubbles → Color → fx → Rules:
//   1 → #1D9E75 (green)
//   2 → #FFC107 (amber)
//   3 → #E24B4A (red)
// Beklenen: Berliner = 1 (green), Hamburg/Wien = 2 (amber), Amsterdam/Istanbul/Frankfurt = 3 (red)


// ==========================================================================
// 6) U-Value Actual
//    KOLON ADI HATASI DÜZELTİLDİ:
//    v34 rehberinde yanlış: u_value_wall, u_value_roof, u_value_floor, u_value_window
//    Doğru (CSV/Silver şeması): wall_u_value, roof_u_value, floor_u_value, window_u_value
// ==========================================================================

U-Value Actual =
VAR _comp = MAX ( 'U-Value Categories'[Component] )
RETURN
    SWITCH (
        _comp,
        "Wall",   AVERAGE ( silver_building_master[wall_u_value] ),
        "Roof",   AVERAGE ( silver_building_master[roof_u_value] ),
        "Floor",  AVERAGE ( silver_building_master[floor_u_value] ),
        "Window", AVERAGE ( silver_building_master[window_u_value] )
    )
// Önce 'U-Value Categories' tablosunu oluşturman lazım (aşağıya bak)
//
// Beklenen değerler (All binalar seçili):
//   Wall:   AVG(0.28, 0.80, 0.22, 0.45, 0.50, 0.90) ≈ 0.53
//   Roof:   AVG(0.18, 0.55, 0.15, 0.30, 0.35, 0.60) ≈ 0.36
//   Floor:  AVG(0.30, 0.70, 0.25, 0.45, 0.50, 0.80) ≈ 0.50
//   Window: AVG(1.10, 2.80, 0.90, 1.80, 1.50, 2.50) ≈ 1.77
//
// Berliner (B001) seçili:
//   Wall: 0.28, Roof: 0.18, Floor: 0.30, Window: 1.10
//   GEG referansları: 0.24 / 0.20 / 0.35 / 1.30
//   → Wall iyi (0.28 > 0.24 sadece az üst), Window iyi (1.10 < 1.30 ✅)
//
// Amsterdam (B006) seçili:
//   Wall: 0.90, Roof: 0.60, Floor: 0.80, Window: 2.50
//   → Tümü GEG referansının çok üzerinde ❌ → Renovation High


// ==========================================================================
// 'U-Value Categories' CALCULATED TABLE — Power BI'da New Table olarak ekle
// DAX query view'da New Table:
// ==========================================================================
//
// U-Value Categories =
// DATATABLE (
//     "Component", STRING,
//     "SortIdx",   INTEGER,
//     "GEG_Ref",   DOUBLE,
//     {
//         { "Wall",   1, 0.24 },
//         { "Roof",   2, 0.20 },
//         { "Floor",  3, 0.35 },
//         { "Window", 4, 1.30 }
//     }
// )
//
// NOT: "GEG_Ref" kolonu V3 visual'da reference line olarak:
//   Format → Reference line → "GEG_Ref" kolonunu "Reference (GEG 2023)" label'i ile ekle
// ==========================================================================


// ==========================================================================
// VALIDATION CHECKLIST — v35 uyguladıktan sonra
// ==========================================================================
//
// V2 Tablo (Slicer All):
// ┌─────────────────────────┬────────────────────────────┬──────────────┬──────────────┐
// │ Building                │ System Type                │ Priority     │ COP          │
// ├─────────────────────────┼────────────────────────────┼──────────────┼──────────────┤
// │ Berliner Bürogebäude    │ 🔵 Heat Pump (ASHP/GSHP)  │ 🟢 Low      │ 3.80 (rated) │
// │ Istanbul Ticaret        │ 🟠 Gas Boiler (CSRD risk) │ 🔴 High     │ n/a (gas)    │
// │ Hamburg Logistics       │ 🟠 Gas Boiler (CSRD risk) │ 🟡 Medium   │ n/a (gas)    │
// │ Wien Grand Hotel        │ 🟠 Gas Boiler (CSRD risk) │ 🟡 Medium   │ n/a (gas)    │
// │ Frankfurt Klinikum      │ 🟠 Gas Boiler (CSRD risk) │ 🔴 High     │ n/a (gas)    │  ← nb11 re-run sonrası
// │ Amsterdam Universiteit  │ 🟠 Gas Boiler (CSRD risk) │ 🔴 High     │ n/a (gas)    │
// └─────────────────────────┴────────────────────────────┴──────────────┴──────────────┘
//
// V5 Scatter (Slicer All):
//   B001 Berliner sağ-üst köşe → yeşil bubble (Priority Color = 1)
//   B006 Amsterdam sol-alt köşe → kırmızı bubble (Priority Color = 3)
//   B002, B003, B004 orta → amber bubble (Priority Color = 2 veya 3)
//
// V3 Bar (Slicer All):
//   4 bar görünür: Wall ~0.53, Roof ~0.36, Floor ~0.50, Window ~1.77
//   GEG reference line üstünde: Wall, Window → kırmızı zone
//
// ==========================================================================
// v35 toplam ölçü sayısı: 5 yeni ölçü + 1 U-Value Actual
// v34'ten değişmeyen (çalışıyor): C1-C5 ölçüleri, V1 ölçüleri, Insulation Score v34, Heat Loss v34
// ==========================================================================
