// ==========================================================================
// Energy Copilot Platform — DAX v36: Page 7 FORMAT FIX + PRE-COMPUTED
// File: semantic-model/45_dax_v36_page7_format_and_precomputed.dax
// Last updated: 2026-05-04
//
// ===  NEDEN v36? ============================================================
//
// v34/v35 ölçüleri veri hesaplamasını gold_hvac_analytics kolonlarından
// (heating_energy_kwh, cooling_energy_kwh, ventilation_kwh) yapıyordu.
// Bu kolonlar HDD/CDD bağımlı model tahminidir — pipeline'da hdd_hour
// coalesce eksikliği (2026-05-04 fix yapıldı) varsa değerler düşük çıkar.
//
// gold_hvac_analytics'te zaten PRE-COMPUTED sütunlar var:
//   hvac_share_pct       → notebook 11'de Spark'ta hesaplandı
//   hvac_efficiency_score → notebook 11'de Spark'ta hesaplandı
//   heat_loss_kwh_m2     → notebook 11'de Spark'ta hesaplandı
//   insulation_score     → notebook 11'de Spark'ta hesaplandı
//
// Bu ölçüler DAX hesaplama zincirine girmeden doğrudan bu kolonları okur.
// Notebook 11 re-run sonrası tüm değerler güncellenmiş olacak.
//
// ===  FORMAT FIX ============================================================
//
// C1 "16,546..." → format string Power BI'da yanlış. DOĞRU yaklaşım:
//   Card (new) visual → Format pane → Callout value → Custom format: 0.0"%"
//   Display units = None, Decimal places = 1
//
// C4 "17,199..." → aynı sorun + değer yıllık değil periyod toplamı.
//   Heat Loss kWh m2 Annual v36: AVERAGEX over buildings, her bina için
//   yıllık normalize (12 aylık oran ile düzelt).
//
// ==========================================================================


// ==========================================================================
// 1) C1 — HVAC SHARE (pre-computed sütundan)
//    gold_hvac_analytics[hvac_share_pct] = notebook 11'de hesaplandı
//    Enerji yöneticisine gösterilecek değer: portföy ortalaması
// ==========================================================================

HVAC Share Pct v36 =
AVERAGEX (
    VALUES ( gold_hvac_analytics[building_id] ),
    CALCULATE ( AVERAGE ( gold_hvac_analytics[hvac_share_pct] ) )
)
// Format (Card New visual → Callout value): 0.0"%"
// Display units: None
// Beklenen (All binalar, tüm yıl):
//   Office (Berlin): heating_sens=0.35 + cooling_sens=0.12 + vent=0.15 → ~40-55%
//   Healthcare (Frankfurt): hs=0.22 + cs=0.10 + vent=0.20 → ~35-45%
//   Logistics (Hamburg): hs=0.42 + cs=0.05 + vent=0.10 → ~40-50%
//   Portföy ortalama → 35-50%
//
// EĞER hâlâ ~16% görünüyorsa:
//   → gold_kpi_daily[hdd_day] ≈ 0 (weather join bug, 03_gold_kpi_engine fix yapıldı)
//   → Fabric'te Notebook 03 → 11 sırasıyla re-run yap


// ==========================================================================
// 2) C4 — HEAT LOSS kWh/m²·yıl (pre-computed + yıllık normalize)
//    heat_loss_kwh_m2 = aylık değer (kWh/m²/ay)
//    Yıllığa çevirmek için: bir bina için 12 aylık SUM
//    Portföy için: binalar arası ortalama
// ==========================================================================

Heat Loss kWh m2 Annual v36 =
AVERAGEX (
    VALUES ( gold_hvac_analytics[building_id] ),
    CALCULATE (
        SUM ( gold_hvac_analytics[heat_loss_kwh_m2] ),
        // Sadece tam 12 ay içeren yılı kullan — kısmi yıl sonucu düşürür
        FILTER (
            ALL ( 'Date' ),
            'Date'[Year] = MAXX ( ALL ( 'Date' ), 'Date'[Year] ) - 1
                OR 'Date'[Year] = MAXX ( ALL ( 'Date' ), 'Date'[Year] )
        )
    )
)
// DAHA BASIT ALTERNATİF (eğer yukarıdaki çalışmıyorsa):
// Heat Loss kWh m2 Annual v36 =
// AVERAGEX(
//     VALUES(gold_hvac_analytics[building_id]),
//     CALCULATE(SUM(gold_hvac_analytics[heat_loss_kwh_m2]))
// )
// → Slicer date range ne olursa olsun, seçilen dönem toplamını verir
// → Card label'ı "Seçili Dönem kWh/m²" olarak ayarla (yıllık değil)
//
// Format: 0.0" kWh/m²"
// Beklenen (12 ay, All binalar):
//   Berliner (iyi yalıtım, Berlin iklimi): ~35-55 kWh/m²·yr
//   Amsterdam (kötü yalıtım, NL iklimi): ~70-100 kWh/m²·yr
//   Portföy ortalama → 50-80 kWh/m²·yr


// ==========================================================================
// 3) C2 — HVAC EFFICIENCY (pre-computed)
//    gold_hvac_analytics[hvac_efficiency_score] = notebook 11'de hesaplandı
//    v34 ile AYNI MANTIK — v34 çalışıyorsa bu gerek yok
// ==========================================================================

HVAC Efficiency v36 =
AVERAGEX (
    VALUES ( gold_hvac_analytics[building_id] ),
    CALCULATE ( AVERAGE ( gold_hvac_analytics[hvac_efficiency_score] ) )
)
// Beklenen: 42-58 (gas-heavy portföy, B001 HP ile biraz yukarı)
// B001 Berliner: score = COP_rated/COP_excellent × 100 = 3.8/4.5 × 100 = 84 → maks 100 → ~84
// B002-B006 Gas: insulation_score × 0.45, max 50
//   B003 Hamburg (en iyi yalıtım, ins_score ~85): 85 × 0.45 = 38.3
//   B006 Amsterdam (kötü, ins_score ~40): 40 × 0.45 = 18
//   Portföy ortalama → 35-50 ✓


// ==========================================================================
// 4) C3 — INSULATION SCORE (pre-computed)
//    v34 ile AYNI — zaten çalışıyor (screenshot'ta 78 görünüyor ✅)
//    Bu ölçü eğer v34 yoksa fallback olarak kullanılır
// ==========================================================================

Insulation Score v36 =
AVERAGEX (
    VALUES ( gold_hvac_analytics[building_id] ),
    CALCULATE ( AVERAGE ( gold_hvac_analytics[insulation_score] ) )
)
// Beklenen: All → 60-75 (Berliner ~82, Amsterdam ~35, diğerleri orta)


// ==========================================================================
// 5) V1 — HVAC ENERGY BREAKDOWN (pre-computed kolonlar)
//    EĞER v34 V1 ölçüleri düzgün veri göstermiyorsa bu alternatifi dene
//    (aynı notebook 11 kolonlarını kullanıyor ama DAX SUMX değil SUM)
// ==========================================================================

Heating kWh v36 = SUM ( gold_hvac_analytics[heating_energy_kwh] )
// Beklenen (winter months dominant, kış=heating %70+)

Cooling kWh v36 = SUM ( gold_hvac_analytics[cooling_energy_kwh] )
// Beklenen (summer months dominant)

Ventilation kWh v36 = SUM ( gold_hvac_analytics[ventilation_kwh] )
// Beklenen: sabit %15 (tüm yıl benzer)

// NOT: V1'de heating çok küçükse → HDD data pipeline bug.
// Fix: Fabric'te 03_gold_kpi_engine.py (hdd_hour coalesce eklendi) → 11_hvac_analytics_engine.py
// sırasıyla re-run. Sonra Power BI model refresh.


// ==========================================================================
// 6) V3 CARD LABELS — C1/C4 için format string ölçüleri
//    Card (new) visual format yetersizse bu TEXT ölçülerini kullan
// ==========================================================================

HVAC Share Display v36 =
VAR _pct = [HVAC Share Pct v36]
RETURN
    IF (
        ISBLANK ( _pct ),
        "—",
        FORMAT ( _pct, "0.0" ) & " %"
    )
// Beklenen: "42.3 %"
// NOT: Bu TEXT döndürür → "Callout value" formatı otomatik apply edilmez.
// Kullanım: Card (classic) → tek değer olarak bağla, değer doğrudan string gösterir.


Heat Loss Display v36 =
VAR _hl = [Heat Loss kWh m2 Annual v36]
RETURN
    IF (
        ISBLANK ( _hl ),
        "—",
        FORMAT ( _hl, "0.0" ) & " kWh/m²"
    )


// ==========================================================================
// VALIDATION NOTES
// ==========================================================================
//
// Şu an "All" seçili iken beklenen değerler:
//   C1 HVAC Share:       35–55%   (hâlâ ~16% ise → pipeline re-run lazım)
//   C2 HVAC Efficiency:  40–55    (şu an 49 ✅)
//   C3 Avg Insulation:   60–75    (şu an 78 ✅ — biraz yüksek ama kabul)
//   C4 Heat Loss:        50–90 kWh/m²·yr (hâlâ ~17 ise → partial period veya HDD bug)
//   C5 Retrofit:         2–4      (şu an 1 → Frankfurt dahil olunca 3+ olmalı)
//
// Pipeline fix sonrası (Notebook 03 → 11 re-run):
//   C1 ve C4 doğru aralığa girecek
//   C5 Frankfurt'u sayacak (3+ olmalı)
//   V1 heating kış aylarında dominant olacak
//
// ==========================================================================
