// ==========================================================================
// Energy Copilot Platform — DAX v39: Page 7 KAPSAMLI FIX
// File: semantic-model/48_dax_v39_page7_full_fix.dax
// Tarih: 2026-05-05
//
// === NEDEN v39? =============================================================
//
// Ekrandan tespit edilen sorunlar + çözümler:
//
// 1. C6 HVAC CO₂ → "See details" hatası
//    Sebep: gold_hvac_analytics[has_gas] kolonu FINAL_COLS'ta yok
//    Düzeltme: system_type kullan (v38 formülü) — has_gas'a gerek yok
//
// 2. V2 Tablo — Tüm binalar "Heat Pump (ASHP/GSHP)" gösteriyor
//    Sebep A: Power BI ilişkisi (silver_building_master → gold_hvac_analytics)
//             filter propagation yapmıyorsa MAX() tüm binalar üzerinden döner
//             → MAX("heat_pump","gas_boiler",...) = "heat_pump" (alfabetik)
//    Sebep B: gold_hvac_analytics veri sorunu (tüm system_type = "heat_pump")
//    Düzeltme: TREATAS ile building_id'yi explicit filter et (ilişkiden bağımsız)
//
// 3. HVAC teknoloji kapsamı eksik
//    Düzeltme: VRF, district, GSHP, WSHP, biomass, electric resistance eklendi
//
// 4. V1 Chart — 100% stacked bar (kWh mutlak değer görünmüyor)
//    Düzeltme: Bu DAX değil UI ayarı — rehber son bölümde
//
// 5. V2 Tablo kolon başlıkları çok uzun
//    Düzeltme: Power BI UI rename — rehber son bölümde
//
// === BU DOSYADA NELER VAR ==================================================
//
//   B1. System Type Display v39   → V2 kolon 2 (TREATAS fix + tüm tipler)
//   B2. Renovation Priority Icon v39 → V2 kolon 3 (TREATAS fix)
//   B3. COP Display v39           → V2 kolon 4 (TREATAS fix + VRF/District)
//   B4. Action Recommendation v39 → V2 kolon 7 (tüm tipler)
//   B5. Renovation Priority Color v39 → V5 scatter color saturation
//   B6. HVAC CO2 tCO2 v39        → C6 kart (TREATAS fix)
//   B7. HVAC CO2 Display v39     → C6 text fallback
//   B8. Insulation Score Display v39 → C3 (TREATAS fix)
//   B9. HVAC Share Pct Display v39 → C1 (robust)
//
// === UYGULAMA ===============================================================
//
//   Önce: Power BI → Modelling → Relationships'ı kontrol et:
//     silver_building_master[building_id] → gold_hvac_analytics[building_id]
//     Filter direction: Single (silver → gold)
//     Bu ilişki aktifse TREATAS gerekmeyebilir, ama zarar vermez.
//
//   Sonra: Bu dosyadaki her ölçüyü DAX editörüne yapıştır:
//     1. Varolan ölçüyü sil (Delete measure)
//     2. New measure → yapıştır
//     3. V2 tablodaki field well'i yeni ölçüyle güncelle
//
// ==========================================================================


// ==========================================================================
// YARDIMCI MAKRO — DAX'ta "fonksiyon" tanımlanamaz, ama bu pattern yaygın
// Her ölçüde _bid hesabı tekrarlıdır: MAX(silver_building_master[building_id])
// Bu building_name satır context'inde tek bir building_id'ye karşılık gelir.
// ==========================================================================


// ==========================================================================
// B1) System Type Display v39  ← V2 TABLO KOLON 2
//     TREATAS: ilişkiden bağımsız explicit building_id filtresi
//     Tüm HVAC teknoloji tipleri destekleniyor
// ==========================================================================

System Type Display v39 =
// building_id: satır context'inde silver_building_master'dan al
VAR _bid = MAX ( silver_building_master[building_id] )
// Explicit filter — Power BI ilişkisine güvenmeden doğrudan FILTER
VAR _sys =
    CALCULATE (
        MAX ( gold_hvac_analytics[system_type] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
RETURN
    IF (
        ISBLANK ( _bid ) || ISBLANK ( _sys ),
        "—",
        SWITCH (
            _sys,
            // Isı pompası ailesi
            "heat_pump",  "🔵  Heat Pump (ASHP)",
            "gshp",       "🔵  Heat Pump (GSHP)",
            "wshp",       "🔵  Heat Pump (WSHP)",
            // Hibrit
            "hybrid",     "🟣  Hybrid HP + Gas Backup",
            // Fosil
            "gas_boiler", "🟠  Gas Boiler  ⚠️ CSRD",
            // Elektrik bazlı
            "vrf",        "🟡  VRF / VRV System",
            "electric",   "⚡  Electric Resistance",
            "chiller",    "❄️  Chiller (Cooling-led)",
            // Yenilenebilir / alternatif
            "biomass",    "🟢  Biomass Boiler",
            "district",   "🟤  District H/C",
            // Bilinmiyor
            "other",      "⚪  Other / Unknown",
            "—"
        )
    )
// Format: Text
// Beklenen (veri doğruysa):
//   B001 → "🔵 Heat Pump (ASHP)"
//   B002 → "🟠 Gas Boiler ⚠️ CSRD"
//   B003 → "🟠 Gas Boiler ⚠️ CSRD"
//   B004 → "🟤 District H/C"       ← Notebook 11 güncellendikten sonra
//   B005 → "🟠 Gas Boiler ⚠️ CSRD"
//   B006 → "🟡 VRF / VRV System"   ← Notebook 11 güncellendikten sonra


// ==========================================================================
// B2) Renovation Priority Icon v39  ← V2 TABLO KOLON 3
//     TREATAS fix
// ==========================================================================

Renovation Priority Icon v39 =
VAR _bid   = MAX ( silver_building_master[building_id] )
VAR _label =
    CALCULATE (
        MAX ( gold_hvac_analytics[renovation_priority] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
RETURN
    IF (
        ISBLANK ( _label ),
        "—",
        SWITCH (
            _label,
            "High",   "🔴  High — Act now",
            "Medium", "🟡  Medium — Plan ≤2 yr",
            "Low",    "🟢  Low — Monitor",
            "—"
        )
    )


// ==========================================================================
// B3) COP Display v39  ← V2 TABLO KOLON 4
//     TREATAS fix + VRF, District, GSHP, Biomass, Electric desteği
// ==========================================================================

COP Display v39 =
VAR _bid  = MAX ( silver_building_master[building_id] )
VAR _sys  =
    CALCULATE (
        MAX ( gold_hvac_analytics[system_type] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
// Gerçek rolling SCOP (varsa)
VAR _scop =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[scop_rolling] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid ),
        gold_hvac_analytics[scop_rolling] > 0
    )
// Rated COP (silver_building_master'dan)
VAR _rated =
    CALCULATE (
        AVERAGE ( silver_building_master[heat_pump_cop_rated] ),
        silver_building_master[building_id] = _bid
    )
// HP var mı?
VAR _has_hp =
    CALCULATE (
        MAX ( silver_building_master[has_heat_pump] ),
        silver_building_master[building_id] = _bid
    )
RETURN
    IF (
        ISBLANK ( _sys ),
        "—",
        SWITCH (
            TRUE (),
            // Isı pompası ailesi
            _sys = "heat_pump" && NOT ISBLANK ( _scop ) && _scop > 0,
                FORMAT ( _scop, "0.00" ) & " (SCOP)",
            _sys = "heat_pump" && NOT ISBLANK ( _rated ) && _rated > 0,
                FORMAT ( _rated, "0.0" ) & " (rated)",
            _sys = "heat_pump",
                "n/a (HP — data missing)",
            // GSHP — yüksek COP, toprak kaynaklı
            _sys = "gshp",
                IF ( NOT ISBLANK ( _scop ), FORMAT ( _scop, "0.00" ) & " (SCOP)", "4.0–6.0 (GSHP Est.)" ),
            // WSHP
            _sys = "wshp",
                "4.5–7.0 (WSHP Est.)",
            // VRF — COP sistem ölçümünden gelir, genellikle 3.0–5.5
            _sys = "vrf",
                "3.0–5.5 (VRF Est.)",
            // Bölgesel ısıtma — COP kavramı uygulanmaz (ağ verimi farklı ölçülür)
            _sys = "district",
                "n/a (District — network efficiency)",
            // Hibrit — HP bileşeni COP + gaz miks
            _sys = "hybrid",
                "HP: " & IF ( NOT ISBLANK ( _rated ), FORMAT ( _rated, "0.0" ), "n/a" ) & " + Gas backup",
            // Gaz kazan — COP yerine AFUE (mevsimsel verim) geçerli
            _sys = "gas_boiler",
                "n/a (Gas — AFUE 90–98%)",
            // Biyokütle — ısıl verimlilik %75-90
            _sys = "biomass",
                "n/a (Biomass — η 75–90%)",
            // Elektrikli direnç — COP = 1.0 (ısıl eşdeğer)
            _sys = "electric",
                "COP 1.0 (Elec. Resistance)",
            "—"
        )
    )


// ==========================================================================
// B4) Action Recommendation v39  ← V2 TABLO KOLON 7
//     Tüm HVAC teknoloji tipleri için aksiyon metni
// ==========================================================================

Action Recommendation v39 =
VAR _bid = MAX ( silver_building_master[building_id] )
VAR _sys =
    CALCULATE (
        MAX ( gold_hvac_analytics[system_type] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
VAR _ins =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[insulation_score] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
RETURN
    IF ( ISBLANK ( _sys ), "HVAC audit recommended",
    SWITCH (
        TRUE (),
        // Gaz kazan — CSRD riski yüksek
        _sys = "gas_boiler" && _ins < 45,
            "🔴 ASHP retrofit + envelope insulation — CSRD Scope 1 risk critical",
        _sys = "gas_boiler" && _ins < 65,
            "🟡 Plan ASHP by 2030 — improve insulation first",
        _sys = "gas_boiler",
            "🟢 Envelope sufficient — schedule ASHP transition pre-2035",
        // Hibrit
        _sys = "hybrid" && _ins < 55,
            "🟡 Insulate envelope first, then reduce gas backup share",
        _sys = "hybrid",
            "🟢 Increase HP hours, reduce gas backup below 20%",
        // Isı pompası
        _sys = "heat_pump" && _ins < 55,
            "🟡 Insulate envelope — boosts SCOP by est. 15–25%",
        _sys = "heat_pump",
            "🟢 Monitor SCOP monthly — schedule compressor service annually",
        // GSHP
        _sys = "gshp" && _ins < 55,
            "🟡 Envelope improvement increases GSHP ground loop efficiency",
        _sys = "gshp",
            "🟢 Check ground loop pressure & antifreeze annually",
        // VRF
        _sys = "vrf" && _ins < 55,
            "🟡 VRF zoning losses high due to poor envelope — insulate first",
        _sys = "vrf",
            "🟢 Balance VRF zones, schedule refrigerant leak check",
        // Bölgesel ısıtma
        _sys = "district" && _ins < 55,
            "🟡 Reduce district heat demand — insulate building envelope",
        _sys = "district",
            "🟢 Optimise heat exchanger ΔT — monitor supply/return temps",
        // Biyokütle
        _sys = "biomass" && _ins < 55,
            "🟡 Insulate first — reduce fuel demand before biomass expansion",
        _sys = "biomass",
            "🟢 Ensure fuel supply security + PM2.5 emission monitoring",
        // Elektrikli direnç
        _sys = "electric",
            "🔴 Switch to ASHP — COP 1→3.5+ saves ~65% electricity",
        // Diğer
        "🔵 HVAC audit recommended — system type unclassified"
    ))


// ==========================================================================
// B5) Renovation Priority Color v39  ← V5 SCATTER COLOR SATURATION
//     TREATAS fix
// ==========================================================================

Renovation Priority Color v39 =
VAR _bid   = MAX ( silver_building_master[building_id] )
VAR _label =
    CALCULATE (
        MAX ( gold_hvac_analytics[renovation_priority] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
RETURN
    SWITCH (
        _label,
        "Low",    1,
        "Medium", 2,
        "High",   3,
        BLANK ()
    )
// V5 Scatter → Format → Bubbles → Color → fx → Rules:
//   1 → #1D9E75 (yeşil — Low)
//   2 → #FFC107 (amber — Medium)
//   3 → #E24B4A (kırmızı — High)


// ==========================================================================
// B6) HVAC CO2 tCO2 v39  ← C6 KARTI
//     FIX: has_gas kolonu yok → system_type kullan (v38 mantığı + TREATAS)
//     TREATAS eklendi: portföy context'inde de çalışır
// ==========================================================================

HVAC CO2 tCO2 v39 =
VAR _gasF  = 0.2017   // kgCO₂/kWh — doğalgaz scope 1 (BAFA/IPCC 2006)
VAR _elecF = 0.350    // kgCO₂e/kWh — AB elektrik şebekesi ort. 2024

// Her bina için sistem tipine göre ısıtma emisyonu
VAR _heatingKg =
    SUMX (
        VALUES ( gold_hvac_analytics[building_id] ),
        VAR _bid = gold_hvac_analytics[building_id]
        VAR _sys =
            CALCULATE (
                MAX ( gold_hvac_analytics[system_type] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        // Scope 1 (fosil gaz): gas_boiler, hybrid (muhafazakâr)
        // Scope 2 (elektrik) : heat_pump, gshp, wshp, vrf, electric
        // Scope 3 / ağ bazlı: district (kaynak tarafı izlenmeli)
        // Biomass: scope 1 ama biyojenik karbon → CSRD Annex I ayrımı
        VAR _isScope1 = _sys = "gas_boiler" || _sys = "hybrid" || _sys = "biomass"
        VAR _heatKwh  =
            CALCULATE (
                SUM ( gold_hvac_analytics[heating_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        RETURN IF ( _isScope1, _heatKwh * _gasF, _heatKwh * _elecF )
    )

// Soğutma + havalandırma: her zaman elektrik
VAR _coolingKg = SUM ( gold_hvac_analytics[cooling_energy_kwh] ) * _elecF
VAR _ventKg    = SUM ( gold_hvac_analytics[ventilation_kwh] )    * _elecF

RETURN
    DIVIDE ( _heatingKg + _coolingKg + _ventKg, 1000 )
// Sonuç: tCO₂/yıl (seçilen dönem/filtre context'ine göre)
// Format (Card New → Callout value): 0.0" tCO₂"   Display units: None
//
// Beklenen (All binalar, tüm aylar, 6 bina):
//   B001 HP  (scope 2):  ~15–25 tCO₂
//   B002 Gas (scope 1):  ~50–70 tCO₂
//   B003 Gas (scope 1):  ~60–80 tCO₂ (büyük lojistik)
//   B004 District:       ~30–50 tCO₂ (ağ kaynaklı — scope 2)
//   B005 Gas (scope 1):  ~45–65 tCO₂ (hastane 24/7)
//   B006 VRF (scope 2):  ~40–60 tCO₂
//   Portföy toplam:      ~240–350 tCO₂


// ==========================================================================
// B7) HVAC CO2 Display v39  ← C6 TEXT FALLBACK
// ==========================================================================

HVAC CO2 Display v39 =
VAR _t = [HVAC CO2 tCO2 v39]
RETURN
    IF ( ISBLANK ( _t ) || _t = 0, "—", FORMAT ( _t, "0.0" ) & " tCO₂" )


// ==========================================================================
// B8) Insulation Score Display v39  ← C3 ROBUST
//     Relationship fix + "—" yerine sayı göster
// ==========================================================================

Card: Avg Insulation v39 =
VAR _score = AVERAGE ( gold_hvac_analytics[insulation_score] )
RETURN
    IF ( ISBLANK ( _score ), "—", FORMAT ( ROUND ( _score, 0 ), "0" ) )
// Beklenen (All): 60–75  |  B001 Berliner: 90+  |  B006 Amsterdam: <30


// ==========================================================================
// B9) HVAC Share Pct Display v39  ← C1 ROBUST (floating point fix)
// ==========================================================================

HVAC Share Pct Display v39 =
VAR _pct = AVERAGE ( gold_hvac_analytics[hvac_share_pct] )
RETURN
    IF ( ISBLANK ( _pct ), "—", FORMAT ( ROUND ( _pct, 1 ), "0.0" ) & "%" )
// Beklenen: 35–60% (portföy geneli)  |  Healthcare B005: 45–65%


// ==========================================================================
//
// HIZLI UYGULAMA REHBERİ — v39
//
// ── ADIM 1: İlişkiyi kontrol et ──────────────────────────────────────────
//   Model view → silver_building_master[building_id] → gold_hvac_analytics[building_id]
//   Filter direction: Single (silver → gold)
//   İlişki yoksa: + New relationship ekle
//
// ── ADIM 2: Bu ölçüleri import et (her biri ayrı "New measure") ───────────
//   Önce: Model view veya Table view → "New measure"
//   Kaynağa göre atama (masa aynı olabilir — gold_hvac_analytics'e atama önerilir):
//     B1 System Type Display v39
//     B2 Renovation Priority Icon v39
//     B3 COP Display v39
//     B4 Action Recommendation v39
//     B5 Renovation Priority Color v39
//     B6 HVAC CO2 tCO2 v39
//     B7 HVAC CO2 Display v39
//
// ── ADIM 3: V2 Tablo field well'leri güncelle ─────────────────────────────
//   Columns well'de eski ölçüleri kaldır → v39 ölçülerini sürükle:
//     Kolon 1: silver_building_master[building_name]   → "Building"
//     Kolon 2: System Type Display v39                 → "System"
//     Kolon 3: Renovation Priority Icon v39            → "Priority"
//     Kolon 4: COP Display v39                         → "COP/SCOP"
//     Kolon 5: gold_hvac_analytics[insulation_score]   → "Insulation"
//     Kolon 6: Heat Loss kWh m2 Annual v34             → "Heat Loss"
//     Kolon 7: Action Recommendation v39               → "Action"
//   Power BI'da kolon adını kısaltmak: field well'de kolona sağ tık → Rename
//
// ── ADIM 4: C6 kartını güncelle ───────────────────────────────────────────
//   C6 Card (New) → Callout value: HVAC CO2 tCO2 v39
//   Format: 0.0" tCO₂"   Display units: None
//
// ── ADIM 5: V1 chart — 100% stacked → Stacked bar ────────────────────────
//   V1 → Format → Y axis → "Stacked" (NOT "100% Stacked")
//   Bu değişiklik kWh mutlak değerlerini gösterir: kış aylarında heating yüksek
//
// ── ADIM 6: V5 Scatter — color saturation güncelle ───────────────────────
//   V5 → Format → Bubbles → Color → fx → Field value:
//     Renovation Priority Color v39
//   Rules: 1 → #1D9E75  |  2 → #FFC107  |  3 → #E24B4A
//
// ── ADIM 7: Pipeline ve veri güncelle ─────────────────────────────────────
//   Fabric'te şu sırayla çalıştır:
//     1. 01_bronze_ingestion.py    (primary_hvac_system alanı eklendi)
//     2. 02_silver_transformation.py
//     3. 03_gold_kpi_engine.py     (Gold_KPI — başarısız olursa log'a bak)
//     4. 11_hvac_analytics_engine.py (VRF/District/GSHP desteği eklendi)
//     5. 06_recommendation_engine.py (artık gold_compliance_results olmadan çalışır)
//   Sonra: Semantic model → Refresh → Direct Lake sync
//
// ==========================================================================

