// ==========================================================================
// DAX v40 — PAGE 7 HVAC & Building Envelope — ENHANCED KPI CARDS
// Energy Copilot Platform — 2026-05-05
//
// v39'dan fark: Yeni COP kartı + zenginleştirilmiş card ölçüleri +
//               referans çizgisi ölçüleri + CSRD Gas Exposure kartı +
//               EPC compliance kartı + V1/V5 için yardımcı ölçüler
//
// Tablo: gold_hvac_analytics (27 kolon, v39 pipeline ile doldurulmuş)
// İlişki: silver_building_master[building_id] → gold_hvac_analytics[building_id]
//         (Single direction)
//
// UYGULAMA:
//   1. Bu ölçüleri "New measure" ile import et (gold_hvac_analytics tablosuna)
//   2. v39 kartlarını bu v40 ölçüleriyle değiştir (eski ölçüler de çalışmaya devam eder)
//   3. New Card görselinde: Callout = ana ölçü | Reference label = _Label ölçüsü
// ==========================================================================


// ==========================================================================
// C1) HVAC SHARE — Güçlendirilmiş versiyon
// ==========================================================================

Card: HVAC Share v40 =
VAR _pct = AVERAGE ( gold_hvac_analytics[hvac_share_pct] )
RETURN
    IF ( ISBLANK ( _pct ), "—", FORMAT ( ROUND ( _pct, 1 ), "0.0" ) & "%" )
// New Card → Callout value
// EU benchmark: ~35%. >55% yüksek risk (CSRD enerji yoğunluğu)

Card: HVAC Share Label v40 =
VAR _pct  = AVERAGE ( gold_hvac_analytics[hvac_share_pct] )
VAR _cat  =
    SWITCH ( TRUE (),
        _pct >= 55, "⚠️ Yüksek Oran — CSRD Riski",
        _pct >= 42, "🟡 Orta — AB Ortalaması Üzeri",
        _pct >= 30, "✅ Normal Aralık",
        "ℹ️ Düşük HVAC Payı"
    )
RETURN IF ( ISBLANK ( _pct ), "Veri yok", _cat )
// New Card → Reference label alanına sürükle


// ==========================================================================
// C2) COP / SCOP — TAMAMEN YENİ (kullanıcı istedi)
// ==========================================================================

Card: Avg COP v40 =
// Önce ölçülen gerçek COP, yoksa rated COP kullan
// Sadece heat_pump/gshp/vrf/wshp sistemleri için anlamlı
VAR _cop_actual =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[cop_actual_avg] ),
        NOT ISBLANK ( gold_hvac_analytics[cop_actual_avg] )
    )
VAR _scop =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[scop_rolling] ),
        NOT ISBLANK ( gold_hvac_analytics[scop_rolling] )
    )
VAR _val = COALESCE ( _scop, _cop_actual )
RETURN
    IF (
        ISBLANK ( _val ),
        "N/A",
        FORMAT ( ROUND ( _val, 2 ), "0.00" )
    )
// Beklenen: B001 HP → ~3.4–3.8  |  B006 VRF → ~3.8–4.2
// Gas binalar için "N/A" döner (kasıtlı — COP gaz kazanlarına uygulanamaz)

Card: COP Label v40 =
VAR _val =
    COALESCE (
        CALCULATE ( AVERAGE ( gold_hvac_analytics[scop_rolling] ),
            NOT ISBLANK ( gold_hvac_analytics[scop_rolling] ) ),
        CALCULATE ( AVERAGE ( gold_hvac_analytics[cop_actual_avg] ),
            NOT ISBLANK ( gold_hvac_analytics[cop_actual_avg] ) )
    )
VAR _sys = MAX ( gold_hvac_analytics[system_type] )
VAR _label =
    SWITCH ( TRUE (),
        ISBLANK ( _val ) && _sys = "gas_boiler",    "Gas Kazanı — COP Uygulanamaz",
        ISBLANK ( _val ) && _sys = "district",       "Bölgesel Isıtma — COP Dışı",
        ISBLANK ( _val ),                            "Ölçüm Verisi Yok",
        _val >= 4.5,   "🟢 Mükemmel (≥4.5)",
        _val >= 3.5,   "🟢 İyi (3.5–4.5)",
        _val >= 2.5,   "🟡 Orta (2.5–3.5)",
        _val >= 1.5,   "🔴 Düşük (1.5–2.5)",
                       "🔴 Kritik (<1.5)"
    )
RETURN _label
// New Card → Reference label

Card: COP vs Rated v40 =
// Gerçek SCOP ile rated COP'un farkını göster
// Negatif = beklentinin altında performans → bakım/arıza sinyali
VAR _actual =
    COALESCE (
        CALCULATE ( AVERAGE ( gold_hvac_analytics[scop_rolling] ),
            NOT ISBLANK ( gold_hvac_analytics[scop_rolling] ) ),
        CALCULATE ( AVERAGE ( gold_hvac_analytics[cop_actual_avg] ),
            NOT ISBLANK ( gold_hvac_analytics[cop_actual_avg] ) )
    )
VAR _rated  =
    CALCULATE (
        AVERAGE ( silver_building_master[heat_pump_cop_rated] ),
        NOT ISBLANK ( silver_building_master[heat_pump_cop_rated] )
    )
VAR _diff   = _actual - _rated
RETURN
    IF (
        ISBLANK ( _actual ) || ISBLANK ( _rated ),
        "—",
        FORMAT ( _diff, "+0.00;−0.00;0.00" ) & " vs rated"
    )
// Tooltip veya ikincil kart olarak kullanılabilir


// ==========================================================================
// C3) INSULATION SCORE — Referans çizgili versiyon (v39 ile aynı, label eklendi)
// ==========================================================================

Card: Avg Insulation v40 =
VAR _score = AVERAGE ( gold_hvac_analytics[insulation_score] )
RETURN
    IF ( ISBLANK ( _score ), "—", FORMAT ( ROUND ( _score, 0 ), "0" ) & " / 100" )

Card: Insulation Label v40 =
VAR _score = AVERAGE ( gold_hvac_analytics[insulation_score] )
VAR _label =
    SWITCH ( TRUE (),
        _score >= 80, "🟢 EPC A/B — NZEB Hazır",
        _score >= 65, "🟡 EPC C — İyileştirme Önerilir",
        _score >= 50, "🟠 EPC D — GEG Limit Altı",
        _score >= 35, "🔴 EPC E/F — Zorunlu Retrofit",
                      "🔴 EPC G — Acil Eylem"
    )
RETURN IF ( ISBLANK ( _score ), "Veri yok", _label )


// ==========================================================================
// C4) HEAT LOSS — kWh/m²·yr (v39 ile uyumlu, label eklendi)
// ==========================================================================

Card: Heat Loss v40 =
VAR _hl = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
RETURN
    IF ( ISBLANK ( _hl ), "—", FORMAT ( ROUND ( _hl, 0 ), "0" ) & " kWh/m²" )

Card: Heat Loss Label v40 =
VAR _hl = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
VAR _label =
    SWITCH ( TRUE (),
        _hl <= 30,  "🟢 Pasif Haus Seviyesi (<30)",
        _hl <= 55,  "🟢 EPC A — NZEB Uyumlu",
        _hl <= 90,  "🟡 EPC B/C — AB Ortalaması",
        _hl <= 150, "🟠 EPC D/E — Yüksek Kayıp",
                    "🔴 EPC F/G — Kritik Kayıp"
    )
RETURN IF ( ISBLANK ( _hl ), "Veri yok", _label )


// ==========================================================================
// C5) BUILDINGS FOR RETROFIT — v39 ile aynı mantık
// ==========================================================================

Card: Buildings For Retrofit v40 =
VAR _cnt =
    CALCULATE (
        DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
        gold_hvac_analytics[renovation_priority] = 1  -- Priority: Now
    )
RETURN IF ( ISBLANK ( _cnt ), "0", FORMAT ( _cnt, "0" ) )

Card: Retrofit Label v40 =
VAR _now   = CALCULATE ( DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
                gold_hvac_analytics[renovation_priority] = 1 )
VAR _soon  = CALCULATE ( DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
                gold_hvac_analytics[renovation_priority] = 2 )
VAR _total = DISTINCTCOUNT ( silver_building_master[building_id] )
VAR _now_s  = COALESCE ( _now,  0 )
VAR _soon_s = COALESCE ( _soon, 0 )
RETURN
    FORMAT ( _now_s,  "0" ) & " acil  |  " &
    FORMAT ( _soon_s, "0" ) & " planlanmış  |  " &
    FORMAT ( _total - _now_s - _soon_s, "0" ) & " izleniyor"


// ==========================================================================
// C6) HVAC CO₂ — Scope 1 vs Scope 2 ayrımı (v39'dan geliştirildi)
// ==========================================================================

Card: HVAC CO2 v40 =
// v39 HVAC CO2 tCO2 v39 ile aynı hesap — daha kısa format
VAR _gasF  = 0.2017   -- DE/AT/NL scope 1: BAFA/IPCC 2024
VAR _elecF = 0.350    -- EU avg scope 2: EEA 2024
VAR _total_kg =
    SUMX (
        VALUES ( gold_hvac_analytics[building_id] ),
        VAR _bid = gold_hvac_analytics[building_id]
        VAR _sys =
            CALCULATE (
                MAX ( gold_hvac_analytics[system_type] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _isScope1 = _sys = "gas_boiler" || _sys = "hybrid" || _sys = "biomass"
        VAR _hkwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[heating_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _ckwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[cooling_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _vkwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[ventilation_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _hkg  = IF ( _isScope1, COALESCE ( _hkwh, 0 ) * _gasF,  COALESCE ( _hkwh, 0 ) * _elecF )
        VAR _ckg  = COALESCE ( _ckwh, 0 ) * _elecF
        VAR _vkg  = COALESCE ( _vkwh, 0 ) * _elecF
        RETURN _hkg + _ckg + _vkg
    )
RETURN
    IF ( ISBLANK ( _total_kg ), "—",
         FORMAT ( ROUND ( DIVIDE ( _total_kg, 1000 ), 1 ), "0.0" ) & " tCO₂" )

Card: CO2 Label v40 =
// Scope 1 (gaz) vs Scope 2 (elektrik) ayrımı — CSRD için kritik
VAR _gasF  = 0.2017
VAR _elecF = 0.350
VAR _s1_kg =
    SUMX (
        VALUES ( gold_hvac_analytics[building_id] ),
        VAR _bid = gold_hvac_analytics[building_id]
        VAR _sys =
            CALCULATE ( MAX ( gold_hvac_analytics[system_type] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid ) )
        VAR _isScope1 = _sys = "gas_boiler" || _sys = "hybrid" || _sys = "biomass"
        VAR _hkwh =
            CALCULATE ( SUM ( gold_hvac_analytics[heating_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid ) )
        RETURN IF ( _isScope1, COALESCE ( _hkwh, 0 ) * _gasF, 0 )
    )
VAR _total_kg =
    SUMX (
        VALUES ( gold_hvac_analytics[building_id] ),
        VAR _bid  = gold_hvac_analytics[building_id]
        VAR _sys  =
            CALCULATE ( MAX ( gold_hvac_analytics[system_type] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid ) )
        VAR _is1  = _sys = "gas_boiler" || _sys = "hybrid" || _sys = "biomass"
        VAR _hkwh =
            CALCULATE ( SUM ( gold_hvac_analytics[heating_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid ) )
        VAR _ckwh =
            CALCULATE ( SUM ( gold_hvac_analytics[cooling_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid ) )
        VAR _vkwh =
            CALCULATE ( SUM ( gold_hvac_analytics[ventilation_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid ) )
        RETURN
            IF ( _is1, COALESCE(_hkwh,0)*_gasF, COALESCE(_hkwh,0)*_elecF )
            + COALESCE(_ckwh,0)*_elecF
            + COALESCE(_vkwh,0)*_elecF
    )
VAR _s1_pct = ROUND ( DIVIDE ( _s1_kg, _total_kg ) * 100, 0 )
RETURN
    IF ( ISBLANK ( _total_kg ), "Veri yok",
         "Scope 1: " & FORMAT ( _s1_pct, "0" ) & "%  |  " &
         "Scope 2: " & FORMAT ( 100 - _s1_pct, "0" ) & "%" )


// ==========================================================================
// C7) GAS EXPOSURE % — YENİ (CSRD / EU Taxonomi risk göstergesi)
// ==========================================================================
// SOL ALT — 7. kart

Card: Gas Exposure v40 =
// Portföyde fosil ısıtmaya bağımlı bina oranı
// CSRD/SFDR: %100 fossil = yüksek transition risk
VAR _gas_cnt =
    CALCULATE (
        DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
        gold_hvac_analytics[system_type] IN { "gas_boiler", "hybrid", "biomass" }
    )
VAR _total = DISTINCTCOUNT ( gold_hvac_analytics[building_id] )
VAR _pct   = DIVIDE ( _gas_cnt, _total ) * 100
RETURN
    IF ( ISBLANK ( _pct ), "—", FORMAT ( ROUND ( _pct, 0 ), "0" ) & "%" )
// Beklenen portföy (B001=HP, B004=district, B006=VRF): 50% (B002/B003/B005 gas)
// EU 2030 hedefi: Sıfır yeni gaz bağlantısı

Card: Gas Exposure Label v40 =
VAR _gas_cnt =
    CALCULATE (
        DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
        gold_hvac_analytics[system_type] IN { "gas_boiler", "hybrid", "biomass" }
    )
VAR _total = DISTINCTCOUNT ( gold_hvac_analytics[building_id] )
VAR _pct   = DIVIDE ( _gas_cnt, _total ) * 100
VAR _label =
    SWITCH ( TRUE (),
        _pct >= 80, "🔴 Kritik — Yüksek Transition Riski",
        _pct >= 50, "🟠 Yüksek — CSRD Açıklama Gerekli",
        _pct >= 25, "🟡 Orta — Geçiş Planı Önerilir",
                    "🟢 Düşük Fosil Bağımlılığı"
    )
RETURN IF ( ISBLANK ( _pct ), "Veri yok", _label )


// ==========================================================================
// C8) EPC COMPLIANCE — YENİ (EU EPBD 2024 EPC B target)
// ==========================================================================
// SOL ALT — 8. kart

Card: EPC Compliance v40 =
// EPC B = insulation_score ≥ 65 AND heat_loss_kwh_m2 ≤ 90
// EU EPBD 2024: 2030'dan itibaren ticari binalar EPC E veya üzeri zorunlu
VAR _compliant =
    CALCULATE (
        DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
        gold_hvac_analytics[insulation_score]  >= 65,
        gold_hvac_analytics[heat_loss_kwh_m2]  <= 90
    )
VAR _total = DISTINCTCOUNT ( gold_hvac_analytics[building_id] )
VAR _pct   = DIVIDE ( _compliant, _total ) * 100
RETURN
    IF ( ISBLANK ( _pct ), "—",
         FORMAT ( _compliant, "0" ) & " / " & FORMAT ( _total, "0" ) & " bina" )

Card: EPC Label v40 =
VAR _compliant =
    CALCULATE (
        DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
        gold_hvac_analytics[insulation_score]  >= 65,
        gold_hvac_analytics[heat_loss_kwh_m2]  <= 90
    )
VAR _total = DISTINCTCOUNT ( gold_hvac_analytics[building_id] )
VAR _pct   = ROUND ( DIVIDE ( _compliant, _total ) * 100, 0 )
VAR _label =
    SWITCH ( TRUE (),
        _pct >= 80, "🟢 EPC D+ Uyumlu",
        _pct >= 50, "🟡 Kısmi Uyum — EPBD 2030 Riski",
                    "🔴 Çoğunluk EPC E/F/G — Acil Eylem"
    )
RETURN IF ( ISBLANK ( _pct ), "Veri yok", _label & "  (EPBD 2024 hedef: EPC E+)" )


// ==========================================================================
// C9) ANNUAL HEAT LOSS TOTAL — YENİ (mutlak enerji kayıp miktarı)
// ==========================================================================
// SOL ALT — 9. kart (isteğe göre)

Card: Total Heat Loss MWh v40 =
// Portföy genelinde yıllık ısı kayıp hacmi (MWh)
// Bu değer yalıtım yatırımının potansiyel tasarrufunu gösterir
VAR _kwh_m2  = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
VAR _area_m2 =
    CALCULATE (
        SUM ( silver_building_master[conditioned_area_m2] ),
        ALLEXCEPT ( silver_building_master, silver_building_master[building_id] )
    )
VAR _total_kwh = _kwh_m2 * _area_m2
VAR _mwh       = DIVIDE ( _total_kwh, 1000 )
RETURN
    IF ( ISBLANK ( _mwh ), "—", FORMAT ( ROUND ( _mwh, 0 ), "#,0" ) & " MWh/yr" )

Card: Heat Loss MWh Label v40 =
VAR _kwh_m2  = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
VAR _area_m2 =
    CALCULATE (
        SUM ( silver_building_master[conditioned_area_m2] ),
        ALLEXCEPT ( silver_building_master, silver_building_master[building_id] )
    )
VAR _total_kwh = _kwh_m2 * _area_m2
VAR _eur = _total_kwh * 0.18    -- Avrupa ortalama ısı maliyeti €/kWh
RETURN
    IF ( ISBLANK ( _eur ), "Veri yok",
         "~€" & FORMAT ( ROUND ( _eur / 1000, 0 ), "#,0" ) & "K yıllık maliyet" )


// ==========================================================================
// VİZÜEL DESTEK — V1 için referans çizgisi ölçüleri
// ==========================================================================

Ref: HVAC Heating Target kWh =
// V1 (HVAC Breakdown bar chart) → Analytics bölmesi → Constant Line
// Ortalama ısıtma enerjisi — hedef = iyi yalıtımlı binanın beklentisi
// Config: Analytics → Y-Axis Constant Line → bu ölçüyü kullan
VAR _area_m2 =
    CALCULATE (
        AVERAGE ( silver_building_master[conditioned_area_m2] ),
        ALLEXCEPT ( silver_building_master, silver_building_master[building_id] )
    )
RETURN _area_m2 * 40 / 12   -- 40 kWh/m²·yr ÷ 12 ay = aylık hedef
// NZEB hedef: 40 kWh/m²·yr ısıtma (Pasif Haus = ~15)

Ref: Avg Efficiency Benchmark =
// V5 (Renovation Priority scatter) için benchmark ekseni çizgisi
// HVAC Efficiency Score 60 = EPBD D sınırı
RETURN 60

// ==========================================================================
// VİZÜEL DESTEK — V2 tablo için ek kolon (Scope badge)
// ==========================================================================

Scope Badge v40 =
// V2 tablosunda "Scope 1/2" kolonu olarak kullan
VAR _bid = MAX ( silver_building_master[building_id] )
VAR _sys =
    CALCULATE (
        MAX ( gold_hvac_analytics[system_type] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
RETURN
    SWITCH ( _sys,
        "gas_boiler", "🔴 Scope 1",
        "hybrid",     "🟡 S1+S2",
        "biomass",    "🟠 Scope 1",
        "heat_pump",  "🟢 Scope 2",
        "gshp",       "🟢 Scope 2",
        "vrf",        "🟢 Scope 2",
        "district",   "🔵 Scope 3",
        "electric",   "🟢 Scope 2",
        "—"
    )


// ==========================================================================
// HIZLI UYGULAMA REHBERİ — v40
// ==========================================================================
//
// ── YENİ KARTLAR (New Card görseli kullan, CLASSIC CARD değil) ──────────
//
// C1  HVAC Share %
//     Callout:   Card: HVAC Share v40
//     Reference: Card: HVAC Share Label v40
//
// C2  Avg COP / SCOP  ← YENİ
//     Callout:   Card: Avg COP v40
//     Reference: Card: COP Label v40
//     (Tek bina seçildiğinde cop_actual gösterir, portföyde ortalama)
//
// C3  Insulation Score
//     Callout:   Card: Avg Insulation v40
//     Reference: Card: Insulation Label v40
//
// C4  Heat Loss
//     Callout:   Card: Heat Loss v40
//     Reference: Card: Heat Loss Label v40
//
// C5  Buildings for Retrofit
//     Callout:   Card: Buildings For Retrofit v40
//     Reference: Card: Retrofit Label v40
//
// C6  HVAC CO₂
//     Callout:   Card: HVAC CO2 v40
//     Reference: Card: CO2 Label v40   ← Scope 1 / Scope 2 ayrımı
//
// ── SOL ALT EKSTRA KARTLAR ──────────────────────────────────────────────
//
// C7  Gas Exposure %  ← YENİ (CSRD risk)
//     Callout:   Card: Gas Exposure v40
//     Reference: Card: Gas Exposure Label v40
//     Kart rengi: >50% → kırmızı arka plan, <25% → yeşil
//
// C8  EPC Compliance  ← YENİ
//     Callout:   Card: EPC Compliance v40
//     Reference: Card: EPC Label v40
//
// ── V2 TABLOSU — YENİ KOLON ────────────────────────────────────────────
//     Scope Badge v40 kolonu ekle: "Scope 1/2" başlığıyla
//     Pozisyon: COP Display v39 kolonundan sonra
//
// ── V1 CHART — REFERANS ÇİZGİSİ ───────────────────────────────────────
//     V1 seç → Analytics bölmesi (Σ simgesi) →
//     "Y-axis constant line" → Value: Ref: HVAC Heating Target kWh
//     Label: "NZEB Hedef"  |  Color: #1D9E75  |  Dash style: Dashed
//
// ── V5 SCATTER — REFERANS ÇİZGİLERİ ──────────────────────────────────
//     X-axis ref line: 60 (insulation threshold)  → Label: "EPC D Sınırı"
//     Y-axis ref line: 90 (heat loss threshold)   → Label: "NZEB Limiti"
//     Ref çizgileri kırmızı noktalı olarak ayarla
//
// ── NEW CARD GÖRSEL AYARLARI (her kart için) ──────────────────────────
//     Format → Callout value → Font size: 28  Bold: ON
//     Format → Reference label → Font size: 10  Color: #aaaaaa
//     Format → Spacing → Padding: 12px
//     Format → Background → Color: transparent
//     Format → Border → OFF
//
// ==========================================================================
