// ==========================================================================
// DAX v41 — PAGE 7 HVAC & Building Envelope — BUG FIXES + VISUAL ENHANCEMENTS
// Energy Copilot Platform — 2026-05-05
//
// v40'dan fark:
//   (1) heat_loss_kwh_m2 × 12 düzeltmesi (monthly → annual)
//   (2) EPC Compliance eşiği güncellendi (7.5 monthly = 90 annual)
//   (3) V3 yeni görsel: CO₂ by Building — Scope 1 vs Scope 2 stacked bar
//   (4) V4 yeni görsel: Annual Heat Loss by Building bar + EPC class label
//   (5) Insulation Score düzeltmesi — tek bina seçimde filtre bypass
//
// UYGULAMA SIRASI:
//   1. Bu ölçüleri import et
//   2. V40 ölçülerini override eden aynı ada sahip ölçüleri sil (veya v41 kullan)
//   3. V3/V4 görsel yapısını değiştir (rehbere bak: page7-v41-guide.md)
// ==========================================================================


// ==========================================================================
// FIX 1 — HEAT LOSS kWh/m²·YR (MONTHLY → ANNUAL ×12)
// ==========================================================================
// Sorun: gold_hvac_analytics[heat_loss_kwh_m2] AYLIK ortalama değer (~4–5)
// Gerçek yıllık = ×12 (~48–60 kWh/m²·yr — EPC C/D aralığı ✓)

Card: Heat Loss v41 =
VAR _hl_monthly = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
VAR _hl_annual  = _hl_monthly * 12
RETURN
    IF ( ISBLANK ( _hl_monthly ), "—", FORMAT ( ROUND ( _hl_annual, 0 ), "0" ) & " kWh/m²·yr" )
// Beklenen aralık: 30–150 kWh/m²·yr
// Berliner (HP + iyi yalıtım) → ~35–50  |  Frankfurt (gas, kötü) → ~90–140

Card: Heat Loss Label v41 =
VAR _hl_monthly = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
VAR _hl = _hl_monthly * 12   -- Yıllıklaştır
VAR _label =
    SWITCH ( TRUE (),
        ISBLANK ( _hl ),  "Veri yok",
        _hl <= 30,        "🟢 Pasif Haus Seviyesi (<30 kWh/m²·yr)",
        _hl <= 55,        "🟢 EPC A — NZEB Uyumlu",
        _hl <= 90,        "🟡 EPC B/C — AB Ortalaması",
        _hl <= 150,       "🟠 EPC D/E — Yüksek Kayıp",
                          "🔴 EPC F/G — Kritik Kayıp (>150)"
    )
RETURN _label
// Reference label → New Card

Card: Total Heat Loss MWh v41 =
// Portföy genelinde yıllık toplam ısı kayıp hacmi (MWh)
VAR _hl_monthly = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
VAR _hl_annual  = _hl_monthly * 12
VAR _area_m2 =
    SUMX (
        VALUES ( silver_building_master[building_id] ),
        CALCULATE ( MAX ( silver_building_master[conditioned_area_m2] ) )
    )
VAR _total_kwh = _hl_annual * _area_m2
VAR _mwh       = DIVIDE ( _total_kwh, 1000 )
RETURN
    IF ( ISBLANK ( _mwh ), "—", FORMAT ( ROUND ( _mwh, 0 ), "#,0" ) & " MWh/yr" )

Card: Heat Loss MWh Label v41 =
VAR _hl_monthly = AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] )
VAR _hl_annual  = _hl_monthly * 12
VAR _area_m2 =
    SUMX (
        VALUES ( silver_building_master[building_id] ),
        CALCULATE ( MAX ( silver_building_master[conditioned_area_m2] ) )
    )
VAR _total_kwh = _hl_annual * _area_m2
VAR _eur = _total_kwh * 0.18
RETURN
    IF ( ISBLANK ( _eur ), "Veri yok",
         "~€" & FORMAT ( ROUND ( _eur / 1000, 0 ), "#,0" ) & "K yıllık ısıtma maliyeti" )


// ==========================================================================
// FIX 2 — EPC COMPLIANCE eşiği güncellendi (×12 düzeltmesine göre)
// ==========================================================================
// Eski: heat_loss_kwh_m2 <= 90  (yanlış — bu monthly değerde imkansız bir hedef)
// Yeni: heat_loss_kwh_m2 <= 7.5 (= 90 kWh/m²·yr ÷ 12)

Card: EPC Compliance v41 =
// EPC B eşiği: insulation ≥ 65 VE yıllık heat loss ≤ 90 kWh/m²·yr
// gold_hvac_analytics[heat_loss_kwh_m2] AYLIK olduğundan ÷12 eşik kullanıyoruz
VAR _compliant =
    CALCULATE (
        DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
        gold_hvac_analytics[insulation_score]  >= 65,
        gold_hvac_analytics[heat_loss_kwh_m2]  <= 7.5   -- 7.5 × 12 = 90 kWh/m²·yr
    )
VAR _total = DISTINCTCOUNT ( gold_hvac_analytics[building_id] )
RETURN
    IF ( ISBLANK ( _total ), "—",
         FORMAT ( COALESCE ( _compliant, 0 ), "0" ) & " / " &
         FORMAT ( _total, "0" ) & " bina EPC D+" )

Card: EPC Label v41 =
VAR _compliant =
    CALCULATE (
        DISTINCTCOUNT ( gold_hvac_analytics[building_id] ),
        gold_hvac_analytics[insulation_score]  >= 65,
        gold_hvac_analytics[heat_loss_kwh_m2]  <= 7.5
    )
VAR _total = DISTINCTCOUNT ( gold_hvac_analytics[building_id] )
VAR _pct   = ROUND ( DIVIDE ( COALESCE ( _compliant, 0 ), _total ) * 100, 0 )
VAR _label =
    SWITCH ( TRUE (),
        _pct >= 80, "🟢 Portföy EPC D+ Uyumlu",
        _pct >= 50, "🟡 Kısmi Uyum — EPBD 2030 Riski Var",
                    "🔴 Çoğunluk EPC E/F/G — Acil Eylem Gerekli"
    )
RETURN
    IF ( ISBLANK ( _total ), "Veri yok",
         _label & "  (EPBD 2024: 2030'dan itibaren EPC E+ zorunlu)" )


// ==========================================================================
// FIX 3 — INSULATION SCORE filtre bypass (tek bina seçimde boş göstermeme)
// ==========================================================================

Card: Avg Insulation v41 =
// ALLSELECTED ile slicer context'ini koru ama boş dönmeyi engelle
VAR _score =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[insulation_score] ),
        ALLSELECTED ( gold_hvac_analytics )
    )
RETURN
    IF ( ISBLANK ( _score ), "—", FORMAT ( ROUND ( _score, 0 ), "0" ) & " / 100" )

Card: Insulation Label v41 =
VAR _score =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[insulation_score] ),
        ALLSELECTED ( gold_hvac_analytics )
    )
VAR _label =
    SWITCH ( TRUE (),
        ISBLANK ( _score ),  "Veri yok",
        _score >= 80,        "🟢 EPC A/B — NZEB Hazır",
        _score >= 65,        "🟡 EPC C — İyileştirme Önerilir",
        _score >= 50,        "🟠 EPC D — GEG Limit Altı",
        _score >= 35,        "🔴 EPC E/F — Zorunlu Retrofit",
                             "🔴 EPC G — Acil Eylem"
    )
RETURN _label


// ==========================================================================
// V3 YENİ GÖRSEL — CO₂ by Building: Scope 1 vs Scope 2 stacked bar
// ==========================================================================
// Eski V3: Envelope U-Values (pasif bilgi, düşük aksiyon değeri)
// Yeni V3: Her binanın HVAC CO₂ emisyonu — fosil vs elektrik ayrımı
//          → CSRD transition risk'i görsel olarak anlatır
//
// GÖRSELİ NASIL OLUŞTURURSUN:
//   Görsel tipi: Stacked bar chart (yatay önerilir)
//   Y ekseni:    silver_building_master[building_name]
//   X (serileri): V3: CO2 Scope1 kgCO2 v41  + V3: CO2 Scope2 kgCO2 v41
//   Renk:        Scope 1 → #E84040 (kırmızı)  |  Scope 2 → #1D9E75 (yeşil)
//   Tooltip:     Scope Badge v40 ekle
//   Başlık:      "HVAC CO₂ Emisyonu — Scope 1 (Fosil) vs Scope 2 (Elektrik)"

V3: CO2 Scope1 kgCO2 v41 =
// Fosil kaynaklı HVAC CO₂ — gas_boiler/hybrid/biomass binaların ISITMA emisyonu
// Scope 1: Yakma kaynaklı, direkt bina sorumluluğu (CSRD mandatory disclosure)
VAR _gasF = 0.2017   -- kg CO₂/kWh gaz (BAFA/IPCC 2024, Almanya ortalama)
RETURN
    SUMX (
        VALUES ( gold_hvac_analytics[building_id] ),
        VAR _bid = gold_hvac_analytics[building_id]
        VAR _sys =
            CALCULATE (
                MAX ( gold_hvac_analytics[system_type] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _isScope1 = _sys = "gas_boiler" || _sys = "hybrid" || _sys = "biomass"
        VAR _hkwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[heating_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        RETURN
            IF ( _isScope1, COALESCE ( _hkwh, 0 ) * _gasF, 0 )
    )
// Beklenen: B002 Hamburg (gas) → büyük kırmızı bar  |  B001 Berliner (HP) → 0

V3: CO2 Scope2 kgCO2 v41 =
// Elektrik kaynaklı HVAC CO₂ — tüm sistemlerin soğutma + havalandırma
// + heat_pump/vrf/district/gshp binaların ısıtma elektrik tüketimi
// Scope 2: Satın alınan elektrik emisyonu (location-based)
VAR _elecF = 0.350   -- kg CO₂e/kWh EU ort. (EEA 2024; building-specific için silver[emission_factor] kullanılabilir)
RETURN
    SUMX (
        VALUES ( gold_hvac_analytics[building_id] ),
        VAR _bid = gold_hvac_analytics[building_id]
        VAR _sys =
            CALCULATE (
                MAX ( gold_hvac_analytics[system_type] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _isScope1 = _sys = "gas_boiler" || _sys = "hybrid" || _sys = "biomass"
        VAR _hkwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[heating_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _ckwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[cooling_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _vkwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[ventilation_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _heat_scope2 = IF ( NOT _isScope1, COALESCE ( _hkwh, 0 ) * _elecF, 0 )
        VAR _cool_scope2 = COALESCE ( _ckwh, 0 ) * _elecF
        VAR _vent_scope2 = COALESCE ( _vkwh, 0 ) * _elecF
        RETURN _heat_scope2 + _cool_scope2 + _vent_scope2
    )
// Beklenen: B001 Berliner (HP) → sadece yeşil bar  |  B006 VRF → sadece yeşil

V3: CO2 Total tCO2 v41 =
// Tooltip veya ikincil gösterge — toplam tCO₂ (Scope 1+2)
VAR _s1 = [V3: CO2 Scope1 kgCO2 v41]
VAR _s2 = [V3: CO2 Scope2 kgCO2 v41]
RETURN
    IF (
        ISBLANK ( _s1 ) && ISBLANK ( _s2 ),
        BLANK (),
        DIVIDE ( COALESCE ( _s1, 0 ) + COALESCE ( _s2, 0 ), 1000 )
    )
// Format: 0.0 "tCO₂"

V3: HP Transition Saving kgCO2 v41 =
// "Eğer tüm gaz binalar heat pump'a geçseydi ne kadar CO₂ tasarruf edilirdi?"
// CSRD Transition Plan için güçlü aksiyon metriği
VAR _gasF  = 0.2017
VAR _elecF = 0.350
VAR _cop   = 3.5    -- Ortalama HP SCOP (muhafazakar)
RETURN
    SUMX (
        VALUES ( gold_hvac_analytics[building_id] ),
        VAR _bid = gold_hvac_analytics[building_id]
        VAR _sys =
            CALCULATE (
                MAX ( gold_hvac_analytics[system_type] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        VAR _isGas = _sys = "gas_boiler" || _sys = "hybrid"
        VAR _hkwh =
            CALCULATE (
                SUM ( gold_hvac_analytics[heating_energy_kwh] ),
                FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
            )
        -- Şu anki gaz CO₂ vs HP'ye geçince scope 2 CO₂
        VAR _current_kg  = IF ( _isGas, COALESCE ( _hkwh, 0 ) * _gasF, 0 )
        VAR _hp_kwh      = COALESCE ( _hkwh, 0 ) / _cop   -- HP için elektrik tüketimi
        VAR _hp_kg       = IF ( _isGas, _hp_kwh * _elecF, 0 )
        RETURN _current_kg - _hp_kg
    )
// Pozitif değer = tasarruf.  Beklenen: portföy geneli 10–40 tCO₂/yr


// ==========================================================================
// V4 YENİ GÖRSEL — Annual Heat Loss by Building (kWh/m²·yr) bar chart
// ==========================================================================
// Eski V4: Insulation Score by Building (sadece skor, context yok)
// Yeni V4: Her binanın yıllık ısı kayıp yoğunluğu + EPC sınıf etiketi
//          → Hangi binaya önce yatırım yapılacağını direkt gösterir
//
// GÖRSELİ NASIL OLUŞTURURSUN:
//   Görsel tipi: Clustered bar chart
//   Y ekseni:    silver_building_master[building_name]
//   X değeri:    V4: Heat Loss Annual kWh m2 v41  (sayısal)
//   Renk lejandı (data colors): Manuel renk ata (kırmızı=yüksek, yeşil=düşük)
//   Analytics → X-axis constant line:
//     - 90 kWh/m²·yr  "EPBD/GEG Sınırı"   (kırmızı noktalı)
//     - 55 kWh/m²·yr  "EPC A Hedef"        (yeşil noktalı)
//   Başlık: "Yıllık Isı Kayıp Yoğunluğu (kWh/m²·yr)"
//   Tooltip'e: V4: EPC Class Label v41 ekle

V4: Heat Loss Annual kWh m2 v41 =
// Bina başına yıllık ısı kayıp yoğunluğu
// gold_hvac_analytics[heat_loss_kwh_m2] monthly ortalama → ×12
VAR _bid = MAX ( silver_building_master[building_id] )
VAR _hl_monthly =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
RETURN
    IF ( ISBLANK ( _hl_monthly ), BLANK (), ROUND ( _hl_monthly * 12, 1 ) )
// Format: 0.0 "kWh/m²·yr"
// Beklenen: Berliner (B001) → ~40–55  |  Frankfurt (B005) → ~100–140

V4: EPC Class Label v41 =
// Her bina için EPC sınıfı — V4 tooltipte veya ikincil tablo kolonunda kullan
VAR _bid = MAX ( silver_building_master[building_id] )
VAR _hl_monthly =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
VAR _hl = _hl_monthly * 12
VAR _ins =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[insulation_score] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
// EPC sınıfı: heat loss + insulation kombinasyonu
VAR _epc =
    SWITCH ( TRUE (),
        ISBLANK ( _hl ),           "—",
        _hl <= 30 && _ins >= 80,   "A+",
        _hl <= 50 && _ins >= 70,   "A",
        _hl <= 70 && _ins >= 60,   "B",
        _hl <= 90 && _ins >= 50,   "C",
        _hl <= 120 && _ins >= 40,  "D",
        _hl <= 160 && _ins >= 30,  "E",
        _hl <= 200,                "F",
                                   "G"
    )
RETURN _epc
// Tooltip veya tablo kolonunda göster

V4: Insulation Score by Bldg v41 =
// V4 görselinde ikincil eksen veya tooltip için insulation score
VAR _bid = MAX ( silver_building_master[building_id] )
RETURN
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[insulation_score] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
// Format: 0 "puan"

V4: Retrofit Urgency Score v41 =
// Yenileme aciliyeti skoru (0–100, yüksek = acil)
// heat_loss yüksek + insulation düşük + gaz sistem = en yüksek skor
VAR _bid = MAX ( silver_building_master[building_id] )
VAR _hl_monthly =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[heat_loss_kwh_m2] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
VAR _hl       = COALESCE ( _hl_monthly * 12, 0 )
VAR _ins      =
    CALCULATE (
        AVERAGE ( gold_hvac_analytics[insulation_score] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
VAR _ins_s    = COALESCE ( _ins, 50 )
VAR _sys =
    CALCULATE (
        MAX ( gold_hvac_analytics[system_type] ),
        FILTER ( gold_hvac_analytics, gold_hvac_analytics[building_id] = _bid )
    )
VAR _gas_penalty = IF ( _sys = "gas_boiler" || _sys = "hybrid", 20, 0 )
// Normalise: heat loss 0–200 → 0–50, insulation 100→0 – 0→50, gas penalty 0/20
VAR _hl_score  = MIN ( DIVIDE ( _hl, 200 ) * 50, 50 )
VAR _ins_score = MIN ( DIVIDE ( 100 - _ins_s, 100 ) * 30, 30 )
RETURN ROUND ( _hl_score + _ins_score + _gas_penalty, 0 )
// Format: 0 (conditional formatting: 0–33 yeşil, 34–66 sarı, 67–100 kırmızı)
// Beklenen: Frankfurt (B005, gas+kötü yalıtım) → 70–90  |  Berliner → 20–35


// ==========================================================================
// HIZLI UYGULAMA REHBERİ — v41
// ==========================================================================
//
// ── FIX 1: HEAT LOSS KARTLARI (C4) ─────────────────────────────────────
//   Power BI'da eski ölçüyü kaldır:   Card: Heat Loss v40
//   Yeni ölçüyü Callout'a ekle:       Card: Heat Loss v41
//   Yeni label'ı Reference label'a:   Card: Heat Loss Label v41
//   (Beklenen değer aralığı: 30–150 kWh/m²·yr)
//
// ── FIX 2: EPC COMPLIANCE KARTI (C8) ────────────────────────────────────
//   Eski: Card: EPC Compliance v40  → Yeni: Card: EPC Compliance v41
//   Eski: Card: EPC Label v40       → Yeni: Card: EPC Label v41
//
// ── FIX 3: INSULATION KARTI (C3) ────────────────────────────────────────
//   Eski: Card: Avg Insulation v40   → Yeni: Card: Avg Insulation v41
//   Eski: Card: Insulation Label v40 → Yeni: Card: Insulation Label v41
//   (ALLSELECTED ile tek bina seçimde boş dönmeme sorunu düzeltildi)
//
// ── V3 YENİ GÖRSEL OLUŞTURMA ────────────────────────────────────────────
//   1. Mevcut "Envelope U-Values" görselini sil (veya gizle)
//   2. Yeni Stacked Bar chart ekle (aynı konuma)
//   3. Y ekseni:    silver_building_master[building_name]
//   4. Seri 1:      V3: CO2 Scope1 kgCO2 v41   — renk: #E84040
//   5. Seri 2:      V3: CO2 Scope2 kgCO2 v41   — renk: #1D9E75
//   6. Tooltip'e:   Scope Badge v40 ekle
//   7. Format → Data labels → ON (unit: otomatik kgCO₂ → auto)
//   8. Başlık: "HVAC CO₂ Emisyonu — Scope 1 (Fosil) vs Scope 2 (Elektrik)"
//   NOT: Building slicer'ın bu görsele "Filter" interaction kurması OK
//        S2 (tarih) slicer → edit interactions → bu görsele None
//
// ── V4 YENİ GÖRSEL OLUŞTURMA ────────────────────────────────────────────
//   1. Mevcut "Insulation by Building" görselini sil (veya gizle)
//   2. Yeni Clustered Bar chart ekle
//   3. Y ekseni:    silver_building_master[building_name]
//   4. X değeri:    V4: Heat Loss Annual kWh m2 v41
//   5. Tooltip:     V4: EPC Class Label v41  +  V4: Insulation Score by Bldg v41
//   6. Analytics bölmesi → X-axis constant line:
//        Değer 1: 90   Label: "GEG/EPBD Sınırı"   Renk: #E84040  Style: Dashed
//        Değer 2: 55   Label: "EPC A Hedefi"       Renk: #1D9E75  Style: Dotted
//   7. Başlık: "Yıllık Isı Kayıp Yoğunluğu (kWh/m²·yr)"
//   NOT: Çubuğu kırmızıdan yeşile data rengine göre yap:
//        ≤55 → yeşil (#1D9E75)  |  55–90 → sarı (#F2A93B)  |  >90 → kırmızı (#E84040)
//        Power BI'da: Data colors → Conditional formatting → Rules
//
// ── NEW CARD — LABEL NASIL GÖRÜNMELİ (BÜTÜN KARTLAR) ───────────────────
//   Sorun: Label ölçüleri eklenmiş ama görünmüyor
//   Çözüm: Format bölmesi → "Callout value" alanına ana ölçüyü AT
//           Görsel Fields bölmesinde "Reference label" alanına _Label ölçüsünü AT
//   ÖNEMLİ: "Values" veya "Fields" alanına değil, "Reference label" alanına
//   Doğrulama: Format → Reference label → Font size: 10 → metin göründüğünde OK
//   Eğer Reference label alanı yoksa: Görsel tipini "Card (new)" ile değiştir
//        (Visualizations → "..." → Search → "Card (new)")
//
// ==========================================================================
