// =============================================================================
// DAX v45 — Cross-Page IoT Enrichment (Pages 2 and 7)
// Energy Copilot Platform
// Updated: 2026-05-08 — corrected to use only actual tables in semantic model
//
// TABLES USED (confirmed in Data pane):
//   iot_hot_readings   — KQL shortcut (live stream)
//                        Columns: anomaly_severity, anomaly_type, building_id,
//                        device_id, is_anomaly, reading_quality, reading_unit,
//                        reading_value, sensor_location, sensor_type,
//                        source_protocol, timestamp
//   iot_anomaly_alerts — KQL shortcut (alert events)
//                        Columns: alert_time, anomaly_severity, anomaly_type,
//                        building_id, device_id, is_resolved, reading_quality,
//                        reading_unit, reading_value, resolved_time,
//                        sensor_location, sensor_type, source_protocol
//
// RELATIONSHIP REQUIRED (Model view):
//   iot_hot_readings[building_id]   → silver_building_master[building_id]  Many:1
//   iot_anomaly_alerts[building_id] → silver_building_master[building_id]  Many:1
//
// HOME TABLE: iot_hot_readings
//
// DATE SLICER: All measures use REMOVEFILTERS('Date') — IoT is always live.
//              Building slicer (silver_building_master) IS respected.
// =============================================================================


// ─────────────────────────────────────────────────────────────────────────────
// UTILITY — applies to all pages
// ─────────────────────────────────────────────────────────────────────────────

IoT_Building_Has_Sensors =
// TRUE if selected building has any IoT readings.
// Use for conditional card visibility: filter card visual by this measure = TRUE.
VAR RowCount =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        REMOVEFILTERS('Date')
    )
RETURN
    IF(ISBLANK(RowCount) || RowCount = 0, FALSE(), TRUE())

IoT_Last_Reading_Age_Min =
// Minutes since the last IoT reading was received.
// Shows data freshness — use as tooltip on live cards.
VAR LatestTS =
    CALCULATE(
        MAX(iot_hot_readings[timestamp]),
        REMOVEFILTERS('Date')
    )
RETURN
    IF(
        ISBLANK(LatestTS),
        BLANK(),
        DATEDIFF(LatestTS, NOW(), MINUTE)
    )

IoT_Last_Reading_Age_Label =
VAR Age = [IoT_Last_Reading_Age_Min]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(Age),  "No data",
        Age <= 1,      "Live — just now",
        Age <= 15,     "Updated " & FORMAT(Age, "0") & " min ago",
        Age <= 60,     FORMAT(Age, "0") & " min ago",
        Age <= 1440,   FORMAT(INT(Age / 60), "0") & "h ago",
        "Data may be stale"
    )


// ─────────────────────────────────────────────────────────────────────────────
// PAGE 2 — Building Energy Overview
// Adds real-time kW context alongside historical daily kWh cards
// ─────────────────────────────────────────────────────────────────────────────

IoT_Building_kW_Now =
// Latest building_kwh reading — instantaneous total power demand
VAR LatestTS =
    CALCULATE(
        MAX(iot_hot_readings[timestamp]),
        iot_hot_readings[sensor_type] = "building_kwh",
        REMOVEFILTERS('Date')
    )
RETURN
    CALCULATE(
        AVERAGE(iot_hot_readings[reading_value]),
        iot_hot_readings[sensor_type] = "building_kwh",
        iot_hot_readings[timestamp] = LatestTS,
        REMOVEFILTERS('Date')
    )

IoT_Building_kW_Baseline =
// Average of non-anomaly building_kwh readings — used as reference for color coding.
// Timestamp filter removed so baseline is constant regardless of current time context.
CALCULATE(
    AVERAGE(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "building_kwh",
    iot_hot_readings[is_anomaly] = FALSE(),
    REMOVEFILTERS(iot_hot_readings[timestamp]),
    REMOVEFILTERS('Date')
)

IoT_Building_kW_Display =
VAR kW    = [IoT_Building_kW_Now]
VAR Base  = [IoT_Building_kW_Baseline]
VAR Ratio = DIVIDE(kW, Base, 1)
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(kW),   "-- kW",
        Ratio > 1.2,   FORMAT(kW, "0.0") & " kW ▲ High",
        Ratio > 1.0,   FORMAT(kW, "0.0") & " kW ~ Above normal",
        FORMAT(kW, "0.0") & " kW ✓ Normal"
    )

IoT_Building_kW_Color =
VAR kW    = [IoT_Building_kW_Now]
VAR Base  = [IoT_Building_kW_Baseline]
VAR Ratio = DIVIDE(kW, Base, 1)
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(kW),  "#AAAAAA",
        Ratio > 1.2,  "#FF4136",
        Ratio > 1.0,  "#FF851B",
        "#2ECC40"
    )


// ─────────────────────────────────────────────────────────────────────────────

IoT_HVAC_kW_Now =
// Latest hvac_kwh reading — HVAC-only power demand
VAR LatestTS =
    CALCULATE(
        MAX(iot_hot_readings[timestamp]),
        iot_hot_readings[sensor_type] = "hvac_kwh",
        REMOVEFILTERS('Date')
    )
RETURN
    CALCULATE(
        AVERAGE(iot_hot_readings[reading_value]),
        iot_hot_readings[sensor_type] = "hvac_kwh",
        iot_hot_readings[timestamp] = LatestTS,
        REMOVEFILTERS('Date')
    )

IoT_HVAC_Share_Of_Building_Pct =
// HVAC load as % of total building load (instantaneous)
VAR HVACkW     = [IoT_HVAC_kW_Now]
VAR BuildingkW = [IoT_Building_kW_Now]
RETURN
    DIVIDE(HVACkW, BuildingkW, BLANK()) * 100

IoT_HVAC_kW_Display =
VAR kW    = [IoT_HVAC_kW_Now]
VAR Share = [IoT_HVAC_Share_Of_Building_Pct]
RETURN
    IF(
        ISBLANK(kW),
        "-- kW",
        FORMAT(kW, "0.0") & " kW — " & FORMAT(ROUND(Share, 0), "0") & "% of total"
    )

IoT_HVAC_kW_Color =
// Red if HVAC >60% of building load (overconsumption)
VAR Share = [IoT_HVAC_Share_Of_Building_Pct]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(Share), "#AAAAAA",
        Share > 60,     "#FF4136",
        Share > 45,     "#FF851B",
        "#2ECC40"
    )


// ─────────────────────────────────────────────────────────────────────────────
// PAGE 7 — HVAC Analysis
// Adds live sensor data alongside historical HVAC efficiency charts
// ─────────────────────────────────────────────────────────────────────────────

// P7-C1: Supply/Return Delta-T
// Delta-T = |supply_temp − return_temp|
// Optimal: 8–15°C (EN 14825 / EN 15316)
// Low (<5°C): coil fouling or pump underperformance
// High (>20°C): low flow rate risk

IoT_Supply_Temp_Live =
VAR LatestTS =
    CALCULATE(
        MAX(iot_hot_readings[timestamp]),
        iot_hot_readings[sensor_type] = "HVAC_supply_temp",
        REMOVEFILTERS('Date')
    )
RETURN
    CALCULATE(
        AVERAGE(iot_hot_readings[reading_value]),
        iot_hot_readings[sensor_type] = "HVAC_supply_temp",
        iot_hot_readings[timestamp] = LatestTS,
        REMOVEFILTERS('Date')
    )

IoT_Return_Temp_Live =
VAR LatestTS =
    CALCULATE(
        MAX(iot_hot_readings[timestamp]),
        iot_hot_readings[sensor_type] = "HVAC_return_temp",
        REMOVEFILTERS('Date')
    )
RETURN
    CALCULATE(
        AVERAGE(iot_hot_readings[reading_value]),
        iot_hot_readings[sensor_type] = "HVAC_return_temp",
        iot_hot_readings[timestamp] = LatestTS,
        REMOVEFILTERS('Date')
    )

IoT_Delta_T_Live =
VAR Supply = [IoT_Supply_Temp_Live]
VAR Return = [IoT_Return_Temp_Live]
RETURN
    IF(
        ISBLANK(Supply) || ISBLANK(Return),
        BLANK(),
        ABS(Supply - Return)
    )

IoT_Delta_T_Label =
VAR DeltaT = [IoT_Delta_T_Live]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(DeltaT),  "No supply/return sensors",
        DeltaT < 3,       FORMAT(DeltaT, "0.0") & "°C — Very low — check pump/coil",
        DeltaT < 8,       FORMAT(DeltaT, "0.0") & "°C — Below optimal (8-15°C)",
        DeltaT <= 15,     FORMAT(DeltaT, "0.0") & "°C — Optimal range",
        DeltaT <= 20,     FORMAT(DeltaT, "0.0") & "°C — Above optimal — check flow",
        FORMAT(DeltaT, "0.0") & "°C — High — low flow rate risk"
    )

IoT_Delta_T_Color =
VAR DeltaT = [IoT_Delta_T_Live]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(DeltaT), "#AAAAAA",
        DeltaT < 3,      "#FF4136",
        DeltaT < 8,      "#FF851B",
        DeltaT <= 15,    "#2ECC40",
        DeltaT <= 20,    "#FF851B",
        "#FF4136"
    )


// ─────────────────────────────────────────────────────────────────────────────

// P7-C2: Zone comfort compliance % (live)
// Proxy: % of HVAC_temp/humidity/CO2 readings with is_anomaly = FALSE
// Same logic as Page 8 C2 — consistent number across both pages

IoT_Zone_Compliance_Live =
VAR TotalReadings =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        iot_hot_readings[sensor_type] IN {"HVAC_temp", "humidity", "CO2"},
        REMOVEFILTERS('Date')
    )
VAR NormalReadings =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        iot_hot_readings[sensor_type] IN {"HVAC_temp", "humidity", "CO2"},
        iot_hot_readings[is_anomaly] = FALSE(),
        REMOVEFILTERS('Date')
    )
RETURN
    DIVIDE(NormalReadings, TotalReadings, BLANK()) * 100

IoT_Zone_Compliance_Label =
VAR Pct = [IoT_Zone_Compliance_Live]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(Pct), "No comfort sensors",
        Pct >= 90,    FORMAT(ROUND(Pct, 0), "0") & "% zones OK — Good",
        Pct >= 75,    FORMAT(ROUND(Pct, 0), "0") & "% zones OK — Review",
        FORMAT(ROUND(Pct, 0), "0") & "% zones OK — Action needed"
    )

IoT_Zone_Compliance_Color =
VAR Pct = [IoT_Zone_Compliance_Live]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(Pct), "#AAAAAA",
        Pct >= 90,    "#2ECC40",
        Pct >= 75,    "#FF851B",
        "#FF4136"
    )


// ─────────────────────────────────────────────────────────────────────────────

// P7-C3: Live CO₂ level
// High CO₂ on Page 7 = ventilation is underperforming relative to HVAC load
// EN 13779 / EN 16798 IDA classification (non-residential buildings)

IoT_CO2_Live =
CALCULATE(
    MAX(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "CO2",
    REMOVEFILTERS('Date')
)

IoT_CO2_Label =
VAR CO2 = [IoT_CO2_Live]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(CO2), "No CO2 sensors",
        CO2 < 800,    FORMAT(CO2, "0") & " ppm — IDA 1 Excellent",
        CO2 < 1000,   FORMAT(CO2, "0") & " ppm — IDA 2 Good",
        CO2 < 1400,   FORMAT(CO2, "0") & " ppm — IDA 3 Review ventilation",
        FORMAT(CO2, "0") & " ppm — IDA 4 Increase fresh air"
    )

IoT_CO2_Color =
VAR CO2 = [IoT_CO2_Live]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(CO2), "#AAAAAA",
        CO2 < 1000,   "#2ECC40",
        CO2 < 1400,   "#FF851B",
        "#FF4136"
    )


// ─────────────────────────────────────────────────────────────────────────────
// SUMMARY — cross-page badges and tooltips
// ─────────────────────────────────────────────────────────────────────────────

IoT_Total_Cost_Today_EUR =
// Total estimated anomaly cost today across all buildings in slicer context.
// Uses iot_anomaly_alerts — same cost model as C4_Alert_Cost_Today_EUR in v44.
VAR GridPrice = 0.20
VAR AvgDurH   = 0.50
RETURN
CALCULATE(
    SUMX(
        iot_anomaly_alerts,
        VAR ST  = iot_anomaly_alerts[sensor_type]
        VAR Sev = iot_anomaly_alerts[anomaly_severity]
        VAR ExtraKW =
            SWITCH(
                TRUE(),
                ST = "HVAC_temp"    && Sev = "High",   5.0,
                ST = "HVAC_temp"    && Sev = "Medium",  2.5,
                ST = "CO2"          && Sev = "High",    3.0,
                ST = "CO2"          && Sev = "Medium",  1.5,
                ST = "building_kwh" && Sev = "High",    8.0,
                ST = "building_kwh" && Sev = "Medium",  3.0,
                ST = "hvac_kwh"     && Sev = "High",    4.0,
                ST = "hvac_kwh"     && Sev = "Medium",  2.0,
                1.5
            )
        RETURN ExtraKW * AvgDurH * GridPrice
    ),
    iot_anomaly_alerts[alert_time] >= TODAY(),
    REMOVEFILTERS('Date')
)

IoT_High_Alert_Count =
// Count of active (unresolved) High-severity alerts — used as cross-page badge.
CALCULATE(
    COUNTROWS(iot_anomaly_alerts),
    iot_anomaly_alerts[anomaly_severity] = "High",
    iot_anomaly_alerts[is_resolved] = FALSE(),
    REMOVEFILTERS('Date')
)
