// =============================================================================
// DAX v46 — Page 8: IoT Real-Time Monitoring — FINAL
// Energy Copilot Platform
// Updated: 2026-05-08
//
// CHANGES FROM v44:
//   [C1] Timestamp exact-match fixed → plain AVERAGE, no timestamp filter (DirectQuery safe)
//   [C4] Rewritten to use iot_hot_readings — iot_anomaly_alerts not required
//   [V3] Replaced broken second matrix → clustered bar chart measures (anomaly count by zone+severity)
//   [V4] New table measures with proper avg reading, unit, action, cost per anomaly
//
// KEY DESIGN RULE — KQL DirectQuery:
//   DO NOT use NOW(), TODAY(), or TIME() in filter predicates.
//   Power BI cannot translate these into KQL query predicates → runtime error.
//   iot_hot_readings is already a rolling-window live table — no additional
//   time filtering needed. REMOVEFILTERS('Date') is sufficient to keep cards live.
//
// TABLES USED:
//   iot_hot_readings   — KQL DirectQuery (primary — all C1-C4 and V1-V4 measures)
//                        Columns: anomaly_severity, anomaly_type, building_id,
//                        device_id, is_anomaly, reading_quality, reading_unit,
//                        reading_value, sensor_location, sensor_type,
//                        source_protocol, timestamp
//   iot_anomaly_alerts — KQL DirectQuery (connected but not required for core measures)
//
// HOME TABLE: assign all measures to iot_hot_readings
// =============================================================================


// ─────────────────────────────────────────────────────────────────────────────
// C1: Real-time building power (kW)
// FIX v46: no timestamp filter — iot_hot_readings is already a live rolling-window
//          table. AVERAGE of all building_kwh rows = current power level.
//          NOW()/TIME() removed — crashes KQL DirectQuery.
// Color: green ≤100% baseline | amber 100-120% | red >120%
// ─────────────────────────────────────────────────────────────────────────────

C1_Building_kW_Raw =
CALCULATE(
    AVERAGE(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "building_kwh",
    REMOVEFILTERS('Date')
)

C1_Building_kW_Baseline =
// Average of all non-anomaly building_kwh readings — rolling normal reference.
// REMOVEFILTERS on timestamp so baseline is constant across any slicer context.
CALCULATE(
    AVERAGE(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "building_kwh",
    iot_hot_readings[is_anomaly] = FALSE(),
    REMOVEFILTERS(iot_hot_readings[timestamp]),
    REMOVEFILTERS('Date')
)

C1_Building_kW_Display =
VAR kW    = [C1_Building_kW_Raw]
VAR Base  = [C1_Building_kW_Baseline]
VAR Ratio = DIVIDE(kW, Base, 1)
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(kW),   "-- kW",
        Ratio > 1.2,   FORMAT(kW, "0.0") & " kW ▲ High",
        Ratio > 1.0,   FORMAT(kW, "0.0") & " kW ~ Above normal",
        FORMAT(kW, "0.0") & " kW ✓ Normal"
    )

C1_Building_kW_Color =
VAR kW    = [C1_Building_kW_Raw]
VAR Base  = [C1_Building_kW_Baseline]
VAR Ratio = DIVIDE(kW, Base, 1)
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(kW),  "#AAAAAA",
        Ratio > 1.2,  "#FF4136",
        Ratio > 1.0,  "#FF851B",
        "#2ECC40"
    )


// ─────────────────────────────────────────────────────────────────────────────
// C2: Zone comfort compliance %
// % of HVAC_temp / humidity / CO2 readings where is_anomaly = FALSE
// Thresholds: ≥90% = Good, 75-89% = Review, <75% = Action needed
// ─────────────────────────────────────────────────────────────────────────────

C2_Zone_Compliance_Pct_Raw =
VAR TotalReadings =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        iot_hot_readings[sensor_type] IN {"HVAC_temp", "humidity", "CO2"},
        REMOVEFILTERS('Date')
    )
VAR NormalReadings =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        iot_hot_readings[sensor_type] IN {"HVAC_temp", "humidity", "CO2"},
        iot_hot_readings[is_anomaly] = FALSE(),
        REMOVEFILTERS('Date')
    )
RETURN
    DIVIDE(NormalReadings, TotalReadings, 0) * 100

C2_Zone_Compliance_Display =
VAR Pct = [C2_Zone_Compliance_Pct_Raw]
RETURN
    IF(
        ISBLANK(Pct),
        "-- %",
        FORMAT(ROUND(Pct, 0), "0") & "% zones OK"
    )

C2_Zone_Compliance_Color =
VAR Pct = [C2_Zone_Compliance_Pct_Raw]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(Pct), "#AAAAAA",
        Pct >= 90,    "#2ECC40",
        Pct >= 75,    "#FF851B",
        "#FF4136"
    )


// ─────────────────────────────────────────────────────────────────────────────
// C3: CO₂ level — peak reading across selected building
// Standard: EN 13779 / EN 16798 IDA classification (non-residential)
//   IDA 1 Excellent: <800 ppm
//   IDA 2 Good:      800–999 ppm
//   IDA 3 Review:    1000–1399 ppm
//   IDA 4 Poor:      ≥1400 ppm → ventilate immediately
// ─────────────────────────────────────────────────────────────────────────────

C3_CO2_Current_Raw =
CALCULATE(
    MAX(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "CO2",
    REMOVEFILTERS('Date')
)

C3_CO2_Quality_Label =
VAR CO2 = [C3_CO2_Current_Raw]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(CO2), "No Data",
        CO2 < 800,    "IDA 1 Excellent",
        CO2 < 1000,   "IDA 2 Good",
        CO2 < 1400,   "IDA 3 Review",
        "IDA 4 Poor — Ventilate"
    )

C3_CO2_Display =
VAR CO2   = [C3_CO2_Current_Raw]
VAR Label = [C3_CO2_Quality_Label]
RETURN
    IF(ISBLANK(CO2), "-- ppm", FORMAT(CO2, "0") & " ppm — " & Label)

C3_CO2_Color =
VAR CO2 = [C3_CO2_Current_Raw]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(CO2), "#AAAAAA",
        CO2 < 1000,   "#2ECC40",
        CO2 < 1400,   "#FF851B",
        "#FF4136"
    )


// ─────────────────────────────────────────────────────────────────────────────
// C4: Active anomalies + estimated daily cost
// FIX v46: REWRITTEN to use iot_hot_readings (no dependency on iot_anomaly_alerts)
//
// Logic:
//   "Active" = is_anomaly = TRUE in the last 60 minutes (live window)
//   "High severity" = anomaly_severity = "High"
//   Cost = count × avg_extra_kw × avg_duration_hours × grid_price
//
// Energy assumption (CLAUDE.md):
//   HVAC_temp High → 5 kW extra | Medium → 2.5 kW
//   CO2 High       → 3 kW extra | Medium → 1.5 kW
//   building_kwh High → 8 kW   | Medium → 3 kW
//   hvac_kwh High  → 4 kW      | Medium → 2 kW
//   default        → 1.5 kW
//   Avg anomaly duration: 30 min = 0.5 h
//   Grid price: €0.20/kWh (DE)
// ─────────────────────────────────────────────────────────────────────────────

C4_Active_High_Alerts =
// Count of High-severity anomaly rows in iot_hot_readings.
// No time filter — table is already live rolling window.
// NOW()/TIME() removed — crashes KQL DirectQuery.
CALCULATE(
    COUNTROWS(iot_hot_readings),
    iot_hot_readings[is_anomaly] = TRUE(),
    iot_hot_readings[anomaly_severity] = "High",
    REMOVEFILTERS('Date')
)

C4_Alert_Cost_Today_EUR =
// Estimate cost for all anomaly rows in the live table.
// TODAY() removed — crashes KQL DirectQuery. No date filter needed:
// iot_hot_readings is already the recent rolling window.
VAR GridPrice = 0.20
VAR AvgDurH   = 0.50
RETURN
    CALCULATE(
        SUMX(
            FILTER(iot_hot_readings, iot_hot_readings[is_anomaly] = TRUE()),
            VAR ST  = iot_hot_readings[sensor_type]
            VAR Sev = iot_hot_readings[anomaly_severity]
            VAR ExtraKW =
                SWITCH(
                    TRUE(),
                    ST = "HVAC_temp"    && Sev = "High",   5.0,
                    ST = "HVAC_temp"    && Sev = "Medium",  2.5,
                    ST = "CO2"          && Sev = "High",    3.0,
                    ST = "CO2"          && Sev = "Medium",  1.5,
                    ST = "building_kwh" && Sev = "High",    8.0,
                    ST = "building_kwh" && Sev = "Medium",  3.0,
                    ST = "hvac_kwh"     && Sev = "High",    4.0,
                    ST = "hvac_kwh"     && Sev = "Medium",  2.0,
                    1.5
                )
            RETURN ExtraKW * AvgDurH * GridPrice
        ),
        REMOVEFILTERS('Date')
    )

C4_Alert_Label =
VAR Alerts = [C4_Active_High_Alerts]
VAR Cost   = [C4_Alert_Cost_Today_EUR]
RETURN
    IF(
        ISBLANK(Alerts) || Alerts = 0,
        "All Clear",
        FORMAT(Alerts, "0") & " Active — Est. €" & FORMAT(ROUND(Cost, 0), "0") & " today"
    )

C4_Alert_Color =
VAR Alerts = [C4_Active_High_Alerts]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(Alerts) || Alerts = 0, "#2ECC40",
        Alerts <= 3,                   "#FF851B",
        "#FF4136"
    )


// ─────────────────────────────────────────────────────────────────────────────
// V1: 24h Power Trend (Line Chart)
// FIX v46: Axis = iot_hot_readings[timestamp] grouped by HOUR
//          Add V1_Hour_Label for cleaner X-axis (use this as axis field instead)
//
// Binding:
//   X-axis: iot_hot_readings[timestamp] — set hierarchy to "Hour" level in PBI
//           OR use V1_Hour_Bucket below as a calculated column alternative
//   Y-axis: [V1_Building_kW], [V1_HVAC_kW], [V1_Baseline_kW]
//   Tooltip: [V1_HVAC_Share_Pct]
// ─────────────────────────────────────────────────────────────────────────────

V1_Building_kW =
CALCULATE(
    AVERAGE(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "building_kwh"
)

V1_HVAC_kW =
CALCULATE(
    AVERAGE(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "hvac_kwh"
)

V1_Baseline_kW =
// Flat reference line — average of all non-anomaly building_kwh readings.
// REMOVEFILTERS on timestamp → same value rendered at every hour.
CALCULATE(
    AVERAGE(iot_hot_readings[reading_value]),
    iot_hot_readings[sensor_type] = "building_kwh",
    iot_hot_readings[is_anomaly] = FALSE(),
    REMOVEFILTERS(iot_hot_readings[timestamp]),
    REMOVEFILTERS('Date')
)

V1_HVAC_Share_Pct =
// Tooltip: HVAC as % of total building load at each timestamp bucket
VAR TotalKW = [V1_Building_kW]
VAR HvacKW  = [V1_HVAC_kW]
RETURN DIVIDE(HvacKW, TotalKW, BLANK()) * 100


// ─────────────────────────────────────────────────────────────────────────────
// V2: Sensor Uptime Matrix
// Visual: Matrix
//   Rows: iot_hot_readings[sensor_location]
//   Columns: iot_hot_readings[sensor_type]
//   Values: [V2_Sensor_Uptime_Pct]
//   Conditional format: [V2_Uptime_Color_Index] → background color rule
//     Rules: 1 = green (#2ECC40), 2 = yellow (#FF851B), 3 = red (#FF4136)
// ─────────────────────────────────────────────────────────────────────────────

V2_Sensor_Uptime_Pct =
// reading_quality is 0–100 from the simulator.
// 100 = clean signal, <75 = sensor problem (noise, dropout, calibration issue).
AVERAGE(iot_hot_readings[reading_quality])

V2_Uptime_Color_Index =
VAR Uptime = [V2_Sensor_Uptime_Pct]
RETURN
    SWITCH(
        TRUE(),
        ISBLANK(Uptime), BLANK(),
        Uptime >= 90, 1,
        Uptime >= 75, 2,
        3
    )


// ─────────────────────────────────────────────────────────────────────────────
// V3: Zone Anomaly Overview (Stacked Bar Chart) — REPLACES broken second matrix
//
// DESIGN CHANGE v46: The second matrix (Zone Comfort Compliance) is removed.
//   Reason: (a) had no valid value field, (b) matrix was wrong visual type,
//            (c) V2 already covers the sensor×zone view.
//
// V3 now shows: "Which zones have the most issues, by severity"
//   Visual: Clustered Bar Chart (horizontal, easier to read zone names)
//   X-axis (Value): [V3_Anomaly_Count_High] / [V3_Anomaly_Count_Medium] / [V3_Anomaly_Count_Low]
//   Y-axis (Category): iot_hot_readings[sensor_location]
//   → One bar per zone, color-coded: High=red, Medium=orange, Low=yellow
//
//   Secondary tooltip: [V3_Zone_Compliance_Pct] — how compliant this specific zone is
//
// Energy logic: zones with high anomaly counts = HVAC setpoint violations,
//   CO2 spikes, or humidity drift. Facility Manager sees which floor/zone to visit.
// ─────────────────────────────────────────────────────────────────────────────

V3_Anomaly_Count_High =
// Count of High-severity anomaly readings in current filter context (zone + date).
CALCULATE(
    COUNTROWS(iot_hot_readings),
    iot_hot_readings[is_anomaly] = TRUE(),
    iot_hot_readings[anomaly_severity] = "High"
)

V3_Anomaly_Count_Medium =
CALCULATE(
    COUNTROWS(iot_hot_readings),
    iot_hot_readings[is_anomaly] = TRUE(),
    iot_hot_readings[anomaly_severity] = "Medium"
)

V3_Anomaly_Count_Low =
CALCULATE(
    COUNTROWS(iot_hot_readings),
    iot_hot_readings[is_anomaly] = TRUE(),
    iot_hot_readings[anomaly_severity] = "Low"
)

V3_Total_Anomalies =
// Total anomaly count for a zone — used as bar sort key (sort Y-axis DESC).
CALCULATE(
    COUNTROWS(iot_hot_readings),
    iot_hot_readings[is_anomaly] = TRUE()
)

V3_Zone_Compliance_Pct =
// Compliance % per zone — used as tooltip on V3 chart.
// Same logic as C2 but scoped to current zone filter context.
VAR Total =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        iot_hot_readings[sensor_type] IN {"HVAC_temp", "humidity", "CO2"}
    )
VAR Normal =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        iot_hot_readings[sensor_type] IN {"HVAC_temp", "humidity", "CO2"},
        iot_hot_readings[is_anomaly] = FALSE()
    )
RETURN
    DIVIDE(Normal, Total, BLANK()) * 100


// ─────────────────────────────────────────────────────────────────────────────
// V4: Alert Detail Table
//
// Visual: Table (not matrix — no cross-tabulation needed here)
// Columns to add to the table visual:
//   [Column] iot_hot_readings[sensor_location]     → "Zone"
//   [Column] iot_hot_readings[sensor_type]         → "Sensor"
//   [Measure] [V4_Avg_Reading_Value]               → "Reading"
//   [Column] iot_hot_readings[reading_unit]        → "Unit"
//   [Column] iot_hot_readings[anomaly_severity]    → "Severity"
//   [Measure] [V4_Action_Label]                    → "Recommended Action"
//   [Measure] [V4_Est_Cost_EUR]                    → "Est. Cost (€)"
//
// IMPORTANT: Add a Visual-level filter on this table:
//   iot_hot_readings[is_anomaly] = TRUE
//   → Shows only anomaly rows, not all readings
//
// Sort: anomaly_severity (High → Medium → Low) or V4_Est_Cost_EUR DESC
// ─────────────────────────────────────────────────────────────────────────────

V4_Avg_Reading_Value =
// Average reading value in current table row context (zone + sensor_type).
// Do NOT use Sum — CO2 sum across all readings gives meaningless 135,000+ values.
AVERAGE(iot_hot_readings[reading_value])

V4_Action_Label =
// Recommended action based on sensor_type and anomaly_severity.
// Energy logic: each sensor type has a specific corrective action.
VAR ST  = SELECTEDVALUE(iot_hot_readings[sensor_type], "unknown")
VAR Sev = SELECTEDVALUE(iot_hot_readings[anomaly_severity], "Low")
RETURN
    SWITCH(
        TRUE(),
        ST = "HVAC_temp"    && Sev = "High",    "Check HVAC setpoint — temp deviation >2°C",
        ST = "HVAC_temp"    && Sev = "Medium",  "Monitor HVAC — temp slightly off setpoint",
        ST = "CO2"          && Sev = "High",    "Increase fresh air — IDA 4 (>1400 ppm)",
        ST = "CO2"          && Sev = "Medium",  "Review ventilation schedule",
        ST = "humidity"     && Sev = "High",    "Check humidifier/dehumidifier setting",
        ST = "humidity"     && Sev = "Medium",  "Monitor humidity — approaching limit",
        ST = "building_kwh" && Sev = "High",    "Power spike detected — check load profile",
        ST = "building_kwh" && Sev = "Medium",  "Above-normal consumption — investigate",
        ST = "hvac_kwh"     && Sev = "High",    "HVAC overconsumption — inspect equipment",
        ST = "hvac_kwh"     && Sev = "Medium",  "HVAC load elevated — check schedule",
        "Review sensor reading"
    )

V4_Est_Cost_EUR =
// Estimated cost contribution of anomaly readings in current row context.
// Uses same energy logic as C4_Alert_Cost_Today_EUR.
VAR GridPrice = 0.20
VAR AvgDurH   = 0.50
VAR ST  = SELECTEDVALUE(iot_hot_readings[sensor_type], "")
VAR Sev = SELECTEDVALUE(iot_hot_readings[anomaly_severity], "Low")
VAR ExtraKW =
    SWITCH(
        TRUE(),
        ST = "HVAC_temp"    && Sev = "High",   5.0,
        ST = "HVAC_temp"    && Sev = "Medium",  2.5,
        ST = "CO2"          && Sev = "High",    3.0,
        ST = "CO2"          && Sev = "Medium",  1.5,
        ST = "building_kwh" && Sev = "High",    8.0,
        ST = "building_kwh" && Sev = "Medium",  3.0,
        ST = "hvac_kwh"     && Sev = "High",    4.0,
        ST = "hvac_kwh"     && Sev = "Medium",  2.0,
        1.5
    )
VAR AnomalyCount =
    CALCULATE(
        COUNTROWS(iot_hot_readings),
        iot_hot_readings[is_anomaly] = TRUE()
    )
RETURN
    AnomalyCount * ExtraKW * AvgDurH * GridPrice

V4_Severity_Sort =
// Numeric sort key for anomaly_severity column — High=1 (top), Medium=2, Low=3.
// Add this measure to the table, then sort by it (ascending) to get High first.
// You can hide this column but keep it for sorting.
VAR Sev = SELECTEDVALUE(iot_hot_readings[anomaly_severity], "Low")
RETURN
    SWITCH(Sev, "High", 1, "Medium", 2, "Low", 3, 4)
