// =============================================================================
// DAX v46 Patch 2 — C4 alert count fix + V4 action labels + sensor type labels
// =============================================================================
// CHANGES:
//   [C4] COUNTROWS → DISTINCTCOUNT(device_id): shows distinct sensors in alert,
//        not total anomaly row count (which inflates to 800+ due to rolling window)
//   [V4] Action label extended: boiler_eff, fan_rpm, chiller_cop, pump_pressure,
//        HVAC_supply_temp, HVAC_return_temp, lighting_kwh, plug_load_kwh added
//   [V2] sensor_type_label: calculated column for clean matrix column headers
//
// HOW TO APPLY:
//   DELETE old C4_Active_High_Alerts and V4_Action_Label measures, replace with these.
//   Add sensor_type_label as a NEW CALCULATED COLUMN (not measure) on iot_hot_readings.
//   In V2 matrix: swap sensor_type column → sensor_type_label column.
// =============================================================================


// -----------------------------------------------------------------------------
// C4_Active_High_Alerts  (REPLACE old version)
// -----------------------------------------------------------------------------
// WHY DISTINCTCOUNT: COUNTROWS counted every anomaly reading in the rolling window
// (e.g. 871 rows). We want: "how many distinct sensors are currently in High alert?"
// A sensor with 50 anomaly readings still counts as 1 alert device.
// -----------------------------------------------------------------------------
C4_Active_High_Alerts =
CALCULATE(
    DISTINCTCOUNT(iot_hot_readings[device_id]),
    iot_hot_readings[is_anomaly]       = TRUE(),
    iot_hot_readings[anomaly_severity] = "High",
    REMOVEFILTERS('Date')
)


// -----------------------------------------------------------------------------
// V4_Action_Label  (REPLACE old version)
// Extended to cover all simulator sensor types.
// Old version only covered 5 types → all others showed "Review sensor reading"
// -----------------------------------------------------------------------------
V4_Action_Label =
VAR ST  = SELECTEDVALUE(iot_hot_readings[sensor_type], "unknown")
VAR Sev = SELECTEDVALUE(iot_hot_readings[anomaly_severity], "Low")
RETURN
    SWITCH(
        TRUE(),
        // Comfort sensors
        ST = "HVAC_temp"        && Sev = "High",   "Check HVAC setpoint — temp deviation >2°C",
        ST = "HVAC_temp"        && Sev = "Medium", "Monitor HVAC — temp slightly off setpoint",
        ST = "CO2"              && Sev = "High",   "Increase fresh air — IDA 4 (>1400 ppm)",
        ST = "CO2"              && Sev = "Medium", "Review ventilation schedule",
        ST = "humidity"         && Sev = "High",   "Check humidifier/dehumidifier setting",
        ST = "humidity"         && Sev = "Medium", "Monitor humidity — approaching limit",
        // Power sensors
        ST = "building_kwh"     && Sev = "High",   "Power spike detected — check load profile",
        ST = "building_kwh"     && Sev = "Medium", "Above-normal consumption — investigate",
        ST = "hvac_kwh"         && Sev = "High",   "HVAC overconsumption — inspect equipment",
        ST = "hvac_kwh"         && Sev = "Medium", "HVAC load elevated — check schedule",
        ST = "lighting_kwh"     && Sev = "High",   "Lighting spike — check occupancy sensors",
        ST = "lighting_kwh"     && Sev = "Medium", "Lighting above baseline — review schedule",
        ST = "plug_load_kwh"    && Sev = "High",   "Plug load spike — check unauthorized equipment",
        ST = "plug_load_kwh"    && Sev = "Medium", "Plug load elevated — identify source",
        // Supply/return delta-T
        ST = "HVAC_supply_temp" && Sev = "High",   "Supply air fault — check cooling/heating coil",
        ST = "HVAC_supply_temp" && Sev = "Medium", "Supply temp drifting — inspect AHU controls",
        ST = "HVAC_return_temp" && Sev = "High",   "Poor delta-T — check air distribution system",
        ST = "HVAC_return_temp" && Sev = "Medium", "Return temp irregular — check zone dampers",
        // Mechanical equipment
        ST = "boiler_eff"       && Sev = "High",   "Boiler efficiency critical (<75%) — schedule service",
        ST = "boiler_eff"       && Sev = "Medium", "Boiler efficiency declining — preventive check",
        ST = "chiller_cop"      && Sev = "High",   "Chiller COP critically low — check refrigerant",
        ST = "chiller_cop"      && Sev = "Medium", "Chiller efficiency declining — inspect coils",
        ST = "pump_pressure"    && Sev = "High",   "Pressure fault — check pump and expansion vessel",
        ST = "pump_pressure"    && Sev = "Medium", "Pressure irregular — monitor system",
        ST = "fan_rpm"          && Sev = "High",   "Fan over/underspeed — inspect VFD and belts",
        ST = "fan_rpm"          && Sev = "Medium", "Fan RPM irregular — check filter and belt",
        // Fallback — should not appear for known sensor types
        "Inspect " & ST & " reading"
    )


// =============================================================================
// sensor_type_label — CALCULATED COLUMN (not a measure!)
// =============================================================================
// HOW TO ADD IN POWER BI:
//   1. Select iot_hot_readings table in the Fields pane
//   2. Table tools → New column
//   3. Paste the formula below (just the body, no variable name)
//   4. In V2 matrix: remove sensor_type from Columns, add sensor_type_label
//
// Result: matrix column headers become "Bldg kW", "CO₂", "Humid" etc.
// instead of "building_kwh", "CO2", "humidity"
// =============================================================================

// sensor_type_label =
// SWITCH(
//     iot_hot_readings[sensor_type],
//     "building_kwh",     "Bldg kW",
//     "hvac_kwh",         "HVAC kW",
//     "HVAC_temp",        "HVAC T°",
//     "CO2",              "CO₂",
//     "humidity",         "Humid",
//     "HVAC_supply_temp", "Supply T°",
//     "HVAC_return_temp", "Return T°",
//     "boiler_eff",       "Boiler %",
//     "chiller_cop",      "Chiller COP",
//     "fan_rpm",          "Fan RPM",
//     "lighting_kwh",     "Light kW",
//     "plug_load_kwh",    "Plug kW",
//     "pump_pressure",    "Pressure",
//     iot_hot_readings[sensor_type]
// )
