// =============================================================================
// DAX MEASURES — v47 — PAGE 9: Battery Dispatch Strategies & Financial Simulation
// File     : 58_dax_v47_page9_battery.dax
// Updated  : 2026-05-08
// Tables   : gold_battery_dispatch, gold_battery_simulation, gold_battery_daily_summary
//            gold_battery_technologies, silver_building_master
//
// MEASURE GROUPS
//   C1–C4  : KPI cards (top row)
//   V1     : 30-day SoC trend + charge/discharge area chart
//   V2     : Daily charge/discharge stacked bar
//   V3     : Scenario comparison table (with EU compliance)
//   V4     : ROI gauge (savings vs target)
//   V5     : Cost vs payback scatter bubble
//   LABELS : Card label measures for reference lines
//   SLICERS: Supporting measures for slicers/filters
//
// ENERGY LOGIC ASSUMPTIONS (approved 2026-05-08)
//   - Annual savings extrapolated from last 365 days of dispatch data
//   - Payback = Total CAPEX / Annual Net Savings (simple payback, unlevered)
//   - NPV uses 5% discount rate, 3% energy price inflation, 10-year horizon
//   - CO2 avoided = discharge_kwh × country grid CO2 intensity (g/kWh) / 1000
//   - Battery health degrades ~1.8%/1000 cycles (LFP) and ~3.5%/1000 (NMC)
//   - EU compliance per EU Regulation 2023/1542 (in force 2024-01-01)
// =============================================================================


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 1 — KPI CARDS (C1–C4)
// ─────────────────────────────────────────────────────────────────────────────

// C1: Annual Net Savings (€/year)
// Logic: Annualize net savings from dispatch data over selected period
// Source: gold_battery_dispatch[net_savings_eur]
// Expected range: €800–€70,000 (varies by building size and strategy)
[C1 Annual Savings EUR] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
VAR FilteredDispatch =
    FILTER(
        gold_battery_dispatch,
        gold_battery_dispatch[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )
VAR TotalDays =
    COUNTROWS(
        SUMMARIZE(FilteredDispatch, gold_battery_dispatch[date])
    )
VAR TotalSavings =
    SUMX(FilteredDispatch, gold_battery_dispatch[net_savings_eur])
VAR AnnualRate =
    IFERROR(
        DIVIDE(TotalSavings, TotalDays) * 365,
        BLANK()
    )
RETURN
    IF(TotalDays >= 30, AnnualRate, BLANK())


// C1 Label: formatted display string for card reference label
[C1 Label Savings] =
VAR Val = [C1 Annual Savings EUR]
RETURN
    IF(
        ISBLANK(Val), "No data",
        IF(Val >= 10000,
            FORMAT(Val / 1000, "#,##0.0") & "k €/yr",
            FORMAT(Val, "#,##0") & " €/yr"
        )
    )


// C2: Simple Payback Period (years)
// Logic: Total CAPEX / Annual Net Savings
// Source: gold_battery_simulation (pre-computed per scenario)
// Expected range: 1.5–12 years for EU commercial buildings
[C2 Payback Years] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
VAR SelectedStrategy = SELECTEDVALUE(gold_battery_dispatch[strategy])
VAR BestScenario =
    CALCULATE(
        MINX(
            gold_battery_simulation,
            gold_battery_simulation[payback_years]
        ),
        gold_battery_simulation[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding),
        gold_battery_simulation[strategy] = SelectedStrategy
            || ISBLANK(SelectedStrategy)
    )
RETURN
    IFERROR(BestScenario, BLANK())


// C2 Label
[C2 Label Payback] =
VAR Val = [C2 Payback Years]
RETURN
    IF(ISBLANK(Val), "No data",
        FORMAT(Val, "#,##0.0") & " years"
    )


// C3: Annual CO₂ Avoided (tonnes CO₂/year)
// Logic: Annualized from dispatch data, converted kg → tCO₂
// Source: gold_battery_dispatch[co2_avoided_kg]
// Expected range: 0.5–30 tCO₂/year
[C3 CO2 Avoided tCO2 Annual] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
VAR FilteredDispatch =
    FILTER(
        gold_battery_dispatch,
        gold_battery_dispatch[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )
VAR TotalDays =
    COUNTROWS(
        SUMMARIZE(FilteredDispatch, gold_battery_dispatch[date])
    )
VAR TotalCO2kg =
    SUMX(FilteredDispatch, gold_battery_dispatch[co2_avoided_kg])
VAR AnnualTonnes =
    IFERROR(
        DIVIDE(TotalCO2kg, TotalDays) * 365 / 1000,
        BLANK()
    )
RETURN
    IF(TotalDays >= 30, AnnualTonnes, BLANK())


// C3 Label
[C3 Label CO2] =
VAR Val = [C3 CO2 Avoided tCO2 Annual]
RETURN
    IF(ISBLANK(Val), "No data",
        FORMAT(Val, "#,##0.1") & " tCO₂/yr"
    )


// C4: Average Round-Trip Efficiency (%)
// Logic: Average efficiency across selected building/period
// Source: gold_battery_dispatch[round_trip_efficiency]
// Expected range: 90–95% (LFP 93–95%, NMC 90–91%)
[C4 Round Trip Efficiency Pct] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
VAR AvgEff =
    CALCULATE(
        AVERAGEX(
            gold_battery_dispatch,
            gold_battery_dispatch[round_trip_efficiency]
        ),
        gold_battery_dispatch[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )
RETURN
    IFERROR(AvgEff * 100, BLANK())


// C4 Label
[C4 Label Efficiency] =
VAR Val = [C4 Round Trip Efficiency Pct]
VAR BattType = SELECTEDVALUE(gold_battery_dispatch[battery_type])
VAR EUFlag =
    IF(
        CALCULATE(
            MAX(gold_battery_dispatch[eu_compliant]),
            gold_battery_dispatch[building_id]
                = SELECTEDVALUE(silver_building_master[building_id])
        ),
        " (EU OK)",
        " (NON-EU)"
    )
RETURN
    IF(ISBLANK(Val), "No data",
        FORMAT(Val, "#,##0.0") & "% RTE" & EUFlag
    )


// C4b: Battery Health Score (for secondary card or tooltip)
[C4b Battery Health Pct] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
RETURN
    CALCULATE(
        AVERAGEX(
            gold_battery_dispatch,
            gold_battery_dispatch[battery_health_percent]
        ),
        gold_battery_dispatch[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 2 — V1: SoC TREND (Area/Line chart, date axis)
// ─────────────────────────────────────────────────────────────────────────────

// V1 SoC End % (by date, by strategy — for legend/series)
// Used on: Line chart or Area chart, X-axis = date, Y-axis = this measure
// Legend: gold_battery_dispatch[strategy]
[V1 SoC End Percent] =
AVERAGE(gold_battery_dispatch[soc_end_percent])


// V1 SoC Start % (secondary series or tooltip)
[V1 SoC Start Percent] =
AVERAGE(gold_battery_dispatch[soc_start_percent])


// V1 SoC Avg Day (single line for portfolio view)
[V1 SoC Daily Avg] =
AVERAGEX(
    VALUES(gold_battery_dispatch[date]),
    CALCULATE(AVERAGE(gold_battery_dispatch[soc_end_percent]))
)


// V1 Reference line: minimum safe SoC (10%)
[V1 SoC Min Reference] =
VAR BattType = SELECTEDVALUE(gold_battery_dispatch[battery_type])
RETURN
    IF(BattType = "NMC", 20.0, 10.0)  -- NMC has higher min SoC recommendation


// V1 Reference line: optimal SoC target range label
[V1 SoC Target Label] =
VAR Strategy = SELECTEDVALUE(gold_battery_dispatch[strategy])
RETURN
    SWITCH(Strategy,
        "peak_shaving",     "Target: 80% (pre-charge)",
        "backup",           "Target: 65% (reserve)",
        "tou",              "Target: 30% (morning)",
        "self_consumption", "Target: 20% (morning)",
        "Strategy SoC target"
    )


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 3 — V2: DAILY CHARGE / DISCHARGE (Stacked Bar)
// ─────────────────────────────────────────────────────────────────────────────

// V2 Daily Charge (kWh) — blue series
[V2 Charge kWh Daily] =
SUM(gold_battery_dispatch[charge_kwh])


// V2 PV Charge portion — green fill within charge bar
[V2 PV Charge kWh Daily] =
SUM(gold_battery_dispatch[pv_charge_kwh])


// V2 Grid Charge portion — grey fill within charge bar
[V2 Grid Charge kWh Daily] =
SUM(gold_battery_dispatch[grid_charge_kwh])


// V2 Daily Discharge (kWh) — amber/orange series
[V2 Discharge kWh Daily] =
SUM(gold_battery_dispatch[discharge_kwh])


// V2 PV Generation (line overlay on bar chart)
[V2 PV Generation kWh] =
SUM(gold_battery_dispatch[pv_generation_kwh])


// V2 Net Daily Savings (EUR) — secondary axis line
[V2 Net Savings EUR Daily] =
SUM(gold_battery_dispatch[net_savings_eur])


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 4 — V3: SCENARIO COMPARISON TABLE
// ─────────────────────────────────────────────────────────────────────────────
// These measures are primarily bound to gold_battery_simulation columns directly.
// The DAX measures below support conditional formatting and calculated display fields.

// V3 EU Compliance Badge (for conditional formatting: True=green, False=red)
[V3 EU Compliant Flag] =
MAX(gold_battery_simulation[eu_compliant])


// V3 EU Compliance Display (text for column)
[V3 EU Compliance Label] =
VAR IsCompliant = MAX(gold_battery_simulation[eu_compliant])
RETURN
    IF(IsCompliant, "EU Compliant", "NON-COMPLIANT")


// V3 Comparison Score Color (for data bar / conditional format)
// Returns 1=excellent (>80), 2=good (60-80), 3=poor (<60)
[V3 Score Category] =
VAR Score = MAX(gold_battery_simulation[comparison_score])
RETURN
    IF(Score >= 80, 1,
    IF(Score >= 60, 2, 3))


// V3 Payback Traffic Light (1=green <7yr, 2=amber 7-12yr, 3=red >12yr)
[V3 Payback Status] =
VAR PB = MIN(gold_battery_simulation[payback_years])
RETURN
    IF(PB <= 7, 1,
    IF(PB <= 12, 2, 3))


// V3 Recommended Strategy label per building
[V3 Best Strategy Label] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
VAR BestScenario =
    CALCULATE(
        TOPN(1,
            FILTER(gold_battery_simulation,
                gold_battery_simulation[building_id] = SelectedBuilding),
            gold_battery_simulation[comparison_score], DESC
        )
    )
RETURN
    MAXX(BestScenario, gold_battery_simulation[strategy_label])


// V3 NPV label (display friendly)
[V3 NPV Display] =
VAR Val = MAX(gold_battery_simulation[npv_10yr_eur])
RETURN
    IF(ISBLANK(Val), "—",
    IF(Val >= 0,
        "+" & FORMAT(Val / 1000, "#,##0.0") & "k €",
        FORMAT(Val / 1000, "#,##0.0") & "k €"
    ))


// V3 EU Recommendation text
[V3 EU Recommendation] =
VAR IsCompliant = MAX(gold_battery_simulation[eu_compliant])
VAR BattType    = SELECTEDVALUE(gold_battery_simulation[battery_type])
RETURN
    IF(
        IsCompliant,
        "Meets EU 2023/1542",
        "Replace with LFP — EU non-compliant since 2024-01"
    )


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 5 — V4: ROI GAUGE (Annual Savings vs Target)
// ─────────────────────────────────────────────────────────────────────────────

// V4 Gauge value: actual savings / target × 100
// Target is dynamically set from simulation best-case scenario
[V4 ROI Gauge Pct] =
VAR ActualSavings = [C1 Annual Savings EUR]
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
// Target = best-case annual savings from simulation (top scenario)
VAR TargetSavings =
    CALCULATE(
        MAXX(gold_battery_simulation, gold_battery_simulation[annual_savings_eur]),
        gold_battery_simulation[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )
RETURN
    IFERROR(
        DIVIDE(ActualSavings, TargetSavings) * 100,
        BLANK()
    )


// V4 Gauge: target value (max of gauge scale = best scenario savings)
[V4 Savings Target EUR] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
RETURN
    CALCULATE(
        MAXX(gold_battery_simulation, gold_battery_simulation[annual_savings_eur]),
        gold_battery_simulation[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )


// V4 Status label
[V4 ROI Status Label] =
VAR Pct = [V4 ROI Gauge Pct]
RETURN
    IF(ISBLANK(Pct), "No data",
    IF(Pct >= 90, "On target",
    IF(Pct >= 70, "Below target",
    "Strategy review needed")))


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 6 — V5: COST vs PAYBACK SCATTER BUBBLE
// ─────────────────────────────────────────────────────────────────────────────
// Used on scatter chart: X = battery_cost_eur, Y = payback_years
// Bubble size = battery_capacity_kwh, Color = comparison_score
// These are column references but DAX wraps for context safety.

// V5 X-axis: Battery CAPEX (EUR)
[V5 Battery Cost EUR] =
MAX(gold_battery_simulation[battery_cost_eur])


// V5 Y-axis: Payback Period (years) — lower is better
[V5 Payback Years] =
MIN(gold_battery_simulation[payback_years])


// V5 Bubble size: Battery Capacity (kWh)
[V5 Capacity kWh] =
MAX(gold_battery_simulation[battery_capacity_kwh])


// V5 Color: Comparison Score (for conditional gradient)
[V5 Comparison Score] =
MAX(gold_battery_simulation[comparison_score])


// V5 Quadrant label (tooltip overlay)
[V5 Quadrant Label] =
VAR Cost    = [V5 Battery Cost EUR]
VAR Payback = [V5 Payback Years]
VAR Score   = [V5 Comparison Score]
RETURN
    IF(Score >= 80 && Payback <= 7,  "Best value",
    IF(Score >= 60 && Payback <= 10, "Good investment",
    IF(Payback > 15,                 "Long payback — review",
    "Consider alternatives")))


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 7 — CUMULATIVE KPIs (for summary cards and trend line)
// ─────────────────────────────────────────────────────────────────────────────

// Total cumulative savings to date (€)
[Total Savings to Date EUR] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
RETURN
    CALCULATE(
        MAX(gold_battery_daily_summary[total_cost_avoided_eur]),
        gold_battery_daily_summary[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )


// Total CO₂ avoided to date (tonnes)
[Total CO2 Avoided tCO2] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
VAR TotalKg =
    CALCULATE(
        MAX(gold_battery_daily_summary[total_co2_avoided_kg]),
        gold_battery_daily_summary[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )
RETURN
    IFERROR(TotalKg / 1000, BLANK())


// Total cycle count to date
[Total Cycles to Date] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
RETURN
    CALCULATE(
        MAX(gold_battery_daily_summary[total_cycles_cumulative]),
        gold_battery_daily_summary[building_id] = SelectedBuilding
            || ISBLANK(SelectedBuilding)
    )


// Estimated remaining battery life (years)
[Estimated Life Remaining Years] =
VAR TotalCycles     = [Total Cycles to Date]
VAR BattType        = SELECTEDVALUE(gold_battery_dispatch[battery_type])
VAR DesignCycles    = IF(BattType = "LFP", 6000, IF(BattType = "NMC", 3000, 4000))
VAR CyclesRemaining = MAX(0, DesignCycles - TotalCycles)
// Estimate: assume 1 full cycle per day average usage
VAR DaysRemaining   = CyclesRemaining / 0.4  -- 0.4 cycles/day typical commercial use
RETURN
    IFERROR(DaysRemaining / 365, BLANK())


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 8 — EU COMPLIANCE SUMMARY
// ─────────────────────────────────────────────────────────────────────────────

// Buildings with EU-compliant batteries (count)
[EU Compliant Buildings Count] =
CALCULATE(
    DISTINCTCOUNT(gold_battery_dispatch[building_id]),
    gold_battery_dispatch[eu_compliant] = TRUE()
)


// Buildings with non-compliant batteries (count + flag for alert)
[Non EU Compliant Buildings Count] =
CALCULATE(
    DISTINCTCOUNT(gold_battery_dispatch[building_id]),
    gold_battery_dispatch[eu_compliant] = FALSE(),
    gold_battery_dispatch[is_simulated] = FALSE()  -- only actual installed batteries
)


// EU compliance portfolio summary label
[EU Compliance Portfolio Label] =
VAR Compliant    = [EU Compliant Buildings Count]
VAR NonCompliant = [Non EU Compliant Buildings Count]
RETURN
    IF(
        NonCompliant > 0,
        FORMAT(NonCompliant, "0") & " bldg non-compliant (EU 2023/1542)",
        "All batteries EU-compliant"
    )


// ─────────────────────────────────────────────────────────────────────────────
// SECTION 9 — SLICER SUPPORT MEASURES
// ─────────────────────────────────────────────────────────────────────────────

// Is the selected building a simulated scenario (no physical battery)?
[Is Simulated Building] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
RETURN
    CALCULATE(
        MAX(gold_battery_dispatch[is_simulated]),
        gold_battery_dispatch[building_id] = SelectedBuilding
    )


// Active (installed) strategy label for card subtitle
[Active Strategy Label] =
VAR SelectedBuilding = SELECTEDVALUE(silver_building_master[building_id])
VAR ActiveStrat =
    CALCULATE(
        MAXX(
            FILTER(gold_battery_simulation,
                gold_battery_simulation[is_active_strategy] = TRUE()),
            gold_battery_simulation[strategy_label]
        ),
        gold_battery_simulation[building_id] = SelectedBuilding
    )
RETURN
    IF(ISBLANK(ActiveStrat), "Simulation only", "Active: " & ActiveStrat)


// Data currency label (last date in dispatch table)
[Page9 Data As Of] =
"Data as of: " & FORMAT(MAX(gold_battery_dispatch[date]), "DD MMM YYYY")


// =============================================================================
// END OF v47 DAX MEASURES — PAGE 9
// =============================================================================
//
// BINDING REFERENCE (for Power BI Desktop):
//   C1 card  → [C1 Annual Savings EUR]           reference label: [C1 Label Savings]
//   C2 card  → [C2 Payback Years]                reference label: [C2 Label Payback]
//   C3 card  → [C3 CO2 Avoided tCO2 Annual]      reference label: [C3 Label CO2]
//   C4 card  → [C4 Round Trip Efficiency Pct]    reference label: [C4 Label Efficiency]
//
//   V1 area  → Y: [V1 SoC End Percent]  X: date  Legend: strategy
//              Add reference line at 10% (min SoC)
//   V2 bar   → Y1: [V2 Charge kWh Daily]  Y2: [V2 Discharge kWh Daily]  X: date
//              Add line: [V2 PV Generation kWh]
//   V3 table → Columns from gold_battery_simulation + [V3 EU Compliance Label]
//              Conditional format: eu_compliant (green/red), comparison_score (data bar)
//   V4 gauge → Value: [V4 ROI Gauge Pct]  Max: 150  Target: 100
//   V5 scatter→ X: [V5 Battery Cost EUR]  Y: [V5 Payback Years]
//              Size: [V5 Capacity kWh]     Color: [V5 Comparison Score]
//
// SLICERS FOR PAGE 9:
//   S1 → silver_building_master[building_name]  (only buildings with PV: B001,B003,B004,B005,B006)
//   S2 → gold_battery_dispatch[strategy]
//   S3 → date range slicer on gold_battery_dispatch[date]
// =============================================================================
