// ============================================================
// Energy Copilot Platform — Page 9 Battery Dispatch & Financial Simulation
// DAX Measures — Version 48
// Layout: v2 (left sidebar + 5 visuals, 2026-05-08)
// Total measures: 32  (unchanged from v47, reorganised by visual position)
// ============================================================
//
// VISUAL MAP (new layout)
// ───────────────────────────────────────────────────────────────
//  LEFT SIDEBAR
//    Active Strategy card  →  [Active Strategy Label], [Page9 Data As Of]
//    EU Compliance card    →  [EU Compliance Portfolio Label]
//
//  KPI CARDS (top row)
//    C1  x:215  →  [C1 Annual Savings EUR],  [C1 Label Savings]
//    C2  x:483  →  [C2 Payback Years],        [C2 Label Payback]
//    C3  x:751  →  [C3 CO2 Avoided tCO2 Annual], [C3 Label CO2]
//    C4  x:1019 →  [C4 Round Trip Efficiency Pct], [C4 Label Efficiency]
//
//  MIDDLE ROW
//    V1  x:215  y:188  w:635  →  [V1 SoC End Percent], [V1 SoC Start Percent]
//    V4  x:858  y:188  w:409  →  [V4 ROI Gauge Pct], [V4 ROI Status Label]
//    V2  x:858  y:304  w:409  →  [V2 Charge kWh Daily], [V2 Discharge kWh Daily],
//                                 [V2 PV Generation kWh], [V2 Grid Charge kWh Daily],
//                                 [V2 PV Charge kWh Daily], [V2 Net Savings EUR Daily]
//
//  BOTTOM ROW
//    V5  x:215  y:423  w:370  →  [V5 Battery Cost EUR], [V5 Payback Years],
//                                 [V5 Capacity kWh], [V5 Comparison Score], [V5 Quadrant Label]
//    V3  x:593  y:423  w:674  →  [V3 NPV Display], [V3 EU Compliance Label],
//                                 [V3 Payback Status]
//
//  SLICERS
//    S1 → silver_building_master[building_name]  (Building)
//    S2 → gold_battery_dispatch[strategy]        (Strategy)
//    S3 → gold_battery_dispatch[date]            (Date Range)
// ============================================================


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 0 — LEFT SIDEBAR CARDS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SIDEBAR: Active Strategy card — top text line
// Visual: Card text visual in left sidebar  |  Field: Value
Active Strategy Label =
VAR _ActiveRows =
    FILTER(
        gold_battery_dispatch,
        gold_battery_dispatch[is_simulated] = FALSE
    )
VAR _TopBuilding =
    TOPN(1,
        SUMMARIZE(_ActiveRows,
            gold_battery_dispatch[building_name],
            gold_battery_dispatch[strategy],
            "savings", SUM(gold_battery_dispatch[net_savings_eur])
        ),
        [savings], DESC
    )
RETURN
    CONCATENATEX(
        _TopBuilding,
        gold_battery_dispatch[building_name] & " — " & gold_battery_dispatch[strategy],
        ", "
    )

// SIDEBAR: Active Strategy card — date subtitle
// Visual: Card text visual  |  Field: Reference label / subtitle
Page9 Data As Of =
"Data as of " &
FORMAT(
    CALCULATE(MAX(gold_battery_dispatch[date])),
    "DD MMM YYYY"
)

// SIDEBAR: EU Compliance summary badge
// Visual: Card text visual  |  Field: Value
// Conditional format: Green if 0 non-compliant, Red if > 0
EU Compliance Portfolio Label =
VAR _NonCompliant =
    CALCULATE(
        DISTINCTCOUNT(gold_battery_dispatch[building_id]),
        gold_battery_dispatch[eu_compliant] = FALSE
    )
VAR _Total =
    CALCULATE(
        DISTINCTCOUNT(gold_battery_dispatch[building_id]),
        gold_battery_dispatch[eu_compliant] <> BLANK()
    )
RETURN
    IF(
        _NonCompliant = 0,
        FORMAT(_Total, "0") & " / " & FORMAT(_Total, "0") & " buildings EU OK",
        FORMAT(_NonCompliant, "0") & " NON-COMPLIANT building(s) — action required"
    )


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 1 — C1: ANNUAL SAVINGS CARD  (x:215 y:72 w:260 h:108)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Value (callout number)
// Format: € #,##0 "/ yr"   |  Green > €5k, Amber €1k–5k, Grey < €1k
C1 Annual Savings EUR =
VAR _MaxDate = CALCULATE(MAX(gold_battery_dispatch[date]))
VAR _MinDate = DATE(YEAR(_MaxDate) - 1, MONTH(_MaxDate), DAY(_MaxDate))
VAR _Days =
    CALCULATE(
        COUNTROWS(gold_battery_dispatch),
        gold_battery_dispatch[date] >= _MinDate,
        gold_battery_dispatch[date] <= _MaxDate
    )
VAR _Sum =
    CALCULATE(
        SUM(gold_battery_dispatch[net_savings_eur]),
        gold_battery_dispatch[date] >= _MinDate,
        gold_battery_dispatch[date] <= _MaxDate
    )
RETURN
    IF(_Days > 0, _Sum / _Days * 365, BLANK())

// SLOT: Reference label (subtitle below number)
C1 Label Savings =
VAR _s = [C1 Annual Savings EUR]
RETURN
    IF(_s > 5000, "Excellent ROI",
    IF(_s > 1000, "Moderate savings",
    IF(_s > 0,    "Low savings — review strategy",
    "No data")))


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 2 — C2: PAYBACK PERIOD CARD  (x:483 y:72 w:260 h:108)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Value  |  Format: #,##0.0 "yr"
// Conditional: Green ≤ 7yr, Amber 7–12yr, Red > 12yr
C2 Payback Years =
CALCULATE(
    AVERAGE(gold_battery_simulation[payback_years]),
    gold_battery_simulation[is_active_strategy] = TRUE
)

// SLOT: Reference label
C2 Label Payback =
VAR _p = [C2 Payback Years]
RETURN
    IF(_p <= 7,  "Good — below 7yr threshold",
    IF(_p <= 12, "Acceptable — monitor closely",
    IF(_p <= 25, "Poor — consider alternative strategy",
    "No active strategy")))


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 3 — C3: CO2 AVOIDED CARD  (x:751 y:72 w:260 h:108)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Value  |  Format: #,##0.0 "tCO₂ / yr"
C3 CO2 Avoided tCO2 Annual =
VAR _MaxDate = CALCULATE(MAX(gold_battery_dispatch[date]))
VAR _MinDate = DATE(YEAR(_MaxDate) - 1, MONTH(_MaxDate), DAY(_MaxDate))
VAR _Days =
    CALCULATE(
        COUNTROWS(gold_battery_dispatch),
        gold_battery_dispatch[date] >= _MinDate,
        gold_battery_dispatch[date] <= _MaxDate
    )
VAR _KgSum =
    CALCULATE(
        SUM(gold_battery_dispatch[co2_avoided_kg]),
        gold_battery_dispatch[date] >= _MinDate,
        gold_battery_dispatch[date] <= _MaxDate
    )
RETURN
    IF(_Days > 0, (_KgSum / _Days * 365) / 1000, BLANK())

// SLOT: Reference label
C3 Label CO2 =
VAR _t = [C3 CO2 Avoided tCO2 Annual]
RETURN
    FORMAT(_t, "#,##0.1") & " tCO₂ avoided per year"


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 4 — C4: EFFICIENCY + EU STATUS  (x:1019 y:72 w:248 h:108)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Value  |  Format: #,##0.0 "%"
C4 Round Trip Efficiency Pct =
CALCULATE(
    AVERAGE(gold_battery_dispatch[round_trip_efficiency]) * 100,
    gold_battery_dispatch[is_simulated] = FALSE
)

// SLOT: Reference label / subtitle
// Shows EU compliance flag inline with efficiency
C4 Label Efficiency =
VAR _eff = [C4 Round Trip Efficiency Pct]
VAR _IsEU =
    CALCULATE(
        MIN(gold_battery_dispatch[eu_compliant]),
        gold_battery_dispatch[is_simulated] = FALSE
    )
RETURN
    IF(_eff >= 94, "LFP — high efficiency",
    IF(_eff >= 90, "NMC/NCA — moderate",
    "Check battery type")) &
    IF(_IsEU = TRUE, " · EU OK", " · NON-EU — replace at maintenance")


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 5 — V1: STATE OF CHARGE TREND  (x:215 y:188 w:635 h:225)
//           Visual type: Area chart (or Line chart)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Y-axis (primary series, area)
// X-axis: gold_battery_dispatch[date]
// Legend: gold_battery_dispatch[strategy]
V1 SoC End Percent =
AVERAGE(gold_battery_dispatch[soc_end_pct])

// SLOT: Secondary line (dashed, secondary Y)
// Add as additional Y-axis series — set line style to dashed
V1 SoC Start Percent =
AVERAGE(gold_battery_dispatch[soc_start_pct])

// Reference line: add constant line at Y = 10 labelled "Min SoC (10%)"
// Color: Red  |  Style: Dashed
// Do NOT add as a measure — use the Analytics pane → Constant Line → Value: 10

// Series colors to set manually in Format → Data colors:
//   self_consumption → #2ECC71  (green)
//   peak_shaving     → #F4A62A  (amber)
//   tou              → #3498DB  (blue)
//   backup           → #9B59B6  (purple)

// Edit interactions:
//   S1 Building → Cross-filter V1
//   S2 Strategy → Cross-filter V1
//   S3 Date     → Cross-filter V1
//   V3 Table row click → Cross-filter V1


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 6 — V4: ROI GAUGE  (x:858 y:188 w:409 h:108)
//           Visual type: Gauge
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Value (needle position)   |  Format: #,##0 "%"
// Min: 0  |  Max: 150  |  Target: 100
// Color: Green > 100, Amber 70–100, Red < 70
V4 ROI Gauge Pct =
VAR _Savings = [C1 Annual Savings EUR]
VAR _Capex =
    CALCULATE(
        AVERAGE(gold_battery_simulation[total_capex_eur]),
        gold_battery_simulation[is_active_strategy] = TRUE
    )
VAR _Payback = DIVIDE(_Capex, _Savings, 25)
RETURN
    // 100% = payback exactly at 10yr target; > 100 = faster than target
    IF(_Payback > 0, DIVIDE(10, _Payback) * 100, BLANK())

// SLOT: Callout value (number in gauge centre)
// Use: [C1 Annual Savings EUR]  (shows € savings as context number)

// SLOT: Subtitle below gauge
V4 ROI Status Label =
VAR _p = [V4 ROI Gauge Pct]
RETURN
    IF(_p >= 100, "On target — excellent ROI",
    IF(_p >= 70,  "Acceptable — 7-12yr payback",
    IF(_p > 0,    "Below target — review strategy",
    "No active battery")))


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 7 — V2: DAILY CHARGE / DISCHARGE  (x:858 y:304 w:409 h:109)
//           Visual type: Clustered Bar Chart + Line overlay
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Y-axis bar 1 — Charge  |  Color: #2980B9
// X-axis: gold_battery_dispatch[date]
V2 Charge kWh Daily =
SUM(gold_battery_dispatch[charge_kwh])

// SLOT: Y-axis bar 2 — Discharge  |  Color: #F39C12
V2 Discharge kWh Daily =
SUM(gold_battery_dispatch[discharge_kwh])

// SLOT: Line overlay — PV Generation  |  Color: #F1C40F, dashed
V2 PV Generation kWh =
SUM(gold_battery_dispatch[pv_generation_kwh])

// SLOT: Tooltip field 1
V2 Grid Charge kWh Daily =
SUM(gold_battery_dispatch[grid_charge_kwh])

// SLOT: Tooltip field 2
V2 PV Charge kWh Daily =
SUM(gold_battery_dispatch[pv_charge_kwh])

// SLOT: Tooltip field 3  |  Format: € #,##0.00
V2 Net Savings EUR Daily =
SUM(gold_battery_dispatch[net_savings_eur])


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 8 — V5: CAPEX vs PAYBACK SCATTER  (x:215 y:423 w:370 h:287)
//           Visual type: Scatter Chart
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: X-axis  |  Axis title: "Battery CAPEX (€)"
V5 Battery Cost EUR =
AVERAGE(gold_battery_simulation[total_capex_eur])

// SLOT: Y-axis  |  Axis title: "Simple Payback (years)"
V5 Payback Years =
AVERAGE(gold_battery_simulation[payback_years])

// SLOT: Size (bubble diameter = battery capacity)
V5 Capacity kWh =
AVERAGE(gold_battery_simulation[battery_capacity_kwh])

// SLOT: Color saturation (green = high score, red = low score)
V5 Comparison Score =
AVERAGE(gold_battery_simulation[comparison_score])

// SLOT: Details / Legend (one bubble per scenario)
// Use: gold_battery_simulation[scenario_id]  (text field — no measure needed)

// SLOT: Tooltip  |  Format: Text
V5 Quadrant Label =
VAR _cost  = [V5 Battery Cost EUR]
VAR _years = [V5 Payback Years]
RETURN
    IF(_years <= 7  && _cost <= 100000, "Best buy — low cost, fast payback",
    IF(_years <= 7  && _cost >  100000, "Premium — expensive but fast payback",
    IF(_years <= 12 && _cost <= 100000, "Acceptable — cheap but slow",
    "Avoid — high cost, long payback")))

// Reference lines (Analytics pane — no measure needed):
//   Horizontal at Y = 7:  "7yr threshold"  color #27AE60 dashed
//   Horizontal at Y = 12: "Max acceptable" color #E74C3C dashed


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 9 — V3: SCENARIO COMPARISON TABLE  (x:593 y:423 w:674 h:287)
//           Visual type: Table
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// SLOT: Column "NPV 10yr"  |  Format: Text (pre-formatted with sign)
V3 NPV Display =
VAR _npv = AVERAGE(gold_battery_simulation[npv_10yr_eur])
RETURN
    IF(ISBLANK(_npv), "—",
    IF(_npv >= 0,
        "+" & FORMAT(_npv / 1000, "#,##0.0") & "k",
        FORMAT(_npv / 1000, "#,##0.0") & "k"
    ))

// SLOT: Column "EU Compliance"  |  Conditional format: Green / Red
// Format rule: IF value = "EU Compliant" → green background  |  "NON-COMPLIANT" → red
V3 EU Compliance Label =
VAR _IsEU = MIN(gold_battery_simulation[eu_compliant])
RETURN
    IF(_IsEU = TRUE, "EU Compliant", "NON-COMPLIANT")

// SLOT: Column "Payback" conditional format helper
// Apply as background color rule to the Payback column
V3 Payback Status =
VAR _p = AVERAGE(gold_battery_simulation[payback_years])
RETURN
    IF(_p <= 7, 1,      // Green
    IF(_p <= 12, 2,     // Amber
    3))                 // Red
// Color rule: 1 → #D4EDDA background, 2 → #FFF3CD, 3 → #F8D7DA

// TABLE COLUMNS (in order — all from gold_battery_simulation unless noted):
//  1. Building name     → silver_building_master[building_name]
//  2. Strategy label    → gold_battery_simulation[strategy_label]
//  3. Battery type      → gold_battery_simulation[battery_type]
//  4. Capacity (kWh)    → gold_battery_simulation[battery_capacity_kwh]
//  5. CAPEX (€)         → gold_battery_simulation[total_capex_eur]
//  6. Ann. Savings (€)  → gold_battery_simulation[annual_savings_eur]
//  7. Payback (yr)      → gold_battery_simulation[payback_years]  + [V3 Payback Status] cond.format
//  8. NPV 10yr          → [V3 NPV Display]
//  9. IRR (%)           → gold_battery_simulation[irr_percent]
// 10. CO₂ (tCO₂/yr)    → gold_battery_simulation[annual_co2_avoided_kg]  ÷ 1000
// 11. EU Compliance     → [V3 EU Compliance Label]  + conditional format
// 12. Score             → gold_battery_simulation[comparison_score]  as Data Bar 0–100

// Sort: comparison_score DESC
// Row highlight: gold_battery_simulation[is_active_strategy] = TRUE → Bold text
// Row filter: Add visual-level filter: building_id NOT IN (B002)


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// GROUP 10 — SLICERS (left sidebar)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

// S1 — Building Slicer
// Visual type: Dropdown  |  Position: sidebar y:88
// Field: silver_building_master[building_name]
// Filter: building_id IN (B001, B003, B004, B005, B006)  — exclude B002

// S2 — Strategy Slicer
// Visual type: List  |  Position: sidebar y:134
// Field: gold_battery_dispatch[strategy]

// S3 — Date Range Slicer
// Visual type: Between  |  Position: sidebar y:180
// Field: gold_battery_dispatch[date]


// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// INTERACTION MATRIX
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
//            → C1 C2 C3 C4  V1 V4 V2  V5 V3
//  S1 Bldg   →  F  F  F  F   F  F  F   F  F    (Filter all)
//  S2 Strat  →  F  F  F  F   F  F  F   F  F    (Filter all)
//  S3 Date   →  F  –  F  F   F  –  F   –  –    (Filter dispatch-based visuals)
//  V3 click  →  F  –  –  –   F  F  F   H  –    (H = highlight)
//
//  F = cross-filter  |  H = highlight  |  – = no interaction
