// =============================================================================
// DAX PATCH — v52 — EU Compliance Label (final working version)
// File    : 63_dax_v52_eu_compliance_fix.dax
// Date    : 2026-05-09
//
// PROBLEM: Previous versions failed because:
//   - gold_battery_simulation[eu_compliant] stores text "True"/"False" in Direct Lake
//   - CALCULATE with boolean || in filter predicate is unreliable in Direct Lake
//
// FIX: Avoid all boolean comparison. Count compliant (eu_compliant = "True"),
//      subtract from total. No FALSE()/TRUE() used anywhere.
//
// ALSO INCLUDED: [V6 Hourly SoC Label] — measure for the new hourly chart
//   subtitle, showing the strategy's charging logic in one line.
// =============================================================================


// ─────────────────────────────────────────────────────────────────────────────
// EU Compliance Portfolio Label — v52 (text-only, no boolean comparison)
//
// Bind to: Card subtitle under [Active Battery Label]
// Output:
//   "1 NON-COMPLIANT · EU 2023/1670"   (if Frankfurt B005 NMC battery selected)
//   "All batteries EU-compliant ✓"     (if LFP-only building selected)
// ─────────────────────────────────────────────────────────────────────────────

[EU Compliance Portfolio Label] =
VAR TotalBuildings =
    DISTINCTCOUNT(gold_battery_simulation[building_id])
VAR CompliantBuildings =
    CALCULATE(
        DISTINCTCOUNT(gold_battery_simulation[building_id]),
        gold_battery_simulation[eu_compliant] = "True"
    )
VAR NonCompliant = TotalBuildings - CompliantBuildings
RETURN
    IF(
        ISBLANK(TotalBuildings) || TotalBuildings = 0,
        "No battery data",
        IF(
            NonCompliant > 0,
            FORMAT(NonCompliant, "0") & " NON-COMPLIANT · EU 2023/1670",
            "All batteries EU-compliant ✓"
        )
    )


// ─────────────────────────────────────────────────────────────────────────────
// V6 Hourly Chart Strategy Label
// Bind to: subtitle of the new Hourly Battery Behavior chart
// Shows a one-line explanation of WHY the selected strategy charges when it does.
// ─────────────────────────────────────────────────────────────────────────────

[V6 Strategy Logic Label] =
VAR SelStrat = SELECTEDVALUE(gold_battery_dispatch[strategy])
RETURN
    SWITCH(
        SelStrat,
        "peak_shaving",
            "Charges 00h–07h (night, off-peak) · Discharges 07h–20h (building demand peaks)",
        "self_consumption",
            "Charges 10h–15h (PV generation) · Discharges 18h–23h (evening load)",
        "tou",
            "Charges 00h–07h (cheapest EPEX hours) · Discharges 08h–20h (expensive hours)",
        "backup",
            "Maintains 80–90% SoC always · Small opportunistic discharge during peak hours",
        "Select a strategy (S2) to see its logic"
    )


// =============================================================================
// HOW TO APPLY v52
//
// 1. Modeling → New Measure → paste [EU Compliance Portfolio Label]
//    (if old version exists, delete it first)
//
// 2. Bind to Active Battery Label card:
//    Click the battery info card → Format Visual → Subtitle → Field:
//    Select [EU Compliance Portfolio Label]
//
// 3. Test:
//    Select Frankfurt (B005, NMC) → subtitle should show "1 NON-COMPLIANT · EU 2023/1670"
//    Select Hamburg (B003, LFP)   → subtitle should show "All batteries EU-compliant ✓"
//
// 4. New Measure → paste [V6 Strategy Logic Label]
//    Bind to: subtitle of the new Hourly Battery Behavior chart (after adding it)
// =============================================================================
