// ==========================================================================
// Energy Copilot Platform — DAX v53: Page 4 Final Polish
// File: semantic-model/65_dax_v53_page4_final_polish.dax
// Last updated: 2026-05-18
//
// AMAÇ:
//   Sayfa 4 (Forecast & Recommendations) production-ready hâle getirir.
//   Trial deadline (2026-05-21) öncesi son cila — yeni görsel YOK,
//   mevcut layout korunur, sadece domain enrichment + UX polish.
//
// EKLENECEKLER (4 measure cluster):
//   1. Forecast Emission Factor (CO2 intensity baseline)
//   2. Forecast CO2 7Day / 30Day (tCO2 — CSRD/Scope 2 framing)
//   3. C5 MAPE Portfolio Context Label (tek-bina filtresi şüpheli iyi görünmesin)
//   4. C2 Subtitle Label (PY karşılaştırma context'i)
//
// YAPILMAYACAKLAR (kapsam dışı — Phase 2 backlog):
//   - "What if" senaryo simülasyonu (Page 9 batarya senaryolarına benzer mantık)
//   - V11 drill-through to building detail (cross-page navigation)
//   - V5 → "Forecast Accuracy Trend" replace (mevcut MAPE distribution yararlı)
//   - Yeni KPI kartı (5'ten 6'ya çıkmak layout'u bozar)
//
// VERİ TEMELİ:
//   gold_kpi_daily.emission_factor_kg_kwh — ülke/grid bazında kg CO2/kWh
//     (DE: ~0.37, AT: ~0.15, TR: ~0.44, NL: ~0.34 — 2024 ortalamaları)
//   gold_kpi_daily.co2_emissions_kg — günlük actual emissions
//   gold_consumption_forecast.predicted_kwh — Prophet tahmin
//
// MANTIK:
//   Forecast CO2 = Forecast kWh × Avg Emission Factor (son 30 gün)
//   "Son 30 gün" pencere seçildi çünkü grid mix mevsimsel değişir
//   (yaz: solar+wind ağırlık, kış: gaz ağırlık) — yakın tarihli ortalama
//   daha temsili.
//
// KURULUM:
//   Tabular Editor → C# Script → idempotent add script (aşağıda)
//   Power BI Desktop → Refresh → tooltip binding (UI adımları aşağıda)
//
// ETKİLENEN SAYFALAR: Sayfa 4 (Forecast & Recommendations)
// ==========================================================================


// ==========================================================================
// BÖLÜM 1 — EMISSION FACTOR BASELINE
//
// Son 30 günün ortalama emission factor'unu hesaplar.
// Slicer'dan bağımsız (REMOVEFILTERS) — forecast hesabı tutarlı kalsın.
// Building slicer korunur — bina seçilince o binanın grid bölgesi gelir.
// ==========================================================================

// Son 30 gün ortalama grid emission factor (kg CO2 / kWh)
// Format: "0.000"
Avg Emission Factor kg per kWh =
VAR _maxDate = MAXX ( ALL ( gold_kpi_daily ), gold_kpi_daily[date] )
VAR _start = _maxDate - 29
VAR _avg =
    CALCULATE (
        AVERAGE ( gold_kpi_daily[emission_factor_kg_kwh] ),
        gold_kpi_daily[date] >= _start,
        gold_kpi_daily[date] <= _maxDate,
        REMOVEFILTERS ( 'Date' )
    )
RETURN
    IF ( NOT ISBLANK ( _avg ) && _avg > 0, _avg, 0.30 )
// FALLBACK: 0.30 kg/kWh = EU-27 ortalaması (2024, Eurostat)
// Bu fallback sadece veri tamamen yoksa devreye girer — güvenlik ağı


// ==========================================================================
// BÖLÜM 2 — FORECAST CO2 EMISSIONS
//
// 7-Day ve 30-Day forecast CO2 emisyonları.
// CSRD (EU 2023) Scope 2 raporlaması için doğrudan kullanılabilir.
// V4 chart tooltip'inde ve C1/C2 tooltip'lerinde gösterilir.
// ==========================================================================

// 7 günlük tahmin emisyonu (kg CO2)
// Format: "#,##0"
Forecast CO2 7Day kg =
VAR _kwh = [Forecast 7Day kWh]
VAR _factor = [Avg Emission Factor kg per kWh]
RETURN
    IF (
        NOT ISBLANK ( _kwh ) && _factor > 0,
        ROUND ( _kwh * _factor, 0 ),
        BLANK ()
    )


// 7 günlük tahmin emisyonu (tCO2 — yönetici dilinde)
// Format: "0.00"
Forecast CO2 7Day tCO2 =
DIVIDE ( [Forecast CO2 7Day kg], 1000 )


// 30 günlük tahmin emisyonu (kg CO2)
// Format: "#,##0"
Forecast CO2 30Day kg =
VAR _kwh = [Forecast 30Day kWh]
VAR _factor = [Avg Emission Factor kg per kWh]
RETURN
    IF (
        NOT ISBLANK ( _kwh ) && _factor > 0,
        ROUND ( _kwh * _factor, 0 ),
        BLANK ()
    )


// 30 günlük tahmin emisyonu (tCO2)
// Format: "0.0"
Forecast CO2 30Day tCO2 =
DIVIDE ( [Forecast CO2 30Day kg], 1000 )


// 30 günlük PY karşılaştırma — geçen yıl aynı 30 günün CO2'si
// Format: "0.0"
Forecast CO2 30Day PY tCO2 =
VAR _last  = MAXX ( ALL ( gold_consumption_forecast ), gold_consumption_forecast[forecast_date] )
VAR _start = _last - 29
VAR _pyLast  = DATE ( YEAR ( _last ) - 1, MONTH ( _last ), DAY ( _last ) )
VAR _pyStart = DATE ( YEAR ( _start ) - 1, MONTH ( _start ), DAY ( _start ) )
VAR _co2 = CALCULATE (
    SUM ( gold_kpi_daily[co2_emissions_kg] ),
    gold_kpi_daily[date] >= _pyStart,
    gold_kpi_daily[date] <= _pyLast,
    REMOVEFILTERS ( 'Date' )
)
RETURN
    IF ( ISBLANK ( _co2 ), BLANK (), ROUND ( _co2 / 1000, 1 ) )


// Forecast vs PY CO2 delta (% — pozitif = artış, negatif = azalış)
// Format: "+0.0%;-0.0%;—"
Forecast CO2 Delta Pct =
VAR _this = [Forecast CO2 30Day tCO2]
VAR _py   = [Forecast CO2 30Day PY tCO2]
RETURN
    IF (
        NOT ISBLANK ( _this ) && NOT ISBLANK ( _py ) && _py > 0,
        ROUND ( DIVIDE ( _this - _py, _py ) * 100, 1 ),
        BLANK ()
    )


// CO2 status label — V4 tooltip veya kart subtitle için
// Format: metin
Forecast CO2 Status Label =
VAR _delta = [Forecast CO2 Delta Pct]
RETURN
    SWITCH (
        TRUE (),
        ISBLANK ( _delta ),         "— No comparison data",
        _delta <= -5,               "🟢 Lower than last year (-" & FORMAT ( ABS(_delta), "0.0" ) & "%)",
        _delta < 5,                 "🟡 Similar to last year (Δ " & FORMAT ( _delta, "+0.0;-0.0;0" ) & "%)",
        _delta < 15,                "🟠 Higher than last year (+" & FORMAT ( _delta, "0.0" ) & "%)",
                                    "🔴 Significantly higher (+" & FORMAT ( _delta, "0.0" ) & "%) — review usage"
    )


// ==========================================================================
// BÖLÜM 3 — C5 MAPE PORTFOLIO CONTEXT
//
// SORUN:
//   Tek bina filtre seçildiğinde C5 MAPE çok düşük gösterir (örn. 1.0% Frankfurt).
//   Bu yanıltıcıdır — gerçekte portföy ortalaması daha yüksek olabilir (~7%).
//
// ÇÖZÜM:
//   Tooltip alanına portfolyo bağlamı ekle.
//   "Selected: X% | Portfolio avg: Y%" formatında.
//   ALL() ile slicer'dan bağımsız global ortalama.
// ==========================================================================

// Portföy ortalama MAPE (tüm binalar, slicer'dan bağımsız)
// Format: "0.0"
Portfolio Avg MAPE Pct =
CALCULATE (
    AVERAGE ( gold_consumption_forecast[model_mape_pct] ),
    REMOVEFILTERS ( 'Date' ),
    REMOVEFILTERS ( silver_building_master )
)


// C5 tooltip için context label
// "Selected: 1.0% | Portfolio avg: 7.2%" şeklinde tek satır
// Format: metin
MAPE Context Label =
VAR _selected = CALCULATE (
    AVERAGE ( gold_consumption_forecast[model_mape_pct] ),
    REMOVEFILTERS ( 'Date' )
)
VAR _portfolio = [Portfolio Avg MAPE Pct]
RETURN
    IF (
        NOT ISBLANK ( _selected ) && NOT ISBLANK ( _portfolio ),
        "Selected: " & FORMAT ( _selected, "0.0" ) & "% | Portfolio avg: " & FORMAT ( _portfolio, "0.0" ) & "%",
        IF (
            NOT ISBLANK ( _portfolio ),
            "Portfolio avg: " & FORMAT ( _portfolio, "0.0" ) & "%",
            "— No MAPE data"
        )
    )


// ==========================================================================
// BÖLÜM 4 — C2 SUBTITLE LABEL (PY context)
//
// C2 30-Day Forecast kartı %18.6 sapma gösterirken context vermiyor.
// "vs same 30-day period last year" mesajı PY karşılaştırma anlamını netleştirir.
// ==========================================================================

C2 PY Context Label =
VAR _forecast = [Forecast 30Day kWh]
VAR _py       = [Forecast 30Day PY kWh]
RETURN
    IF (
        NOT ISBLANK ( _forecast ) && NOT ISBLANK ( _py ),
        "vs " & FORMAT ( _py, "#,##0" ) & " kWh same period last year",
        "vs prior year (no data)"
    )


// ==========================================================================
// KURULUM REHBERİ — POWER BI ADIMLAR
// ==========================================================================
//
// ADIM 1 — Tabular Editor C# Script ile measure'ları ekle
//   (idempotent — aynı isim varsa update eder)
//
//   string homeTable = "gold_kpi_daily";  // CO2 measure'ları için
//   string recTable  = "gold_recommendations";  // (yok, sadece referans)
//   ... script aşağıdaki TE Script bölümünde
//
// ADIM 2 — V11 (Payback vs Savings) — visual filter fix
//   V11 seç → Filters pane → Rec Has Financial Data
//   "is less than 1" → "is 1" olarak değiştir (veya Basic filtering, 1 checked)
//
// ADIM 3 — V4 (Monthly Consumption) — forecast başlangıç dikey çizgi
//   V4 seç → Format pane → Analytics → Constant line → + Add line
//     Value: [Actual Data End Date Numeric] (v26'da yazıldı, kullan)
//     Color: #FFC107 (amber) | Style: Dashed | Width: 2px
//     Data label: ON → text "Forecast →" | position: above right
//   Eğer measure binding hatası: manuel tarih gir (örn. 2026-04-18)
//
// ADIM 4 — V4 tooltip enhancement
//   V4 seç → Visualizations pane → Tooltips → + Add fields:
//     Forecast CO2 30Day tCO2
//     Forecast CO2 Status Label
//     Forecast Cost 30Day EUR (v25'te yazıldı — varsa kullan)
//   Sonuç: V4 üzerinde hover → ay başına kWh + tCO2 + EUR + status
//
// ADIM 5 — C5 (Avg MAPE %) — portfolio context tooltip
//   C5 seç → Visualizations pane → Tooltips → + Add field:
//     MAPE Context Label
//   Sonuç: C5 hover → "Selected: 1.0% | Portfolio avg: 7.2%"
//
// ADIM 6 — C2 (30-Day Forecast kWh) — subtitle açıklama
//   C2 seç → Format pane → Callout subtitle → Text:
//     "vs same 30-day period last year"
//   Veya tooltip: C2 PY Context Label measure'ını tooltip alanına bağla
//
// ADIM 7 — Edit Interactions kontrolü
//   Format → Edit Interactions (canvas boş alanına tıklı durumdayken)
//   "Date Range" slicer'ı seç → V4 üstündeki ikonu None (zincir kırık) yap
//   Date Range V4'ü filtrelemesin (V4 kendi DAX'ında REMOVEFILTERS'la zaten korunuyor ama UI'da güvenlik)
//
// ==========================================================================
// DOĞRULAMA (Tüm filtre temizliğinde, all buildings)
//
// ✅ C1: 7-Day forecast ~140-160K kWh portfolyo
// ✅ C2: 30-Day forecast ~600-700K kWh, subtitle "vs same period last year"
// ✅ C3: Savings Potential CRITICAL ~€362K / €300K (+20%)
// ✅ C4: 5 CRITICAL portfolyo bazında
// ✅ C5: MAPE 5-10%, hover tooltip "Portfolio avg: 7.2%"
// ✅ V4: Mavi+mor sütunlar, sarı PY çizgi, amber "Forecast →" çizgi,
//       hover tooltip kWh+tCO2+EUR+status
// ✅ V5: 6 bina çubuğu, B006 amber, B005 yeşil
// ✅ V10: 30+ recommendation tablo
// ✅ V11: ~25 finansal scatter noktası (compliance hariç)
// ✅ V12: 5/9/13/7/3 priority distribution
// ==========================================================================

// SON
