// ════════════════════════════════════════════════════════════════════
// PAGE 5 — SURGICAL FIX (v55)
// ════════════════════════════════════════════════════════════════════
// Date          : 2026-05-21
// Scope         : Page 5 occupancy_analysis — fix broken Y-axis measure
// Replaces      : 2 measures from 38_dax_v29_page5_occupancy_fix.dax
// Notebook touch: NONE (no pipeline re-run needed)
//
// PROBLEM
// -------
// gold_occupancy_profile Delta table schema (Notebook 08, Cell 9) writes
// 9 columns. The column `estimated_headcount` is NOT among them — it only
// existed in the deprecated _FABRIC_KOPYALA.py copy.
// Power BI error on Page 5:
//   "Column estimated_headcount in table gold_occupancy_profile
//    cannot be found or may not be used in this expression."
//
// FIX STRATEGY
// ------------
// Compute headcount ON-THE-FLY from existing columns:
//     headcount = occupancy_probability  ×  max_occupants
//                 (gold_occupancy_profile) (silver_building_master)
//
// silver_building_master[max_occupants] is already in the CSV/model.
// TREATAS is used so the measure works correctly under any building filter
// context (single-building selection, slicer multi-select, portfolio).
//
// IMPACT
// ------
// - Page 5 V6 bar chart (Y-axis: Building Avg Headcount Business Hours)
//   renders correctly for all buildings + portfolio.
// - Building Peak Headcount measure (if used in tooltip / drill-through)
//   also restored.
// - No pipeline run, no notebook edit, no model schema change.
// ════════════════════════════════════════════════════════════════════


// ───────── Replace existing measure ─────────
// Home table: gold_occupancy_profile
// Display folder: Page 5 / Headcount
Building Avg Headcount Business Hours =
VAR _avg_prob =
    CALCULATE(
        AVERAGE( gold_occupancy_profile[occupancy_probability] ),
        gold_occupancy_profile[hour_of_day] >= 8,
        gold_occupancy_profile[hour_of_day] <= 18
    )
VAR _max_occ =
    CALCULATE(
        SUM( silver_building_master[max_occupants] ),
        TREATAS(
            VALUES( gold_occupancy_profile[building_id] ),
            silver_building_master[building_id]
        )
    )
VAR _result = _avg_prob * _max_occ
RETURN
    IF( ISBLANK( _avg_prob ) || ISBLANK( _max_occ ) || _max_occ = 0,
        BLANK(),
        ROUND( _result, 0 )
    )


// ───────── Replace existing measure ─────────
// Home table: gold_occupancy_profile
// Display folder: Page 5 / Headcount
Building Peak Headcount =
VAR _peak_prob =
    CALCULATE(
        MAX( gold_occupancy_profile[occupancy_probability] )
    )
VAR _max_occ =
    CALCULATE(
        SUM( silver_building_master[max_occupants] ),
        TREATAS(
            VALUES( gold_occupancy_profile[building_id] ),
            silver_building_master[building_id]
        )
    )
VAR _result = _peak_prob * _max_occ
RETURN
    IF( ISBLANK( _peak_prob ) || ISBLANK( _max_occ ) || _max_occ = 0,
        BLANK(),
        ROUND( _result, 0 )
    )


// ════════════════════════════════════════════════════════════════════
// VALIDATION (after import — expect these ranges)
// ════════════════════════════════════════════════════════════════════
// Portfolio view (all 6 EU + TR buildings):
//   Building Avg Headcount Business Hours  → 300–500  (weighted avg)
//   Building Peak Headcount                → 800–1200 (Healthcare/Edu peak)
//
// Per building (business hours avg ≈ max_occupants × ~0.6):
//   B001 Berlin Office       (260 max)   →  ~150
//   B002 Istanbul Retail     (700 max)   →  ~400
//   B003 Hamburg Logistics   ( 80 max)   →   ~45
//   B004 Vienna Hotel        (230 max)   →  ~140
//   B005 Frankfurt Healthcare(750 max)   →  ~450
//   B006 Amsterdam Edu       (950 max)   →  ~570
//
// These ranges match base-archetype occupancy profiles
// (EN 15232 typical business-hours fill rate).
// ════════════════════════════════════════════════════════════════════
