// ════════════════════════════════════════════════════════════════════
// PAGE 9 v56 — MASTER DAX (Battery Dispatch + Financial Simulation)
// ════════════════════════════════════════════════════════════════════
// Date          : 2026-05-21
// Scope         : Page 9 (09_Battery_Strategy) — complete refactor
// Replaces      : v47 + v48 + v50 + v51 + v52 (legacy patches)
// New tables    : gold_country_regulations, gold_strategy_fitness
//                 (5 new rows added to gold_battery_technologies)
//
// DESIGN PRINCIPLES (from feedback_dax_patterns.md, v54 lessons)
//   • Self-contained: no [Measure] chain references
//   • Building-type aware: SWITCH by silver_building_master[building_type]
//   • Country aware: SWITCH by silver_building_master[country_code]
//   • Safe TREATAS for cross-table filter propagation
//   • All ISBLANK / div-by-zero guards
//
// ───────────────────────────────────────────────────────────────────
// SECTION INDEX
//   §1  Orphaned V2 measure FIX (6 measures rehomed + IFERROR guards)
//   §2  KPI Cards C1–C5 (master)
//   §3  Visual measures V1–V7
//   §4  Insight strip I1–I4 (prescriptive)
//   §5  Slicer / helper measures
// ════════════════════════════════════════════════════════════════════


// ════════════════════════════════════════════════════════════════════
// §1 — ORPHANED V2 MEASURE FIX
// ════════════════════════════════════════════════════════════════════
// PROBLEM: After last data refresh, six V2 measures show
//          "(gold_battery_dispatch) Move measure to another table".
// CAUSE:   Schema mismatch after Notebook 12/14/15 pipeline change.
// FIX:     Re-anchor home table to gold_battery_dispatch + safe IFERROR
//          + explicit USERELATIONSHIP if a duplicate date relationship
//          is involved.
//
// IMPORTANT: In Tabular Editor 2 install script, ensure each measure's
//            "table" property is set to gold_battery_dispatch.
// ════════════════════════════════════════════════════════════════════

// Home: gold_battery_dispatch  |  Folder: "Page 9 / V2 Daily Flow"
V2 Charge kWh Daily =
IFERROR(
    SUM( gold_battery_dispatch[charge_kwh] ),
    BLANK()
)

V2 Discharge kWh Daily =
IFERROR(
    SUM( gold_battery_dispatch[discharge_kwh] ),
    BLANK()
)

V2 PV Generation kWh =
IFERROR(
    SUM( gold_battery_dispatch[pv_generation_kwh] ),
    BLANK()
)

V2 Grid Charge kWh Daily =
IFERROR(
    SUM( gold_battery_dispatch[grid_charge_kwh] ),
    BLANK()
)

V2 PV Charge kWh Daily =
IFERROR(
    SUM( gold_battery_dispatch[pv_charge_kwh] ),
    BLANK()
)

V2 Net Savings EUR Daily =
IFERROR(
    SUM( gold_battery_dispatch[net_savings_eur] ),
    BLANK()
)


// ════════════════════════════════════════════════════════════════════
// §2 — KPI CARDS C1–C5
// ════════════════════════════════════════════════════════════════════

// ─── C1 Active Strategy Annual Savings (€) ───────────────────────────
// Home: gold_battery_dispatch | Folder: "Page 9 / KPI"
// Logic: Filter to active strategy rows (is_simulated = false where exists),
//        sum 12 most-recent months, scale to 365-day equivalent if partial.
C1 Annual Savings EUR =
VAR _has_active =
    NOT ISBLANK( CALCULATE( COUNTROWS( gold_battery_dispatch ),
        gold_battery_dispatch[is_simulated] = FALSE() ) )
VAR _annual_savings =
    CALCULATE(
        SUM( gold_battery_dispatch[net_savings_eur] ),
        gold_battery_dispatch[is_simulated] = FALSE(),
        gold_battery_dispatch[date] >= DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))
    )
VAR _fallback_sim =
    CALCULATE(
        AVERAGE( gold_battery_simulation[annual_savings_eur] ),
        gold_battery_simulation[is_active_strategy] = TRUE()
    )
RETURN
    IF( _has_active && NOT ISBLANK(_annual_savings) && _annual_savings > 0,
        _annual_savings,
        _fallback_sim )


// ─── C2 Payback Years ────────────────────────────────────────────────
C2 Payback Years =
VAR _payback =
    CALCULATE(
        AVERAGE( gold_battery_simulation[payback_years] ),
        gold_battery_simulation[is_active_strategy] = TRUE()
    )
RETURN
    IF( ISBLANK(_payback) || _payback >= 99, BLANK(), ROUND(_payback, 1) )

C2 Payback Status Label =
VAR _y = [C2 Payback Years]
RETURN
    SWITCH( TRUE(),
        ISBLANK(_y),       "—",
        _y <= 5,           "✓ Excellent",
        _y <= 8,           "✓ Good",
        _y <= 12,          "⚠ Acceptable",
        "✗ Poor"
    )


// ─── C3 CO2 Avoided (t/yr) ───────────────────────────────────────────
C3 CO2 Avoided Tonnes Annual =
VAR _co2_kg =
    CALCULATE(
        SUM( gold_battery_dispatch[co2_avoided_kg] ),
        gold_battery_dispatch[is_simulated] = FALSE(),
        gold_battery_dispatch[date] >= DATE(YEAR(TODAY())-1, MONTH(TODAY()), DAY(TODAY()))
    )
RETURN
    DIVIDE( _co2_kg, 1000 )


// ─── C4 Round Trip Efficiency (%) ────────────────────────────────────
C4 Round Trip Efficiency Pct =
VAR _rte =
    CALCULATE(
        AVERAGE( gold_battery_dispatch[round_trip_efficiency_percent] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
RETURN
    DIVIDE( _rte, 100 )   // → format as Percentage in modeling pane


// ─── C5 EU Compliance Status (rich) ──────────────────────────────────
// Home: gold_battery_simulation | Folder: "Page 9 / KPI"
// Logic: per-building active battery compliance + country regulation overlay
C5 EU Compliance Status Text =
VAR _active_tech =
    CALCULATE(
        MAX( gold_battery_dispatch[battery_tech] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
VAR _country =
    SELECTEDVALUE( silver_building_master[country_code], "DE" )
VAR _reg_row =
    CALCULATETABLE(
        VALUES( gold_country_regulations ),
        gold_country_regulations[country_code] = _country
    )
VAR _is_eu_member =
    CALCULATE( MAX(gold_country_regulations[is_eu_member]), _reg_row )
VAR _nmc_allowed =
    CALCULATE( MAX(gold_country_regulations[nmc_allowed_new_2025]), _reg_row )
VAR _battery_eu_compliant =
    CALCULATE(
        MAX( gold_battery_dispatch[eu_compliant] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
RETURN
    SWITCH( TRUE(),
        ISBLANK(_active_tech),                                   "— No active battery",
        _active_tech = "NMC" && _country IN {"DE","AT"} && NOT _nmc_allowed,
                            "❌ NMC banned for new installs in " & _country,
        NOT _battery_eu_compliant && _is_eu_member,
                            "⚠ Non-compliant under EU 2023/1542",
        _is_eu_member && _battery_eu_compliant,
                            "✓ EU 2023/1542 compliant",
        NOT _is_eu_member,  "ℹ Outside EU framework",
        "ℹ Status unknown"
    )


// ════════════════════════════════════════════════════════════════════
// §3 — VISUAL MEASURES V1–V7
// ════════════════════════════════════════════════════════════════════

// ─── V1 Strategy Recommender Matrix ──────────────────────────────────
// Used on matrix visual: rows = building_type, cols = strategy,
// values = fitness_score. Home: gold_strategy_fitness | Folder: "Page 9 / V1"
V1 Strategy Fitness Score =
AVERAGE( gold_strategy_fitness[fitness_score] )

// Color rule (formula in conditional formatting):
//   0–40 = red, 40–70 = amber, 70–100 = green
V1 Fitness Color Bucket =
VAR _s = [V1 Strategy Fitness Score]
RETURN
    SWITCH( TRUE(),
        _s >= 80, "#27AE60",
        _s >= 60, "#F39C12",
        _s >= 40, "#E67E22",
        "#C0392B"
    )


// ─── V2 24h Battery Behavior — already exists (kept from v48) ────────
// Uses gold_battery_hourly_dispatch[charge_kwh / discharge_kwh / soc_percent / grid_price_index]
// No changes required.


// ─── V3 CAPEX vs Payback Scatter (enhanced — chemistry color) ────────
V3 CAPEX EUR =
AVERAGE( gold_battery_simulation[total_capex_eur] )

V3 Payback Years =
AVERAGE( gold_battery_simulation[payback_years] )

V3 Battery Chemistry Color =
VAR _tech =
    SELECTEDVALUE( gold_battery_simulation[battery_tech], "LFP" )
RETURN
    SWITCH( TRUE(),
        _tech = "LFP",                   "#27AE60",
        _tech = "Sodium-Ion",            "#F1C40F",
        _tech = "Solid-State",           "#9B59B6",
        _tech = "LFP-V2G",               "#16A085",
        _tech IN {"NMC","NCA"},          "#E67E22",
        _tech = "Second-Life NMC",       "#7F8C8D",
        _tech = "LFP-Supercap-Hybrid",   "#2980B9",
        "#95A5A6"
    )


// ─── V4 Monthly Net Savings Trend (€ + CO2 dual axis) ────────────────
V4 Monthly Net Savings EUR =
CALCULATE(
    SUM( gold_battery_dispatch[net_savings_eur] ),
    gold_battery_dispatch[is_simulated] = FALSE()
)

V4 Monthly CO2 Avoided Kg =
CALCULATE(
    SUM( gold_battery_dispatch[co2_avoided_kg] ),
    gold_battery_dispatch[is_simulated] = FALSE()
)


// ─── V5 EU Regulation Heatmap (Country × Chemistry) ──────────────────
// Matrix visual: rows = country_code, cols = battery_type (LFP/NMC/NCA/Sodium-Ion/...)
// Values: numeric flag for conditional formatting.
//   1 = ✓ allowed   0 = ⚠ caveat   -1 = ❌ banned
V5 Country Chemistry Flag =
VAR _country = SELECTEDVALUE( gold_country_regulations[country_code] )
VAR _chem    = SELECTEDVALUE( gold_battery_technologies[battery_type] )
VAR _is_eu   = CALCULATE( MAX(gold_country_regulations[is_eu_member]),
                          gold_country_regulations[country_code] = _country )
VAR _nmc_ok  = CALCULATE( MAX(gold_country_regulations[nmc_allowed_new_2025]),
                          gold_country_regulations[country_code] = _country )
VAR _sodium_ok = CALCULATE( MAX(gold_country_regulations[sodium_ion_approved]),
                            gold_country_regulations[country_code] = _country )
VAR _ss_ok   = CALCULATE( MAX(gold_country_regulations[solid_state_pilot]),
                          gold_country_regulations[country_code] = _country )
RETURN
    SWITCH( TRUE(),
        ISBLANK(_country) || ISBLANK(_chem), BLANK(),
        _chem = "LFP",                                       1,
        _chem = "LFP-V2G",                                   IF(_is_eu, 1, 0),
        _chem = "LFP-Supercap-Hybrid",                       1,
        _chem = "NMC" && _nmc_ok,                            0,
        _chem = "NMC" && NOT _nmc_ok,                       -1,
        _chem = "Second-Life NMC",                           IF(_is_eu, 0, -1),
        _chem = "NCA",                                       0,
        _chem = "Sodium-Ion" && _sodium_ok,                  1,
        _chem = "Sodium-Ion" && NOT _sodium_ok,              0,
        _chem = "Solid-State" && _ss_ok,                     1,
        _chem = "Solid-State",                               0,
        0
    )

V5 Country Chemistry Symbol =
VAR _f = [V5 Country Chemistry Flag]
RETURN
    SWITCH( TRUE(),
        ISBLANK(_f), "—",
        _f = 1,      "✓",
        _f = 0,      "⚠",
        _f = -1,     "✗",
        ""
    )


// ─── V6 Scenario Comparison Table (existing — kept) ──────────────────
// Uses gold_battery_simulation columns directly. No new measure needed.


// ─── V7 Battery Health & Degradation ─────────────────────────────────
V7 Current SoH Pct =
DIVIDE(
    CALCULATE(
        AVERAGE( gold_battery_dispatch[battery_health_percent] ),
        gold_battery_dispatch[is_simulated] = FALSE(),
        gold_battery_dispatch[date] = MAX( gold_battery_dispatch[date] )
    ),
    100
)

V7 Cycles Used Pct =
VAR _used =
    CALCULATE(
        MAX( gold_battery_dispatch[cumulative_cycles] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
VAR _warranty =
    LOOKUPVALUE(
        gold_battery_technologies[warranty_cycles],
        gold_battery_technologies[battery_id],
        SELECTEDVALUE( gold_battery_dispatch[battery_id] )
    )
RETURN
    DIVIDE( _used, _warranty )

V7 Years Until Replacement =
VAR _used = CALCULATE(
        MAX( gold_battery_dispatch[cumulative_cycles] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
VAR _warranty =
    LOOKUPVALUE(
        gold_battery_technologies[warranty_cycles],
        gold_battery_technologies[battery_id],
        SELECTEDVALUE( gold_battery_dispatch[battery_id] )
    )
VAR _avg_daily_cycles =
    DIVIDE( _used,
        DATEDIFF(
            CALCULATE( MIN( gold_battery_dispatch[date] ),
                       gold_battery_dispatch[is_simulated] = FALSE() ),
            CALCULATE( MAX( gold_battery_dispatch[date] ),
                       gold_battery_dispatch[is_simulated] = FALSE() ),
            DAY ) )
VAR _remaining = _warranty - _used
RETURN
    IF( _avg_daily_cycles > 0,
        DIVIDE( _remaining, _avg_daily_cycles ) / 365,
        BLANK() )


// ════════════════════════════════════════════════════════════════════
// §4 — INSIGHT STRIP I1–I4 (PRESCRIPTIVE TEXT)
// ════════════════════════════════════════════════════════════════════

// ─── I1 Best Strategy Recommendation Text ────────────────────────────
I1 Strategy Recommendation Text =
VAR _bt = SELECTEDVALUE( silver_building_master[building_type], "office" )
VAR _country = SELECTEDVALUE( silver_building_master[country_code], "DE" )
VAR _primary =
    CALCULATE(
        SELECTEDVALUE( gold_strategy_fitness[strategy_label] ),
        gold_strategy_fitness[building_type] = _bt,
        gold_strategy_fitness[is_primary] = TRUE()
    )
VAR _secondary =
    CALCULATE(
        SELECTEDVALUE( gold_strategy_fitness[strategy_label] ),
        gold_strategy_fitness[building_type] = _bt,
        gold_strategy_fitness[is_secondary] = TRUE()
    )
VAR _primary_savings =
    CALCULATE(
        AVERAGE( gold_strategy_fitness[typical_annual_savings_eur_per_kwh] ),
        gold_strategy_fitness[building_type] = _bt,
        gold_strategy_fitness[is_primary] = TRUE()
    )
VAR _cap =
    SELECTEDVALUE( silver_building_master[battery_capacity_kwh], 100 )
VAR _est_eur = ROUND( _primary_savings * _cap, -2 )
RETURN
    "For this " & _bt & " building in " & _country & ", primary strategy: " &
    _primary &
    IF( NOT ISBLANK(_secondary), " (combined with " & _secondary & ")", "" ) &
    ". Estimated annual savings ≈ €" & FORMAT( _est_eur, "#,0" ) &
    " (range ±25%)."


// ─── I2 Chemistry Recommendation Text ────────────────────────────────
I2 Chemistry Recommendation Text =
VAR _country = SELECTEDVALUE( silver_building_master[country_code], "DE" )
VAR _is_cold_climate = _country IN {"FI","NO","SE","DK","AT"}
VAR _nmc_ok =
    CALCULATE( MAX(gold_country_regulations[nmc_allowed_new_2025]),
               gold_country_regulations[country_code] = _country )
VAR _sodium_ok =
    CALCULATE( MAX(gold_country_regulations[sodium_ion_approved]),
               gold_country_regulations[country_code] = _country )
RETURN
    SWITCH( TRUE(),
        _is_cold_climate && _sodium_ok,
            "Recommended: Sodium-Ion (CATL Naxtra) — superior cold-weather performance below -10°C, lowest carbon footprint (28 kg CO₂/kWh), available Q3 2026 in " & _country & ".",
        _country IN {"DE","AT"} && NOT _nmc_ok,
            "Recommended: LFP (CATL or Fluence) — NMC chemistry banned for new installs in " & _country & " per BattG 2025 amendment. LFP yields 6,000+ cycles and full EU 2023/1542 compliance.",
        _country = "NL",
            "Recommended: LFP-V2G (BYD Battery-Box HVS) — Netherlands has most mature V2G regulation. Bidirectional charger + EV fleet integration yields ~30% additional revenue.",
        _country = "UK",
            "Recommended: LFP-Supercap-Hybrid (Skeleton SkelGrid) — UK Dynamic Containment + Capacity Market favor high-power chemistry with 1M+ cycle equivalent.",
        "Recommended: LFP (CATL or Fluence) — best lifecycle value, full EU 2023/1542 compliance, 12-year warranty, 6,000+ cycles."
    )


// ─── I3 Compliance Flag Text ─────────────────────────────────────────
I3 Compliance Flag Text =
VAR _active_tech =
    CALCULATE(
        MAX( gold_battery_dispatch[battery_tech] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
VAR _country = SELECTEDVALUE( silver_building_master[country_code], "DE" )
VAR _compliant =
    CALCULATE(
        MAX( gold_battery_dispatch[eu_compliant] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
VAR _is_eu_member =
    CALCULATE( MAX(gold_country_regulations[is_eu_member]),
               gold_country_regulations[country_code] = _country )
RETURN
    SWITCH( TRUE(),
        ISBLANK(_active_tech),
            "No active battery — simulation mode only.",
        _active_tech = "NMC" && _country IN {"DE","AT"},
            "⚠ Active battery is NMC — banned in " & _country & " for new installs from 2025-01. Replacement window: 2027-Q1.",
        _is_eu_member && NOT _compliant,
            "⚠ Active battery does not meet EU 2023/1542 thresholds (carbon footprint or recycled content). Mandatory replacement before 2027 in regulated tenders.",
        _is_eu_member && _compliant,
            "✓ Active battery fully EU 2023/1542 compliant — Digital Battery Passport on file.",
        "ℹ Active battery outside EU regulatory perimeter."
    )


// ─── I4 Next Action Text ─────────────────────────────────────────────
I4 Next Action Text =
VAR _yr_to_replace = [V7 Years Until Replacement]
VAR _payback = [C2 Payback Years]
RETURN
    SWITCH( TRUE(),
        ISBLANK(_yr_to_replace) && ISBLANK(_payback),
            "Run a 12-month dispatch simulation to populate financial metrics.",
        NOT ISBLANK(_yr_to_replace) && _yr_to_replace < 2,
            "⚠ Battery cycle headroom < 2 years. Plan replacement procurement now (lead time 8-14 weeks for LFP).",
        NOT ISBLANK(_yr_to_replace) && _yr_to_replace < 5,
            "Cycle headroom " & FORMAT(_yr_to_replace, "0.0") & " years. Schedule mid-life maintenance + warranty audit.",
        NOT ISBLANK(_payback) && _payback < 5,
            "✓ Strong investment case (payback < 5 years). Recommend portfolio rollout to similar buildings.",
        "Battery operating within design envelope. Monitor next mid-life review in 24 months."
    )


// ════════════════════════════════════════════════════════════════════
// §5 — SLICER / HELPER MEASURES
// ════════════════════════════════════════════════════════════════════

// Active battery short label (for left-panel card)
Active Battery Label =
VAR _tech =
    CALCULATE(
        MAX( gold_battery_dispatch[battery_tech] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
VAR _type =
    CALCULATE(
        MAX( gold_battery_dispatch[battery_type] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
VAR _cap =
    CALCULATE(
        MAX( gold_battery_dispatch[capacity_kwh] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
RETURN
    IF( ISBLANK(_tech), "— No active battery —",
        _type & " · " & FORMAT(_cap, "#,0") & " kWh" )

// Active strategy short label
Active Strategy Short Label =
VAR _s =
    CALCULATE(
        MAX( gold_battery_dispatch[strategy] ),
        gold_battery_dispatch[is_simulated] = FALSE()
    )
RETURN
    SWITCH( TRUE(),
        ISBLANK(_s),               "— Select strategy —",
        _s = "self_consumption",   "● Self-Consumption",
        _s = "peak_shaving",       "● Peak-Shaving",
        _s = "tou",                "● Time-of-Use",
        _s = "backup",             "● Backup + Opportunistic",
        _s = "frequency_reserve",  "● Frequency Reserve",
        _s = "capacity_market",    "● Capacity Market",
        _s = "v2g",                "● V2G Coordination",
        "● " & _s
    )

// Page data freshness
Page9 Data As Of =
"Data as of " &
FORMAT(
    CALCULATE( MAX(gold_battery_dispatch[date]),
               gold_battery_dispatch[is_simulated] = FALSE() ),
    "MMMM yyyy"
)

// ════════════════════════════════════════════════════════════════════
// END OF v56 MASTER
// ════════════════════════════════════════════════════════════════════
