"""add organizations is_sample

Revision ID: 7cfe01762f07
Revises: 8078b37adc9c
Create Date: 2026-05-27 15:06:54.437067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfe01762f07'
down_revision: Union[str, Sequence[str], None] = '8078b37adc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_sample', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_sample')
    # ### end Alembic commands ###
