"""add org_invitations

Revision ID: d5f2a8c41e6b
Revises: c44d7e89f1a2
Create Date: 2026-05-30

Day 19 -- backs the /settings member-invite flow. A pending invitation
carries a capability token; on accept an OrgMember row is created.

Hand-written (not autogenerated) per the project's Alembic convention:
columns and constraints mirror app/db/models/invitation.py exactly so the
model and schema stay in lockstep.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5f2a8c41e6b"
down_revision: Union[str, Sequence[str], None] = "c44d7e89f1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "org_invitations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "organization_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "invited_by_user_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "accepted_by_user_id", postgresql.UUID(as_uuid=True), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_org_invitation_token"),
    )
    op.create_index(
        "ix_org_invitations_organization_id",
        "org_invitations",
        ["organization_id"],
    )
    op.create_index(
        "ix_org_invitations_email", "org_invitations", ["email"]
    )


def downgrade() -> None:
    op.drop_index("ix_org_invitations_email", table_name="org_invitations")
    op.drop_index(
        "ix_org_invitations_organization_id", table_name="org_invitations"
    )
    op.drop_table("org_invitations")
