"""03_answer_questions.py -- run 04_pm_questions.sql block by block and print
each answer with its framing. Writes output/pm_answers.md as the work sample."""
import duckdb, os, re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SQLF = HERE.parent / "sql" / "04_pm_questions.sql"
DB   = Path(os.environ.get("DUCKDB_PATH", HERE.parent / "output" / "energy.duckdb"))
OUT  = HERE.parent / "output" / "pm_answers.md"

text = SQLF.read_text()
blocks = re.split(r"\n-- (Q\d+) -+\n", text)[1:]
pairs = [(blocks[i], blocks[i+1]) for i in range(0, len(blocks), 2)]

con = duckdb.connect(str(DB), read_only=True); con.execute("SET TimeZone='UTC'")
lines = ["# PM analysis answers", "",
         "Generated by `03_answer_questions.py` from `04_pm_questions.sql`.",
         "Synthetic data. Every number below is reproducible by rerunning the pipeline.", ""]
for qid, body in pairs:
    comment = "\n".join(l.lstrip("- ").strip() for l in body.splitlines()
                        if l.strip().startswith("--"))
    sql = "\n".join(l for l in body.splitlines() if not l.strip().startswith("--")).strip()
    df = con.execute(sql).df()
    print(f"\n{'='*78}\n{qid}: {comment}\n{'-'*78}")
    print(df.to_string(index=False))
    lines += [f"## {qid}", "", f"> {comment}", "", "```", df.to_string(index=False), "```", ""]
con.close()
OUT.write_text("\n".join(lines))
print(f"\n\nwritten -> {OUT}")
